### ISSUE TITLE
Error when open image in the VisionHandler

### ISSUE THREAD

**Issue by xiumingliu** [pytorch/serve#1019]
Hi, I am running torchserve mnist example in a container image derived from [pytorch/torchserve:0.3.0-cpu](https://hub.docker.com/layers/pytorch/torchserve/0.3.0-cpu/images/sha256-09135470e8e5a97bbbb2c22027da5624c1bd944dd289eba63b1f7369ea42ace8?context=explore). The example is from [this GCP document](https://cloud.google.com/ai-platform/prediction/docs/getting-started-pytorch-container#run_the_container_locally_optional): 

After running the container image **locally**, the health check is ok. But when send a prediction request to the container's server, I got the prediction failed message: 
{
  "code": 503,
  "type": "InternalServerException",
  "message": "Prediction failed"
}

The logs from the container shows that **the error occurs during opening the image in the vision handler**: 
```
2021-03-25 07:56:49,905 [INFO ] W-9004-mnist_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Invoking custom service failed.
2021-03-25 07:56:49,905 [INFO ] W-9004-mnist_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Traceback (most recent call last):
2021-03-25 07:56:49,905 [INFO ] W-9004-mnist_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - File "/home/venv/lib/python3.6/site-packages/ts/service.py", line 100, in predict
2021-03-25 07:56:49,905 [INFO ] W-9004-mnist_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - ret = self._entry_point(input_batch, self.context)
2021-03-25 07:56:49,905 [INFO ] W-9004-mnist_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - File "/home/venv/lib/python3.6/site-packages/ts/torch_handler/request_envelope/base.py", line 28, in handle
2021-03-25 07:56:49,906 [INFO ] W-9004-mnist_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - results = self._handle_fn(data, context)
2021-03-25 07:56:49,906 [INFO ] W-9004-mnist_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - File "/home/venv/lib/python3.6/site-packages/ts/torch_handler/base_handler.py", line 194, in handle
2021-03-25 07:56:49,906 [INFO ] W-9004-mnist_1.0 org.pytorch.serve.wlm.WorkerThread - Backend response time: 53
2021-03-25 07:56:49,906 [INFO ] W-9004-mnist_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - data_preprocess = self.preprocess(data)
2021-03-25 07:56:49,906 [INFO ] W-9004-mnist_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - File "/home/venv/lib/python3.6/site-packages/ts/torch_handler/vision_handler.py", line 45, in preprocess
2021-03-25 07:56:49,906 [INFO ] W-9004-mnist_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - image = Image.open(io.BytesIO(image))
2021-03-25 07:56:49,906 [INFO ] W-9004-mnist_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - File "/home/venv/lib/python3.6/site-packages/PIL/Image.py", line 2944, in open
2021-03-25 07:56:49,907 [INFO ] W-9004-mnist_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - "cannot identify image file %r" % (filename if filename else fp)
2021-03-25 07:56:49,907 [INFO ] W-9004-mnist_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fb511fa5308>
2021-03-25 07:56:49,907 [INFO ] W-9004-mnist_1.0 ACCESS_LOG - /172.17.0.1:50246 "POST /predictions/mnist HTTP/1.1" 503 65
2021-03-25 07:56:49,907 [INFO ] W-9004-mnist_1.0 TS_METRICS - Requests5XX.Count:1|#Level:Host|#hostname:d53d6fdec1f6,timestamp:null
2021-03-25 07:56:49,907 [DEBUG] W-9004-mnist_1.0 org.pytorch.serve.job.Job - Waiting time ns: 304600, Inference time ns: 55761100
2021-03-25 07:56:49,907 [INFO ] W-9004-mnist_1.0 TS_METRICS - WorkerThreadTime.ms:2|#Level:Host|#hostname:d53d6fdec1f6,timestamp:null
```

Here is the Dockerfile: 
```
FROM pytorch/torchserve:0.3.0-cpu

COPY mnist.py mnist_cnn.pt mnist_handler.py /home/model-server/

USER root
RUN printf "\nservice_envelope=json" >> /home/model-server/config.properties
USER model-server

RUN torch-model-archiver \
  --model-name=mnist \
  --version=1.0 \
  --model-file=/home/model-server/mnist.py \
  --serialized-file=/home/model-server/mnist_cnn.pt \
  --handler=/home/model-server/mnist_handler.py \
  --export-path=/home/model-server/model-store

CMD ["torchserve", \
     "--start", \
     "--ts-config=/home/model-server/config.properties", \
     "--models", \
     "mnist=mnist.mar"]

```

The request: 
```
curl -X POST -H "Content-Type: application/json; charset=utf-8" -d @instances.json localhost:8080/predictions/mnist
```

And the json data file: 
```
{
  "instances": [
    {
      "data": {
        "b64": "$(base64 --wrap=0 test_data/3.png)"
      }
    }
  ]
}
```

**Comment by xiumingliu** [comment]
The problem is caused by sending the request in windows cmd, but the image path and the base 64 in json file is for Linux environment. Not an issue of pytorch serve. Closed.
