### ISSUE TITLE
Missing Java dependency install

### ISSUE THREAD

**Issue by msaroufim** [pytorch/serve#1030]
## 📚 Documentation

In https://github.com/pytorch/serve/README.md for the Mac CPU instructions there is a missing implicit dependency on Java which `install_dependencies.py` does take care of but doesn't actually make sure it's linked. This is especially an issue if someone has multiple Java versions installed. 

`
(servefinal) marksaroufim@marksaroufim-mbp Dev % torchserve --start --ncs --model-store model_store --models densenet161.mar
(servefinal) marksaroufim@marksaroufim-mbp Dev % java.lang.NoSuchMethodError: java.nio.file.Files.readString(Ljava/nio/file/Path;)Ljava/lang/String;
	at org.pytorch.serve.util.ConfigManager.readFile(ConfigManager.java:208)
	at org.pytorch.serve.util.ConfigManager.<init>(ConfigManager.java:120)
	at org.pytorch.serve.util.ConfigManager.init(ConfigManager.java:258)
	at org.pytorch.serve.ModelServer.main(ModelServer.java:80)
`

**Comment by msaroufim** [comment]
For reference to others this is what fixed my java issue on Mac Catalina

`export JAVA_HOME=$(/usr/libexec/java_home -v16)` change the version to whatever version works best for you from here https://www.oracle.com/java/technologies/javase-downloads.html
