### ISSUE TITLE
W-9008-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread

### ISSUE THREAD

**Issue by lonngxiang** [pytorch/serve#1034]
[DEBUG] W-9008-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133)
        at java.base/java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:432)
        at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:188)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by msaroufim** [comment]
Hi @lonngxiang could you please share some repro instructions? What were you trying to do? In what kind of environment? When did it break?

The format for bugs here is pretty good https://github.com/pytorch/serve/issues/new/choose

Happy to help if I get more detail

**Comment by msaroufim** [comment]
Closing for now since a worker dying does not mean the model isn't working - need to make sure an inference can actually run. Rerunning the hello world model for densenet on my end seems to work just fine

```
(batch) ubuntu@ip-172-31-73-244:~$ curl http://127.0.0.1:8080/predictions/densenet161 -T kitten_small.jpg
{
  "tabby": 0.5078848004341125,
  "lynx": 0.18985238671302795,
  "tiger_cat": 0.16152901947498322,
  "tiger": 0.054622188210487366,
  "Egyptian_cat": 0.04894307628273964
```
