### ISSUE TITLE
Backpropogate error from backend server to user

### ISSUE THREAD

**Issue by saurabheights-ecr** [pytorch/serve#1046]
## Is your feature request related to a problem? Please describe.

Scenario - User  does not get information of root cause of failures. AFAIK, the failure can happen during model initialization and during prediction/inference call. 

For model setup(installation of packages, etc.), currently user gets response :-

```
curl http://localhost:8444/models/yolov4 
[
  {
    "modelName": "yolov4",
    "modelVersion": "1.0",
    "modelUrl": "yolov4.mar",
    "runtime": "python",
    "minWorkers": 0,
    "maxWorkers": 0,
    "batchSize": 1,
    "maxBatchDelay": 100,
    "loadedAtStartup": false,  # Only this field.
    "workers": []
  }
]
```

However, backend logs more details:-

```
2021-04-29 14:34:20,195 [INFO ] main org.pytorch.serve.wlm.ModelManager - Model yolov4 loaded.
2021-04-29 14:34:22,308 [WARN ] main org.pytorch.serve.ModelServer - Failed to load model: yolov4.mar
org.pytorch.serve.archive.ModelException: Custom pip package installation failed for yolov4 
	at org.pytorch.serve.wlm.ModelManager.setupModelDependencies(ModelManager.java:190)
	at org.pytorch.serve.wlm.ModelManager.registerModel(ModelManager.java:125)
	at org.pytorch.serve.ModelServer.initModelStore(ModelServer.java:213)
	at org.pytorch.serve.ModelServer.start(ModelServer.java:308)
	at org.pytorch.serve.ModelServer.startAndWait(ModelServer.java:104)
	at org.pytorch.serve.ModelServer.main(ModelServer.java:85)
```

For prediction, currently user gets response:-

```
$ curl http://localhost:8443/predictions/yolov4 -T kitten_small.jpg
{
  "code": 503,
  "type": "InternalServerException",
  "message": "Prediction failed"
}

```

whereas backend logs error

```
2021-04-29 14:19:00,442 [INFO ] W-9000-yolov4_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/venv/lib/python3.6/site-packages/ts/service.py", line 100, in predict
2021-04-29 14:19:00,442 [INFO ] W-9000-yolov4_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     ret = self._entry_point(input_batch, self.context)
2021-04-29 14:19:00,442 [INFO ] W-9000-yolov4_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/model-server/tmp/models/3b43f822b74b4997a4277f83f0b0f887/yolov4_handler.py", line 196, in handle
2021-04-29 14:19:00,442 [INFO ] W-9000-yolov4_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     return _service.handle(data, context)
2021-04-29 14:19:00,442 [INFO ] W-9000-yolov4_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/model-server/tmp/models/3b43f822b74b4997a4277f83f0b0f887/yolov4_handler.py", line 180, in handle
2021-04-29 14:19:00,443 [INFO ] W-9000-yolov4_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     raise ValueError('You shall not run')
2021-04-29 14:19:00,443 [INFO ] W-9000-yolov4_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - ValueError: You shall not run
```

## Describe the solution

Return the exception/failure description to user. This can be returned as part of `message`(in case of prediction api call) or better, use a new output field say `description` to keep changes backward compatible.

Furthermore, we should have two configuration field:-
a. Enable description field - The ML team and user are separate and ML team does not want user to know about code/model. To provide secrecy.
b. Limiting description field - Unlikely, but long messages can pop up in production and cause issues. Limiting the description string to a certain number of characters would help and keep system robust. A negative number or default value can be used to provide full description, i.e. no limiting the error description. However, I wonder if limiting first or last N characters makes sense, or if we should also make this configurable.

Note: for model management api, the information on model load failure, should be saved to return later.

## Describe alternatives solution

P.S. tfserving follows suggested approach where they return the full information on why error happened as response to inference call.

**Comment by msaroufim** [comment]
This is an interesting proposal. I'm assuming the request is about letting teams calling a deployed model still get useful debug information in case there's an error without having to dig through logs which would be owned by a seperate backend team that may need to deal with compliance issues.

I'm guessing there's an easy way to do this by extending a handler but let me think about this more since I'm new and still ramping up on this codebase.

**Comment by saurabheights** [comment]
@msaroufim For the first part, yes. We want user to know the details(no secrecy required), and it would help a lot since often, user mar files are incorrect. Knowing where the error comes from will allow the right team to focus on resolving the issue.

For later part, ~~I dont think the issue is handler. The response from handler is completely ignored in torchserve backend and the error is returned~~. On second thought, it might be doable, if the output from handler is exception message itself. For our case, however, this puts more work on clients to make sure they do error handling, which is less desirable. Also, not just our case, this puts more work on every user who has to make mar files with proper error handling.

Finally, regarding you being new, let me know if I can assist. I have played around with torchserve internal codebase a lot. I think I can draft a design proposal and if its alright by your side, I can create a PR afterwards.

**Comment by msaroufim** [comment]
That’d be fantastic please do!
