### ISSUE TITLE
transformers complain, TypeError: Can't convert 'True' to PyBool

### ISSUE THREAD

**Issue by liusida** [pytorch/serve#1072]
## Context
I was trying to follow the tutorial [https://github.com/pytorch/serve/tree/master/examples/Huggingface_Transformers](https://github.com/pytorch/serve/tree/master/examples/Huggingface_Transformers) to run 
```bash
python Download_Transformer_models.py
```
* torchserve version: 0.3.1
* torch-model-archiver version: 0.3.1
* torch version: 1.7.1+cpu
* java version: openjdk 11.0.11 2021-04-20
* Operating System and version: Ubuntu 20.04.2 LTS

## Current Behavior
```bash
Traceback (most recent call last):
  File "Download_Transformer_models.py", line 72, in <module>
    transformers_model_dowloader(mode,model_name, num_labels,do_lower_case, max_length, torchscript)
  File "Download_Transformer_models.py", line 22, in transformers_model_dowloader
    tokenizer = AutoTokenizer.from_pretrained(pretrained_model_name,do_lower_case=do_lower_case)
  File "/home/liusida/anaconda3/envs/torchserve/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 435, in from_pretrained
    return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/liusida/anaconda3/envs/torchserve/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1719, in from_pretrained
    return cls._from_pretrained(
  File "/home/liusida/anaconda3/envs/torchserve/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1791, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/liusida/anaconda3/envs/torchserve/lib/python3.8/site-packages/transformers/models/bert/tokenization_bert_fast.py", line 199, in __init__
    self.backend_tokenizer.normalizer = pre_tok_class(**pre_tok_state)
TypeError: Can't convert 'True' to PyBool
```

## Possible Solution
This is due to this line [https://github.com/pytorch/serve/blob/689c78e6a7823ff2b024abd35c50df9400d57f84/examples/Huggingface_Transformers/Download_Transformer_models.py#L64](https://github.com/pytorch/serve/blob/689c78e6a7823ff2b024abd35c50df9400d57f84/examples/Huggingface_Transformers/Download_Transformer_models.py#L64).

It should be 
```python
do_lower_case = bool(settings["do_lower_case"])
```

Thanks.

**Comment by HamidShojanazeri** [comment]
Thanks @liusida, this should be covered in this [PR](https://github.com/pytorch/serve/pull/1071).

**Comment by liusida** [comment]
Yes, @HamidShojanazeri , thanks. 

Fixing `setup_config.json` solves this issue. No need to modify the Python code.

**Comment by HamidShojanazeri** [comment]
@liusida yes that's right, the PR will provide additional fixes to cover the latest transformers version changes with some fixes for captum explanations.
