### ISSUE TITLE
Failed to build Docker image in production environment

### ISSUE THREAD

**Issue by AlfredWGA** [pytorch/serve#1134]
## Context

* torchserve version: 0.4.0
* torch version: 1.8.1
* Operating System and version: Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-144-generic x86_64)

## Your Environment

* Installed using source? [yes/no]: no
* Are you planning to deploy it using docker container? [yes/no]: yes
* Is it a CPU or GPU environment?: gpu

## Expected Behavior

Successfully build the Docker image.

## Current Behavior

Here's what happens after I run `./build_image.sh -g -cv cu102` under the `docker` folder,
```shell
[+] Building 303.5s (14/21)
 => [internal] load build definition from Dockerfile                                                                                                                       0.2s
 => => transferring dockerfile: 38B                                                                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                                                          0.3s
 => => transferring context: 2B                                                                                                                                            0.0s
 => resolve image config for docker.io/docker/dockerfile:experimental                                                                                                      0.8s
 => CACHED docker-image://docker.io/docker/dockerfile:experimental@sha256:600e5c62eedff338b3f7a0850beb7c05866e0ef27b2d2e8c02aa468e78496ff5                                 0.0s
 => [internal] load metadata for docker.io/nvidia/cuda:10.2-cudnn7-runtime-ubuntu18.04                                                                                     0.5s
 => [internal] load build context                                                                                                                                          0.1s
 => => transferring context: 80B                                                                                                                                           0.0s
 => [runtime-image 1/9] FROM docker.io/nvidia/cuda:10.2-cudnn7-runtime-ubuntu18.04@sha256:310413de908d073d6e2d9b7a8195ab7a66abd91c6faa5deba021bf7a2f73cba7                 0.0s
 => CACHED [compile-image 2/7] RUN --mount=type=cache,id=apt-dev,target=/var/cache/apt     apt-get update &&     DEBIAN_FRONTEND=noninteractive apt-get install --no-inst  0.0s
 => CACHED [compile-image 3/7] RUN python3 -m venv /home/venv                                                                                                              0.0s
 => CACHED [compile-image 4/7] RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1     && update-alternatives --install /usr/local/bin/pip pip /u  0.0s
 => CACHED [compile-image 5/7] RUN export USE_CUDA=1                                                                                                                       0.0s
 => CACHED [runtime-image 2/9] RUN --mount=type=cache,target=/var/cache/apt     apt-get update &&     DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recomme  0.0s
 => CACHED [runtime-image 3/9] RUN useradd -m model-server     && mkdir -p /home/model-server/tmp                                                                          0.0s
 => ERROR [compile-image 6/7] RUN TORCH_VER=$(curl --silent --location https://pypi.org/pypi/torch/json | python -c "import sys, json, pkg_resources; releases = json.l  301.0s
------
 > [compile-image 6/7] RUN TORCH_VER=$(curl --silent --location https://pypi.org/pypi/torch/json | python -c "import sys, json, pkg_resources; releases = json.load(sys.stdin)['releases']; print(sorted(releases, key=pkg_resources.parse_version)[-1])") &&     TORCH_VISION_VER=$(curl --silent --location https://pypi.org/pypi/torchvision/json | python -c "import sys, json, pkg_resources; releases = json.load(sys.stdin)['releases']; print(sorted(releases, key=pkg_resources.parse_version)[-1])") &&     if echo "nvidia/cuda:10.2-cudnn7-runtime-ubuntu18.04" | grep -q "cuda:"; then         if [ "cu102" ]; then             pip install --no-cache-dir torch==$TORCH_VER+cu102 torchvision==$TORCH_VISION_VER+cu102 -f https://download.pytorch.org/whl/torch_stable.html;         else             pip install --no-cache-dir torch torchvision;         fi     else         pip install --no-cache-dir torch==$TORCH_VER+cpu torchvision==$TORCH_VISION_VER+cpu -f https://download.pytorch.org/whl/torch_stable.html;     fi:
#13 300.8 Traceback (most recent call last):
#13 300.8   File "<string>", line 1, in <module>
#13 300.8   File "/usr/lib/python3.6/json/__init__.py", line 299, in load
#13 300.8     parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
#13 300.8   File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
#13 300.8     return _default_decoder.decode(s)
#13 300.8   File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
#13 300.8     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
#13 300.8   File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
#13 300.8     raise JSONDecodeError("Expecting value", s, err.value) from None
#13 300.8 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
------
executor failed running [/bin/sh -c TORCH_VER=$(curl --silent --location https://pypi.org/pypi/torch/json | python -c "import sys, json, pkg_resources; releases = json.load(sys.stdin)['releases']; print(sorted(releases, key=pkg_resources.parse_version)[-1])") &&     TORCH_VISION_VER=$(curl --silent --location https://pypi.org/pypi/torchvision/json | python -c "import sys, json, pkg_resources; releases = json.load(sys.stdin)['releases']; print(sorted(releases, key=pkg_resources.parse_version)[-1])") &&     if echo "$BASE_IMAGE" | grep -q "cuda:"; then         if [ "$CUDA_VERSION" ]; then             pip install --no-cache-dir torch==$TORCH_VER+$CUDA_VERSION torchvision==$TORCH_VISION_VER+$CUDA_VERSION -f https://download.pytorch.org/whl/torch_stable.html;         else             pip install --no-cache-dir torch torchvision;         fi     else         pip install --no-cache-dir torch==$TORCH_VER+cpu torchvision==$TORCH_VISION_VER+cpu -f https://download.pytorch.org/whl/torch_stable.html;     fi]: exit code: 1
```

It seems like the building is stuck at querying the latest `torch` version. I've tried building with different cuda version, all show the same results. I'd appreciate any kinds of help!

**Comment by msaroufim** [comment]
Hi @AlfredWGA I just tried this out on my local Mac and couldn't repro

Can you try running the command to query the latest torch version from your terminal and paste the output here?

```
(base) ➜  docker git:(master) ./build_image.sh -g -cv cu102
[+] Building 176.3s (22/22) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                                                                                               0.0s
 => => transferring dockerfile: 4.10kB                                                                                                                                                                                                                                                                                             0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                                                                                                  0.0s
 => => transferring context: 2B                                                                                                                                                                                                                                                                                                    0.0s
 => resolve image config for docker.io/docker/dockerfile:experimental                                                                                                                                                                                                                                                              1.1s
 => CACHED docker-image://docker.io/docker/dockerfile:experimental@sha256:600e5c62eedff338b3f7a0850beb7c05866e0ef27b2d2e8c02aa468e78496ff5                                                                                                                                                                                         0.0s
 => [internal] load metadata for docker.io/nvidia/cuda:10.2-cudnn7-runtime-ubuntu18.04                                                                                                                                                                                                                                             1.0s
 => [internal] load build context                                                                                                                                                                                                                                                                                                  0.0s
 => => transferring context: 498B                                                                                                                                                                                                                                                                                                  0.0s
 => [runtime-image 1/9] FROM docker.io/nvidia/cuda:10.2-cudnn7-runtime-ubuntu18.04@sha256:310413de908d073d6e2d9b7a8195ab7a66abd91c6faa5deba021bf7a2f73cba7                                                                                                                                                                        50.1s
 => => resolve docker.io/nvidia/cuda:10.2-cudnn7-runtime-ubuntu18.04@sha256:310413de908d073d6e2d9b7a8195ab7a66abd91c6faa5deba021bf7a2f73cba7                                                                                                                                                                                       0.0s
 => => sha256:889a7173dcfeb409f9d88054a97ab2445f5a799a823f719a5573365ee3662b6f 189B / 189B                                                                                                                                                                                                                                         0.5s
 => => sha256:310413de908d073d6e2d9b7a8195ab7a66abd91c6faa5deba021bf7a2f73cba7 2.21kB / 2.21kB                                                                                                                                                                                                                                     0.0s
 => => sha256:206bdae5f256a3cb1d5b8433e36eca7565b9c94c86692ab75bd9de687f823ea4 8.62kB / 8.62kB                                                                                                                                                                                                                                     0.0s
 => => sha256:4bbfd2c87b7524455f144a03bf387c88b6d4200e5e0df9139a9d5e79110f89ca 26.70MB / 26.70MB                                                                                                                                                                                                                                   0.8s
 => => sha256:d2e110be24e168b42c1a2ddbc4a476a217b73cccdba69cdcb212b812a88f5726 857B / 857B                                                                                                                                                                                                                                         0.4s
 => => sha256:16d3b8690ce08de70360ada9bde3582bbce45b91f227e7339e4fc03f0d6dba5c 7.22MB / 7.22MB                                                                                                                                                                                                                                     1.0s
 => => sha256:080a9b43605d45bcaab8016f8ba1412679b4eed08b6cb02c7ea773a80e525160 9.55MB / 9.55MB                                                                                                                                                                                                                                     1.1s
 => => sha256:9451de56371074e64f5fc7170009d979017170f67e26481a2db100b02d73ba06 184B / 184B                                                                                                                                                                                                                                         0.9s
 => => extracting sha256:4bbfd2c87b7524455f144a03bf387c88b6d4200e5e0df9139a9d5e79110f89ca                                                                                                                                                                                                                                          1.5s
 => => sha256:7dd075385a95f6958841c9645b432432d717bdde3cb942a27e51daed4f04e8f9 6.43kB / 6.43kB                                                                                                                                                                                                                                     1.1s
 => => sha256:95ef991f8c4fe440e42191896c18a46913d2e78fc7e0d8c300d8c8c2b3be511d 716.84MB / 716.84MB                                                                                                                                                                                                                                20.3s
 => => sha256:976e967c6574e96374e122ee757b0cdce94b9dda3daceb8af29e3118de2a6f62 294.58MB / 294.58MB                                                                                                                                                                                                                                16.9s
 => => extracting sha256:d2e110be24e168b42c1a2ddbc4a476a217b73cccdba69cdcb212b812a88f5726                                                                                                                                                                                                                                          0.0s
 => => extracting sha256:889a7173dcfeb409f9d88054a97ab2445f5a799a823f719a5573365ee3662b6f                                                                                                                                                                                                                                          0.0s
 => => extracting sha256:16d3b8690ce08de70360ada9bde3582bbce45b91f227e7339e4fc03f0d6dba5c                                                                                                                                                                                                                                          0.3s
 => => extracting sha256:080a9b43605d45bcaab8016f8ba1412679b4eed08b6cb02c7ea773a80e525160                                                                                                                                                                                                                                          0.4s
 => => extracting sha256:9451de56371074e64f5fc7170009d979017170f67e26481a2db100b02d73ba06                                                                                                                                                                                                                                          0.0s
 => => extracting sha256:7dd075385a95f6958841c9645b432432d717bdde3cb942a27e51daed4f04e8f9                                                                                                                                                                                                                                          0.0s
 => => extracting sha256:95ef991f8c4fe440e42191896c18a46913d2e78fc7e0d8c300d8c8c2b3be511d                                                                                                                                                                                                                                         20.6s
 => => extracting sha256:976e967c6574e96374e122ee757b0cdce94b9dda3daceb8af29e3118de2a6f62                                                                                                                                                                                                                                          8.6s
 => [runtime-image 2/9] RUN --mount=type=cache,target=/var/cache/apt     apt-get update &&     DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y     python3     python3-distutils     python3-dev     openjdk-11-jre-headless     build-essential     && rm -rf /var/lib/apt/lists/*     && cd /tmp      36.1s
 => [compile-image 2/7] RUN --mount=type=cache,id=apt-dev,target=/var/cache/apt     apt-get update &&     DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y     ca-certificates     g++     python3-dev     python3-distutils     python3-venv     openjdk-11-jre-headless     curl     && rm -rf /var/l  39.6s
 => [runtime-image 3/9] RUN useradd -m model-server     && mkdir -p /home/model-server/tmp                                                                                                                                                                                                                                         0.4s
 => [compile-image 3/7] RUN python3 -m venv /home/venv                                                                                                                                                                                                                                                                             1.6s
 => [compile-image 4/7] RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1     && update-alternatives --install /usr/local/bin/pip pip /usr/local/bin/pip3 1                                                                                                                                              0.3s
 => [compile-image 5/7] RUN export USE_CUDA=1                                                                                                                                                                                                                                                                                      0.3s
 => [compile-image 6/7] RUN TORCH_VER=$(curl --silent --location https://pypi.org/pypi/torch/json | python -c "import sys, json, pkg_resources; releases = json.load(sys.stdin)['releases']; print(sorted(releases, key=pkg_resources.parse_version)[-1])") &&     TORCH_VISION_VER=$(curl --silent --location https://pypi.org/  52.2s
 => [compile-image 7/7] RUN pip install --no-cache-dir captum torchtext torchserve torch-model-archiver                                                                                                                                                                                                                           10.7s
 => [runtime-image 4/9] COPY --chown=model-server --from=compile-image /home/venv /home/venv                                                                                                                                                                                                                                       3.4s
 => [runtime-image 5/9] COPY dockerd-entrypoint.sh /usr/local/bin/dockerd-entrypoint.sh                                                                                                                                                                                                                                            0.0s
 => [runtime-image 6/9] RUN chmod +x /usr/local/bin/dockerd-entrypoint.sh     && chown -R model-server /home/model-server                                                                                                                                                                                                          0.3s
 => [runtime-image 7/9] COPY config.properties /home/model-server/config.properties                                                                                                                                                                                                                                                0.0s
 => [runtime-image 8/9] RUN mkdir /home/model-server/model-store && chown -R model-server /home/model-server/model-store                                                                                                                                                                                                           0.3s
 => [runtime-image 9/9] WORKDIR /home/model-server                                                                                                                                                                                                                                                                                 0.0s
 => exporting to image                                                                                                                                                                                                                                                                                                             8.8s
 => => exporting layers                                                                                                                                                                                                                                                                                                            8.8s
 => => writing image sha256:1e3a79552ae641f6c63133627267e1ff787bf00e1511119721065cfc6db021a8                                                                                                                                                                                                                                       0.0s
 => => naming to docker.io/pytorch/torchserve:latest-gpu                                                                                                                                                                                                                                                                           0.0s
(base) ➜  docker git:(master) docker images
REPOSITORY                           TAG                                                     IMAGE ID       CREATED          SIZE
pytorch/torchserve                   latest-gpu                                              1e3a79552ae6   15 seconds ago   4.29GB
```

**Comment by AlfredWGA** [comment]
@msaroufim Hi thank you for the reply. The problem comes from my internet issue. Sorry to bother, closing the issue here.
