### ISSUE TITLE
Custom handler response crashes worker with Netty IndexOutOfBoundsException exception.

### ISSUE THREAD

**Issue by clemens33** [pytorch/serve#1150]
Your issue may already be reported!
- Similar Issue has been reported but was closed (https://github.com/pytorch/serve/issues/455)

## Context

* torchserve version: 0.4.0
* torch-model-archiver version: 0.4.0
* java version: 
** openjdk 11.0.11 2021-04-20
** OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
** OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)
* Operating System and version: Ubuntu 20.04 + docker (issue happens also within docker)

## Your Environment

* Installed using source? [yes/no]: no
* Are you planning to deploy it using docker container? [yes/no]: yes
* Is it a CPU or GPU environment?: issue happens in CPU and GPU environments
* Using a default/custom handler? [If possible upload/share custom handler/model]: yes
* What kind of model is it e.g. vision, text, audio?:  text
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs:
* Link to your project [if any]: I have created a small repository trying to reconstruct the issue - please refer to https://github.com/clemens33/ts-issue

## Current Behavior

When using a custom handler including torchserve batch processing (e.g. "batchSize":256,"maxBatchDelay":100) in a high throughput setting (~100000 application/json requests) worker crashes sometimes with a io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(....

## Possible Solution

After some debugging with a very simple handler (no model used actually - just requests + dummy responses) the issue seams to be related to the either size of the response or complexity of the response within the custom handler.

e.g. seams like more simple/small response - less/no crashes
```
for query in outputs["queries"]:
            dummy_responses.append({
                "query": query,
                "results": ["dummy_class" + str(k) for k in range(3)]
            })
```

e.g. seams like larger/more complex response - more crashes
```
        for query in outputs["queries"]:
            dummy_responses.append({
                "query": query,
                "results": [{
                    "dummy_class" + str(k): 0.01,
                    "dummy_entry1": {
                        "stuff1": 1,
                        "stuff2": 2,
                        "stuff3": 3,
                        "stuff4": 4,
                        "stuff5": {
                            "explain1": 0.1,
                            "explain2": 0.1,
                        }
                    }
                } for k in range(3)]
            })
```

## Steps to Reproduce

I have created a small repository https://github.com/clemens33/ts-issue trying to recreate the issue. The repository includes a small test script which runs ~180000 requests against a within docker running "model". The used handler actually does not have any model - just takes the queries/requests and returns some dummy "complex/large" responses. Model to load, batch size and timeout is defined within docker/config.properties.

1. Clone https://github.com/clemens33/ts-issue
2. Cd into repo 
3. Start the dummy handler/model running in docker
```
docker run --rm --name ts-cpu-dummy -it -p 8080:8080 -p 8081:8081 -p 8082:8082 \
--mount type=bind,source=$(pwd)/logs/,target=/home/model-server/logs \
--mount type=bind,source=$(pwd)/model_store/,target=/home/model-server/model_store \
--mount type=bind,source=$(pwd)/docker/config.properties,target=/home/model-server/config.properties \
--mount type=bind,source=$(pwd)/docker/log4j.properties,target=/home/model-server/log4j.properties \
pytorch/torchserve:0.4.0-cpu \
torchserve \
--model-store=/home/model-server/model_store \
--ts-config config.properties \
--ncs --foreground
```
4. Create the conda environment and run the included test script 
```
conda env create --force -f environment.yml

conda activate ts-issue

python test.py
```

5. The script runs for a few minutes and should crash worker with the mentioned exception - Unfortunately I could not pin down the exact time/request when it happens - crash time changes or is random. If it does not crash the first time rerun the test script - should crash at some point - atleast for me;)

## Failure Logs [if any]

```2021-07-03 12:39:08,236 [ERROR] epollEventLoopGroup-5-3 org.pytorch.serve.wlm.WorkerThread - Unknown exception
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(65535) + length(4) exceeds writerIndex(65536): PooledUnsafeDirectByteBuf(ridx: 65535, widx: 65536, cap: 65536)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:471)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at io.netty.channel.epoll.EpollDomainSocketChannel$EpollDomainUnsafe.epollInReady(EpollDomainSocketChannel.java:138)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(65535) + length(4) exceeds writerIndex(65536): PooledUnsafeDirectByteBuf(ridx: 65535, widx: 65536, cap: 65536)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1478)
	at io.netty.buffer.AbstractByteBuf.readInt(AbstractByteBuf.java:811)
	at org.pytorch.serve.util.codec.ModelResponseDecoder.decode(ModelResponseDecoder.java:56)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	... 16 more
2021-07-03 12:39:08,237 [INFO ] epollEventLoopGroup-5-3 org.pytorch.serve.wlm.WorkerThread - 9001 Worker disconnected. WORKER_MODEL_LOADED
2021-07-03 12:39:08,238 [DEBUG] W-9001-dummy_1.0 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_MODEL_LOADED
2021-07-03 12:39:08,238 [DEBUG] W-9001-dummy_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133)
	at java.base/java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:432)
	at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:188)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-07-03 12:39:08,238 [ERROR] epollEventLoopGroup-5-3 org.pytorch.serve.wlm.WorkerThread - Unknown exception
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(65535) + length(4) exceeds writerIndex(65536): PooledUnsafeDirectByteBuf(ridx: 65535, widx: 65536, cap: 65536)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:471)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:404)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:371)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:819)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(65535) + length(4) exceeds writerIndex(65536): PooledUnsafeDirectByteBuf(ridx: 65535, widx: 65536, cap: 65536)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1478)
	at io.netty.buffer.AbstractByteBuf.readInt(AbstractByteBuf.java:811)
	at org.pytorch.serve.util.codec.ModelResponseDecoder.decode(ModelResponseDecoder.java:56)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	... 18 more
```

**Comment by HamidShojanazeri** [comment]
CC @lxning

**Comment by hsurana299** [comment]
Hi @HamidShojanazeri . Did you find a solution to this problem? I am facing the same issue .

**Comment by lxning** [comment]
@hsurana299 please try increase [max_response_size](https://github.com/pytorch/serve/blob/master/docs/configuration.md)

**Comment by hsurana299** [comment]
Thanks @lxning .
