### ISSUE TITLE
resnet example has a bug.

### ISSUE THREAD

**Issue by roundtable-swk** [pytorch/serve#1166]
https://github.com/pytorch/serve/tree/master/examples/image_classifier/resnet_18

## Context

torch                   1.9.0
torch-model-archiver    0.4.0
torch-workflow-archiver 0.1.0
torchserve              0.4.0
torchvision             0.10.0
* java version: 11.0.11
* Operating System and version: mac os big sur 11.4

## Your Environment

* Installed using source? [yes/no]: yes
* Are you planning to deploy it using docker container? [yes/no]: 
* Is it a CPU or GPU environment?: CPU
* Using a default/custom handler? [If possible upload/share custom handler/model]: default handler
* What kind of model is it e.g. vision, text, audio?: vision
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
  [If public url then provide link.]:no
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs:no
* Link to your project [if any]: 

## Expected Behavior
Serve resnet model

## Current Behavior
```
2021-07-16 15:59:21,706 [INFO ] W-9005-resnet18_1.0-stdout MODEL_LOG -     return super(RecursiveScriptModule, self).__getattr__(attr)
2021-07-16 15:59:21,706 [INFO ] W-9004-resnet18_1.0-stdout MODEL_LOG -   File "/Users/wontakryu/Library/Python/3.8/lib/python/site-packages/torch/nn/modules/module.py", line 1130, in __getattr__
2021-07-16 15:59:21,706 [INFO ] W-9004-resnet18_1.0-stdout MODEL_LOG -     raise AttributeError("'{}' object has no attribute '{}'".format(
2021-07-16 15:59:21,706 [INFO ] W-9004-resnet18_1.0-stdout MODEL_LOG - AttributeError: 'RecursiveScriptModule' object has no attribute 'copy'
2021-07-16 15:59:21,706 [INFO ] W-9005-resnet18_1.0-stdout MODEL_LOG -   File "/Users/wontakryu/Library/Python/3.8/lib/python/site-packages/torch/jit/_script.py", line 384, in __getattr__
2021-07-16 15:59:21,707 [INFO ] W-9005-resnet18_1.0-stdout MODEL_LOG -     return super(ScriptModule, self).__getattr__(attr)
2021-07-16 15:59:21,707 [INFO ] W-9005-resnet18_1.0-stdout MODEL_LOG -   File "/Users/wontakryu/Library/Python/3.8/lib/python/site-packages/torch/nn/modules/module.py", line 1130, in __getattr__
2021-07-16 15:59:21,707 [INFO ] W-9005-resnet18_1.0-stdout MODEL_LOG -     raise AttributeError("'{}' object has no attribute '{}'".format(
2021-07-16 15:59:21,707 [INFO ] W-9005-resnet18_1.0-stdout MODEL_LOG - AttributeError: 'RecursiveScriptModule' object has no attribute 'copy'
2021-07-16 15:59:21,706 [INFO ] W-9007-resnet18_1.0-stdout MODEL_LOG -   File "/Users/wontakryu/Library/Python/3.8/lib/python/site-packages/ts/torch_handler/base_handler.py", line 130, in _load_pickled_model
2021-07-16 15:59:21,707 [INFO ] W-9007-resnet18_1.0-stdout MODEL_LOG -     model.load_state_dict(state_dict)
2021-07-16 15:59:21,707 [INFO ] W-9007-resnet18_1.0-stdout MODEL_LOG -   File "/Users/wontakryu/Library/Python/3.8/lib/python/site-packages/torch/nn/modules/module.py", line 1379, in load_state_dict
2021-07-16 15:59:21,707 [INFO ] W-9007-resnet18_1.0-stdout MODEL_LOG -     state_dict = state_dict.copy()
2021-07-16 15:59:21,706 [INFO ] W-9006-resnet18_1.0-stdout MODEL_LOG -   File "/Users/wontakryu/Library/Python/3.8/lib/python/site-packages/torch/jit/_script.py", line 667, in __getattr__
2021-07-16 15:59:21,706 [INFO ] W-9000-resnet18_1.0-stdout MODEL_LOG -   File "/Users/wontakryu/Library/Python/3.8/lib/python/site-packages/ts/torch_handler/base_handler.py", line 130, in _load_pickled_model
2021-07-16 15:59:21,707 [INFO ] W-9007-resnet18_1.0-stdout MODEL_LOG -   File "/Users/wontakryu/Library/Python/3.8/lib/python/site-packages/torch/jit/_script.py", line 667, in __getattr__
2021-07-16 15:59:21,707 [INFO ] W-9006-resnet18_1.0-stdout MODEL_LOG -     return super(RecursiveScriptModule, self).__getattr__(attr)
2021-07-16 15:59:21,707 [INFO ] W-9000-resnet18_1.0-stdout MODEL_LOG -     model.load_state_dict(state_dict)
2021-07-16 15:59:21,707 [INFO ] W-9000-resnet18_1.0-stdout MODEL_LOG -   File "/Users/wontakryu/Library/Python/3.8/lib/python/site-packages/torch/nn/modules/module.py", line 1379, in load_state_dict
2021-07-16 15:59:21,707 [INFO ] W-9000-resnet18_1.0-stdout MODEL_LOG -     state_dict = state_dict.copy()
2021-07-16 15:59:21,707 [INFO ] W-9000-resnet18_1.0-stdout MODEL_LOG -   File "/Users/wontakryu/Library/Python/3.8/lib/python/site-packages/torch/jit/_script.py", line 667, in __getattr__
2021-07-16 15:59:21,707 [INFO ] W-9000-resnet18_1.0-stdout MODEL_LOG -     return super(RecursiveScriptModule, self).__getattr__(attr)
2021-07-16 15:59:21,707 [INFO ] W-9000-resnet18_1.0-stdout MODEL_LOG -   File "/Users/wontakryu/Library/Python/3.8/lib/python/site-packages/torch/jit/_script.py", line 384, in __getattr__
2021-07-16 15:59:21,707 [INFO ] W-9007-resnet18_1.0-stdout MODEL_LOG -     return super(RecursiveScriptModule, self).__getattr__(attr)
2021-07-16 15:59:21,707 [INFO ] W-9000-resnet18_1.0-stdout MODEL_LOG -     return super(ScriptModule, self).__getattr__(attr)
2021-07-16 15:59:21,707 [INFO ] W-9000-resnet18_1.0-stdout MODEL_LOG -   File "/Users/wontakryu/Library/Python/3.8/lib/python/site-packages/torch/nn/modules/module.py", line 1130, in __getattr__
2021-07-16 15:59:21,707 [INFO ] W-9000-resnet18_1.0-stdout MODEL_LOG -     raise AttributeError("'{}' object has no attribute '{}'".format(
2021-07-16 15:59:21,708 [INFO ] W-9000-resnet18_1.0-stdout MODEL_LOG - AttributeError: 'RecursiveScriptModule' object has no attribute 'copy'
2021-07-16 15:59:21,708 [INFO ] W-9006-resnet18_1.0-stdout MODEL_LOG -   File "/Users/wontakryu/Library/Python/3.8/lib/python/site-packages/torch/jit/_script.py", line 384, in __getattr__
2021-07-16 15:59:21,708 [INFO ] W-9007-resnet18_1.0-stdout MODEL_LOG -   File "/Users/wontakryu/Library/Python/3.8/lib/python/site-packages/torch/jit/_script.py", line 384, in __getattr__
2021-07-16 15:59:21,708 [INFO ] W-9007-resnet18_1.0-stdout MODEL_LOG -     return super(ScriptModule, self).__getattr__(attr)
2021-07-16 15:59:21,708 [INFO ] W-9007-resnet18_1.0-stdout MODEL_LOG -   File "/Users/wontakryu/Library/Python/3.8/lib/python/site-packages/torch/nn/modules/module.py", line 1130, in __getattr__
2021-07-16 15:59:21,708 [INFO ] W-9007-resnet18_1.0-stdout MODEL_LOG -     raise AttributeError("'{}' object has no attribute '{}'".format(
2021-07-16 15:59:21,708 [INFO ] W-9007-resnet18_1.0-stdout MODEL_LOG - AttributeError: 'RecursiveScriptModule' object has no attribute 'copy'
2021-07-16 15:59:21,708 [INFO ] W-9006-resnet18_1.0-stdout MODEL_LOG -     return super(ScriptModule, self).__getattr__(attr)
2021-07-16 15:59:21,708 [INFO ] W-9006-resnet18_1.0-stdout MODEL_LOG -   File "/Users/wontakryu/Library/Python/3.8/lib/python/site-packages/torch/nn/modules/module.py", line 1130, in __getattr__
2021-07-16 15:59:21,708 [INFO ] W-9006-resnet18_1.0-stdout MODEL_LOG -     raise AttributeError("'{}' object has no attribute '{}'".format(
2021-07-16 15:59:21,708 [INFO ] W-9006-resnet18_1.0-stdout MODEL_LOG - AttributeError: 'RecursiveScriptModule' object has no attribute 'copy'
2021-07-16 15:59:21,709 [INFO ] W-9003-resnet18_1.0-stdout MODEL_LOG - Backend worker process died.
2021-07-16 15:59:21,709 [INFO ] W-9003-resnet18_1.0-stdout MODEL_LOG - Traceback (most recent call last):
2021-07-16 15:59:21,709 [INFO ] W-9003-resnet18_1.0-stdout MODEL_LOG -   File "/Users/wontakryu/Library/Python/3.8/lib/python/site-packages/ts/model_service_worker.py", line 182, in <module>
2021-07-16 15:59:21,709 [INFO ] W-9003-resnet18_1.0-stdout MODEL_LOG -     worker.run_server()
2021-07-16 15:59:21,709 [INFO ] W-9003-resnet18_1.0-stdout MODEL_LOG -   File "/Users/wontakryu/Library/Python/3.8/lib/python/site-packages/ts/model_service_worker.py", line 154, in run_server
2021-07-16 15:59:21,709 [INFO ] W-9003-resnet18_1.0-stdout MODEL_LOG -     self.handle_connection(cl_socket)
2021-07-16 15:59:21,709 [INFO ] W-9003-resnet18_1.0-stdout MODEL_LOG -   File "/Users/wontakryu/Library/Python/3.8/lib/python/site-packages/ts/model_service_worker.py", line 116, in handle_connection
2021-07-16 15:59:21,709 [INFO ] W-9003-resnet18_1.0-stdout MODEL_LOG -     service, result, code = self.load_model(msg)
2021-07-16 15:59:21,709 [INFO ] W-9003-resnet18_1.0-stdout MODEL_LOG -   File "/Users/wontakryu/Library/Python/3.8/lib/python/site-packages/ts/model_service_worker.py", line 89, in load_model
2021-07-16 15:59:21,709 [INFO ] W-9003-resnet18_1.0-stdout MODEL_LOG -     service = model_loader.load(model_name, model_dir, handler, gpu, batch_size, envelope)
2021-07-16 15:59:21,709 [INFO ] W-9003-resnet18_1.0-stdout MODEL_LOG -   File "/Users/wontakryu/Library/Python/3.8/lib/python/site-packages/ts/model_loader.py", line 110, in load
2021-07-16 15:59:21,709 [INFO ] W-9003-resnet18_1.0-stdout MODEL_LOG -     initialize_fn(service.context)
2021-07-16 15:59:21,709 [INFO ] W-9003-resnet18_1.0-stdout MODEL_LOG -   File "/Users/wontakryu/Library/Python/3.8/lib/python/site-packages/ts/torch_handler/vision_handler.py", line 20, in initialize
2021-07-16 15:59:21,709 [INFO ] W-9003-resnet18_1.0-stdout MODEL_LOG -     super().initialize(context)
2021-07-16 15:59:21,709 [INFO ] W-9003-resnet18_1.0-stdout MODEL_LOG -   File "/Users/wontakryu/Library/Python/3.8/lib/python/site-packages/ts/torch_handler/base_handler.py", line 66, in initialize
2021-07-16 15:59:21,709 [INFO ] W-9003-resnet18_1.0-stdout MODEL_LOG -     self.model = self._load_pickled_model(model_dir, model_file, model_pt_path)
2021-07-16 15:59:21,709 [INFO ] W-9003-resnet18_1.0-stdout MODEL_LOG -   File "/Users/wontakryu/Library/Python/3.8/lib/python/site-packages/ts/torch_handler/base_handler.py", line 130, in _load_pickled_model
2021-07-16 15:59:21,709 [INFO ] W-9003-resnet18_1.0-stdout MODEL_LOG -     model.load_state_dict(state_dict)
2021-07-16 15:59:21,709 [INFO ] W-9003-resnet18_1.0-stdout MODEL_LOG -   File "/Users/wontakryu/Library/Python/3.8/lib/python/site-packages/torch/nn/modules/module.py", line 1379, in load_state_dict
2021-07-16 15:59:21,709 [INFO ] W-9003-resnet18_1.0-stdout MODEL_LOG -     state_dict = state_dict.copy()
2021-07-16 15:59:21,709 [INFO ] W-9003-resnet18_1.0-stdout MODEL_LOG -   File "/Users/wontakryu/Library/Python/3.8/lib/python/site-packages/torch/jit/_script.py", line 667, in __getattr__
2021-07-16 15:59:21,710 [INFO ] W-9003-resnet18_1.0-stdout MODEL_LOG -     return super(RecursiveScriptModule, self).__getattr__(attr)
2021-07-16 15:59:21,710 [INFO ] W-9003-resnet18_1.0-stdout MODEL_LOG -   File "/Users/wontakryu/Library/Python/3.8/lib/python/site-packages/torch/jit/_script.py", line 384, in __getattr__
2021-07-16 15:59:21,710 [INFO ] W-9003-resnet18_1.0-stdout MODEL_LOG -     return super(ScriptModule, self).__getattr__(attr)
2021-07-16 15:59:21,710 [INFO ] W-9003-resnet18_1.0-stdout MODEL_LOG -   File "/Users/wontakryu/Library/Python/3.8/lib/python/site-packages/torch/nn/modules/module.py", line 1130, in __getattr__
2021-07-16 15:59:21,710 [INFO ] W-9003-resnet18_1.0-stdout MODEL_LOG -     raise AttributeError("'{}' object has no attribute '{}'".format(
2021-07-16 15:59:21,710 [INFO ] W-9003-resnet18_1.0-stdout MODEL_LOG - AttributeError: 'RecursiveScriptModule' object has no attribute 'copy'
2021-07-16 15:59:21,738 [WARN ] W-9004-resnet18_1.0-stderr MODEL_LOG - /Users/wontakryu/Library/Python/3.8/lib/python/site-packages/torch/serialization.py:602: UserWarning: 'torch.load' received a zip file that looks like a TorchScript archive dispatching to 'torch.jit.load' (call 'torch.jit.load' directly to silence this warning)
2021-07-16 15:59:21,738 [WARN ] W-9004-resnet18_1.0-stderr MODEL_LOG -   warnings.warn("'torch.load' received a zip file that looks like a TorchScript archive"
2021-07-16 15:59:21,747 [WARN ] W-9007-resnet18_1.0-stderr MODEL_LOG - /Users/wontakryu/Library/Python/3.8/lib/python/site-packages/torch/serialization.py:602: UserWarning: 'torch.load' received a zip file that looks like a TorchScript archive dispatching to 'torch.jit.load' (call 'torch.jit.load' directly to silence this warning)
2021-07-16 15:59:21,747 [WARN ] W-9007-resnet18_1.0-stderr MODEL_LOG -   warnings.warn("'torch.load' received a zip file that looks like a TorchScript archive"
2021-07-16 15:59:21,774 [WARN ] W-9001-resnet18_1.0-stderr MODEL_LOG - /Users/wontakryu/Library/Python/3.8/lib/python/site-packages/torch/serialization.py:602: UserWarning: 'torch.load' received a zip file that looks like a TorchScript archive dispatching to 'torch.jit.load' (call 'torch.jit.load' directly to silence this warning)
2021-07-16 15:59:21,775 [WARN ] W-9001-resnet18_1.0-stderr MODEL_LOG -   warnings.warn("'torch.load' received a zip file that looks like a TorchScript archive"
```
## Steps to Reproduce

1. run example code following the README.md

...

**Comment by HamidShojanazeri** [comment]
@roundTTable I was not able to repro, it seems you have go this error testing the Torchscripted model, can you pls confirm which mode it was and sequence of steps you followed?
