### ISSUE TITLE
Model specific custom python requirements not woks

### ISSUE THREAD

**Issue by yurkoff-mv** [pytorch/serve#1168]
## Context
* torchserve version: 0.4.0
* torch-model-archiver version: 0.4.0
* torch version: 1.8.1+cu111
* torchvision version [if any]: 0.9.1+cu111
* torchtext version [if any]: 0.9.1
* torchaudio version [if any]: 0.8.1
* java version: OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
* Operating System and version: Windows 10

## Your Environment
* Installed using source? [yes/no]: no
* Are you planning to deploy it using docker container? [yes/no]: yes
* Is it a CPU or GPU environment?: CPU
* Using a default/custom handler? [If possible upload/share custom handler/model]: yes
* What kind of model is it e.g. vision, text, audio?: empty
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
  [If public url then provide link.]: local models from model-store

## Expected Behavior
`Numpy version is 1.20.3`

## Current Behavior
```
2021-07-22 17:29:42,822 [INFO ] W-9000-empty_model_1.0-stdout MODEL_LOG -   File "C:\Users\Lenovo\AppData\Local\Temp\models\05b4b5680f624d76981b26b665aa1461\empty_handler.py", line 2, in
<module>
2021-07-22 17:29:42,822 [WARN ] W-9000-empty_model_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-empty_model_1.0-stdout
2021-07-22 17:29:42,823 [INFO ] W-9000-empty_model_1.0-stdout MODEL_LOG -     import numpy as np
```

## Steps to Reproduce
1. Create a file **empty_handler.py**:
```
import logging
import numpy as np
from ts.torch_handler.base_handler import BaseHandler


logger = logging.getLogger(__name__)


class EmptyHandler(BaseHandler):
    valid_requests = ['get', 'insert', 'delete', 'update']

    def __init__(self):
        super().__init__()
        self._context = None
        self.initialized = False
        self.index = None
        self.manifest = None

    def initialize(self, context):
        self.manifest = context.manifest

        properties = context.system_properties
        model_dir = properties.get("model_dir")
        logger.info('Empty model from path {0} initialized successfully'.format(model_dir))
        logger.info('Numpy version is {}'.format(np.__version__))
        self.initialized = True

    def preprocess(self, input_data):
        data = input_data[0].get("data")
        if data is None:
            data = input_data[0].get("body")
        return data

    def inference(self, input_data):
        logger.info("Empty model inference...")
        return [{'response': 'OK', 'message': 'success'}]

    def postprocess(self, inference_output):
        postprocess_output = inference_output
        return postprocess_output

    def handle(self, data, context):
        model_input = self.preprocess(data)
        model_output = self.inference(model_input)
        return self.postprocess(model_output)
```

2. Create a file **requirements_empty.txt**:
`numpy==1.20.3`

3.  Create mar-file by folowing command:
```
torch-model-archiver --model-name "empty_model" --version 1.0 --handler "./empty_handler.py" --requirements-file "requirements_empty.txt" --export-
path model_store
```
4. Start TorchServe:
`torchserve --start --model-store model_store --models empty_model=empty_model.mar`
...

## Failure Logs
```
(venv) D:\work\projects\python\index_db>2021-07-22 17:29:40,188 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager -  Loading snapshot serializer plugin...
2021-07-22 17:29:41,134 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager - Initializing plugins manager...
2021-07-22 17:29:41,687 [INFO ] main org.pytorch.serve.ModelServer -
Torchserve version: 0.4.0
TS Home: D:\work\projects\python\index_db\venv\Lib\site-packages
Current directory: D:\work\projects\python\index_db
Temp directory: C:\Users\Lenovo\AppData\Local\Temp
Number of GPUs: 1
Number of CPUs: 8
Max heap size: 4070 M
Python executable: d:\work\projects\python\index_db\venv\scripts\python.exe
Config file: config.properties
Inference address: http://127.0.0.1:8080
Management address: http://127.0.0.1:8081
Metrics address: http://127.0.0.1:8082
Model Store: D:\work\projects\python\index_db\model_store
Initial Models: empty_model=empty_model.mar
Log dir: D:\work\projects\python\index_db\logs
Metrics dir: D:\work\projects\python\index_db\logs
Netty threads: 0
Netty client threads: 0
Default workers per model: 1
Blacklist Regex: N/A
Maximum Response Size: 1073741824
Maximum Request Size: 1073741824
Prefer direct buffer: false
Allowed Urls: [file://.*|http(s)?://.*]
Custom python dependency for model allowed: false
Metrics report format: prometheus
Enable metrics API: true
Workflow Store: D:\work\projects\python\index_db\model_store
2021-07-22 17:29:41,698 [INFO ] main org.pytorch.serve.ModelServer - Loading initial models: empty_model.mar
2021-07-22 17:29:41,726 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Adding new version 1.0 for model empty_model
2021-07-22 17:29:41,726 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Setting default version to 1.0 for model empty_model
2021-07-22 17:29:41,726 [INFO ] main org.pytorch.serve.wlm.ModelManager - Model empty_model loaded.
2021-07-22 17:29:41,727 [DEBUG] main org.pytorch.serve.wlm.ModelManager - updateModel: empty_model, count: 1
2021-07-22 17:29:41,743 [INFO ] main org.pytorch.serve.ModelServer - Initialize Inference server with: NioServerSocketChannel.
2021-07-22 17:29:42,622 [INFO ] main org.pytorch.serve.ModelServer - Inference API bind to: http://127.0.0.1:8080
2021-07-22 17:29:42,622 [INFO ] main org.pytorch.serve.ModelServer - Initialize Management server with: NioServerSocketChannel.
2021-07-22 17:29:42,625 [INFO ] main org.pytorch.serve.ModelServer - Management API bind to: http://127.0.0.1:8081
2021-07-22 17:29:42,625 [INFO ] main org.pytorch.serve.ModelServer - Initialize Metrics server with: NioServerSocketChannel.
2021-07-22 17:29:42,627 [INFO ] main org.pytorch.serve.ModelServer - Metrics API bind to: http://127.0.0.1:8082
2021-07-22 17:29:42,736 [INFO ] W-9000-empty_model_1.0-stdout MODEL_LOG - Listening on port: None
2021-07-22 17:29:42,739 [INFO ] W-9000-empty_model_1.0-stdout MODEL_LOG - [PID]21316
2021-07-22 17:29:42,739 [INFO ] W-9000-empty_model_1.0-stdout MODEL_LOG - Torch worker started.
2021-07-22 17:29:42,740 [INFO ] W-9000-empty_model_1.0-stdout MODEL_LOG - Python runtime: 3.7.9
2021-07-22 17:29:42,740 [DEBUG] W-9000-empty_model_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-empty_model_1.0 State change null -> WORKER_STARTED
2021-07-22 17:29:42,745 [INFO ] W-9000-empty_model_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /127.0.0.1:9000
2021-07-22 17:29:42,760 [INFO ] W-9000-empty_model_1.0-stdout MODEL_LOG - Connection accepted: ('127.0.0.1', 9000).
2021-07-22 17:29:42,808 [INFO ] W-9000-empty_model_1.0-stdout MODEL_LOG - Backend worker process died.
2021-07-22 17:29:42,808 [INFO ] W-9000-empty_model_1.0-stdout MODEL_LOG - Traceback (most recent call last):
2021-07-22 17:29:42,811 [INFO ] W-9000-empty_model_1.0-stdout MODEL_LOG -   File "d:\work\projects\python\index_db\venv\lib\site-packages\ts\model_loader.py", line 81, in load
2021-07-22 17:29:42,813 [INFO ] W-9000-empty_model_1.0-stdout MODEL_LOG -     module, function_name = self._load_handler_file(handler)
2021-07-22 17:29:42,813 [INFO ] nioEventLoopGroup-5-1 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_STARTED
2021-07-22 17:29:42,813 [INFO ] W-9000-empty_model_1.0-stdout MODEL_LOG -   File "d:\work\projects\python\index_db\venv\lib\site-packages\ts\model_loader.py", line 121, in _load_handler_f
ile
2021-07-22 17:29:42,814 [DEBUG] W-9000-empty_model_1.0 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_STARTED
2021-07-22 17:29:42,815 [INFO ] W-9000-empty_model_1.0-stdout MODEL_LOG -     module = importlib.import_module(module_name)
2021-07-22 17:29:42,816 [INFO ] W-9000-empty_model_1.0-stdout MODEL_LOG -   File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_mo
dule
2021-07-22 17:29:42,817 [INFO ] W-9000-empty_model_1.0-stdout MODEL_LOG -     return _bootstrap._gcd_import(name[level:], package, level)
2021-07-22 17:29:42,817 [INFO ] W-9000-empty_model_1.0-stdout MODEL_LOG -   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
2021-07-22 17:29:42,818 [INFO ] W-9000-empty_model_1.0-stdout MODEL_LOG -   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
2021-07-22 17:29:42,818 [INFO ] W-9000-empty_model_1.0-stdout MODEL_LOG -   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
2021-07-22 17:29:42,816 [DEBUG] W-9000-empty_model_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133)
        at java.base/java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:432)
        at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:188)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
2021-07-22 17:29:42,819 [INFO ] W-9000-empty_model_1.0-stdout MODEL_LOG -   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
2021-07-22 17:29:42,820 [WARN ] W-9000-empty_model_1.0 org.pytorch.serve.wlm.BatchAggregator - Load model failed: empty_model, error: Worker died.
2021-07-22 17:29:42,821 [INFO ] W-9000-empty_model_1.0-stdout MODEL_LOG -   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
2021-07-22 17:29:42,821 [DEBUG] W-9000-empty_model_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-empty_model_1.0 State change WORKER_STARTED -> WORKER_STOPPED
2021-07-22 17:29:42,821 [INFO ] W-9000-empty_model_1.0-stdout MODEL_LOG -   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2021-07-22 17:29:42,822 [WARN ] W-9000-empty_model_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-empty_model_1.0-stderr
2021-07-22 17:29:42,822 [INFO ] W-9000-empty_model_1.0-stdout MODEL_LOG -   File "C:\Users\Lenovo\AppData\Local\Temp\models\05b4b5680f624d76981b26b665aa1461\empty_handler.py", line 2, in
<module>
2021-07-22 17:29:42,822 [WARN ] W-9000-empty_model_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-empty_model_1.0-stdout
2021-07-22 17:29:42,823 [INFO ] W-9000-empty_model_1.0-stdout MODEL_LOG -     import numpy as np
2021-07-22 17:29:42,825 [INFO ] W-9000-empty_model_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-empty_model_1.0-stdout
2021-07-22 17:29:42,827 [INFO ] W-9000-empty_model_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9000 in 1 seconds.
2021-07-22 17:29:42,828 [INFO ] W-9000-empty_model_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-empty_model_1.0-stderr
Model server started.
```

**Comment by yurkoff-mv** [comment]
Sorry, I was wrong.
The feature works. You need to write a line **`install_py_dep_per_model=true`** in the file **config.properties** and start the service with the flag **`--ts-config config.properties`**:
`torchserve --start --ncs --model-store model_store --models empty_model=empty_model.mar --ts-config config.properties
`

**Comment by HamidShojanazeri** [comment]
@yurkoff-mv Thanks for the update, that is the right way to use this feature.
