### ISSUE TITLE
Combining all REST API to one endpoint

### ISSUE THREAD

**Issue by ArtemisDicoTiar** [pytorch/serve#1177]
## Is your feature request related to a problem? Please describe.

Currently, I am using cloud platform that isn't either AWS, Azure or GCP.
Therefore, the docker container setting for torch_serve deployment is insufficient to expose multiple ports.
The torchserve uses 3 REST API ports (8080, 8081, 8082) for different purpose.
I have tried to put a nginx for reverse proxy in torchserve-cpu docker image but it seems like nginx is not working.

## Describe the solution

Combine all separate endpoints: model-management, inference, metrics → to one endpoint.
eg.
localhost:8000/infer
localhost:8000/manage
localhost:8000/metrics

**Comment by msaroufim** [comment]
Hi @ArtemisDicoTiar you should be able to expose multiple ports with Docker and torchserve already https://github.com/pytorch/serve/tree/master/docker

From the very bottom of that page 

```
docker run --rm --shm-size=1g \
        --ulimit memlock=-1 \
        --ulimit stack=67108864 \
        -p8080:8080 \
        -p8081:8081 \
        -p8082:8082 \
        -p7070:7070 \
        -p7071:7071 \
        --mount type=bind,source=/path/to/model/store,target=/tmp/models <container> torchserve --model-store=/tmp/models 


```



If you'd like to combine all the endpoints try changing your `config.properties` here is an example https://github.com/pytorch/serve/blob/master/benchmarks/config.properties

I don't have much experience with ngninx to help but if you can provide more insight I'd be happy to help

**Comment by lxning** [comment]
@ArtemisDicoTiar you can config all endpoint on the same port in config.properties.eg
inference_address=https://127.0.0.1:8080
management_address=https://127.0.0.1:8080
metrics_address=https://127.0.0.1:8080

**Comment by ArtemisDicoTiar** [comment]
@lxning I have tried that before and have just tried now and the bash shows same error that torch serve fails binding to the address
~~~
2021-08-16 22:03:32,536 [INFO ] main org.pytorch.serve.ModelServer - Torchserve stopped.
java.io.IOException: Failed to bind to address: https://127.0.0.1:8080
	at org.pytorch.serve.ModelServer.initializeServer(ModelServer.java:282)
	at org.pytorch.serve.ModelServer.startRESTserver(ModelServer.java:365)
	at org.pytorch.serve.ModelServer.startAndWait(ModelServer.java:114)
	at org.pytorch.serve.ModelServer.main(ModelServer.java:95)
Caused by: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
Exception in thread "Thread-0" java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:926)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:346)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:828)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:818)
	at io.netty.channel.AbstractChannelHandlerContext.safeExecute(AbstractChannelHandlerContext.java:989)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:608)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:472)
	at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:957)
	at io.netty.channel.AbstractChannel.close(AbstractChannel.java:232)
	at org.pytorch.serve.ModelServer.stop(ModelServer.java:473)
	at org.pytorch.serve.ModelServer$1.run(ModelServer.java:91)
~~~

**Comment by lxning** [comment]
@ArtemisDicoTiar sorry for the wrong info. both inference_address and management_address can share the same port. metrics_address needs a separate port.

**Comment by ArtemisDicoTiar** [comment]
@lxning Thank you. I think this can be one of the solution that I am struggling now! :)

**Comment by msaroufim** [comment]
@ArtemisDicoTiar do you mind sharing which cloud provider you're using? Is this an on prem setup?
