### ISSUE TITLE
Register Model

### ISSUE THREAD

**Issue by Apachaika** [pytorch/serve#1185]
Hello everyone!

I have problem with register models in TorchServe via gRPC or POST request.

My problem in details: 

- I successfully start Server by MAR file. I have done  torch-model-archiver:

```
torch-model-archiver --model-name bot_NN --version 1.0 --serialized-file ./model-store/fraud/model.pt --handler ./handlers/fraud_handler --runtime python3 --extra-files ./model-store/fraud/scaler.bin --export-path model-store/fraud
 ```

- Then start server

```
torchserve --start --ncs --model-store model-store/fraud --models bot_NN.mar --ts-config config.properties
```

- Server is up
```
2021-08-06 14:19:52,717 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager - Initializing plugins manager...
2021-08-06 14:19:52,880 [INFO ] main org.pytorch.serve.ModelServer - 
Torchserve version: 0.4.2
TS Home: /home/alexey/.local/lib/python3.8/site-packages
Current directory: /home/alexey/botserve
Temp directory: /tmp
Number of GPUs: 0
Number of CPUs: 4
Max heap size: 3972 M
Python executable: /usr/bin/python3
Config file: config.properties
Inference address: http://0.0.0.0:8080
Management address: http://0.0.0.0:8081
Metrics address: http://0.0.0.0:8082
Model Store: /home/alexey/botserve/model-store/fraud
Initial Models: bot_NN.mar
Log dir: /home/alexey/botserve/logs
Metrics dir: /home/alexey/botserve/logs
Netty threads: 0
Netty client threads: 0
Default workers per model: 4
Blacklist Regex: N/A
Maximum Response Size: 400000000
Maximum Request Size: 400000000
Prefer direct buffer: false
Allowed Urls: [file://.*|http(s)?://.*]
Custom python dependency for model allowed: false
Metrics report format: prometheus
Enable metrics API: true
Workflow Store: /home/alexey/botserve/model-store/fraud
Model config: N/A
2021-08-06 14:19:52,889 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager -  Loading snapshot serializer plugin...
2021-08-06 14:19:52,924 [INFO ] main org.pytorch.serve.ModelServer - Loading initial models: bot_NN.mar
2021-08-06 14:19:52,985 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Adding new version 1.0 for model bot_NN
2021-08-06 14:19:52,985 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Setting default version to 1.0 for model bot_NN
2021-08-06 14:19:52,985 [INFO ] main org.pytorch.serve.wlm.ModelManager - Model bot_NN loaded.
2021-08-06 14:19:52,985 [DEBUG] main org.pytorch.serve.wlm.ModelManager - updateModel: bot_NN, count: 4
2021-08-06 14:19:53,026 [INFO ] main org.pytorch.serve.ModelServer - Initialize Inference server with: EpollServerSocketChannel.
2021-08-06 14:19:53,390 [INFO ] main org.pytorch.serve.ModelServer - Inference API bind to: http://0.0.0.0:8080
2021-08-06 14:19:53,390 [INFO ] main org.pytorch.serve.ModelServer - Initialize Management server with: EpollServerSocketChannel.
2021-08-06 14:19:53,409 [INFO ] main org.pytorch.serve.ModelServer - Management API bind to: http://0.0.0.0:8081
2021-08-06 14:19:53,409 [INFO ] main org.pytorch.serve.ModelServer - Initialize Metrics server with: EpollServerSocketChannel.
2021-08-06 14:19:53,410 [INFO ] main org.pytorch.serve.ModelServer - Metrics API bind to: http://0.0.0.0:8082
Model server started.
2021-08-06 14:19:53,963 [WARN ] pool-2-thread-1 org.pytorch.serve.metrics.MetricCollector - worker pid is not available yet.
2021-08-06 14:19:54,044 [INFO ] pool-2-thread-1 TS_METRICS - CPUUtilization.Percent:0.0|#Level:Host|#hostname:alexey-GB-BKi5-H-A-7200,timestamp:1628248794
2021-08-06 14:19:54,046 [INFO ] pool-2-thread-1 TS_METRICS - DiskAvailable.Gigabytes:114.43140029907227|#Level:Host|#hostname:alexey-GB-BKi5-H-A-7200,timestamp:1628248794
2021-08-06 14:19:54,048 [INFO ] pool-2-thread-1 TS_METRICS - DiskUsage.Gigabytes:101.66972732543945|#Level:Host|#hostname:alexey-GB-BKi5-H-A-7200,timestamp:1628248794
2021-08-06 14:19:54,051 [INFO ] pool-2-thread-1 TS_METRICS - DiskUtilization.Percent:47.0|#Level:Host|#hostname:alexey-GB-BKi5-H-A-7200,timestamp:1628248794
2021-08-06 14:19:54,051 [INFO ] pool-2-thread-1 TS_METRICS - MemoryAvailable.Megabytes:4388.8203125|#Level:Host|#hostname:alexey-GB-BKi5-H-A-7200,timestamp:1628248794
2021-08-06 14:19:54,052 [INFO ] pool-2-thread-1 TS_METRICS - MemoryUsed.Megabytes:9965.0859375|#Level:Host|#hostname:alexey-GB-BKi5-H-A-7200,timestamp:1628248794
2021-08-06 14:19:54,053 [INFO ] pool-2-thread-1 TS_METRICS - MemoryUtilization.Percent:72.4|#Level:Host|#hostname:alexey-GB-BKi5-H-A-7200,timestamp:1628248794
2021-08-06 14:19:54,259 [INFO ] W-9003-bot_NN_1.0-stdout MODEL_LOG - Listening on port: /tmp/.ts.sock.9003
2021-08-06 14:19:54,260 [INFO ] W-9003-bot_NN_1.0-stdout MODEL_LOG - [PID]304132
2021-08-06 14:19:54,260 [INFO ] W-9003-bot_NN_1.0-stdout MODEL_LOG - Torch worker started.
2021-08-06 14:19:54,261 [INFO ] W-9003-bot_NN_1.0-stdout MODEL_LOG - Python runtime: 3.8.10
2021-08-06 14:19:54,261 [DEBUG] W-9003-bot_NN_1.0 org.pytorch.serve.wlm.WorkerThread - W-9003-bot_NN_1.0 State change null -> WORKER_STARTED
2021-08-06 14:19:54,268 [INFO ] W-9003-bot_NN_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /tmp/.ts.sock.9003
2021-08-06 14:19:54,286 [INFO ] main org.pytorch.serve.ModelServer - Torchserve stopped.
2021-08-06 14:19:54,288 [INFO ] Thread-6 org.pytorch.serve.ModelServer - Unregistering model densenet161 version 1.0
2021-08-06 14:19:54,288 [DEBUG] Thread-6 org.pytorch.serve.wlm.ModelVersionedRefs - Removed model: densenet161 version: 1.0
2021-08-06 14:19:54,291 [DEBUG] Thread-6 org.pytorch.serve.wlm.WorkerThread - W-9004-densenet161_1.0 State change WORKER_MODEL_LOADED -> WORKER_SCALED_DOWN
2021-08-06 14:19:54,291 [WARN ] Thread-6 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9004-densenet161_1.0-stderr
2021-08-06 14:19:54,291 [WARN ] Thread-6 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9004-densenet161_1.0-stdout
2021-08-06 14:19:54,292 [DEBUG] W-9004-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_SCALED_DOWN
2021-08-06 14:19:54,292 [DEBUG] W-9004-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread - Shutting down the thread .. Scaling down.
2021-08-06 14:19:54,292 [INFO ] W-9004-densenet161_1.0-stdout MODEL_LOG - Frontend disconnected.
2021-08-06 14:19:54,293 [INFO ] epollEventLoopGroup-5-5 org.pytorch.serve.wlm.WorkerThread - 9004 Worker disconnected. WORKER_SCALED_DOWN
2021-08-06 14:19:54,293 [DEBUG] W-9004-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread - W-9004-densenet161_1.0 State change WORKER_SCALED_DOWN -> WORKER_STOPPED
2021-08-06 14:19:54,292 [INFO ] W-9004-densenet161_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9004-densenet161_1.0-stdout
2021-08-06 14:19:54,294 [WARN ] W-9004-densenet161_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9004-densenet161_1.0-stderr
2021-08-06 14:19:54,294 [WARN ] W-9004-densenet161_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9004-densenet161_1.0-stdout
2021-08-06 14:19:54,294 [DEBUG] W-9004-densenet161_1.0 org.pytorch.serve.wlm.WorkerThread - Worker terminated due to scale-down call.
2021-08-06 14:19:54,327 [INFO ] Thread-6 org.pytorch.serve.wlm.ModelManager - Model densenet161 unregistered.
2021-08-06 14:19:54,327 [INFO ] Thread-6 org.pytorch.serve.ModelServer - Unregistering model bot_NN version 1.0
2021-08-06 14:19:54,327 [DEBUG] Thread-6 org.pytorch.serve.wlm.ModelVersionedRefs - Removed model: bot_NN version: 1.0
2021-08-06 14:19:54,327 [DEBUG] Thread-6 org.pytorch.serve.wlm.WorkerThread - W-9003-bot_NN_1.0 State change WORKER_MODEL_LOADED -> WORKER_SCALED_DOWN
2021-08-06 14:19:54,328 [INFO ] epollEventLoopGroup-5-1 org.pytorch.serve.wlm.WorkerThread - 9003 Worker disconnected. WORKER_SCALED_DOWN
2021-08-06 14:19:54,328 [INFO ] W-9003-bot_NN_1.0-stdout MODEL_LOG - Frontend disconnected.
2021-08-06 14:19:54,328 [DEBUG] W-9003-bot_NN_1.0 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_SCALED_DOWN
2021-08-06 14:19:54,328 [DEBUG] W-9003-bot_NN_1.0 org.pytorch.serve.wlm.WorkerThread - Shutting down the thread .. Scaling down.
2021-08-06 14:19:54,328 [DEBUG] W-9003-bot_NN_1.0 org.pytorch.serve.wlm.WorkerThread - W-9003-bot_NN_1.0 State change WORKER_SCALED_DOWN -> WORKER_STOPPED
2021-08-06 14:19:54,328 [WARN ] W-9003-bot_NN_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9003-bot_NN_1.0-stderr
2021-08-06 14:19:54,328 [WARN ] W-9003-bot_NN_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9003-bot_NN_1.0-stdout
2021-08-06 14:19:54,328 [DEBUG] W-9003-bot_NN_1.0 org.pytorch.serve.wlm.WorkerThread - Worker terminated due to scale-down call.
2021-08-06 14:19:54,343 [INFO ] W-9003-bot_NN_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9003-bot_NN_1.0-stderr
2021-08-06 14:19:54,346 [WARN ] Thread-6 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9003-bot_NN_1.0-stderr
2021-08-06 14:19:54,346 [WARN ] Thread-6 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9003-bot_NN_1.0-stdout
2021-08-06 14:19:54,356 [INFO ] W-9003-bot_NN_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9003-bot_NN_1.0-stdout
2021-08-06 14:19:54,355 [ERROR] W-9003-bot_NN_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker error
org.pytorch.serve.wlm.WorkerInitializationException: Failed to connect to worker.
	at org.pytorch.serve.wlm.WorkerThread.connect(WorkerThread.java:357)
	at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:179)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.FileNotFoundException
	at io.netty.channel.unix.Errors.throwConnectException(Errors.java:122)
	at io.netty.channel.unix.Socket.connect(Socket.java:239)
	at io.netty.channel.epoll.AbstractEpollChannel.doConnect0(AbstractEpollChannel.java:736)
	at io.netty.channel.epoll.AbstractEpollChannel.doConnect(AbstractEpollChannel.java:721)
	at io.netty.channel.epoll.EpollDomainSocketChannel.doConnect(EpollDomainSocketChannel.java:87)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.connect(AbstractEpollChannel.java:563)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:517)
	at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:978)
	at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:253)
	at io.netty.bootstrap.Bootstrap$3.run(Bootstrap.java:250)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
2021-08-06 14:19:54,361 [DEBUG] Thread-6 org.pytorch.serve.wlm.WorkerThread - W-9002-bot_NN_1.0 State change WORKER_MODEL_LOADED -> WORKER_SCALED_DOWN
2021-08-06 14:19:54,361 [WARN ] Thread-6 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9002-bot_NN_1.0-stderr
2021-08-06 14:19:54,361 [WARN ] Thread-6 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9002-bot_NN_1.0-stdout
2021-08-06 14:19:54,361 [DEBUG] W-9002-bot_NN_1.0 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_SCALED_DOWN
2021-08-06 14:19:54,361 [DEBUG] W-9002-bot_NN_1.0 org.pytorch.serve.wlm.WorkerThread - Shutting down the thread .. Scaling down.
2021-08-06 14:19:54,362 [DEBUG] W-9002-bot_NN_1.0 org.pytorch.serve.wlm.WorkerThread - W-9002-bot_NN_1.0 State change WORKER_SCALED_DOWN -> WORKER_STOPPED
2021-08-06 14:19:54,363 [WARN ] W-9002-bot_NN_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9002-bot_NN_1.0-stderr
2021-08-06 14:19:54,363 [WARN ] W-9002-bot_NN_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9002-bot_NN_1.0-stdout
2021-08-06 14:19:54,363 [DEBUG] W-9002-bot_NN_1.0 org.pytorch.serve.wlm.WorkerThread - Worker terminated due to scale-down call.
2021-08-06 14:19:54,370 [INFO ] epollEventLoopGroup-5-3 org.pytorch.serve.wlm.WorkerThread - 9002 Worker disconnected. WORKER_SCALED_DOWN
2021-08-06 14:19:54,372 [INFO ] W-9004-densenet161_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9004-densenet161_1.0-stderr
2021-08-06 14:19:54,372 [INFO ] W-9002-bot_NN_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9002-bot_NN_1.0-stdout
2021-08-06 14:19:54,372 [INFO ] W-9002-bot_NN_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9002-bot_NN_1.0-stderr
2021-08-06 14:19:54,377 [DEBUG] Thread-6 org.pytorch.serve.wlm.WorkerThread - W-9001-bot_NN_1.0 State change WORKER_MODEL_LOADED -> WORKER_SCALED_DOWN
2021-08-06 14:19:54,378 [WARN ] Thread-6 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9001-bot_NN_1.0-stderr
2021-08-06 14:19:54,378 [WARN ] Thread-6 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9001-bot_NN_1.0-stdout
2021-08-06 14:19:54,378 [DEBUG] W-9001-bot_NN_1.0 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_SCALED_DOWN
2021-08-06 14:19:54,378 [DEBUG] W-9001-bot_NN_1.0 org.pytorch.serve.wlm.WorkerThread - Shutting down the thread .. Scaling down.
2021-08-06 14:19:54,378 [INFO ] epollEventLoopGroup-5-4 org.pytorch.serve.wlm.WorkerThread - 9001 Worker disconnected. WORKER_SCALED_DOWN
2021-08-06 14:19:54,378 [INFO ] W-9001-bot_NN_1.0-stdout MODEL_LOG - ======= MODEL LOG =======
2021-08-06 14:19:54,383 [INFO ] W-9001-bot_NN_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9001-bot_NN_1.0-stdout
2021-08-06 14:19:54,378 [DEBUG] W-9001-bot_NN_1.0 org.pytorch.serve.wlm.WorkerThread - W-9001-bot_NN_1.0 State change WORKER_SCALED_DOWN -> WORKER_STOPPED
2021-08-06 14:19:54,383 [WARN ] W-9001-bot_NN_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9001-bot_NN_1.0-stderr
2021-08-06 14:19:54,383 [WARN ] W-9001-bot_NN_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9001-bot_NN_1.0-stdout
2021-08-06 14:19:54,383 [DEBUG] W-9001-bot_NN_1.0 org.pytorch.serve.wlm.WorkerThread - Worker terminated due to scale-down call.
2021-08-06 14:19:54,403 [INFO ] W-9001-bot_NN_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9001-bot_NN_1.0-stderr
2021-08-06 14:19:54,404 [DEBUG] Thread-6 org.pytorch.serve.wlm.WorkerThread - W-9000-bot_NN_1.0 State change WORKER_MODEL_LOADED -> WORKER_SCALED_DOWN
2021-08-06 14:19:54,404 [WARN ] Thread-6 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-bot_NN_1.0-stderr
2021-08-06 14:19:54,404 [WARN ] Thread-6 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-bot_NN_1.0-stdout
2021-08-06 14:19:54,404 [INFO ] epollEventLoopGroup-5-2 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_SCALED_DOWN
2021-08-06 14:19:54,405 [WARN ] W-9000-bot_NN_1.0-stderr MODEL_LOG - /home/alexey/.local/lib/python3.8/site-packages/ts/model_service_worker.py:114: DtypeWarning: Columns (30,31,32,33,34,35,36,37,38,39,40,41) have mixed types.Specify dtype option on import or set low_memory=False.
2021-08-06 14:19:54,405 [DEBUG] W-9000-bot_NN_1.0 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_SCALED_DOWN
2021-08-06 14:19:54,405 [DEBUG] W-9000-bot_NN_1.0 org.pytorch.serve.wlm.WorkerThread - Shutting down the thread .. Scaling down.
2021-08-06 14:19:54,405 [INFO ] W-9000-bot_NN_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-bot_NN_1.0-stderr
2021-08-06 14:19:54,405 [DEBUG] W-9000-bot_NN_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-bot_NN_1.0 State change WORKER_SCALED_DOWN -> WORKER_STOPPED
2021-08-06 14:19:54,406 [WARN ] W-9000-bot_NN_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-bot_NN_1.0-stderr
2021-08-06 14:19:54,407 [WARN ] W-9000-bot_NN_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-bot_NN_1.0-stdout
2021-08-06 14:19:54,407 [DEBUG] W-9000-bot_NN_1.0 org.pytorch.serve.wlm.WorkerThread - Worker terminated due to scale-down call.
2021-08-06 14:19:54,407 [INFO ] W-9000-bot_NN_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-bot_NN_1.0-stdout
2021-08-06 14:19:54,416 [INFO ] W-9002-bot_NN_1.0-stdout MODEL_LOG - Listening on port: /tmp/.ts.sock.9002
2021-08-06 14:19:54,419 [INFO ] W-9002-bot_NN_1.0-stdout MODEL_LOG - [PID]304130
2021-08-06 14:19:54,421 [INFO ] Thread-6 org.pytorch.serve.wlm.ModelManager - Model bot_NN unregistered.
2021-08-06 14:19:54,420 [INFO ] W-9002-bot_NN_1.0-stdout MODEL_LOG - Torch worker started.
2021-08-06 14:19:54,421 [DEBUG] W-9002-bot_NN_1.0 org.pytorch.serve.wlm.WorkerThread - W-9002-bot_NN_1.0 State change null -> WORKER_STARTED
2021-08-06 14:19:54,427 [INFO ] W-9002-bot_NN_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /tmp/.ts.sock.9002
2021-08-06 14:19:54,430 [INFO ] W-9000-bot_NN_1.0-stdout MODEL_LOG - Listening on port: /tmp/.ts.sock.9000
2021-08-06 14:19:54,433 [INFO ] W-9000-bot_NN_1.0-stdout MODEL_LOG - [PID]304131
2021-08-06 14:19:54,434 [INFO ] W-9000-bot_NN_1.0-stdout MODEL_LOG - Torch worker started.
2021-08-06 14:19:54,434 [INFO ] W-9000-bot_NN_1.0-stdout MODEL_LOG - Python runtime: 3.8.10
2021-08-06 14:19:54,433 [INFO ] W-9002-bot_NN_1.0-stdout MODEL_LOG - Python runtime: 3.8.10
2021-08-06 14:19:54,435 [DEBUG] W-9000-bot_NN_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-bot_NN_1.0 State change null -> WORKER_STARTED
2021-08-06 14:19:54,435 [INFO ] W-9000-bot_NN_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /tmp/.ts.sock.9000
2021-08-06 14:19:54,442 [INFO ] W-9002-bot_NN_1.0-stdout MODEL_LOG - Connection accepted: /tmp/.ts.sock.9002.
2021-08-06 14:19:54,442 [INFO ] W-9000-bot_NN_1.0-stdout MODEL_LOG - Connection accepted: /tmp/.ts.sock.9000.
2021-08-06 14:19:54,445 [INFO ] W-9001-bot_NN_1.0-stdout MODEL_LOG - Listening on port: /tmp/.ts.sock.9001
2021-08-06 14:19:54,446 [INFO ] W-9001-bot_NN_1.0-stdout MODEL_LOG - [PID]304129
2021-08-06 14:19:54,446 [INFO ] W-9001-bot_NN_1.0-stdout MODEL_LOG - Torch worker started.
2021-08-06 14:19:54,446 [DEBUG] W-9001-bot_NN_1.0 org.pytorch.serve.wlm.WorkerThread - W-9001-bot_NN_1.0 State change null -> WORKER_STARTED
2021-08-06 14:19:54,447 [INFO ] W-9001-bot_NN_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /tmp/.ts.sock.9001
2021-08-06 14:19:54,448 [INFO ] W-9001-bot_NN_1.0-stdout MODEL_LOG - Python runtime: 3.8.10
2021-08-06 14:19:54,453 [INFO ] W-9001-bot_NN_1.0-stdout MODEL_LOG - Connection accepted: /tmp/.ts.sock.9001.
2021-08-06 14:19:54,490 [INFO ] W-9002-bot_NN_1.0-stdout MODEL_LOG - model_name: bot_NN, batchSize: 1
2021-08-06 14:19:54,490 [INFO ] W-9001-bot_NN_1.0-stdout MODEL_LOG - model_name: bot_NN, batchSize: 1
2021-08-06 14:19:54,491 [INFO ] W-9000-bot_NN_1.0-stdout MODEL_LOG - model_name: bot_NN, batchSize: 1
2021-08-06 14:19:54,806 [INFO ] W-9002-bot_NN_1.0 org.pytorch.serve.wlm.WorkerThread - Backend response time: 306
2021-08-06 14:19:54,806 [DEBUG] W-9002-bot_NN_1.0 org.pytorch.serve.wlm.WorkerThread - W-9002-bot_NN_1.0 State change WORKER_STARTED -> WORKER_MODEL_LOADED
2021-08-06 14:19:54,806 [INFO ] W-9002-bot_NN_1.0 TS_METRICS - W-9002-bot_NN_1.0.ms:1802|#Level:Host|#hostname:alexey-GB-BKi5-H-A-7200,timestamp:1628248794
2021-08-06 14:19:54,807 [INFO ] W-9002-bot_NN_1.0 TS_METRICS - WorkerThreadTime.ms:53|#Level:Host|#hostname:alexey-GB-BKi5-H-A-7200,timestamp:null
2021-08-06 14:19:54,808 [INFO ] W-9000-bot_NN_1.0 org.pytorch.serve.wlm.WorkerThread - Backend response time: 318
2021-08-06 14:19:54,808 [DEBUG] W-9000-bot_NN_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-bot_NN_1.0 State change WORKER_STARTED -> WORKER_MODEL_LOADED
2021-08-06 14:19:54,808 [INFO ] W-9000-bot_NN_1.0 TS_METRICS - W-9000-bot_NN_1.0.ms:1815|#Level:Host|#hostname:alexey-GB-BKi5-H-A-7200,timestamp:1628248794
2021-08-06 14:19:54,808 [INFO ] W-9000-bot_NN_1.0 TS_METRICS - WorkerThreadTime.ms:42|#Level:Host|#hostname:alexey-GB-BKi5-H-A-7200,timestamp:null
2021-08-06 14:19:54,826 [INFO ] W-9001-bot_NN_1.0 org.pytorch.serve.wlm.WorkerThread - Backend response time: 328
2021-08-06 14:19:54,826 [DEBUG] W-9001-bot_NN_1.0 org.pytorch.serve.wlm.WorkerThread - W-9001-bot_NN_1.0 State change WORKER_STARTED -> WORKER_MODEL_LOADED
2021-08-06 14:19:54,826 [INFO ] W-9001-bot_NN_1.0 TS_METRICS - W-9001-bot_NN_1.0.ms:1826|#Level:Host|#hostname:alexey-GB-BKi5-H-A-7200,timestamp:1628248794
2021-08-06 14:19:54,826 [INFO ] W-9001-bot_NN_1.0 TS_METRICS - WorkerThreadTime.ms:45|#Level:Host|#hostname:alexey-GB-BKi5-H-A-7200,timestamp:null
```

- Check list:

```
alexey@alexey-GB-BKi5-H-A-7200:~/DS-ML$ curl "http://localhost:8080/ping"
{
  "status": "Healthy"
}
alexey@alexey-GB-BKi5-H-A-7200:~/DS-ML$ curl "http://localhost:8081/models"
{
  "models": [
    {
      "modelName": "bot_NN",
      "modelUrl": "bot_NN.mar"
    }
  ]
}
```

- Prediction is working!

I want register new model with new version for example.

I have done again , change version, name for example
```
torch-model-archiver --model-name bot_NN2 --version 2.0 --serialized-file ./model-store/fraud/model.pt --handler ./handlers/fraud_handler --runtime python3 --extra-files ./model-store/fraud/scaler.bin --export-path model-store/fraud
```

I have uploaded bot_NN2.mar for example on my github rep and trying register new model on server and got:

```
alexey@alexey-GB-BKi5-H-A-7200:~/DS-ML$ curl -v -X POST  "http://127.0.0.1:8081/models?model_name=bot_NN2&url=https://github.com/Apachaika/DS-ML/blob/master/Test/bot_NN2.mar"
*   Trying 127.0.0.1:8081...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8081 (#0)
> POST /models?model_name=bot_NN2&url=https://github.com/Apachaika/DS-ML/blob/master/Test/bot_NN2.mar HTTP/1.1
> Host: 127.0.0.1:8081
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< content-type: application/json
< x-request-id: 59fbb808-1627-4065-bd78-8cdf6a326c37
< Pragma: no-cache
< Cache-Control: no-cache; no-store, must-revalidate, private
< Expires: Thu, 01 Jan 1970 00:00:00 UTC
< content-length: 99
< connection: close
< 
{
  "code": 400,
  "type": "InvalidModelException",
  "message": "**Model version is not defined.**"
}
* Closing connection 0
```
First time I got Model name is not defined. I have added name in request, then I was got Model version is not defined.
Why Model version is not defined ? I have MANIFEST.json file with
```
{
  "createdOn": "05/08/2021 14:04:19",
  "runtime": "python3",
  "model": {
    "modelName": "bot_NN2.0",
    "serializedFile": "model.pt",
    "handler": "fraud_handler.py",
    "modelVersion": "2.0"
  },
  "archiverVersion": "0.4.2"
}
```
I have tried via gRPC
```
alexey@alexey-GB-BKi5-H-A-7200:~/botserve$ python ts_scripts/torchserve_grpc_client.py register test_NN
Failed to register model test_NN.
Model version is not defined.
org.pytorch.serve.archive.model.InvalidModelException
```

Some shock for me when I'm using by docs example, it's working!!!
```
alexey@alexey-GB-BKi5-H-A-7200:~/DS-ML$ curl -X POST  "http://localhost:8081/models?url=https://torchserve.pytorch.org/mar_files/squeezenet1_1.mar"

{
  "status": "Model \"squeezenet_v1.1\" Version: 1.0 registered with 0 initial workers. Use scale workers API to add workers for the model."
}
alexey@alexey-GB-BKi5-H-A-7200:~/DS-ML$ curl "http://localhost:8081/models"
{
  "models": [
    {
      "modelName": "bot_NN",
      "modelUrl": "bot_NN.mar"
    },
    {
      "modelName": "squeezenet1_1",
      "modelUrl": "https://torchserve.pytorch.org/mar_files/squeezenet1_1.mar"
    }
  ]
}

```

**Question: Can you explain, how I should register models? I know that I can use very stupid and easy way when I start server, write couple models, but I can't all time stop server and use this way.**

ps. I installed by pip
`pip install torchserve torch-model-archiver torch-workflow-archiver`

**Comment by chauhang** [comment]
@Apachaika Please check the steps for gRPC Model registration and inference [here](https://github.com/pytorch/serve/blob/master/docs/grpc_api.md#python-client-example-for-grpc-apis).

**Comment by Apachaika** [comment]
I have read a lot of gRPC registration and didn't find answer on my question. I found new function https://github.com/mlflow/mlflow-torchserve it's more easy registration and see lifecycle model.
