### ISSUE TITLE
Load model failed: mymodel, error: Worker died

### ISSUE THREAD

**Issue by ovlia** [pytorch/serve#1234]
## 📚 Documentation

2021-09-03 14:26:44,745 [WARN ] W-9000-mymodel1_1.0-stderr MODEL_LOG - model_service_worker.py: error: unrecognized arguments: --sock-type unix --sock-name /tmp/.ts.sock.9000
2021-09-03 14:26:44,745 [INFO ] epollEventLoopGroup-5-7 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_STARTED
2021-09-03 14:26:44,745 [DEBUG] W-9000-mymodel1_1.0 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_STARTED
2021-09-03 14:26:44,745 [DEBUG] W-9000-mymodel1_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1668)
        at java.base/java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:435)
        at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:188)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)
2021-09-03 14:26:44,746 [WARN ] W-9000-mymodel1_1.0 org.pytorch.serve.wlm.BatchAggregator - Load model failed: mymodel1, error: Worker died.

**Comment by toretak** [comment]
Hi @ovlia, please provide more information about the model. Is it default or custom handler? Are you running TorchServe in docker, or locally? Is it latest version of torchserve? Is the version of torchserve and model-archiver the same?

**Comment by ovlia** [comment]
running TorchServe in docker, latest version of torchserve 0.4.2

**Comment by HamidShojanazeri** [comment]
@ovlia Can you please share more details on the model and handler and full model_log, this would help us better understand the context and suggest solutions.

**Comment by msaroufim** [comment]
@ovlia can you try this PR and building from source to see if it fixes your problem https://github.com/pytorch/serve/pull/1272
