### ISSUE TITLE
torch-model-archiver does not accept python module structure for the handler

### ISSUE THREAD

**Issue by NathanPages** [pytorch/serve#1313]
`torch-model-archiver` does not accept python module structure for custom handlers path handler

## Context

* torchserve version: 0.4.2
* torch-model-archiver version:0.4.2
* torch version:1.9.0
* torchvision version [if any]: N/A
* torchtext version [if any]: N/A
* torchaudio version [if any]: N/A
* java version: N/A
* Operating System and version: Ubuntu 20.04

## Your Environment
* Installed using source? [yes/no]:  yes
* Are you planning to deploy it using docker container? [yes/no]: yes
* Is it a CPU or GPU environment?: both
* Using a default/custom handler? [If possible upload/share custom handler/model]: custom handler

## Expected Behavior
```terminal
torch-model-archiver   --handler my_module.my_submodule.handler
```
Should be a valid entry if the module `my_module` is installed and available.

## Current Behavior
```terminal
torch-model-archiver   --handler my_module.my_submodule.handler
```
raises the following error:
```terminal
Traceback (most recent call last):                                                                                            
File "/usr/local/bin/torch-model-archiver", line 8, in <module>                                                             
  sys.exit(generate_model_archive())
File "/usr/local/lib/python3.8/dist-packages/model_archiver/model_packaging.py", line 56, in generate_model_archive
  package_model(args, manifest=manifest)
File "/usr/local/lib/python3.8/dist-packages/model_archiver/model_packaging.py", line 36, in package_model
  model_path = ModelExportUtils.copy_artifacts(model_name, **artifact_files)
File "/usr/local/lib/python3.8/dist-packages/model_archiver/model_packaging_utils.py", line 163, in copy_artifacts
  shutil.copy(path, model_path)
File "/usr/lib/python3.8/shutil.py", line 418, in copy
  copyfile(src, dst, follow_symlinks=follow_symlinks)
File "/usr/lib/python3.8/shutil.py", line 264, in copyfile
  with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'my_module.my_submodule.handler.py'
```

## Possible Solution
The culprit is [Line 147 in model-archiver/model_archiver/model_packaging_utils.py](https://github.com/pytorch/serve/blob/master/model-archiver/model_archiver/model_packaging_utils.py#L146):
```python
if '.py' not in path:
    path = (path.split(':')[0] if ':' in path else path) + '.py'
```
That could be replace by:
imports:
```python
from importlib.util import find_spec
```
[...]
```python
if not path.endswith(".py"):
    path = (path.split(':')[0] if ':' in path else path)
    path = find_spec(path).origin
```

## Steps to Reproduce
Run the command:
```terminal
torch-model-archiver --model-name test_model --version 0.1  --handler ts.torch_handler.base_handler
```

## Failure Logs [if any]
```terminal
Traceback (most recent call last):
  File "/home/nathan/anaconda3/envs/cloudvision/bin/torch-model-archiver", line 33, in <module>
    sys.exit(load_entry_point('torch-model-archiver==0.4.2', 'console_scripts', 'torch-model-archiver')())
  File "/home/nathan/anaconda3/envs/cloudvision/lib/python3.9/site-packages/torch_model_archiver-0.4.2-py3.9.egg/model_archiver/model_packaging.py", line 56, in generate_model_archive
    package_model(args, manifest=manifest)
  File "/home/nathan/anaconda3/envs/cloudvision/lib/python3.9/site-packages/torch_model_archiver-0.4.2-py3.9.egg/model_archiver/model_packaging.py", line 36, in package_model
    model_path = ModelExportUtils.copy_artifacts(model_name, **artifact_files)
  File "/home/nathan/anaconda3/envs/cloudvision/lib/python3.9/site-packages/torch_model_archiver-0.4.2-py3.9.egg/model_archiver/model_packaging_utils.py", line 163, in copy_artifacts
    shutil.copy(path, model_path)
  File "/home/nathan/anaconda3/envs/cloudvision/lib/python3.9/shutil.py", line 426, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/nathan/anaconda3/envs/cloudvision/lib/python3.9/shutil.py", line 265, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'ts.torch_handler.base_handler.py'
```

**Comment by HamidShojanazeri** [comment]
@NathanPages thanks for opening the ticket, this should be [supported](https://github.com/pytorch/serve/tree/master/model-archiver#handler), although slightly different format from what you did here, can you please give it a try and let us know if that works for you.

**Comment by NathanPages** [comment]
@HamidShojanazeri Thanks for pointing out the documentation. However, that would not work for me. 
The current implementation assumes you know the path to the file containing your module. This path could be different between two different machines or if you are using different conda environment for example. Using the module/submodule structure that python uses would solve that issue.

Two other issues I see with the current version of the code:
* In the documentation it is said that:
> if it has `my_entry_point` module level function then [use] `--handler /home/serve/example/custom_image_classifier:my_entry_point_func`
I don't think `my_entry_point` will be used in the code since in `model_packaging_utils.py` we have:
```python
    path = (path.split(':')[0] if ':' in path else path) + '.py'
```
which will drop what is after the column and the `handler` path does not seem to be used anywhere else than in `ModelExportUtils.copy_artifacts(...)`.
* The check to verify if `path` is a python file is currently checking if `.py` is in the string, checking if it ends with `.py` (or the part before the column ends with `.py`) seems safer.
