### ISSUE TITLE
Question about number_of_netty_threads, netty_client_threads and job_queue_size

### ISSUE THREAD

**Issue by NormXU** [pytorch/serve#1360]
## 【Description】

I set up a docker stack on a cpu machine, which had 6 physical cores. This stack contained 2 sub services, a torchserver-based container as my server, and a client container to  post requests via **request**, a python libray.  

The client can post  request parallel to the service. **number_of_netty_threads** was set to 32, **job_queue_size** was 1,000. **default_workers_per_model** was 6

Here comes my questions. The service reported error as following

```python
ERROR - logging.py:246 - _exception() - exception info:('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) 
Traceback (most recent call last):      File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen        chunked=chunked, File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 445, in _make_request        six.raise_from(e, None)     
File "<string>", line 3, in raise_from      File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 440, in _make_request        httplib_response = conn.getresponse()      File "/usr/local/lib/python3.7/http/client.py", line 1373, in getresponse        response.begin()     
File "/usr/local/lib/python3.7/http/client.py", line 319, in begin        version, status, reason = self._read_status()      File "/usr/local/lib/python3.7/http/client.py", line 280, in _read_status        line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-
File "/usr/local/lib/python3.7/socket.py", line 589, in readinto        return self._sock.recv_into(b)   
ConnectionResetError: [Errno 104] Connection reset by peer        During handling of the above exception, another exception occurred:        
Traceback (most recent call last):      File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send        timeout=timeout      File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen   method, url, error=e, _pool=self, _stacktrace=sys.exc_info()
```

Since I didn't intend to solve this problem by simply retry my post request until it succeed, I tried to set number_of_netty_threads to 16, job_queue_size to 2,000, default_workers_per_model was still 6. Fortunately, it turned out to solve the problem.

According to  https://pytorch.org/serve/configuration.html#other-properties, `number_of_netty_threads` means Number frontend netty thread, but **why I set `number_of_netty_threads`too large can lead to the error above?**

**Is it possible because that my cpu has been fully occupied, and some worker were restarted, therefore the http request failed to post and finally return ConnectionResetError?**

I am appreciate if you could give me simpler explanations of what **number_of_netty_threads** and **netty_client_threads** are used for in English.

**Comment by lxning** [comment]
number_of_netty_threads: defines the number of threads to accept incoming http requests from your client container.
job_queue_size: defines the size of a models's job queue which stores incoming http requests.
default_workers_per_model: defines the number of workers which fetches a http request from a model's job queue.
netty_client_threads: defines the number of threads of a model's worker to receive http response from a model's worker backend in TS internal.

The incoming http request will be blocked and eventually timeout if a job queue is full. That's why client got the error. Usually, a model's throughput depends on a model's processing latency and the above first 3 parameters together.
