### ISSUE TITLE
Worker threads crash on shutdown

### ISSUE THREAD

**Issue by fbbradheintz** [pytorch/serve#155]
Repro:
* Started TorchServe with no models
* Registered a model from the Model Store
* Scaled up to 4 workers
* Tested image classification inference
* Scaled up to 8 workers
* Stopped TorchServe

Error output from log:

```
2020-04-02 02:32:08,979 [INFO ] epollEventLoopGroup-4-3 org.pytorch.serve.wlm.WorkerThread - 9001 Worker disconnected. WORKER_MODEL_LOADED
2020-04-02 02:32:08,980 [INFO ] epollEventLoopGroup-4-1 org.pytorch.serve.wlm.WorkerThread - 9002 Worker disconnected. WORKER_MODEL_LOADED
2020-04-02 02:32:08,980 [INFO ] epollEventLoopGroup-4-6 org.pytorch.serve.wlm.WorkerThread - 9004 Worker disconnected. WORKER_MODEL_LOADED
2020-04-02 02:32:08,980 [INFO ] epollEventLoopGroup-4-2 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_MODEL_LOADED
2020-04-02 02:32:08,980 [INFO ] epollEventLoopGroup-4-4 org.pytorch.serve.wlm.WorkerThread - 9003 Worker disconnected. WORKER_MODEL_LOADED
2020-04-02 02:32:08,980 [INFO ] epollEventLoopGroup-4-5 org.pytorch.serve.wlm.WorkerThread - 9007 Worker disconnected. WORKER_MODEL_LOADED
2020-04-02 02:32:08,981 [INFO ] epollEventLoopGroup-4-8 org.pytorch.serve.wlm.WorkerThread - 9006 Worker disconnected. WORKER_MODEL_LOADED
2020-04-02 02:32:08,981 [INFO ] epollEventLoopGroup-4-7 org.pytorch.serve.wlm.WorkerThread - 9005 Worker disconnected. WORKER_MODEL_LOADED
2020-04-02 02:32:08,981 [WARN ] W-9001-r18_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker thread exception.
java.lang.IllegalMonitorStateException
	at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:151)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1261)
	at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:457)
	at org.pytorch.serve.wlm.Model.pollBatch(Model.java:175)
	at org.pytorch.serve.wlm.BatchAggregator.getRequest(BatchAggregator.java:33)
	at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-04-02 02:32:08,981 [INFO ] epollEventLoopGroup-2-1 org.pytorch.serve.ModelServer - Inference model server stopped.
2020-04-02 02:32:08,981 [INFO ] epollEventLoopGroup-2-2 org.pytorch.serve.ModelServer - Management model server stopped.
2020-04-02 02:32:08,981 [DEBUG] W-9005-r18_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2088)
	at java.util.concurrent.LinkedBlockingDeque.pollFirst(LinkedBlockingDeque.java:522)
	at java.util.concurrent.LinkedBlockingDeque.poll(LinkedBlockingDeque.java:684)
	at org.pytorch.serve.wlm.Model.pollBatch(Model.java:155)
	at org.pytorch.serve.wlm.BatchAggregator.getRequest(BatchAggregator.java:33)
	at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-04-02 02:32:08,981 [DEBUG] W-9002-r18_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2088)
	at java.util.concurrent.LinkedBlockingDeque.pollFirst(LinkedBlockingDeque.java:522)
	at java.util.concurrent.LinkedBlockingDeque.poll(LinkedBlockingDeque.java:684)
	at org.pytorch.serve.wlm.Model.pollBatch(Model.java:155)
	at org.pytorch.serve.wlm.BatchAggregator.getRequest(BatchAggregator.java:33)
	at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-04-02 02:32:08,981 [WARN ] W-9004-r18_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker thread exception.
java.lang.IllegalMonitorStateException
	at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:151)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1261)
	at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:457)
	at org.pytorch.serve.wlm.Model.pollBatch(Model.java:175)
	at org.pytorch.serve.wlm.BatchAggregator.getRequest(BatchAggregator.java:33)
	at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-04-02 02:32:08,981 [WARN ] W-9000-r18_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker thread exception.
java.lang.IllegalMonitorStateException
	at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:151)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1261)
	at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:457)
	at org.pytorch.serve.wlm.Model.pollBatch(Model.java:175)
	at org.pytorch.serve.wlm.BatchAggregator.getRequest(BatchAggregator.java:33)
	at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-04-02 02:32:08,981 [WARN ] W-9006-r18_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker thread exception.
java.lang.IllegalMonitorStateException
	at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:151)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1261)
	at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:457)
	at org.pytorch.serve.wlm.Model.pollBatch(Model.java:175)
	at org.pytorch.serve.wlm.BatchAggregator.getRequest(BatchAggregator.java:33)
	at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-04-02 02:32:08,981 [WARN ] W-9003-r18_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker thread exception.
java.lang.IllegalMonitorStateException
	at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:151)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1261)
	at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:457)
	at org.pytorch.serve.wlm.Model.pollBatch(Model.java:175)
	at org.pytorch.serve.wlm.BatchAggregator.getRequest(BatchAggregator.java:33)
	at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-04-02 02:32:08,981 [WARN ] W-9007-r18_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker thread exception.
java.lang.IllegalMonitorStateException
	at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:151)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1261)
	at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:457)
	at org.pytorch.serve.wlm.Model.pollBatch(Model.java:175)
	at org.pytorch.serve.wlm.BatchAggregator.getRequest(BatchAggregator.java:33)
	at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-04-02 02:32:08,985 [DEBUG] W-9007-r18_1.0 org.pytorch.serve.wlm.WorkerThread - W-9007-r18_1.0 State change WORKER_MODEL_LOADED -> WORKER_STOPPED
2020-04-02 02:32:08,985 [DEBUG] W-9003-r18_1.0 org.pytorch.serve.wlm.WorkerThread - W-9003-r18_1.0 State change WORKER_MODEL_LOADED -> WORKER_STOPPED
2020-04-02 02:32:08,984 [DEBUG] W-9006-r18_1.0 org.pytorch.serve.wlm.WorkerThread - W-9006-r18_1.0 State change WORKER_MODEL_LOADED -> WORKER_STOPPED
2020-04-02 02:32:08,984 [DEBUG] W-9000-r18_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-r18_1.0 State change WORKER_MODEL_LOADED -> WORKER_STOPPED
2020-04-02 02:32:08,984 [DEBUG] W-9004-r18_1.0 org.pytorch.serve.wlm.WorkerThread - W-9004-r18_1.0 State change WORKER_MODEL_LOADED -> WORKER_STOPPED
2020-04-02 02:32:08,983 [DEBUG] W-9002-r18_1.0 org.pytorch.serve.wlm.WorkerThread - W-9002-r18_1.0 State change WORKER_MODEL_LOADED -> WORKER_STOPPED
2020-04-02 02:32:08,983 [DEBUG] W-9005-r18_1.0 org.pytorch.serve.wlm.WorkerThread - W-9005-r18_1.0 State change WORKER_MODEL_LOADED -> WORKER_STOPPED
2020-04-02 02:32:08,983 [DEBUG] W-9001-r18_1.0 org.pytorch.serve.wlm.WorkerThread - W-9001-r18_1.0 State change WORKER_MODEL_LOADED -> WORKER_STOPPED
2020-04-02 02:32:08,992 [INFO ] W-9007-r18_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9007 in 1 seconds.
2020-04-02 02:32:08,992 [INFO ] W-9002-r18_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9002 in 1 seconds.
2020-04-02 02:32:08,993 [INFO ] W-9006-r18_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9006 in 1 seconds.
2020-04-02 02:32:08,992 [INFO ] W-9004-r18_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9004 in 1 seconds.
2020-04-02 02:32:08,992 [INFO ] W-9001-r18_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9001 in 1 seconds.
2020-04-02 02:32:08,992 [INFO ] W-9000-r18_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9000 in 1 seconds.
2020-04-02 02:32:08,992 [INFO ] W-9005-r18_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9005 in 1 seconds.
2020-04-02 02:32:08,993 [INFO ] W-9003-r18_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9003 in 1 seconds.
```

**Comment by fbbradheintz** [comment]
I flagged this for the patch release, because it would be nice to get those errors out of the log. As I said in the relevant PR, though, I'm very reluctant to just silence the exceptions without a clear understanding of why the exceptions come up in the first place, and whether they have any effect on the system.

**Comment by dhaniram-kshirsagar** [comment]
> I flagged this for the patch release, because it would be nice to get those errors out of the log. As I said in the relevant PR, though, I'm very reluctant to just silence the exceptions without a clear understanding of why the exceptions come up in the first place, and whether they have any effect on the system.

@fbbradheintz updates in #172

**Comment by chauhang** [comment]
@harshbafna Please see the [comments](https://github.com/pytorch/serve/pull/172#discussion_r422620498) and verify that remove code for terminating child process does not have any other side effects of hanging child processes
