### ISSUE TITLE
Model loading failed with torchserve 0.5.3 docker image

### ISSUE THREAD

**Issue by jagadeeshi2i** [pytorch/serve#1587]
Cannot load model with pytorch/torchserve:0.5.3-cpu docker image. The same model is loaded on using pytorch/torchserve:0.5.1-cpu and the docker image built from the master branch.

Marfile and config.properties - https://drive.google.com/drive/folders/1vD6HvB0IivS9nvpfRHj4nn6hNyjEukei?usp=sharing

## Steps to Reproduce
```
$ docker run -it -v /home/ubuntu/117069db-a48b-4ca3-a9df-fc2512f9e21c/:/mnt/models pytorch/torchserve:0.5.3-cpu bash
$ cd /mnt/models/config
$ torchserve --start --ts-config config.properties.txt
```

## Failure Logs [if any]
```
model-server@b2f1774fe894:/mnt/models/config$ WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2022-04-26T08:22:12,775 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager - Initializing plugins manager...
2022-04-26T08:22:12,891 [INFO ] main org.pytorch.serve.ModelServer - 
Torchserve version: 0.5.3
TS Home: /home/venv/lib/python3.8/site-packages
Current directory: /mnt/models/config
Temp directory: /home/model-server/tmp
Number of GPUs: 0
Number of CPUs: 8
Max heap size: 3922 M
Python executable: /home/venv/bin/python
Config file: config.properties
Inference address: http://0.0.0.0:8085
Management address: http://0.0.0.0:8085
Metrics address: http://0.0.0.0:8082
Model Store: /mnt/models/model-store
Initial Models: N/A
Log dir: /mnt/models/config/logs
Metrics dir: /mnt/models/config/logs
Netty threads: 0
Netty client threads: 0
Default workers per model: 8
Blacklist Regex: N/A
Maximum Response Size: 6553500
Maximum Request Size: 6553500
Limit Maximum Image Pixels: true
Prefer direct buffer: false
Allowed Urls: [file://.*|http(s)?://.*]
Custom python dependency for model allowed: true
Metrics report format: prometheus
Enable metrics API: true
Workflow Store: /mnt/models/model-store
Model config: N/A
2022-04-26T08:22:12,899 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager -  Loading snapshot serializer plugin...
2022-04-26T08:22:12,919 [INFO ] main org.pytorch.serve.snapshot.SnapshotManager - Started restoring models from snapshot {"name":"startup.cfg","modelCount":1,"models":{"cifar10":{"1.0":{"defaultVersion":true,"marName":"cifar10_test.mar","minWorkers":1,"maxWorkers":5,"batchSize":1,"maxBatchDelay":5000,"responseTimeout":900}}}}
2022-04-26T08:22:12,929 [INFO ] main org.pytorch.serve.snapshot.SnapshotManager - Validating snapshot startup.cfg
2022-04-26T08:22:12,929 [INFO ] main org.pytorch.serve.snapshot.SnapshotManager - Snapshot startup.cfg validated successfully
2022-04-26T08:22:14,242 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Adding new version 1 for model cifar10
2022-04-26T08:22:14,242 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Setting default version to 1 for model cifar10
2022-04-26T08:24:12,894 [INFO ] main org.pytorch.serve.wlm.ModelManager - Model cifar10 loaded.                                                                                        
2022-04-26T08:24:12,895 [DEBUG] main org.pytorch.serve.wlm.ModelManager - updateModel: cifar10, count: 1                                                                               
2022-04-26T08:24:12,914 [DEBUG] W-9000-cifar10_1 org.pytorch.serve.wlm.WorkerLifeCycle - Worker cmdline: [/home/venv/bin/python, /home/venv/lib/python3.8/site-packages/ts/mode[45/106]
e_worker.py, --sock-type, unix, --sock-name, /home/model-server/tmp/.ts.sock.9000]                                                                                                     
2022-04-26T08:24:12,923 [INFO ] main org.pytorch.serve.ModelServer - Initialize Inference server with: EpollServerSocketChannel.                                                       
2022-04-26T08:24:13,062 [INFO ] main org.pytorch.serve.ModelServer - Inference API bind to: http://0.0.0.0:8085                                                                        
2022-04-26T08:24:13,062 [INFO ] main org.pytorch.serve.ModelServer - Initialize Metrics server with: EpollServerSocketChannel.                                                         
2022-04-26T08:24:13,070 [INFO ] main org.pytorch.serve.ModelServer - Metrics API bind to: http://0.0.0.0:8082                                                                          
Model server started.                                                                                                                                                                  
2022-04-26T08:24:13,349 [WARN ] pool-3-thread-1 org.pytorch.serve.metrics.MetricCollector - worker pid is not available yet.                                                           
2022-04-26T08:24:13,450 [INFO ] pool-3-thread-1 TS_METRICS - CPUUtilization.Percent:0.0|#Level:Host|#hostname:b2f1774fe894,timestamp:1650961453                                        
2022-04-26T08:24:13,461 [INFO ] pool-3-thread-1 TS_METRICS - DiskAvailable.Gigabytes:273.0296058654785|#Level:Host|#hostname:b2f1774fe894,timestamp:1650961453                         
2022-04-26T08:24:13,461 [INFO ] pool-3-thread-1 TS_METRICS - DiskUsage.Gigabytes:171.0927391052246|#Level:Host|#hostname:b2f1774fe894,timestamp:1650961453                             
2022-04-26T08:24:13,462 [INFO ] pool-3-thread-1 TS_METRICS - DiskUtilization.Percent:38.5|#Level:Host|#hostname:b2f1774fe894,timestamp:1650961453                                      
2022-04-26T08:24:13,462 [INFO ] pool-3-thread-1 TS_METRICS - MemoryAvailable.Megabytes:5775.04296875|#Level:Host|#hostname:b2f1774fe894,timestamp:1650961453                           
2022-04-26T08:24:13,462 [INFO ] pool-3-thread-1 TS_METRICS - MemoryUsed.Megabytes:8242.4140625|#Level:Host|#hostname:b2f1774fe894,timestamp:1650961453                                 
2022-04-26T08:24:13,463 [INFO ] pool-3-thread-1 TS_METRICS - MemoryUtilization.Percent:63.2|#Level:Host|#hostname:b2f1774fe894,timestamp:1650961453                                    
2022-04-26T08:24:13,863 [INFO ] W-9000-cifar10_1-stdout MODEL_LOG - Listening on port: /home/model-server/tmp/.ts.sock.9000                                                            
2022-04-26T08:24:13,864 [INFO ] W-9000-cifar10_1-stdout MODEL_LOG - [PID]85                                                                                                            
2022-04-26T08:24:13,864 [INFO ] W-9000-cifar10_1-stdout MODEL_LOG - Torch worker started.                                                                                              
2022-04-26T08:24:13,865 [INFO ] W-9000-cifar10_1-stdout MODEL_LOG - Python runtime: 3.8.0                                                                                              
2022-04-26T08:24:13,865 [DEBUG] W-9000-cifar10_1 org.pytorch.serve.wlm.WorkerThread - W-9000-cifar10_1 State change null -> WORKER_STARTED                                             
2022-04-26T08:24:13,873 [INFO ] W-9000-cifar10_1 org.pytorch.serve.wlm.WorkerThread - Connecting to: /home/model-server/tmp/.ts.sock.9000                                              
2022-04-26T08:24:13,882 [INFO ] W-9000-cifar10_1-stdout MODEL_LOG - Connection accepted: /home/model-server/tmp/.ts.sock.9000.                                                         
2022-04-26T08:24:13,888 [INFO ] W-9000-cifar10_1 org.pytorch.serve.wlm.WorkerThread - Flushing req. to backend at: 1650961453888                                                       
2022-04-26T08:24:13,944 [INFO ] W-9000-cifar10_1-stdout MODEL_LOG - model_name: cifar10, batchSize: 1                                                                                  
2022-04-26T08:24:14,420 [INFO ] W-9000-cifar10_1-stdout MODEL_LOG - generated new fontManager                                                                                          
2022-04-26T08:24:15,159 [WARN ] W-9000-cifar10_1-stderr MODEL_LOG - terminate called after throwing an instance of 'std::bad_alloc'                                                    
2022-04-26T08:24:15,160 [WARN ] W-9000-cifar10_1-stderr MODEL_LOG -   what():  std::bad_alloc
2022-04-26T08:24:18,193 [INFO ] W-9000-cifar10_1-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-cifar10_1-stderr
2022-04-26T08:24:18,193 [INFO ] W-9000-cifar10_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-cifar10_1-stdout
2022-04-26T08:24:18,203 [INFO ] epollEventLoopGroup-5-1 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_STARTED
2022-04-26T08:24:18,207 [DEBUG] W-9000-cifar10_1 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_STARTED
2022-04-26T08:24:18,207 [DEBUG] W-9000-cifar10_1 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException: null
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056) ~[?:?]
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133) ~[?:?]
        at java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:432) ~[?:?] 
        at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:189) [model-server.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
2022-04-26T08:24:18,250 [WARN ] W-9000-cifar10_1 org.pytorch.serve.wlm.BatchAggregator - Load model failed: cifar10, error: Worker died.
```

**Comment by msaroufim** [comment]
Just managed to repro, taking a closer look now

**Comment by msaroufim** [comment]
Ok running experiments one more time - tracking them all here https://gist.github.com/msaroufim/b8569bab0d2ddd777a53a9c59d8ebffe

**Comment by Sigura** [comment]
Same issue. @jagadeeshi2i: Did you up docker container on MacOS? In my case same exception on Macbook 2019 i9. Because looks like it work on Ubuntu

MacOS details
![Screenshot 2022-06-09 at 12 21 59](https://user-images.githubusercontent.com/428500/172813441-90c4776f-0105-4c3d-9532-c27876305015.png)
