### ISSUE TITLE
How to return n images instead of 1? 

### ISSUE THREAD

**Issue by mhashas** [pytorch/serve#1647]
Hi,

I am trying to deploy a DALL-E type model, in which you get as input a text and you receive as output a couple of images.

```
outputs = []
for i, image in enumerate(images):
    byte_output = io.BytesIO()
    output.convert('RGB').save(byte_output, format='JPEG')
    bin_img_data = byte_output.getvalue()
    
    outputs.append(bin_img_data)

return [outputs]
```

 
  This does not work and results in a failure, with the logs from torchserve saying 'object of type bytearray is not json serializable'
  
  However, changing `return [outputs]` into `return [outputs[0]]` makes it work. What can I do regarding this?

**Comment by msaroufim** [comment]
By default, all the handler functions `preprocess, inference, postprocess` take in a `List[Any]` and output a `List[Any]` so a `List[List[Any]]` also works just fine. So if your `preprocess(input : List[str]) -> List[torch.tensor]` `inference(tensors : List[torch.tensor]) -> List[torch.tensor]` and finally `postprocess(tensors : List[torch.tensor]) -> List[Image])`

I'm not exactly sure where you're hitting the `object of type bytearray is not json serializable error`, is this in torchserve code or in your handler? If you'd like to share more details in a repro, I'd be happy to take a look

This also sounds very cool, I'd be very eager to merge a DALL-E handler in `examples/` if you'd like to make the PR

**Comment by mhashas** [comment]
Hi @msaroufim, thanks for the quick response, these are the logs that I get back

2022-05-23T15:52:22,028 [INFO ] W-9000-image-generation-glid-3_1.0-stdout MODEL_LOG - Unable to serialize model output.
2022-05-23T15:52:22,028 [INFO ] W-9000-image-generation-glid-3_1.0-stdout MODEL_LOG - Traceback (most recent call last):
2022-05-23T15:52:22,028 [INFO ] W-9000-image-generation-glid-3_1.0-stdout MODEL_LOG -   File "/app/playground/glid-3/glid-3/lib/python3.8/site-packages/ts/protocol/otf_message_handler.py", line 130, in create_predict_response
2022-05-23T15:52:22,028 [INFO ] W-9000-image-generation-glid-3_1.0-stdout MODEL_LOG -     json_value = json.dumps(val, indent=2).encode("utf-8")
2022-05-23T15:52:22,029 [INFO ] W-9000-image-generation-glid-3_1.0-stdout MODEL_LOG -   File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
2022-05-23T15:52:22,029 [INFO ] W-9000-image-generation-glid-3_1.0-stdout MODEL_LOG -     return cls(
2022-05-23T15:52:22,029 [INFO ] W-9000-image-generation-glid-3_1.0-stdout MODEL_LOG -   File "/usr/lib/python3.8/json/encoder.py", line 201, in encode
2022-05-23T15:52:22,029 [INFO ] W-9000-image-generation-glid-3_1.0-stdout MODEL_LOG -     chunks = list(chunks)
2022-05-23T15:52:22,029 [INFO ] W-9000-image-generation-glid-3_1.0-stdout MODEL_LOG -   File "/usr/lib/python3.8/json/encoder.py", line 429, in _iterencode
2022-05-23T15:52:22,029 [INFO ] W-9000-image-generation-glid-3_1.0-stdout MODEL_LOG -     yield from _iterencode_list(o, _current_indent_level)
2022-05-23T15:52:22,029 [INFO ] W-9000-image-generation-glid-3_1.0-stdout MODEL_LOG -   File "/usr/lib/python3.8/json/encoder.py", line 325, in _iterencode_list
2022-05-23T15:52:22,029 [INFO ] W-9000-image-generation-glid-3_1.0-stdout MODEL_LOG -     yield from chunks
2022-05-23T15:52:22,029 [INFO ] W-9000-image-generation-glid-3_1.0-stdout MODEL_LOG -   File "/usr/lib/python3.8/json/encoder.py", line 438, in _iterencode
2022-05-23T15:52:22,029 [INFO ] W-9000-image-generation-glid-3_1.0-stdout MODEL_LOG -     o = _default(o)
2022-05-23T15:52:22,029 [INFO ] W-9000-image-generation-glid-3_1.0-stdout MODEL_LOG -   File "/usr/lib/python3.8/json/encoder.py", line 179, in default
2022-05-23T15:52:22,029 [INFO ] W-9000-image-generation-glid-3_1.0-stdout MODEL_LOG -     raise TypeError(f'Object of type {o.__class__.__name__} '
2022-05-23T15:52:22,029 [INFO ] W-9000-image-generation-glid-3_1.0-stdout MODEL_LOG - TypeError: Object of type bytes is not JSON serializable
2022-05-23T15:52:22,029 [INFO ] W-9000-image-generation-glid-3_1.0 org.pytorch.serve.wlm.WorkerThread - Backend response time: 69879

**Comment by msaroufim** [comment]
Ideally I'd still like a full repro with your mar file for example - this template helps https://github.com/pytorch/serve/issues/new?assignees=&labels=&template=bug_template.md

But if you can't provide that the issue seems to be here

`2022-05-23T15:52:22,028 [INFO ] W-9000-image-generation-glid-3_1.0-stdout MODEL_LOG - json_value = json.dumps(val, indent=2).encode("utf-8")`

Since after that the error is in the json encoder library which is stdlib. Is the data you're sending in encodable in `utf-8`? You can test this out by just running this function on the val you expect. It's true that you cannot convert an object of type bytes to a JSON object, so maybe first try changing your data to be a string

**Comment by mhashas** [comment]
Thanks for the help.

Changing the append line into `outputs.append(base64.b64encode(byte_output.getvalue()).decode())` solved it.

Regarding the repo, I can share with you my handler and the requirements file. What is left is to download the models from:  https://github.com/Jack000/glid-3-xl. I unfortunately do not have time to make a PR, sorry about that.

Let me know if you think its useful to share the handler file :)
