### ISSUE TITLE
Assign Device Inside of Model

### ISSUE THREAD

**Issue by CerebralSeed** [pytorch/serve#1671]
This is a really simple question. My model's forward pass has something like this:

`out=torch.empty(size=(batch_size,0))`

Which I then fill with an iterator. The above, if left as is, will give a "RuntimeError: Expected all tensors to be on the same device, but found at least two devices". 

With Torch Serve, the model is entirely encapsulated in a single .py file. And the Handler.py file defines the self.device during "initialize". How do I go about getting that definition into my model?

Here is the Handler.py "initialize" definition:

```
    def initialize(self, ctx):
        """ Loads the model.pt file and initializes the model object.
        """
        torch.set_num_threads(1)
        self.manifest = ctx.manifest
        properties = ctx.system_properties
        model_dir = properties.get("model_dir")
        self.device = torch.device("cuda:" + str(properties.get("gpu_id")) if torch.cuda.is_available() else "cpu")

        # Read model serialize/pt file
        serialized_file = self.manifest["model"]["serializedFile"]
        model_pt_path = os.path.join(model_dir, serialized_file)
        if not os.path.isfile(model_pt_path):
            raise RuntimeError("Missing the model.pt or pytorch_model.bin file")

        model_file = self.manifest["model"].get("modelFile", "")
        if model_file:
            logger.debug("Loading eager model")

            self.model = self._load_pickled_model(model_dir, model_file, model_pt_path)
            # Load model
            self.model = self._load_pickled_model(model_dir, model_file, model_pt_path)

        else:
            logger.debug("Loading torchscript model")
            if not os.path.isfile(model_pt_path):
                raise RuntimeError("Missing the model.pt file")

            self.model = self._load_torchscript_model(model_pt_path)

        self.model.to(self.device)
        self.model.eval()
        logger.debug('Price Prediction model from path {0} loaded successfully'.format(model_dir))

        self.initialized = True
```

**Comment by CerebralSeed** [comment]
Add one more thing, I've already tried putting this in the init of the model:

`self.device = torch.device("cuda:" + str(properties.get("gpu_id")) if torch.cuda.is_available() else "cpu")`

That just gives a bunch of non-descript errors:

```
2022-06-06 15:57:19,650 [INFO ] W-9000-conv1dichi1_1.0-stdout MODEL_LOG - Backend worker process died.
2022-06-06 15:57:19,650 [INFO ] W-9000-conv1dichi1_1.0-stdout MODEL_LOG - Traceback (most recent call last):
2022-06-06 15:57:19,650 [INFO ] nioEventLoopGroup-5-3 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_STARTED
2022-06-06 15:57:19,651 [INFO ] W-9000-conv1dichi1_1.0-stdout MODEL_LOG -   File "C:\ProgramData\Anaconda3\Lib\site-packages\ts\model_service_worker.py", line 183, in <module>
2022-06-06 15:57:19,651 [DEBUG] W-9000-conv1dichi1_1.0 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_STARTED
2022-06-06 15:57:19,651 [INFO ] W-9000-conv1dichi1_1.0-stdout MODEL_LOG -     worker.run_server()
2022-06-06 15:57:19,651 [INFO ] W-9000-conv1dichi1_1.0-stdout MODEL_LOG -   File "C:\ProgramData\Anaconda3\Lib\site-packages\ts\model_service_worker.py", line 155, in run_server
2022-06-06 15:57:19,651 [DEBUG] W-9000-conv1dichi1_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133)
        at java.base/java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:432)
        at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:188)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
2022-06-06 15:57:19,651 [INFO ] W-9000-conv1dichi1_1.0-stdout MODEL_LOG -     self.handle_connection(cl_socket)
2022-06-06 15:57:19,652 [WARN ] W-9000-conv1dichi1_1.0 org.pytorch.serve.wlm.BatchAggregator - Load model failed: conv1dichi1, error: Worker died.
2022-06-06 15:57:19,652 [DEBUG] W-9000-conv1dichi1_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-conv1dichi1_1.0 State change WORKER_STARTED -> WORKER_STOPPED
2022-06-06 15:57:19,652 [INFO ] W-9000-conv1dichi1_1.0-stdout MODEL_LOG -   File "C:\ProgramData\Anaconda3\Lib\site-packages\ts\model_service_worker.py", line 117, in handle_connection
2022-06-06 15:57:19,652 [WARN ] W-9000-conv1dichi1_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-conv1dichi1_1.0-stderr
2022-06-06 15:57:19,652 [INFO ] W-9000-conv1dichi1_1.0-stdout MODEL_LOG -     service, result, code = self.load_model(msg)
2022-06-06 15:57:19,652 [WARN ] W-9000-conv1dichi1_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-conv1dichi1_1.0-stdout
2022-06-06 15:57:19,652 [INFO ] W-9000-conv1dichi1_1.0-stdout MODEL_LOG -   File "C:\ProgramData\Anaconda3\Lib\site-packages\ts\model_service_worker.py", line 90, in load_model
2022-06-06 15:57:19,652 [INFO ] W-9000-conv1dichi1_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9000 in 2 seconds.
2022-06-06 15:57:19,653 [INFO ] W-9000-conv1dichi1_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-conv1dichi1_1.0-stdout
2022-06-06 15:57:19,657 [INFO ] W-9000-conv1dichi1_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-conv1dichi1_1.0-stderr
```

The main question is just how can I get the device into the model for use in making new tensors in the forward pass.
