### ISSUE TITLE
Serving other framework models with Torchserve?

### ISSUE THREAD

**Issue by vuongdanghuy** [pytorch/serve#1725]
Hi everyone.

As in the title, I want to ask if torchserve can serve other framework models or pytorch models only?

For example, I have a model written in mxnet. This is the snippet code of `initialize` method in my custom handler.
```python
def initialize(self, context):
        properties = context.system_properties
        if (torch.cuda.is_available() and
                properties.get("gpu_id") is not None):
            ctx_id = properties.get("gpu_id")
        else:
            ctx_id = -1

        self.manifest = context.manifest
        model_dir = properties.get("model_dir")
        prefix = os.path.join(model_dir, "model/resnet-50")

        # load model
        sym, arg_params, aux_params = mx.model.load_checkpoint(prefix, 0)
        if ctx_id >= 0:
            self.ctx = mx.gpu(ctx_id)
        else:
            self.ctx = mx.cpu()
        self.model = mx.mod.Module(symbol=sym,
                                   context=self.ctx,
                                   label_names=None)
        self.model.bind(
            data_shapes=[('data', (1, 3, 640, 640))],
            for_training=False
        )
        self.model.set_params(arg_params, aux_params)
        self.initialized = True
```
For some reason, pretrained mxnet model can't be loaded. But that same model works fine in my training and inferencing script. This is the error log.
```
2022-07-06T15:48:07,468 [INFO ] W-9000-face_detect_1.0-stdout MODEL_LOG -   File "/apps/conda/huyvd/envs/insightface/lib/python3.8/site-packages/ts/model_loader.py", line 151, in load
2022-07-06T15:48:07,468 [INFO ] W-9000-face_detect_1.0-stdout MODEL_LOG -     initialize_fn(service.context)
2022-07-06T15:48:07,469 [INFO ] W-9000-face_detect_1.0-stdout MODEL_LOG -   File "/tmp/models/4b6bbba5e16445ffbe70f89282a0d30a/handler.py", line 34, in initialize
2022-07-06T15:48:07,469 [INFO ] W-9000-face_detect_1.0-stdout MODEL_LOG -     sym, arg_params, aux_params = mx.model.load_checkpoint(prefix, 0)
2022-07-06T15:48:07,469 [INFO ] W-9000-face_detect_1.0-stdout MODEL_LOG -   File "/apps/conda/huyvd/envs/insightface/lib/python3.8/site-packages/mxnet/model.py", line 476, in load_checkpoint
2022-07-06T15:48:07,470 [INFO ] W-9000-face_detect_1.0-stdout MODEL_LOG -     symbol = sym.load('%s-symbol.json' % prefix)
2022-07-06T15:48:07,470 [INFO ] W-9000-face_detect_1.0-stdout MODEL_LOG -   File "/apps/conda/huyvd/envs/insightface/lib/python3.8/site-packages/mxnet/symbol/symbol.py", line 3054, in load
2022-07-06T15:48:07,470 [INFO ] W-9000-face_detect_1.0-stdout MODEL_LOG -     check_call(_LIB.MXSymbolCreateFromFile(c_str(fname), ctypes.byref(handle)))
2022-07-06T15:48:07,471 [INFO ] W-9000-face_detect_1.0-stdout MODEL_LOG -   File "/apps/conda/huyvd/envs/insightface/lib/python3.8/site-packages/mxnet/base.py", line 246, in check_call
2022-07-06T15:48:07,471 [INFO ] W-9000-face_detect_1.0-stdout MODEL_LOG -     raise get_last_ffi_error()
2022-07-06T15:48:07,471 [INFO ] W-9000-face_detect_1.0-stdout MODEL_LOG - mxnet.base.MXNetError: Traceback (most recent call last):
2022-07-06T15:48:07,472 [INFO ] W-9000-face_detect_1.0-stdout MODEL_LOG -   File "../include/dmlc/././json.h", line 718
2022-07-06T15:48:07,472 [INFO ] W-9000-face_detect_1.0-stdout MODEL_LOG - MXNetError: Check failed: !is_->fail(): Error at Line 32, around ^``, Expect number
```

**Comment by lxning** [comment]
@vuongdanghuy torchserve do support different frameworks eg. MxNet. According to the log, it seems that there is error in the model itself about json.

**Comment by vuongdanghuy** [comment]
Thanks @lxning . 
I also do believe torchserve can support different frameworks.
So maybe it's an error because the same model can be loaded totally fine in my training and inference script.
I'll try to provide a minimum script to repro this error.

**Comment by vuongdanghuy** [comment]
Hi,

I create a simple repo to repro this error [here](https://github.com/vuongdanghuy/torchserve_mxnet/tree/master).
I found out that if torch is imported, the error happened. You can check it by running `test_script.py`.
I'm not sure if it's because of my MXNet and PyTorch version compatibility. Currently i'm running Pytorch 11.6 nightly because I only have CUDA 11.6, but MXNet highest version 1.9.1 is CUDA 11.2.

**Comment by vuongdanghuy** [comment]
UPDATE!

I uninstall my PyTorch with CUDA 11.6 nightly and install new stable version and the error is gone.

Thanks anyway.
