### ISSUE TITLE
How to transfer files to a custom handler with curl command

### ISSUE THREAD

**Issue by Shin-ichi-Takayama** [pytorch/serve#1819]
I have created a custom handler that inputs and outputs wav files. 
The code is as follows
```Python
# custom handler file

# model_handler.py

"""
ModelHandler defines a custom model handler.
"""
import os
import soundfile
from espnet2.bin.enh_inference import *

from ts.torch_handler.base_handler import BaseHandler

class ModelHandler(BaseHandler):
    """
    A custom model handler implementation.
    """

    def __init__(self):
        self._context = None
        self.initialized = False
        self.model = None
        self.device = None

    def initialize(self, context):
        """
        Invoke by torchserve for loading a model
        :param context: context contains model server system properties
        :return:
        """

        #  load the model
        self.manifest = context.manifest

        properties = context.system_properties
        model_dir = properties.get("model_dir")
        self.device = torch.device("cuda:" + str(properties.get("gpu_id")) if torch.cuda.is_available() else "cpu")

        # Read model serialize/pt file
        serialized_file = self.manifest['model']['serializedFile']
        model_pt_path = os.path.join(model_dir, serialized_file)

        if not os.path.isfile(model_pt_path):
            raise RuntimeError("Missing the model.pt file")

        self.model = SeparateSpeech("./train_enh_transformer_tf.yaml", "./valid.loss.best.pth", normalize_output_wav=True)

        self.initialized = True

    def preprocess(self,data):
        audio_data, rate  = soundfile.read(data)
        preprocessed_data = audio_data[np.newaxis, :]

        return preprocessed_data

    def inference(self, model_input):
        model_output = self.model(model_input)
        return model_output

    def postprocess(self, inference_output):
        """
        Return inference result.
        :param inference_output: list of inference output
        :return: list of predict results
        """
        # Take output from network and post-process to desired format
        postprocess_output = inference_output
        #wav ni suru
        return postprocess_output

    def handle(self, data, context):
        model_input = self.preprocess(data)
        model_output = self.inference(model_input)
        return self.postprocess(model_output)
```

I transferred the wav file to torhserve with the following command
> curl --data-binary @Mix.wav --noproxy '*'  http://127.0.0.1:8080/predictions/denoise_transformer -v

However, I got the following response
```
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> POST /predictions/denoise_transformer HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Length: 128046
> Content-Type: application/x-www-form-urlencoded
> Expect: 100-continue
>
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
< HTTP/1.1 500 Internal Server Error
< content-type: application/json
< x-request-id: 445155a4-5971-490a-ba7c-206f8eda5ea0
< Pragma: no-cache
< Cache-Control: no-cache; no-store, must-revalidate, private
< Expires: Thu, 01 Jan 1970 00:00:00 UTC
< content-length: 89
< connection: close
<
{
  "code": 500,
  "type": "ErrorDataDecoderException",
  "message": "Bad end of line"
}
* Closing connection 0
```

What is wrong?

I have confirmed that the following command returns the response.
> curl  --noproxy '*'  http://127.0.0.1:8081/models
```
{
  "models": [
    {
      "modelName": "denoise_transformer",
      "modelUrl": "denoise_transformer.mar"
    }
  ]
}
```

**Comment by Shin-ichi-Takayama** [comment]
The logs on the torchserve side are as follows

```
2022-08-27T19:32:10,449 [ERROR] epollEventLoopGroup-3-19 org.pytorch.serve.http.HttpRequestHandler -
io.netty.handler.codec.http.multipart.HttpPostRequestDecoder$ErrorDataDecoderException: Bad end of line
        at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.parseBodyAttributesStandard(HttpPostStandardRequestDecoder.java:456) ~[model-server.jar:?]
        at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.parseBodyAttributes(HttpPostStandardRequestDecoder.java:519) ~[model-server.jar:?]
        at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.parseBody(HttpPostStandardRequestDecoder.java:375) ~[model-server.jar:?]
        at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.offer(HttpPostStandardRequestDecoder.java:304) ~[model-server.jar:?]
        at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.<init>(HttpPostStandardRequestDecoder.java:158) ~[model-server.jar:?]
        at io.netty.handler.codec.http.multipart.HttpPostRequestDecoder.<init>(HttpPostRequestDecoder.java:95) ~[model-server.jar:?]
        at io.netty.handler.codec.http.multipart.HttpPostRequestDecoder.<init>(HttpPostRequestDecoder.java:69) ~[model-server.jar:?]
        at org.pytorch.serve.http.api.rest.InferenceRequestHandler.parseRequest(InferenceRequestHandler.java:285) ~[model-server.jar:?]
        at org.pytorch.serve.http.api.rest.InferenceRequestHandler.predict(InferenceRequestHandler.java:237) ~[model-server.jar:?]
        at org.pytorch.serve.http.api.rest.InferenceRequestHandler.handlePredictions(InferenceRequestHandler.java:164) ~[model-server.jar:?]
        at org.pytorch.serve.http.api.rest.InferenceRequestHandler.handleRequest(InferenceRequestHandler.java:80) ~[model-server.jar:?]
        at org.pytorch.serve.http.api.rest.ApiDescriptionRequestHandler.handleRequest(ApiDescriptionRequestHandler.java:41) ~[model-server.jar:?]
        at org.pytorch.serve.http.HttpRequestHandler.channelRead0(HttpRequestHandler.java:45) [model-server.jar:?]
        at org.pytorch.serve.http.HttpRequestHandler.channelRead0(HttpRequestHandler.java:22) [model-server.jar:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [model-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [model-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [model-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [model-server.jar:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [model-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [model-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [model-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [model-server.jar:?]
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [model-server.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [model-server.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [model-server.jar:?]
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [model-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [model-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [model-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [model-server.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [model-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [model-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [model-server.jar:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [model-server.jar:?]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) [model-server.jar:?]
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:388) [model-server.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [model-server.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [model-server.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) [model-server.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [model-server.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [model-server.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [model-server.jar:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
2022-08-27T19:32:10,449 [INFO ] epollEventLoopGroup-3-19 ACCESS_LOG - /127.0.0.1:54296 "POST /predictions/denoise_transformer HTTP/1.1" 500 1
2022-08-27T19:32:10,449 [INFO ] epollEventLoopGroup-3-19 TS_METRICS - Requests5XX.Count:1|#Level:Host|#hostname:0832e168fc4e,timestamp:1661575973
```

**Comment by msaroufim** [comment]
In your `config.properties` can you set `decode_input_request` to false? https://github.com/pytorch/serve/blob/master/docs/configuration.md#other-properties

Otherwise you'd need to make sure the request you send is a JSON which wraps your custom binary data, here's an example of how that works here https://github.com/pytorch/serve/blob/master/examples/MMF-activity-recognition/request.py

**Comment by msaroufim** [comment]
Did anything wrong happen if you convert data to 16 bit from your handler?

**Comment by Shin-ichi-Takayama** [comment]
Thank you for your response.
I was able to get it to work by modifying the custom handler as follows
```Python
# custom handler file

# model_handler.py

"""
ModelHandler defines a custom model handler.
"""
from typing import Dict, List, Tuple
import io
import os
import wave
import array
import soundfile
from scipy.io.wavfile import write
from espnet2.bin.enh_inference import *

from ts.torch_handler.base_handler import BaseHandler

class ModelHandler(BaseHandler):
    """
    A custom model handler implementation.
    """

    def __init__(self):
        self._context = None
        self.initialized = False
        self.model = None
        self.device = None

    def initialize(self, context):
        """
        Invoke by torchserve for loading a model
        :param context: context contains model server system properties
        :return:
        """

        #  load the model
        self.manifest = context.manifest

        properties = context.system_properties
        model_dir = properties.get("model_dir")
        self.device = torch.device("cuda:" + str(properties.get("gpu_id")) if torch.cuda.is_available() else "cpu")

        # Read model serialize/pt file
        serialized_file = self.manifest['model']['serializedFile']
        model_pt_path = os.path.join(model_dir, serialized_file)

        if not os.path.isfile(model_pt_path):
            raise RuntimeError("Missing the model.pt file")

        self.model = SeparateSpeech("./train_enh_transformer_tf.yaml", "./valid.loss.best.pth", normalize_output_wav=True)

        self.initialized = True

    def preprocess(self,data):
        wav_data = data[0]['body']
        audio_data, rate  = soundfile.read(io.BytesIO(wav_data))
        preprocessed_data = audio_data[np.newaxis, :]

        return preprocessed_data
    def inference(self, model_input):
        model_output = self.model(model_input)
        return model_output

    def postprocess(self, inference_output):
        """
        Return inference result.
        :param inference_output: list of inference output
        :return: list of predict results
        """
        # Take output  network and post-process to desired format
        postprocess_output = inference_output
        return postprocess_output

    def handle(self, data, context):
        temp_file_name = '/tmp/temp.wav'

        model_input = self.preprocess(data)
        model_output = self.inference(model_input)
        output = self.postprocess(model_output)
        scaled = np.int16(output[0][0] * 32767)
        write(temp_file_name, 16000, scaled)
        with open(temp_file_name, 'rb') as f:
            out = f.read()
        #os.remove(temp_file_name)

        return [out]


```
