### ISSUE TITLE
gRPC API docs out of date

### ISSUE THREAD

**Issue by msaroufim** [pytorch/serve#1852]
## Start torchserve

Easy fix

Start torchserve: `torchserve --start`: needs to include `--model-store`

```
(serve) ubuntu@ip-172-31-62-14:~/serve$ torchserve --start
Missing mandatory parameter --model-store
```

### Register model: 

Need to document intent behind each arg, maybe just use `argparse` to make this clearer

`python ts_scripts/torchserve_grpc_client.py register densenet161`

```
Traceback (most recent call last):
  File "/home/ubuntu/serve/ts_scripts/torchserve_grpc_client.py", line 86, in <module>
    api(get_management_stub(), args[1], args[2])
IndexError: list index out of range
```

## Run an inference

Probably need to link to the right model in model_zoo

```
(serve) ubuntu@ip-172-31-62-14:~/serve$ python ts_scripts/torchserve_grpc_client.py infer densenet161 examples/image_classifier/kitten.jpg
Traceback (most recent call last):
  File "/home/ubuntu/serve/ts_scripts/torchserve_grpc_client.py", line 82, in <module>
    infer(get_inference_stub(), args[1], args[2])
  File "/home/ubuntu/serve/ts_scripts/torchserve_grpc_client.py", line 26, in infer
    response = stub.Predictions(
  File "/home/ubuntu/anaconda3/envs/serve/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/ubuntu/anaconda3/envs/serve/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.INTERNAL
        details = "Model not found: densenet161
org.pytorch.serve.archive.model.ModelNotFoundException"
        debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::1%5D:7070 {created_time:"2022-09-06T14:27:10.643529272+00:00", grpc_status:13, grpc_message:"Model not found: densenet161\norg.pytorch.serve.archive.model.ModelNotFoundException"}"
>
```

**Comment by LuigiCerone** [comment]
Hello @msaroufim, can I work on this?

**Comment by msaroufim** [comment]
Sure go for it!
