### ISSUE TITLE
separator of models when torch start

### ISSUE THREAD

**Issue by jack-gits** [pytorch/serve#1951]
### 🐛 Describe the bug

when torchseve start with multi-models, can't split the models correctly. it's recognized as one model.
below is the models separated by a blank space.

**_kie-cro_vl_ba_text=kie-cro_vl_ba_text-release-2022-11-03.mar classify-document-latin=document-classify-latin-v5-release-2022-11-03.mar_**

**command:**
torchserve --start --ts-config /home/model-server/config.properties --model-store model-store/ \
     --workflow-store model-store/ \
     --models ${models_str}

**log:**
2022-11-05T19:26:11,679 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager - Initializing plugins manager...
2022-11-05T19:26:11,679 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager - Initializing plugins manager...
2022-11-05T19:26:11,762 [INFO ] main org.pytorch.serve.ModelServer - 
Torchserve version: 0.5.3
TS Home: /home/venv/lib/python3.8/site-packages
Current directory: /home/model-server
Temp directory: /home/model-server/tmp
Number of GPUs: 1
Number of CPUs: 8
Max heap size: 7928 M
Python executable: /home/venv/bin/python
Config file: /home/model-server/config.properties
Inference address: http://0.0.0.0:8080
Management address: http://0.0.0.0:8081
Metrics address: http://0.0.0.0:8082
Model Store: /home/model-server/model-store
Initial Models: **_kie-cro_vl_ba_text=kie-cro_vl_ba_text-release-2022-11-03.mar classify-document-latin=document-classify-latin-v5-release-2022-11-03.mar_**
Log dir: /home/model-server/logs
Metrics dir: /home/model-server/logs
Netty threads: 10
Netty client threads: 0
Default workers per model: 2
Blacklist Regex: N/A
Maximum Response Size: 6553500
Maximum Request Size: 6553500
Limit Maximum Image Pixels: false
Prefer direct buffer: false
Allowed Urls: [file://.*|http(s)?://.*]
Custom python dependency for model allowed: false
Metrics report format: prometheus
Enable metrics API: true
Workflow Store: /home/model-server/model-store
Model config: N/A
2022-11-05T19:26:11,762 [INFO ] main org.pytorch.serve.ModelServer - 
Torchserve version: 0.5.3
TS Home: /home/venv/lib/python3.8/site-packages
Current directory: /home/model-server
Temp directory: /home/model-server/tmp
Number of GPUs: 1
Number of CPUs: 8
Max heap size: 7928 M
Python executable: /home/venv/bin/python
Config file: /home/model-server/config.properties
Inference address: http://0.0.0.0:8080
Management address: http://0.0.0.0:8081
Metrics address: http://0.0.0.0:8082
Model Store: /home/model-server/model-store
Initial Models: **_kie-cro_vl_ba_text=kie-cro_vl_ba_text-release-2022-11-03.mar classify-document-latin=document-classify-latin-v5-release-2022-11-03.mar_**
Log dir: /home/model-server/logs
Metrics dir: /home/model-server/logs
Netty threads: 10
Netty client threads: 0
Default workers per model: 2
Blacklist Regex: N/A
Maximum Response Size: 6553500
Maximum Request Size: 6553500
Limit Maximum Image Pixels: false
Prefer direct buffer: false
Allowed Urls: [file://.*|http(s)?://.*]
Custom python dependency for model allowed: false
Metrics report format: prometheus
Enable metrics API: true
Workflow Store: /home/model-server/model-store
Model config: N/A
2022-11-05T19:26:11,768 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager -  Loading snapshot serializer plugin...
2022-11-05T19:26:11,768 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager -  Loading snapshot serializer plugin...
2022-11-05T19:26:11,787 [INFO ] main org.pytorch.serve.ModelServer - Loading initial models: kie-cro_vl_ba_text-release-2022-11-03.mar classify-document-latin=document-classify-latin-v5-release-2022-11-03.mar
2022-11-05T19:26:11,787 [INFO ] main org.pytorch.serve.ModelServer - Loading initial models: kie-cro_vl_ba_text-release-2022-11-03.mar classify-document-latin=document-classify-latin-v5-release-2022-11-03.mar
2022-11-05T19:26:11,789 [WARN ] main org.pytorch.serve.ModelServer - Failed to load model: kie-cro_vl_ba_text-release-2022-11-03.mar classify-document-latin=document-classify-latin-v5-release-2022-11-03.mar
org.pytorch.serve.archive.model.ModelNotFoundException: Model not found at: **_kie-cro_vl_ba_text-release-2022-11-03.mar classify-document-latin=document-classify-latin-v5-release-2022-11-03.mar_**
	at org.pytorch.serve.archive.model.ModelArchive.downloadModel(ModelArchive.java:75) ~[model-server.jar:?]
	at org.pytorch.serve.wlm.ModelManager.createModelArchive(ModelManager.java:167) ~[model-server.jar:?]
	at org.pytorch.serve.wlm.ModelManager.registerModel(ModelManager.java:133) ~[model-server.jar:?]
	at org.pytorch.serve.ModelServer.initModelStore(ModelServer.java:242) ~[model-server.jar:?]
	at org.pytorch.serve.ModelServer.startRESTserver(ModelServer.java:356) ~[model-server.jar:?]
	at org.pytorch.serve.ModelServer.startAndWait(ModelServer.java:117) ~[model-server.jar:?]
	at org.pytorch.serve.ModelServer.main(ModelServer.java:98) ~[model-server.jar:?]

### Error logs

2022-11-05T19:26:11,679 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager - Initializing plugins manager...
2022-11-05T19:26:11,679 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager - Initializing plugins manager...
2022-11-05T19:26:11,762 [INFO ] main org.pytorch.serve.ModelServer - 
Torchserve version: 0.5.3
TS Home: /home/venv/lib/python3.8/site-packages
Current directory: /home/model-server
Temp directory: /home/model-server/tmp
Number of GPUs: 1
Number of CPUs: 8
Max heap size: 7928 M
Python executable: /home/venv/bin/python
Config file: /home/model-server/config.properties
Inference address: http://0.0.0.0:8080
Management address: http://0.0.0.0:8081
Metrics address: http://0.0.0.0:8082
Model Store: /home/model-server/model-store
Initial Models: kie-cro_vl_ba_text=kie-cro_vl_ba_text-release-2022-11-03.mar classify-document-latin=document-classify-latin-v5-release-2022-11-03.mar
Log dir: /home/model-server/logs
Metrics dir: /home/model-server/logs
Netty threads: 10
Netty client threads: 0
Default workers per model: 2
Blacklist Regex: N/A
Maximum Response Size: 6553500
Maximum Request Size: 6553500
Limit Maximum Image Pixels: false
Prefer direct buffer: false
Allowed Urls: [file://.*|http(s)?://.*]
Custom python dependency for model allowed: false
Metrics report format: prometheus
Enable metrics API: true
Workflow Store: /home/model-server/model-store
Model config: N/A
2022-11-05T19:26:11,762 [INFO ] main org.pytorch.serve.ModelServer - 
Torchserve version: 0.5.3
TS Home: /home/venv/lib/python3.8/site-packages
Current directory: /home/model-server
Temp directory: /home/model-server/tmp
Number of GPUs: 1
Number of CPUs: 8
Max heap size: 7928 M
Python executable: /home/venv/bin/python
Config file: /home/model-server/config.properties
Inference address: http://0.0.0.0:8080
Management address: http://0.0.0.0:8081
Metrics address: http://0.0.0.0:8082
Model Store: /home/model-server/model-store
Initial Models: kie-cro_vl_ba_text=kie-cro_vl_ba_text-release-2022-11-03.mar classify-document-latin=document-classify-latin-v5-release-2022-11-03.mar
Log dir: /home/model-server/logs
Metrics dir: /home/model-server/logs
Netty threads: 10
Netty client threads: 0
Default workers per model: 2
Blacklist Regex: N/A
Maximum Response Size: 6553500
Maximum Request Size: 6553500
Limit Maximum Image Pixels: false
Prefer direct buffer: false
Allowed Urls: [file://.*|http(s)?://.*]
Custom python dependency for model allowed: false
Metrics report format: prometheus
Enable metrics API: true
Workflow Store: /home/model-server/model-store
Model config: N/A
2022-11-05T19:26:11,768 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager -  Loading snapshot serializer plugin...
2022-11-05T19:26:11,768 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager -  Loading snapshot serializer plugin...
2022-11-05T19:26:11,787 [INFO ] main org.pytorch.serve.ModelServer - Loading initial models: kie-cro_vl_ba_text-release-2022-11-03.mar classify-document-latin=document-classify-latin-v5-release-2022-11-03.mar
2022-11-05T19:26:11,787 [INFO ] main org.pytorch.serve.ModelServer - Loading initial models: kie-cro_vl_ba_text-release-2022-11-03.mar classify-document-latin=document-classify-latin-v5-release-2022-11-03.mar
2022-11-05T19:26:11,789 [WARN ] main org.pytorch.serve.ModelServer - Failed to load model: kie-cro_vl_ba_text-release-2022-11-03.mar classify-document-latin=document-classify-latin-v5-release-2022-11-03.mar
org.pytorch.serve.archive.model.ModelNotFoundException: Model not found at: kie-cro_vl_ba_text-release-2022-11-03.mar classify-document-latin=document-classify-latin-v5-release-2022-11-03.mar
	at org.pytorch.serve.archive.model.ModelArchive.downloadModel(ModelArchive.java:75) ~[model-server.jar:?]
	at org.pytorch.serve.wlm.ModelManager.createModelArchive(ModelManager.java:167) ~[model-server.jar:?]
	at org.pytorch.serve.wlm.ModelManager.registerModel(ModelManager.java:133) ~[model-server.jar:?]
	at org.pytorch.serve.ModelServer.initModelStore(ModelServer.java:242) ~[model-server.jar:?]
	at org.pytorch.serve.ModelServer.startRESTserver(ModelServer.java:356) ~[model-server.jar:?]
	at org.pytorch.serve.ModelServer.startAndWait(ModelServer.java:117) ~[model-server.jar:?]
	at org.pytorch.serve.ModelServer.main(ModelServer.java:98) ~[model-server.jar:?]

### Installation instructions

torchseve gpu6.0

### Model Packaing

None

### Versions

gpu 6.0

### Repro instructions

None

**Comment by jack-gits** [comment]
anybody can help on this issue?

**Comment by maaquib** [comment]
https://github.com/pytorch/serve/blob/b87d7e59790e06c74f486c186f4a1d47a557b963/ts/arg_parser.py#L49-L55
The way you are specifying the models is incorrect. It should be the following

```
--models kie-cro_vl_ba_text=kie-cro_vl_ba_text-release-2022-11-03.mar \
--models classify-document-latin=document-classify-latin-v5-release-2022-11-03.mar
```

**Comment by jack-gits** [comment]
@maaquib  I always specify the models like this and it works:

```
     --models neuron-ocr=paddle_ocr-release-2022-11-19.mar \
       kie-cro_vl_ba_text=kie-cro_vl_ba_text-release-2022-11-13.mar \
       classify-document-latin=document-classify-latin-v5-release-2022-11-03.mar
```
