### ISSUE TITLE
ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by david-waterworth** [pytorch/serve#2013]
### 🐛 Describe the bug

I installed serve in a new venv by following the process in the readme, i.e.

python ./ts_scripts/install_dependencies.py --cuda=cu117
pip install torchserve torch-model-archiver torch-workflow-archiver

I then followed the readme from the text classifier example. When I start serve it fails to import the `yaml` module - I manually installed pyyaml but it looks like it may be missing from install_dependencies.py

### Error logs

2022-11-30T14:51:49,986 [INFO ] main org.pytorch.serve.ModelServer - Inference API bind to: http://127.0.0.1:8080
2022-11-30T14:51:49,986 [INFO ] main org.pytorch.serve.ModelServer - Initialize Management server with: EpollServerSocketChannel.
2022-11-30T14:51:49,987 [INFO ] main org.pytorch.serve.ModelServer - Management API bind to: http://127.0.0.1:8081
2022-11-30T14:51:49,987 [INFO ] main org.pytorch.serve.ModelServer - Initialize Metrics server with: EpollServerSocketChannel.
2022-11-30T14:51:49,988 [INFO ] main org.pytorch.serve.ModelServer - Metrics API bind to: http://127.0.0.1:8082
2022-11-30T14:51:49,999 [WARN ] W-9000-my_tc_1.0-stderr MODEL_LOG - Traceback (most recent call last):
2022-11-30T14:51:50,001 [WARN ] W-9000-my_tc_1.0-stderr MODEL_LOG -   File "/home/dave/dev/serve/.venv/lib/python3.8/site-packages/ts/model_service_worker.py", line 16, in <module>
2022-11-30T14:51:50,001 [WARN ] W-9001-my_tc_1.0-stderr MODEL_LOG - Traceback (most recent call last):
2022-11-30T14:51:50,001 [WARN ] W-9000-my_tc_1.0-stderr MODEL_LOG -     from ts.metrics.metric_cache_yaml_impl import MetricsCacheYamlImpl
2022-11-30T14:51:50,002 [WARN ] W-9000-my_tc_1.0-stderr MODEL_LOG -   File "/home/dave/dev/serve/.venv/lib/python3.8/site-packages/ts/metrics/metric_cache_yaml_impl.py", line 5, in <module>
2022-11-30T14:51:50,002 [WARN ] W-9001-my_tc_1.0-stderr MODEL_LOG -   File "/home/dave/dev/serve/.venv/lib/python3.8/site-packages/ts/model_service_worker.py", line 16, in <module>
2022-11-30T14:51:50,002 [WARN ] W-9000-my_tc_1.0-stderr MODEL_LOG -     import yaml
2022-11-30T14:51:50,002 [WARN ] W-9000-my_tc_1.0-stderr MODEL_LOG - ModuleNotFoundError: No module named 'yaml'
2022-11-30T14:51:50,002 [WARN ] W-9001-my_tc_1.0-stderr MODEL_LOG -     from ts.metrics.metric_cache_yaml_impl import MetricsCacheYamlImpl
2022-11-30T14:51:50,004 [WARN ] W-9001-my_tc_1.0-stderr MODEL_LOG -   File "/home/dave/dev/serve/.venv/lib/python3.8/site-packages/ts/metrics/metric_cache_yaml_impl.py", line 5, in <module>
2022-11-30T14:51:50,004 [WARN ] W-9001-my_tc_1.0-stderr MODEL_LOG -     import yaml
2022-11-30T14:51:50,004 [WARN ] W-9001-my_tc_1.0-stderr MODEL_LOG - ModuleNotFoundError: No module named 'yaml'

### Installation instructions

Installed from pip but used /ts_scripts/install_dependencies.py

### Model Packaing

N/A

### config.properties

N/A

### Versions

------------------------------------------------------------------------------------------
Environment headers
------------------------------------------------------------------------------------------
Torchserve branch: 

torchserve==0.6.1
torch-model-archiver==0.6.1

Python version: 3.8 (64-bit runtime)
Python executable: /home/dave/dev/serve/.venv/bin/python

Versions of relevant python libraries:
captum==0.5.0
future==0.18.2
numpy==1.23.5
nvgpu==0.9.0
psutil==5.9.4
requests==2.28.1
torch==1.13.0+cu117
torch-model-archiver==0.6.1
torch-workflow-archiver==0.2.5
torchaudio==0.13.0+cu117
torchdata==0.5.0
torchserve==0.6.1
torchtext==0.14.0
torchvision==0.14.0+cu117
wheel==0.38.4
torch==1.13.0+cu117
torchtext==0.14.0
torchvision==0.14.0+cu117
torchaudio==0.13.0+cu117

Java Version:

OS: Ubuntu 20.04.5 LTS
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: N/A
CMake version: version 3.24.2

Is CUDA available: Yes
CUDA runtime version: 11.3.109
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
Nvidia driver version: 520.61.05
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.6.0

### Repro instructions

Followed example readme - https://github.com/pytorch/serve/tree/master/examples/text_classification

### Possible Solution

pip install pyyaml

**Comment by david-waterworth** [comment]
I'm still seeing this error in 0.7.0

> WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
> 
> 2022-12-15T02:46:07,456 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager - Initializing plugins manager...
> 2022-12-15T02:46:07,554 [INFO ] main org.pytorch.serve.ModelServer - 
> **Torchserve version: 0.7.0**
> TS Home: /home/venv/lib/python3.8/site-packages
> Current directory: /home/model-server
> Temp directory: /home/model-server/tmp
> 
> [snip...]
> 
> 2022-12-15T02:46:36,938 [DEBUG] W-9000-text_classifier_1.0.0 org.pytorch.serve.wlm.WorkerLifeCycle - Worker cmdline: [/home/venv/bin/python, /home/venv/lib/python3.8/site-packages/ts/model_service_worker.py, --sock-type, unix, --sock-name, /home/model-server/tmp/.ts.sock.9000, --metrics-config, /home/venv/lib/python3.8/site-packages/ts/configs/metrics.yaml]
> 
> [snip...]
> 
> 2022-12-15T02:46:37,000 [WARN ] W-9000-text_classifier_1.0.0-stderr MODEL_LOG -     import yaml
> 2022-12-15T02:46:37,000 [WARN ] W-9000-text_classifier_1.0.0-stderr MODEL_LOG - ModuleNotFoundError: No module named 'yaml'
> 2022-12-15T02:46:37,000 [WARN ] W-9001-text_classifier_1.0.0-stderr MODEL_LOG -     from ts.metrics.metric_cache_yaml_impl import MetricsCacheYamlImpl
> 2022-12-15T02:46:37,000 [WARN ] W-9001-text_classifier_1.0.0-stderr MODEL_LOG -   File "/home/venv/lib/python3.8/site-packages/ts/metrics/metric_cache_yaml_impl.py", line 5, in <module>

I'm running in docker; I built the docker container using `./build_image.sh`

In order to fix I had to add `pyaml` to the `requirements.txt` I used when creating the `mar` using `torch-model-archiver --requirements-file`

I'm guessing that if a mar file uses `--requirements-file` that you have to explicitly provide all the worker requirements, and looking at the errors above `yaml` is required by the work processes?
