### ISSUE TITLE
SSL instructions fail

### ISSUE THREAD

**Issue by fbbradheintz** [pytorch/serve#203]
Following "Option 1" of the "[Enable SSL](https://github.com/pytorch/serve/blob/master/docs/configuration.md#enable-ssl)" section of the docs does not bring up working endpoints.

The `config.properties` file:
```
inference_address=https://0.0.0.0:8443
management_address=https://0.0.0.0:8444
keystore=keystore.p12
keystore_pass=aoeuaoeu
keystore_type=PKCS12
```

The failing Management API command:
```
curl -X POST "https://localhost:8444/models?url=r18ts.mar&initial_workers=1"
```

Here's the result on the client side:
```
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

On the server, the following exception turns up in the log:
```
2020-04-15 17:05:50,396 [ERROR] epollEventLoopGroup-3-3 org.pytorch.serve.http.HttpRequestHandler -
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Received fatal alert: unknown_ca
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: unknown_ca
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:307)
        at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:291)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:180)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
        at java.base/sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:668)
        at java.base/sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:623)
        at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:441)
        at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:420)
        at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:634)
        at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:294)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1275)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1177)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1221)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
        ... 14 more
```

**Suggested Remediation:**
* Catch the exception and provide informative logging on the server side.
* Return HTTP response 403 with an informative client side message.
* Provide working instructions for a self-signed cert installation.

**Comment by fbbradheintz** [comment]
Self-assigned for testing

**Comment by fbbradheintz** [comment]
Verified - closing.

**Comment by wugoukanle** [comment]
curl -k https://0.0.0.0:8443/ping

**Comment by udithhaputhanthri** [comment]
@fbbradheintz 
Hi, We are currently developing a website that includes a backend processing that should be done in the pytorch serve on AWS server. The problem is we need a SSL certificate for the application. So we have tried 2 methods that have been shown in the "torchserve advanced configurations". But in there, they only have provided a way to create a "self-signed" SSL certificate. With that, we are getting "self signed certificate error" on browser. We have tried "lets encrypt SSL certification" in order to obtained CA-signed SSL certificate but it is required to provide a domain name instead of IP address. In order to obtain a domain name, we have tried freenom.com but we were unable to proceed with that also. 

Please let us know the proper way to obtain a CA-signed SSL certificate to make secure communication between backend on AWS (torchserve) and front end deployed on Heroku.

**Comment by dhaniram-kshirsagar** [comment]
> Please let us know the proper way to obtain a CA-signed SSL certificate to make secure communication between backend on AWS (torchserve) and front end deployed on Heroku.

As far as I know, you will need a domain name to get CA signed SSL cert. There are different articles on the net on how to [get CA signed cert](https://comodosslstore.com/resources/what-is-a-ca-signed-certificate-how-do-i-get-one/). NOTE this is a general process for any webserver and nothing to do with torchserve as such.
