### ISSUE TITLE
any wrong parameter scales down model workers to 1

### ISSUE THREAD

**Issue by nsabir2011** [pytorch/serve#2045]
### 🐛 Describe the bug

I tried to use the [scale workers](https://pytorch.org/serve/management_api.html#scale-workers) API and scale up/down my model workers. However, I made a mistake. Instead of `min_worker`, I used `min_workers`. The extra `s` wasted a lot of time for me.

I noticed that the workers were getting scaled down even if I hit the API with `min_workers=2`. So, the following command would return:
```bash
$ curl -X PUT "http://localhost:8081/models/test-mdoel?min_workers=2&max_workers=2&synchronous=true"
{
  "status": "Workers scaled to 1 for model: test-model"
}
```

I was really confused and didn't consider to check if the parameter spelling is correct since a GET request returns:
```bash
$ curl "http://localhost:8081/models/test-model"
{
   ...
   "minWorkers": 1,
   "maxWorkers": 1,
   ...
}
```
Here, there is an `s` after `minWorker`. So, there is an inconsistancy.

After I figured out my mistake, I tried to further investigate why this was happening. To my surprise, the following command also returns the same message and actually scale down the workers to 1.
```bash
$ curl -X PUT "http://localhost:8081/models/test-model?not-valid=whatever&synchronous=true"
{
  "status": "Workers scaled to 1 for model: test-model"
}
```

In my opinion, there should be a validation that checks if valid parameters are given or not. So, maybe return an appropiate http status code with a helpful message?

### Error logs

No errors

### Installation instructions

I am on Ubuntu 22.04 LTS.
So I installed open-jdk with `sudo apt install openjdk-17-jdk`
Then I installed with pip `pip install torch-model-archiver torchserve`
I could get everything working just fine with these steps. I did not use the helper script from this repo, since I already had torch with cuda installed in my environment.

### Model Packaing

I used [this example](https://github.com/pytorch/serve/blob/master/docs/custom_service.md#custom-handler-with-class-level-entry-point) to create a custom hanler.

### Versions

openjdk:
```
openjdk 17.0.5 2022-10-18
OpenJDK Runtime Environment (build 17.0.5+8-Ubuntu-2ubuntu122.04)
```
torchserve:
```
torch-model-archiver          0.7.0
torchserve                    0.7.0
```

### Repro instructions

After deploying any model, try to use the scale workers API using wrong parameters. For example,
```
$ curl -X PUT "http://localhost:8081/models/test-model?not-valid=whatever&synchronous=true"
{
  "status": "Workers scaled to 1 for model: test-model"
}
```

**Comment by rohithkrn** [comment]
Thanks for raising this issue. I was able to reproduce this on my end.

**Comment by rohithkrn** [comment]
`handleScaleModel` method is called for a PUT method here https://github.com/pytorch/serve/blob/master/frontend/server/src/main/java/org/pytorch/serve/http/api/rest/ManagementRequestHandler.java#L92 and the default value of 1 min_worker is used - https://github.com/pytorch/serve/blob/master/frontend/server/src/main/java/org/pytorch/serve/http/api/rest/ManagementRequestHandler.java#L229

**Comment by nsabir2011** [comment]
BTW

This issue still exists when any invalid value is given for a valid parameter. Ex:
```
curl -X PUT http://localhost:8081/models/test-model?min_worker=asds  # or min_worker=2.0
```

Moreover, when any negative number is given with the param:
```
curl -X PUT http://localhost:8081/models/test-model?min_worker=-10
{
  "code": 500,
  "type": "IndexOutOfBoundsException",
  "message": "Index -1 out of bounds for length 0"
}
```
This is the error log:
```
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.remove(ArrayList.java:504) ~[?:?]
	at org.pytorch.serve.wlm.WorkLoadManager.modelChanged(WorkLoadManager.java:141) ~[model-server.jar:?]
	at org.pytorch.serve.wlm.ModelManager.updateModel(ModelManager.java:412) ~[model-server.jar:?]
	at org.pytorch.serve.wlm.ModelManager.updateModel(ModelManager.java:427) ~[model-server.jar:?]
	at org.pytorch.serve.util.ApiUtils.updateModelWorkers(ApiUtils.java:237) ~[model-server.jar:?]
	at org.pytorch.serve.http.api.rest.ManagementRequestHandler.handleScaleModel(ManagementRequestHandler.java:241) ~[model-server.jar:?]
	at org.pytorch.serve.http.api.rest.ManagementRequestHandler.handleRequest(ManagementRequestHandler.java:92) ~[model-server.jar:?]
	at org.pytorch.serve.http.api.rest.ApiDescriptionRequestHandler.handleRequest(ApiDescriptionRequestHandler.java:41) ~[model-server.jar:?]
	at org.pytorch.serve.http.HttpRequestHandler.channelRead0(HttpRequestHandler.java:45) [model-server.jar:?]
	at org.pytorch.serve.http.HttpRequestHandler.channelRead0(HttpRequestHandler.java:22) [model-server.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [model-server.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [model-server.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [model-server.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [model-server.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [model-server.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [model-server.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [model-server.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [model-server.jar:?]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [model-server.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [model-server.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [model-server.jar:?]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [model-server.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [model-server.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [model-server.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [model-server.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [model-server.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [model-server.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [model-server.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [model-server.jar:?]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) [model-server.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) [model-server.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [model-server.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [model-server.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [model-server.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [model-server.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```
I think this case should be handled too.
Maybe show an appropriate status code (406 nor something?) with a better message if a negative number is given?
