### ISSUE TITLE
On stopping torchserve number of errors get logged and program does not exit

### ISSUE THREAD

**Issue by chauhang** [pytorch/serve#208]
On stopping torchserve using `torchserve --stop` a number of errors get logged on the console and the program does not exit, one has to hit ctrl-c to kill the process. Errors are thrown on stopping even if there are no active inference requests on the server and it has been idle for few hours. 

Errors: 
------
```
torchserve --stop
TorchServe has stopped.
2020-04-17 05:34:17,093 [INFO ] epollEventLoopGroup-2-2 org.pytorch.serve.ModelServer - Management model server stopped.
2020-04-17 05:34:17,093 [INFO ] epollEventLoopGroup-2-1 org.pytorch.serve.ModelServer - Inference model server stopped.
(serve) ubuntu@ip-172-31-45-171:~/work$ 2020-04-17 05:34:17,326 [INFO ] epollEventLoopGroup-4-2 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_MODEL_LOADED
2020-04-17 05:34:17,327 [WARN ] W-9000-my_text_classifier_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker thread exception.
java.lang.IllegalMonitorStateException
	at java.base/java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:149)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1302)
	at java.base/java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:439)
	at org.pytorch.serve.wlm.Model.pollBatch(Model.java:175)
	at org.pytorch.serve.wlm.BatchAggregator.getRequest(BatchAggregator.java:33)
	at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:123)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-04-17 05:34:17,329 [DEBUG] W-9000-my_text_classifier_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-my_text_classifier_1.0 State change WORKER_MODEL_LOADED -> WORKER_STOPPED
2020-04-17 05:34:17,330 [INFO ] W-9000-my_text_classifier_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9000 in 1 seconds.
2020-04-17 05:34:17,518 [INFO ] epollEventLoopGroup-4-1 org.pytorch.serve.wlm.WorkerThread - 9001 Worker disconnected. WORKER_MODEL_LOADED
2020-04-17 05:34:17,518 [DEBUG] W-9001-my_text_classifier_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133)
	at java.base/java.util.concurrent.LinkedBlockingDeque.pollFirst(LinkedBlockingDeque.java:513)
	at java.base/java.util.concurrent.LinkedBlockingDeque.poll(LinkedBlockingDeque.java:675)
	at org.pytorch.serve.wlm.Model.pollBatch(Model.java:155)
	at org.pytorch.serve.wlm.BatchAggregator.getRequest(BatchAggregator.java:33)
	at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:123)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-04-17 05:34:17,520 [DEBUG] W-9001-my_text_classifier_1.0 org.pytorch.serve.wlm.WorkerThread - W-9001-my_text_classifier_1.0 State change WORKER_MODEL_LOADED -> WORKER_STOPPED
2020-04-17 05:34:17,520 [INFO ] W-9001-my_text_classifier_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9001 in 1 seconds.
2020-04-17 05:34:18,398 [INFO ] W-9000-my_text_classifier_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Listening on port: /tmp/.ts.sock.9000
2020-04-17 05:34:18,398 [INFO ] W-9000-my_text_classifier_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - [PID]8693
2020-04-17 05:34:18,398 [INFO ] W-9000-my_text_classifier_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Torch worker started.
2020-04-17 05:34:18,398 [DEBUG] W-9000-my_text_classifier_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-my_text_classifier_1.0 State change WORKER_STOPPED -> WORKER_STARTED
2020-04-17 05:34:18,398 [INFO ] W-9000-my_text_classifier_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Python runtime: 3.8.2
2020-04-17 05:34:18,398 [INFO ] W-9000-my_text_classifier_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /tmp/.ts.sock.9000
2020-04-17 05:34:18,400 [INFO ] W-9000-my_text_classifier_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Connection accepted: /tmp/.ts.sock.9000.
2020-04-17 05:34:18,586 [INFO ] W-9001-my_text_classifier_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Listening on port: /tmp/.ts.sock.9001
2020-04-17 05:34:18,586 [INFO ] W-9001-my_text_classifier_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - [PID]8698
2020-04-17 05:34:18,586 [INFO ] W-9001-my_text_classifier_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Torch worker started.
2020-04-17 05:34:18,586 [INFO ] W-9001-my_text_classifier_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Python runtime: 3.8.2
2020-04-17 05:34:18,586 [DEBUG] W-9001-my_text_classifier_1.0 org.pytorch.serve.wlm.WorkerThread - W-9001-my_text_classifier_1.0 State change WORKER_STOPPED -> WORKER_STARTED
2020-04-17 05:34:18,586 [INFO ] W-9001-my_text_classifier_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /tmp/.ts.sock.9001
2020-04-17 05:34:18,588 [INFO ] W-9001-my_text_classifier_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Connection accepted: /tmp/.ts.sock.9001.
2020-04-17 05:34:19,229 [INFO ] W-9000-my_text_classifier_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Model loaded on device cuda:1 
2020-04-17 05:34:19,253 [INFO ] W-9001-my_text_classifier_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Model loaded on device cuda:2 
2020-04-17 05:34:19,308 [INFO ] main org.pytorch.serve.ModelServer - Torchserve stopped.
```

**Comment by CerebralSeed** [comment]
I'm not sure if this is the exact issue of the op, but I found going through the model_log.log file in the /logs folder that Torch Serve doesn't like *args, **kwargs in your model's defining parameters. I found after deleting these, that the error went away.
