### ISSUE TITLE
different behaviour of JSONEnvelope when testing locally and running TS in docker

### ISSUE THREAD

**Issue by veronikayurchuk** [pytorch/serve#2159]
### 🐛 Describe the bug

I tested JSON envelope locally and everything worked as expected.
While running in docker, enveloping step transforms the request data so that it doesn't follow local behavior.

Here is the way I tested enveloping step.

```
import os
import base64
from handler_vertex import handle as custom_handle
from ts.torch_handler.request_envelope.json import JSONEnvelope
from ts.torch_handler.unit_tests.test_utils.mock_context import MockContext

PATH = '../helpers/test_data/example_1'


def get_images_dict(path):
    images_dict = {}
    images_pathes = sorted([os.path.join(path, x) for x in os.listdir(path) if x.endswith(".jpg")])
    for (i, image_path) in enumerate(images_pathes):
        with open(image_path, 'rb') as f:
            image_read = f.read()
            image_64_encode = base64.b64encode(image_read)
            bytes_array = image_64_encode.decode("utf-8")
            images_dict["image_{}".format(i)] = bytes_array
    return images_dict


def create_json_eveloped_test_data(path: str) -> dict:
    """
    creates request following example https://cloud.google.com/ai-platform/prediction/docs/getting-started-pytorch-container
    :param path:
    :return: dict
    Example:
    {"instances": [
        {
            "image_0": {
                "b64": # an image of type 'str'
                }
            },
        {
            "image_1": {
                "b64": # an image of type 'str'
                }
            }
        ]
    }
    """
    images_dict = get_images_dict(path)
    request = {"instances": [{k: {"b64": v}} for k, v in images_dict.items()]}
    return request


def test_binary(model_context):
    # took from https://github.com/pytorch/serve/blob/master/ts/torch_handler/unit_tests/test_envelopes.py#L76
    # for local testing
    test_data: dict = create_json_eveloped_test_data(path=PATH)
    envelope = JSONEnvelope(handle_fn=custom_handle)
    results = envelope.handle([test_data], model_context)
    print(results)


if __name__ == '__main__':
    context = MockContext(
        model_pt_file='my_model.pt',
        model_file=None)
    test_binary(context)
print()

```

The `preprocess` function of my custom handler is below
```
class VertexInstance:
    def __init__(self, instance: dict):
        self.name: str = list(instance.keys())[0]
        self.id: int = int(self.name.split("_")[-1])
        self.data: bytes = instance[self.name]

@dataclass
class ImageHolder:
    array: np.ndarray

    @classmethod
    def from_content(cls, content: bytes):
        buf = io.BytesIO(content)
        image = Image.open(buf).convert('RGB')
        return ImageHolder(array=np.array(image))


class Custom_Model(BaseHandler):
    
    def read_img(self, data, i):
        return i, ImageHolder.from_content(data)

    def preprocess(self, request):
        """
        For Vertex schema after enveloping request is a list of dicts with one key, i.e "image_0", etc
        """
        print("________________Received {} request in batch________________".format(len(request)))
        print("________________ Request element type {} ________________".format(type(request[0])))

        images_instances = [VertexInstance(x) for x in request]

        with confu.ThreadPoolExecutor(6) as executor:
            futures = [executor.submit(self.read_img, image_instance.data, image_instance.id) for image_instance in
                       images_instances]
        images = [x.result() for x in confu.as_completed(futures)]
        return [images]
```

### Error logs

Logs show that the problem occurs in the `preprocess` function in the custom handler. After enveloping request data, it transforms it into a list of `int`s. However, when I tested locally using the code above, I received a list of `dict`s, which I expected.

```
...
2023-02-24T20:19:54,784 [INFO ] W-9000-fa_1.0 org.pytorch.serve.wlm.WorkerThread - Flushing req. to backend at: 1677269994784
2023-02-24T20:19:54,786 [INFO ] W-9000-fa_1.0-stdout MODEL_LOG - Backend received inference at: 1677269994
2023-02-24T20:19:54,787 [INFO ] W-9000-fa_1.0-stdout MODEL_LOG - LOCAL LOG  Running on cuda:0
2023-02-24T20:19:54,796 [INFO ] W-9000-fa_1.0-stdout MODEL_LOG - _______________Init time is 0.0095 seconds
2023-02-24T20:19:54,796 [INFO ] W-9000-fa_1.0-stdout MODEL_LOG - _______________Preprocessing_______________
2023-02-24T20:19:54,796 [INFO ] W-9000-fa_1.0-stdout MODEL_LOG - **________________Received 48192 request in batch________________**
2023-02-24T20:19:54,797 [INFO ] W-9000-fa_1.0-stdout MODEL_LOG - **________________ Request element type <class 'int'> ________________**
2023-02-24T20:19:54,797 [INFO ] W-9000-fa_1.0-stdout MODEL_LOG - Invoking custom service failed.
2023-02-24T20:19:54,797 [INFO ] W-9000-fa_1.0-stdout MODEL_LOG - Traceback (most recent call last):
2023-02-24T20:19:54,797 [INFO ] W-9000-fa_1.0-stdout MODEL_LOG -   File "/usr/local/lib/python3.8/dist-packages/ts/service.py", line 120, in predict
2023-02-24T20:19:54,797 [INFO ] W-9000-fa_1.0-stdout MODEL_LOG -     ret = self._entry_point(input_batch, self.context)
2023-02-24T20:19:54,797 [INFO ] W-9000-fa_1.0 org.pytorch.serve.wlm.WorkerThread - Backend response time: 12
2023-02-24T20:19:54,797 [INFO ] W-9000-fa_1.0-stdout MODEL_LOG -   File "/usr/local/lib/python3.8/dist-packages/ts/torch_handler/request_envelope/base.py", line 28, in handle
2023-02-24T20:19:54,797 [INFO ] W-9000-fa_1.0-stdout MODEL_LOG -     results = self._handle_fn(data, context)
2023-02-24T20:19:54,797 [INFO ] W-9000-fa_1.0-stdout MODEL_LOG -   File "/home/model-server/tmp/models/9915ec7bdc1c4d609c9f1c6aa63d4520/handler_vertex.py", line 494, in handle
2023-02-24T20:19:54,797 [INFO ] W-9000-fa_1.0-stdout MODEL_LOG -     preprocesses_data = _service.preprocess(data)
2023-02-24T20:19:54,798 [INFO ] W-9000-fa_1.0 ACCESS_LOG - /172.17.0.1:51988 "POST /predictions/fa HTTP/1.1" 503 23
2023-02-24T20:19:54,798 [INFO ] W-9000-fa_1.0-stdout MODEL_LOG -   File "/home/model-server/tmp/models/9915ec7bdc1c4d609c9f1c6aa63d4520/handler_vertex.py", line 396, in preprocess
2023-02-24T20:19:54,798 [INFO ] W-9000-fa_1.0 TS_METRICS - Requests5XX.Count:1|#Level:Host|#hostname:76348ce69fca,timestamp:1677266787
2023-02-24T20:19:54,798 [INFO ] W-9000-fa_1.0-stdout MODEL_LOG -     images_instances = [VertexInstance(x) for x in request]
2023-02-24T20:19:54,798 [INFO ] W-9000-fa_1.0-stdout MODEL_LOG -   File "/home/model-server/tmp/models/9915ec7bdc1c4d609c9f1c6aa63d4520/handler_vertex.py", line 396, in <listcomp>
2023-02-24T20:19:54,798 [DEBUG] W-9000-fa_1.0 org.pytorch.serve.job.Job - Waiting time ns: 177619, Inference time ns: 14459900
2023-02-24T20:19:54,798 [INFO ] W-9000-fa_1.0-stdout MODEL_LOG -     images_instances = [VertexInstance(x) for x in request]
2023-02-24T20:19:54,798 [INFO ] W-9000-fa_1.0 TS_METRICS - WorkerThreadTime.ms:2|#Level:Host|#hostname:76348ce69fca,timestamp:1677269994
2023-02-24T20:19:54,798 [INFO ] W-9000-fa_1.0-stdout MODEL_LOG -   File "/home/model-server/tmp/models/9915ec7bdc1c4d609c9f1c6aa63d4520/handler_vertex.py", line 295, in __init__
2023-02-24T20:19:54,798 [INFO ] W-9000-fa_1.0-stdout MODEL_LOG -     self.name: str = list(instance.keys())[0]
2023-02-24T20:19:54,798 [INFO ] W-9000-fa_1.0-stdout MODEL_LOG - AttributeError: 'int' object has no attribute 'keys'
```

### Installation instructions

I am using docker as described [here](https://cloud.google.com/blog/topics/developers-practitioners/pytorch-google-cloud-how-deploy-pytorch-models-vertex-ai), the only difference is I am using **pytorch/torchserve:latest-gpu**

### Model Packaing

Packaging is done automatically as described in Dockerfile from the [blogpost](https://cloud.google.com/blog/topics/developers-practitioners/pytorch-google-cloud-how-deploy-pytorch-models-vertex-ai)

### config.properties

inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
metrics_address=http://0.0.0.0:8082
number_of_netty_threads=32
job_queue_size=1000
model_store=/home/model-server/model-store
workflow_store=/home/model-server/wf-store

service_envelope=json
inference_address=http://0.0.0.0:7080
management_address=http://0.0.0.0:7081

### Versions

Environment headers
------------------------------------------------------------------------------------------
Torchserve branch:

torchserve==0.7.1b20230208
torch-model-archiver==0.7.1b20230208

Python version: 3.8 (64-bit runtime)
Python executable: /usr/bin/python3

Versions of relevant python libraries:
captum==0.6.0
intel-extension-for-pytorch==1.13.0
numpy==1.19.2
nvgpu==0.9.0
psutil==5.7.3
pygit2==1.11.1
pylint==2.6.0
pytest==6.0.1
pytest-benchmark==3.2.3
pytest-cov==4.0.0
pytest-mock==3.10.0
requests==2.28.2
requests-toolbelt==0.10.1
torch==1.13.1+cu117
torch-model-archiver==0.7.1b20230208
torch-workflow-archiver==0.2.7b20230208
torchaudio==0.13.1+cu117
torchserve==0.7.1b20230208
torchtext==0.14.1
torchvision==0.14.1+cu117
transformers==4.25.1
wheel==0.38.4
torch==1.13.1+cu117
torchtext==0.14.1
torchvision==0.14.1+cu117
torchaudio==0.13.1+cu117

Java Version:

OS: Ubuntu 20.04.5 LTS
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: N/A
CMake version: N/A

Is CUDA available: Yes
CUDA runtime version: N/A
GPU models and configuration:
GPU 0: Tesla T4
Nvidia driver version: 470.161.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.5.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.5.0

### Repro instructions

wrote on the top, but I can provide more details if needed

**Comment by msaroufim** [comment]
cc @jagadeeshi2i

**Comment by jagadeeshi2i** [comment]
@veronikayurchuk the envelope expects a `data` or `body` key in the input like
```
cat > ./predictor/instances.json <<END
{ 
   "instances": [
     { 
       "data": {
         "b64": "base64 image"
       }
     }
   ]
}
```
Were you able to use service_envelope directly by hitting Torchserve with json input ?

**Comment by jagadeeshi2i** [comment]
@veronikayurchuk the evelope looks for `data` or `body` key. Can you try the below format

```
{
       "instances": [{
              "data": {
                  "b64": "iVBORw0KGgoAAAANSUhEK5CYII="
              }
          }]
}
```

I could run the `mnist` example with `json` service envelope both locally and inside docker.

**Comment by veronikayurchuk** [comment]
Also, this is the structure I expect to receive in my `preprocess` function in my custom handler Custom_Model as this is what I receive testing locally.
```json
[
  {
    "image_0": b'iVBORw0KGgoAAAANSUhEK5CYII='
  },
  {
    "image_1": b'iVBORw0KGgoAAAANSUhEK5CYII='
  }
]
```
but in fact, running in docker I receive a `list` of `int`s

**Comment by jagadeeshi2i** [comment]
Can you share me the steps that you used for running in docker ?

**Comment by veronikayurchuk** [comment]
Hi @jagadeeshi2i ,

I simply followed the [blogpost from the original repo](https://cloud.google.com/blog/topics/developers-practitioners/pytorch-google-cloud-how-deploy-pytorch-models-vertex-ai) starting from step 3 (as my custom handler was already created).

The steps are building a docker image and running a docker container.
In detail, my steps are:
`docker build .`
`docker run -t -d --rm -p 7080:7080 --name="mymodel" 123456abc`

This is how my Dockerfile looks like

```dockerfile
FROM pytorch/torchserve:latest-gpu

# install dependencies
COPY requirements.txt /home/model-server/

ENV APP_NAME=my_model

# copy model artifacts, custom handler and other dependencies
COPY ./handlers/mymodel_vertex.py /home/model-server/
COPY ./handlers/base.py /home/model-server/
COPY ./handlers/utils.py /home/model-server/

COPY ./scripts/model.pt /home/model-server/

# create torchserve configuration file
USER root
RUN printf "\nservice_envelope=json" >> /home/model-server/config.properties
RUN printf "\ninference_address=http://0.0.0.0:7080" >> /home/model-server/config.properties
RUN printf "\nmanagement_address=http://0.0.0.0:7081" >> /home/model-server/config.properties
USER model-server

# expose health and prediction listener ports from the image
EXPOSE 7080
EXPOSE 7081

RUN pip3 install -r /home/model-server/requirements.txt
# create model archive file packaging model artifacts and dependencies
RUN torch-model-archiver -f \
  --model-name=${APP_NAME} \
  --version=1.0 \
  --serialized-file=/home/model-server/model.pt \
  --handler=/home/model-server/mymodel_vertex.py \
  --extra-files="/home/model-server/base.py,/home/model-server/utils.py" \
  --export-path=/home/model-server/model-store
#
## run Torchserve HTTP serve to respond to prediction requests
CMD ["torchserve", \
     "--start", \
     "--ts-config=/home/model-server/config.properties", \
     "--models", \
     "fa=${APP_NAME}.mar", \
     "--model-store", \
     "/home/model-server/model-store"]
```

**Comment by veronikayurchuk** [comment]
The issue was on my side. 
I deeply apologize for the distraction.
