### ISSUE TITLE
Error: Could not find or load main class org.pytorch.serve.ModelServer

### ISSUE THREAD

**Issue by DSXiangLi** [pytorch/serve#2177]
### 🐛 Describe the bug

I found several issue related to this problem. I already tried: create new environment, pip install -U instead of -e,  pip/ conda install. However none of the above solved this problem. 
Here is my environment
1. Java: 
openjdk 11.0.18 2023-01-17 LTS
OpenJDK Runtime Environment (Red_Hat-11.0.18.0.10-1.el7_9) (build 11.0.18+10-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-11.0.18.0.10-1.el7_9) (build 11.0.18+10-LTS, mixed mode, sharing)
2. Linux
Linux version 3.10.0-1160.53.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Fri Jan 14 13:59:45 UTC 2022

One Problem I found is in frontend part. I can't download graddle, instead I put graddle.zip into frontend/gradle/wrapper, and change gradle-wrapper.properties accordingly, however when I run  ./gradlew -p frontend clean assemble, Build failed with exception: The specified project directory '/home/lixiang/serve/frontend/frontend' does not exist. 

Any Idea what happened? 

Thanks 

### Error logs

1. torchserve Error 
Error: Could not find or load main class org.pytorch.serve.ModelServer
Caused by: java.lang.ClassNotFoundException: org.pytorch.serve.ModelServer

2. ./gradlew -p frontend clean assemble --stacktrace
FAILURE: Build failed with an exception.

* What went wrong:
The specified project directory '/home/lixiang/serve/frontend/frontend' does not exist.

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
java.lang.IllegalArgumentException: The specified project directory '/home/lixiang/serve/frontend/frontend' does not exist.
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:52)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:40)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:47)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:31)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:65)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:39)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:29)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:35)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:78)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:75)
        at org.gradle.util.internal.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:75)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:84)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)

* Get more help at https://help.gradle.org

BUILD FAILED in 604ms

### Installation instructions

I build from source 

### Model Packaing

Packing works fine

### Versions

------------------------------------------------------------------------------------------
Environment headers
------------------------------------------------------------------------------------------
Torchserve branch: 

torchserve==0.7.1
torch-model-archiver==0.7.1

Python version: 3.8 (64-bit runtime)
Python executable: /home/sulixiang/.conda/envs/py39_2/bin/python

Versions of relevant python libraries:
captum==0.6.0
numpy==1.24.2
nvgpu==0.9.0
psutil==5.9.4
requests==2.28.2
torch==1.13.1
torch-model-archiver==0.7.1
torch-workflow-archiver==0.2.7
torchserve==0.7.1
wheel==0.38.4
torch==1.13.1
**Warning: torchtext not present ..
**Warning: torchvision not present ..
**Warning: torchaudio not present ..

Java Version:

OS: CentOS Linux release 7.9.2009 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Clang version: N/A
CMake version: version 3.25.0-rc2

Is CUDA available: Yes
CUDA runtime version: N/A
GPU models and configuration: 
GPU 0: Tesla T4
GPU 1: Tesla T4
Nvidia driver version: 460.91.03
cuDNN version: Probably one of the following:
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.8.1.1
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.1.1
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.1.1
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.1.1
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.1.1
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.1.1
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.1.1

### Repro instructions

conda create -n py39_2 python=3.8

DIR='/home/lixiang/serve'
cd $DIR

python ./ts_scripts/install_dependencies.py --cuda=cu113

pip install torchserve torch-model-archiver torch-workflow-archiver -i https://pypi.tuna.tsinghua.edu.cn/simple/

export PYTHONPATH=$PATH:$DIR
models='event.mar'
model_store='./event'
config='./event/config.properties'

torchserve --start \
           --model-store $model_store \
           --models $models \
           --ts-config $config

**Comment by namannandan** [comment]
@DSXiangLi Looking the error logs, I see that gradle is unable to find the project directory
`The specified project directory '/home/lixiang/serve/frontend/frontend' does not exist.`
Could you try running the command from the `/home/lixiang/serve/` directory as follows:
```
$ pwd
/home/lixiang/serve/
$ ./frontend/gradlew -p frontend clean assemble
```

**Comment by DSXiangLi** [comment]
> 

@namannandan Thanks for replying. I have already tried running the gradlew command in the serve folder. However same error occured.

**Comment by lxning** [comment]
@DSXiangLi please try
- cd server/frontned
- ./gradlew clean
- ./gradlew build
