### ISSUE TITLE
How to prevent torchserve unloading my models in case of inactivity?

### ISSUE THREAD

**Issue by petrovicu** [pytorch/serve#2224]
### 📚 The doc issue

According to my experience, even though I wasn't able to find it in documentation, torchserve unloads a model after some time of inactivity. After the inference api for that model is invoked, it will load it again in memory, and thus increasing total inference time.
Can I control that behavior and set appropriate inactivity time?
Or can I just disable that option at all, and have all my models always loaded in memory?

**Comment by lxning** [comment]
@petrovicu it can help us identifying the root cause if you can provide log. The other thing what you can try is to run [describeAPI](https://github.com/pytorch/serve/blob/master/docs/management_api.md#describe-model) to check each model's status  before you re-register a model.

**Comment by petrovicu** [comment]
@lxning Thanks again for helping here.
Since the model re-loading is not controlled by me, but triggered by TS from time to time, it is impossible to invoke describeAPI at that particular moment.
Please find some logs below.

Inside of the **model_log.log** I can only see the model is loaded again. 
However, from a **ts_log.log** I can see that the worker disconnected and some concurrent exceptions as well:

`2023-04-10T15:00:44,117 [INFO ] W-9002-my_model_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9002-my_model_1.0-stdout
2023-04-10T15:00:44,118 [INFO ] epollEventLoopGroup-5-5 org.pytorch.serve.wlm.WorkerThread - 9002 Worker disconnected. WORKER_MODEL_LOADED
2023-04-10T15:00:44,117 [INFO ] W-9002-my_model_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9002-my_model_1.0-stderr
2023-04-10T15:00:44,117 [INFO ] W-9002-my_model_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9002-my_model_1.0-stdout
2023-04-10T15:00:44,117 [INFO ] W-9002-my_model_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9002-my_model_1.0-stderr
2023-04-10T15:00:44,118 [INFO ] epollEventLoopGroup-5-5 org.pytorch.serve.wlm.WorkerThread - 9002 Worker disconnected. WORKER_MODEL_LOADED
2023-04-10T15:00:44,125 [DEBUG] W-9002-my_model_1.0 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_MODEL_LOADED
2023-04-10T15:00:44,125 [DEBUG] W-9002-my_model_1.0 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_MODEL_LOADED
2023-04-10T15:00:44,125 [DEBUG] W-9002-my_model_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.

java.lang.InterruptedException: null
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056) ~[?:?]
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133) ~[?:?]
        at java.util.concurrent.LinkedBlockingDeque.pollFirst(LinkedBlockingDeque.java:513) ~[?:?]
        at java.util.concurrent.LinkedBlockingDeque.poll(LinkedBlockingDeque.java:675) ~[?:?]
        at org.pytorch.serve.wlm.Model.pollBatch(Model.java:200) ~[model-server.jar:?]
        at org.pytorch.serve.wlm.BatchAggregator.getRequest(BatchAggregator.java:33) ~[model-server.jar:?]
        at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:182) [model-server.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
2023-04-10T15:00:44,125 [DEBUG] W-9002-my_model_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException: null
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056) ~[?:?]
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133) ~[?:?]
        at java.util.concurrent.LinkedBlockingDeque.pollFirst(LinkedBlockingDeque.java:513) ~[?:?]
        at java.util.concurrent.LinkedBlockingDeque.poll(LinkedBlockingDeque.java:675) ~[?:?]
        at org.pytorch.serve.wlm.Model.pollBatch(Model.java:200) ~[model-server.jar:?]
        at org.pytorch.serve.wlm.BatchAggregator.getRequest(BatchAggregator.java:33) ~[model-server.jar:?]
        at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:182) [model-server.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
       
2023-04-10T15:00:44,127 [DEBUG] W-9002-my_model_1.0 org.pytorch.serve.wlm.WorkerThread - W-9002-my_model_1.0 State change WORKER_MODEL_LOADED -> WORKER_STOPPED
2023-04-10T15:00:44,127 [DEBUG] W-9002-my_model_1.0 org.pytorch.serve.wlm.WorkerThread - W-9002-my_model_1.0 State change WORKER_MODEL_LOADED -> WORKER_STOPPED
2023-04-10T15:00:44,130 [WARN ] W-9002-my_model_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9002-my_model_1.0-stderr
2023-04-10T15:00:44,130 [WARN ] W-9002-my_model_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9002-my_model_1.0-stderr
2023-04-10T15:00:44,130 [WARN ] W-9002-my_model_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9002-my_model_1.0-stdout
2023-04-10T15:00:44,130 [WARN ] W-9002-my_model_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9002-my_model_1.0-stdout
2023-04-10T15:00:44,130 [INFO ] W-9002-my_model_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9002 in 1 seconds.
2023-04-10T15:00:44,130 [INFO ] W-9002-my_model_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9002 in 1 seconds.
`

Then, 3 seconds later, model is reloaded again with:
`2023-04-10T15:00:47,874 [INFO ] W-9002-my_model_1.0-stdout MODEL_LOG - Listening on port: /tmp/.ts.sock.9002
2023-04-10T15:00:47,876 [INFO ] W-9002-my_model_1.0-stdout MODEL_LOG - [PID]217688
2023-04-10T15:00:47,876 [INFO ] W-9002-my_model_1.0-stdout MODEL_LOG - Torch worker started.
2023-04-10T15:00:47,876 [INFO ] W-9002- .0-stdout MODEL_LOG - Python runtime: 3.9.16
2023-04-10T15:00:47,876 [DEBUG] W-9002-my_model_1.0 org.pytorch.serve.wlm.WorkerThread - W-9002-my_model_1.0 State change WORKER_STOPPED -> WORKER_STARTED
2023-04-10T15:00:47,876 [DEBUG] W-9002-my_model_1.0 org.pytorch.serve.wlm.WorkerThread - W-9002-my_model_1.0 State change WORKER_STOPPED -> WORKER_STARTED
2023-04-10T15:00:47,876 [INFO ] W-9002-my_model_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /tmp/.ts.sock.9002
2023-04-10T15:00:47,876 [INFO ] W-9002-my_model_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /tmp/.ts.sock.9002
2023-04-10T15:00:47,877 [INFO ] W-9002-my_model_1.0-stdout MODEL_LOG - Connection accepted: /tmp/.ts.sock.9002.
2023-04-10T15:00:47,877 [INFO ] W-9002-my_model_1.0 org.pytorch.serve.wlm.WorkerThread - Flushing req. to backend at: 1681138847877
2023-04-10T15:00:47,877 [INFO ] W-9002-my_model_1.0 org.pytorch.serve.wlm.WorkerThread - Flushing req. to backend at: 1681138847877
2023-04-10T15:00:47,877 [INFO ] W-9002-my_model_1.0-stdout MODEL_LOG - model_name: my_model, batchSize: 1
2023-04-10T15:00:48,446 [INFO ] W-9002-my_model_1.0-stdout MODEL_LOG - PyTorch version 1.13.1 available.
...`

Do you have any idea why and when this exception can occur?

**Comment by lxning** [comment]
@petrovicu according to log, TorchServe tried to recover the backend worker since it died. The recovery happens in [back_off](https://github.com/pytorch/serve/blob/master/frontend/server/src/main/java/org/pytorch/serve/wlm/WorkerThread.java#L53) seconds. You can add some log in your handler to debug your model.
```
2023-04-10T15:00:44,130 [INFO ] W-9002-my_model_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9002 in 1 seconds.
2023-04-10T15:00:44,130 [INFO ] W-9002-my_model_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9002 in 1 seconds.
```

the following error is from nvgpu. I'm not sure if this PR fixed the error.
File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/ts/metrics/metric_collector.py", line 27, in
system_metrics.collect_all(sys.modules['ts.metrics.system_metrics'], arguments.gpu)
File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/ts/metrics/system_metrics.py", line 91, in collect_all
value(num_of_gpu)
File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/ts/metrics/system_metrics.py", line 72, in gpu_utilization
statuses = list_gpus.device_statuses()
File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/nvgpu/list_gpus.py", line 67, in device_statuses
return [device_status(device_index) for device_index in range(device_count)]
File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/nvgpu/list_gpus.py", line 67, in
return [device_status(device_index) for device_index in range(device_count)]
File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/nvgpu/list_gpus.py", line 18, in device_status
device_name = device_name.decode('UTF-8')
AttributeError: 'str' object has no attribute 'decode'

**Comment by petrovicu** [comment]
@lxning There is are additional model logs, since my models are working fine, but are just unloaded and loaded again from time to time, due to the fact that the worker thread stopped working.
I think the focus should be on this Java log:

java.lang.InterruptedException: null
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056) ~[?:?]
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133) ~[?:?]
at java.util.concurrent.LinkedBlockingDeque.pollFirst(LinkedBlockingDeque.java:513) ~[?:?]
at java.util.concurrent.LinkedBlockingDeque.poll(LinkedBlockingDeque.java:675) ~[?:?]
at org.pytorch.serve.wlm.Model.pollBatch(Model.java:200) ~[model-server.jar:?]
at org.pytorch.serve.wlm.BatchAggregator.getRequest(BatchAggregator.java:33) ~[model-server.jar:?]
at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:182) [model-server.jar:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
at java.lang.Thread.run(Thread.java:829) [?:?]
2023-04-10T15:00:44,125 [DEBUG] W-9002-my_model_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException: null
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056) ~[?:?]
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133) ~[?:?]
at java.util.concurrent.LinkedBlockingDeque.pollFirst(LinkedBlockingDeque.java:513) ~[?:?]
at java.util.concurrent.LinkedBlockingDeque.poll(LinkedBlockingDeque.java:675) ~[?:?]
at org.pytorch.serve.wlm.Model.pollBatch(Model.java:200) ~[model-server.jar:?]
at org.pytorch.serve.wlm.BatchAggregator.getRequest(BatchAggregator.java:33) ~[model-server.jar:?]
at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:182) [model-server.jar:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
at java.lang.Thread.run(Thread.java:829) [?:?]

Since no additional TS log is provided, maybe you can help with the information when and why this InterruptedException is raised in the TS source code?

**Comment by lxning** [comment]
@petrovicu please try increasing [responseTimeout](https://github.com/pytorch/serve/blob/master/docs/configuration.md#config-model) .
