### ISSUE TITLE
Benchmark auto validation failure for Inf2

### ISSUE THREAD

**Issue by namannandan** [pytorch/serve#2318]
### 🐛 Describe the bug

Inf2 benchmark auto-validation fails with the exception trace shown below
Sample run: https://github.com/pytorch/serve/actions/runs/4834127396/jobs/8699017173

### Error logs

```
Traceback (most recent call last):
  File "benchmarks/validate_report.py", line 95, in <module>
    main()
  File "benchmarks/validate_report.py", line 91, in main
    validate_reports(args.input_artifacts_dir, args.input_report_dir, args.deviation)
  File "benchmarks/validate_report.py", line 20, in validate_reports
    num_reports = len(os.listdir(artifacts_dir))
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ts_artifacts/inf2_benchmark_validation'
Error: Process completed with exit code 1.
```

### Installation instructions

Inf2 benchmark workflow: https://github.com/pytorch/serve/actions/runs/4834127396/workflow

### Model Packaing

Model artifacts:
https://torchserve.pytorch.org/mar_files/BERTSeqClassification_torchscript_neuronx_batch_1.mar
https://torchserve.pytorch.org/mar_files/BERTSeqClassification_torchscript_neuronx_batch_2.mar
https://torchserve.pytorch.org/mar_files/BERTSeqClassification_torchscript_neuronx_batch_4.mar
https://torchserve.pytorch.org/mar_files/BERTSeqClassification_torchscript_neuronx_batch_8.mar

### Versions

Torchserve master branch

### Repro instructions

Run Inf2 benchmark workflow: https://github.com/pytorch/serve/actions/workflows/benchmark_inf2_nightly.yml

**Comment by namannandan** [comment]
This issue was resolved after skipping validation step in a single benchmark run and then enabling the validation steps for subsequent runs: https://github.com/pytorch/serve/actions/runs/4986426850
