### ISSUE TITLE
Server Crashes when gRPC channel is closed unexpectedly on client side.

### ISSUE THREAD

**Issue by LaurinmyReha** [pytorch/serve#2321]
### 🐛 Describe the bug

When closing a GRPC channel on the client side unexpectedly the torchserve server crashes.

The following snipped for example crashes the server. 

```
channel = grpc.insecure_channel(f"{my_ip}:7070")

stub = inference_pb2_grpc.InferenceAPIsServiceStub(channel)

request = inference_pb2.PredictionsRequest(model_name="faster_whisper", input=req)

try:
    for resp in stub.StreamPredictions(request):
        channel.close()
        print(resp.prediction.decode('utf-8'))
        
except grpc.RpcError as e:
    exit(1)
```

### Error logs

2023-05-03T17:01:47,540 [WARN ] W-9000-faster_whisper_1 org.pytorch.serve.wlm.WorkerThread - Backend worker thread exception.
java.lang.IllegalStateException: Stream was terminated by error, no further calls are allowed
        at com.google.common.base.Preconditions.checkState(Preconditions.java:502) ~[model-server.jar:?]
        at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onNext(ServerCalls.java:374) ~[model-server.jar:?]
        at org.pytorch.serve.job.GRPCJob.response(GRPCJob.java:69) ~[model-server.jar:?]
        at org.pytorch.serve.wlm.BatchAggregator.sendResponse(BatchAggregator.java:84) ~[model-server.jar:?]
        at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:239) [model-server.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
2023-05-03T17:01:47,655 [DEBUG] W-9000-faster_whisper_1 org.pytorch.serve.wlm.WorkerThread - W-9000-faster_whisper_1 State change WORKER_MODEL_LOADED -> WORKER_STOPPED
2023-05-03T17:01:47,655 [INFO ] epollEventLoopGroup-5-1 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_MODEL_LOADED
2023-05-03T17:01:47,656 [WARN ] W-9000-faster_whisper_1 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-faster_whisper_1-stderr
2023-05-03T17:01:47,656 [WARN ] W-9000-faster_whisper_1 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-faster_whisper_1-stdout
2023-05-03T17:01:47,657 [INFO ] W-9000-faster_whisper_1 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9000 in 1 seconds.
2023-05-03T17:01:47,872 [INFO ] W-9000-faster_whisper_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-faster_whisper_1-stdout
2023-05-03T17:01:47,872 [INFO ] W-9000-faster_whisper_1-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-faster_whisper_1-stderr
2023-05-03T17:01:48,658 [DEBUG] W-9000-faster_whisper_1 org.pytorch.serve.wlm.WorkerLifeCycle - Worker cmdline: [/opt/conda/envs/faster_whisper/bin/python3.8, /opt/conda/envs/faster_whisper/lib/python3.8/site-packages/ts/model_service_worker.py, --sock-type, unix, --sock-name, /tmp/.ts.sock.9000, --metrics-config, /opt/conda/envs/faster_whisper/lib/python3.8/site-packages/ts/configs/metrics.yaml]
2023-05-03T17:01:53,617 [INFO ] W-9000-faster_whisper_1-stdout MODEL_LOG - s_name_part0=/tmp/.ts.sock, s_name_part1=9000, pid=8767
2023-05-03T17:01:53,619 [INFO ] W-9000-faster_whisper_1-stdout MODEL_LOG - Listening on port: /tmp/.ts.sock.9000
2023-05-03T17:01:53,636 [INFO ] W-9000-faster_whisper_1-stdout MODEL_LOG - Successfully loaded /opt/conda/envs/faster_whisper/lib/python3.8/site-packages/ts/configs/metrics.yaml.
2023-05-03T17:01:53,636 [INFO ] W-9000-faster_whisper_1-stdout MODEL_LOG - [PID]8767
2023-05-03T17:01:53,637 [INFO ] W-9000-faster_whisper_1-stdout MODEL_LOG - Torch worker started.
2023-05-03T17:01:53,637 [INFO ] W-9000-faster_whisper_1-stdout MODEL_LOG - Python runtime: 3.8.16
2023-05-03T17:01:53,637 [DEBUG] W-9000-faster_whisper_1 org.pytorch.serve.wlm.WorkerThread - W-9000-faster_whisper_1 State change WORKER_STOPPED -> WORKER_STARTED
2023-05-03T17:01:53,638 [INFO ] W-9000-faster_whisper_1 org.pytorch.serve.wlm.WorkerThread - Connecting to: /tmp/.ts.sock.9000
2023-05-03T17:01:53,639 [INFO ] epollEventLoopGroup-5-1 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_STARTED
2023-05-03T17:01:53,640 [INFO ] W-9000-faster_whisper_1-stdout MODEL_LOG - Connection accepted: /tmp/.ts.sock.9000.
2023-05-03T17:01:53,640 [DEBUG] W-9000-faster_whisper_1 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_STARTED
2023-05-03T17:01:53,640 [DEBUG] W-9000-faster_whisper_1 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException: null
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1081) ~[?:?]
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1369) ~[?:?]
        at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:278) ~[?:?]
        at org.pytorch.serve.wlm.WorkerThread.connect(WorkerThread.java:426) ~[model-server.jar:?]
        at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:181) [model-server.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
2023-05-03T17:01:53,641 [DEBUG] W-9000-faster_whisper_1 org.pytorch.serve.wlm.WorkerThread - W-9000-faster_whisper_1 State change WORKER_STARTED -> WORKER_STOPPED
2023-05-03T17:01:53,642 [WARN ] W-9000-faster_whisper_1 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-faster_whisper_1-stderr
2023-05-03T17:01:53,642 [WARN ] W-9000-faster_whisper_1 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-faster_whisper_1-stdout
2023-05-03T17:01:53,642 [INFO ] W-9000-faster_whisper_1 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9000 in 1 seconds.
2023-05-03T17:01:53,658 [INFO ] W-9000-faster_whisper_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-faster_whisper_1-stdout
2023-05-03T17:01:53,658 [INFO ] W-9000-faster_whisper_1-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-faster_whisper_1-stderr
2023-05-03T17:01:54,643 [DEBUG] W-9000-faster_whisper_1 org.pytorch.serve.wlm.WorkerLifeCycle - Worker cmdline: [/opt/conda/envs/faster_whisper/bin/python3.8, /opt/conda/envs/faster_whisper/lib/python3.8/site-packages/ts/model_service_worker.py, --sock-type, unix, --sock-name, /tmp/.ts.sock.9000, --metrics-config, /opt/conda/envs/faster_whisper/lib/python3.8/site-packages/ts/configs/metrics.yaml]
2023-05-03T17:01:56,198 [INFO ] W-9000-faster_whisper_1-stdout MODEL_LOG - s_name_part0=/tmp/.ts.sock, s_name_part1=9000, pid=8787
2023-05-03T17:01:56,199 [INFO ] W-9000-faster_whisper_1-stdout MODEL_LOG - Listening on port: /tmp/.ts.sock.9000
2023-05-03T17:01:56,209 [INFO ] W-9000-faster_whisper_1-stdout MODEL_LOG - Successfully loaded /opt/conda/envs/faster_whisper/lib/python3.8/site-packages/ts/configs/metrics.yaml.
2023-05-03T17:01:56,209 [INFO ] W-9000-faster_whisper_1-stdout MODEL_LOG - [PID]8787
2023-05-03T17:01:56,209 [INFO ] W-9000-faster_whisper_1-stdout MODEL_LOG - Torch worker started.
2023-05-03T17:01:56,210 [INFO ] W-9000-faster_whisper_1-stdout MODEL_LOG - Python runtime: 3.8.16
2023-05-03T17:01:56,210 [DEBUG] W-9000-faster_whisper_1 org.pytorch.serve.wlm.WorkerThread - W-9000-faster_whisper_1 State change WORKER_STOPPED -> WORKER_STARTED
2023-05-03T17:01:56,210 [INFO ] W-9000-faster_whisper_1 org.pytorch.serve.wlm.WorkerThread - Connecting to: /tmp/.ts.sock.9000
2023-05-03T17:01:56,212 [INFO ] epollEventLoopGroup-5-1 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_STARTED
2023-05-03T17:01:56,212 [INFO ] W-9000-faster_whisper_1-stdout MODEL_LOG - Connection accepted: /tmp/.ts.sock.9000.
2023-05-03T17:01:56,213 [DEBUG] W-9000-faster_whisper_1 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_STARTED
2023-05-03T17:01:56,213 [DEBUG] W-9000-faster_whisper_1 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException: null
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056) ~[?:?]
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133) ~[?:?]
        at java.util.concurrent.LinkedBlockingDeque.pollFirst(LinkedBlockingDeque.java:513) ~[?:?]
        at java.util.concurrent.LinkedBlockingDeque.poll(LinkedBlockingDeque.java:675) ~[?:?]
        at org.pytorch.serve.wlm.Model.pollBatch(Model.java:256) ~[model-server.jar:?]
        at org.pytorch.serve.wlm.BatchAggregator.getRequest(BatchAggregator.java:36) ~[model-server.jar:?]
        at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:184) [model-server.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
2023-05-03T17:01:56,213 [DEBUG] W-9000-faster_whisper_1 org.pytorch.serve.wlm.WorkerThread - W-9000-faster_whisper_1 State change WORKER_STARTED -> WORKER_STOPPED
2023-05-03T17:01:56,214 [WARN ] W-9000-faster_whisper_1 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-faster_whisper_1-stderr
2023-05-03T17:01:56,214 [WARN ] W-9000-faster_whisper_1 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-faster_whisper_1-stdout
2023-05-03T17:01:56,214 [INFO ] W-9000-faster_whisper_1 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9000 in 2 seconds.
2023-05-03T17:01:56,230 [INFO ] W-9000-faster_whisper_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-faster_whisper_1-stdout
2023-05-03T17:01:56,230 [INFO ] W-9000-faster_whisper_1-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-faster_whisper_1-stderr
2023-05-03T17:01:58,215 [DEBUG] W-9000-faster_whisper_1 org.pytorch.serve.wlm.WorkerLifeCycle - Worker cmdline: [/opt/conda/envs/faster_whisper/bin/python3.8, /opt/conda/envs/faster_whisper/lib/python3.8/site-packages/ts/model_service_worker.py, --sock-type, unix, --sock-name, /tmp/.ts.sock.9000, --metrics-config, /opt/conda/envs/faster_whisper/lib/python3.8/site-packages/ts/configs/metrics.yaml]
2023-05-03T17:01:59,709 [INFO ] W-9000-faster_whisper_1-stdout MODEL_LOG - s_name_part0=/tmp/.ts.sock, s_name_part1=9000, pid=8807
2023-05-03T17:01:59,710 [INFO ] W-9000-faster_whisper_1-stdout MODEL_LOG - Listening on port: /tmp/.ts.sock.9000
2023-05-03T17:01:59,720 [INFO ] W-9000-faster_whisper_1-stdout MODEL_LOG - Successfully loaded /opt/conda/envs/faster_whisper/lib/python3.8/site-packages/ts/configs/metrics.yaml.
2023-05-03T17:01:59,720 [INFO ] W-9000-faster_whisper_1-stdout MODEL_LOG - [PID]8807
2023-05-03T17:01:59,720 [INFO ] W-9000-faster_whisper_1-stdout MODEL_LOG - Torch worker started.
2023-05-03T17:01:59,721 [DEBUG] W-9000-faster_whisper_1 org.pytorch.serve.wlm.WorkerThread - W-9000-faster_whisper_1 State change WORKER_STOPPED -> WORKER_STARTED
2023-05-03T17:01:59,721 [INFO ] W-9000-faster_whisper_1-stdout MODEL_LOG - Python runtime: 3.8.16
2023-05-03T17:01:59,721 [INFO ] W-9000-faster_whisper_1 org.pytorch.serve.wlm.WorkerThread - Connecting to: /tmp/.ts.sock.9000
2023-05-03T17:01:59,723 [INFO ] epollEventLoopGroup-5-1 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_STARTED
2023-05-03T17:01:59,723 [INFO ] W-9000-faster_whisper_1-stdout MODEL_LOG - Connection accepted: /tmp/.ts.sock.9000.
2023-05-03T17:01:59,724 [DEBUG] W-9000-faster_whisper_1 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_STARTED
2023-05-03T17:01:59,724 [DEBUG] W-9000-faster_whisper_1 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException: null
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056) ~[?:?]
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133) ~[?:?]
        at java.util.concurrent.LinkedBlockingDeque.pollFirst(LinkedBlockingDeque.java:513) ~[?:?]
        at java.util.concurrent.LinkedBlockingDeque.poll(LinkedBlockingDeque.java:675) ~[?:?]
        at org.pytorch.serve.wlm.Model.pollBatch(Model.java:256) ~[model-server.jar:?]
        at org.pytorch.serve.wlm.BatchAggregator.getRequest(BatchAggregator.java:36) ~[model-server.jar:?]
        at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:184) [model-server.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
2023-05-03T17:01:59,724 [DEBUG] W-9000-faster_whisper_1 org.pytorch.serve.wlm.WorkerThread - W-9000-faster_whisper_1 State change WORKER_STARTED -> WORKER_STOPPED
2023-05-03T17:01:59,724 [WARN ] W-9000-faster_whisper_1 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-faster_whisper_1-stderr
2023-05-03T17:01:59,725 [WARN ] W-9000-faster_whisper_1 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-faster_whisper_1-stdout
2023-05-03T17:01:59,725 [INFO ] W-9000-faster_whisper_1 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9000 in 3 seconds.
2023-05-03T17:01:59,741 [INFO ] W-9000-faster_whisper_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-faster_whisper_1-stdout
2023-05-03T17:01:59,741 [INFO ] W-9000-faster_whisper_1-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-faster_whisper_1-stderr

### Installation instructions

faster-whisper==0.5.1
nvgpu==0.10.0
torch-model-archiver-nightly==2023.4.18
torchserve-nightly==2023.4.18
torch==2.0.0
torchaudio==2.0.1
transformers==4.23.0
soundfile==0.12.1
openai==0.27.4
grpcio==1.53.0
grpcio-tools==1.53.0
protobuf==4.22.3
pynvml==8.0.4

### Model Packaing
```
import base64
import copy
import logging
import os
import openai
import time

from ast import literal_eval
from faster_whisper import WhisperModel
from functools import wraps
from ts.torch_handler.base_handler import BaseHandler
from ts.protocol.otf_message_handler import send_intermediate_predict_response


logger = logging.getLogger(__name__)

def timeit(my_func):
    @wraps(my_func)
    def timed(*args, **kw):
        tstart = time.time()
        output = my_func(*args, **kw)
        tend = time.time()
        logger.info(
            '"{}" took {:.3f} ms to execute\n'.format(
                my_func.__name__, (tend - tstart) * 1000
            )
        )
        return output

    return timed


def decode_audio(bytes_audio, file_type: str = "mp3"):
    with open(f"decoded_audio.{file_type}", "wb") as file_to_save:
        decoded_audio = base64.decodebytes(bytes_audio)
        file_to_save.write(decoded_audio)
    return None


class StreamHandler(BaseHandler):

    @timeit
    def __init__(self):
        super(StreamHandler, self).__init__()

    @timeit
    def initialize(self, ctx):
        self.model = WhisperModel("large-v1", device="cuda", compute_type="float16")
        self.workdir = os.getcwd()
        self.context = ctx
        self.stream_gpt = True

    @timeit
    def preprocess(self, data):
        data = data[0]
        bytes_audio = data["audio"]
        data_format = data["format"].decode("utf-8")
        language_id = data["language_id"].decode("utf-8")

    @timeit
    def inference(self, data_format, language_id):
        segments, _ = self.model.transcribe(
            os.path.join(self.workdir, f"decoded_audio.{data_format}"),
            beam_size=5,
            language=language_id,
            temperature=0,
        )
        return segments

    @timeit
    def handle(self, data, context):
        (
            data_format,
            prompt_id,
            chat_history,
            language_id,
            gpt_model_version,
        ) = self.preprocess(data)
        segments = self.inference(data_format, language_id)
        # get Whisper Transcription from the segments generator returned by faster_whisper
        total_text = []
        for segment in segments:
            text_piece = segment.text.strip()
            total_text.append(text_piece)
            partial_transcript_result = {
                "response_type": "ASR",
                "transcript": text_piece.strip(),
            }
            # send back intermediate transcriptions
            send_intermediate_predict_response(
                [str(partial_transcript_result).replace("'", '"')],
                context.request_ids,
                "Intermediate Prediction success",
                200,
                context,
            )
        # join the transcripts to a full transcript
        whisper_transcript = (" ").join(total_text)
       
        return [whisper_transcript]
```

### config.properties

inference_address=http://0.0.0.0:8443
management_address=http://127.0.0.1:8444
metrics_address=http://127.0.0.1:8445
grpc_inference_port=7070

### Versions

------------------------------------------------------------------------------------------
Environment headers
------------------------------------------------------------------------------------------
Torchserve branch: 

torchserve==0.7.1b20230418
torch-model-archiver==0.7.1

Python version: 3.8 (64-bit runtime)
Python executable: /opt/conda/envs/faster_whisper/bin/python

Versions of relevant python libraries:
numpy==1.23.5
nvgpu==0.10.0
psutil==5.9.4
requests==2.28.2
torch==2.0.0
torch-model-archiver==0.7.1
torch-model-archiver-nightly==2023.4.18
torch-workflow-archiver==0.2.7
torch-workflow-archiver-nightly==2023.4.18
torchaudio==2.0.1
torchserve==0.7.1b20230418
torchserve-nightly==2023.4.18
transformers==4.23.0
wheel==0.40.0
torch==2.0.0
**Warning: torchtext not present ..
**Warning: torchvision not present ..
torchaudio==2.0.1

Java Version:

OS: Debian GNU/Linux 10 (buster)
GCC version: (Debian 8.3.0-6) 8.3.0
Clang version: N/A
CMake version: version 3.26.3

Is CUDA available: Yes
CUDA runtime version: 11.0.221
GPU models and configuration: 
GPU 0: Tesla T4
Nvidia driver version: 460.73.01
cuDNN version: None

### Repro instructions

torch-model-archiver   --model-name=faster_whisper  --version=1 --handler="faster_whisper_serving_grpc.py"  --force  --export-path=.

nohup torchserve  --ncs --start --ts-config config.properties --model-store . --models faster_whisper=faster_whisper.mar &

**Comment by evanshrestha** [comment]
Running into the same thing. Have you found any solutions?

**Comment by LaurinmyReha** [comment]
also feel free to tell me if i am stupid please!

**Comment by evanshrestha** [comment]
running into the same thing with the gRPC endpoint - unexpected client closures seem to throw the worker into a zombie state. doesn't occur with the HTTP endpoint.

**Comment by hnczlsr** [comment]
save problem
When the stream request is being processed, if the client side interrupt the request, the accessed model will crash, but the status of the queried model status remains "ready"

**Comment by LaurinmyReha** [comment]
i switched to using triton inference server using the python_backend. Takes some getting used to in the beginning but there are many examples and i could basically use my torchserver handler code with minmal adjustments with triton and have no further problems here with grpc there.

https://github.com/triton-inference-server/python_backend

**Comment by alvin319** [comment]
Any updates on this issue?

**Comment by mmjaz** [comment]
I have the same issue when setting timeout in grpc call, when timeout triggered sooner than model inference time with `torchserve-nightly==2024.2.23`
