### ISSUE TITLE
Fail to load ONNX model from MAR file

### ISSUE THREAD

**Issue by chenkai036** [pytorch/serve#2360]
### 🐛 Describe the bug

Since this [commit](https://github.com/pytorch/serve/commit/cf7544bf2150e6c6d42a8b75f52ea31508e9382b#diff-d30e1f5ef9fd05e2ab9f652c116461632586cc132dde5d23ac4bc5cd19c799ccR83) the backend worker process dies consistently during initialising the ONNX session from a given model archive.  The refactoring introduced the bug where `self` is still used in `setup_ort_session`.

### Error logs

2023-05-24T14:33:51,640 [INFO ] W-9001-mnist_8-stdout MODEL_LOG - ONNX enabled
2023-05-24T14:33:51,642 [INFO ] W-9001-mnist_8-stdout MODEL_LOG - Backend worker process died.
2023-05-24T14:33:51,642 [INFO ] W-9001-mnist_8-stdout MODEL_LOG - Traceback (most recent call last):
2023-05-24T14:33:51,643 [INFO ] W-9001-mnist_8-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/model_service_worker.py", line 253, in <module>
2023-05-24T14:33:51,643 [INFO ] W-9001-mnist_8-stdout MODEL_LOG -     worker.run_server()
2023-05-24T14:33:51,645 [INFO ] W-9001-mnist_8-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/model_service_worker.py", line 221, in run_server
2023-05-24T14:33:51,646 [INFO ] W-9001-mnist_8-stdout MODEL_LOG -     self.handle_connection(cl_socket)
2023-05-24T14:33:51,650 [INFO ] W-9001-mnist_8-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/model_service_worker.py", line 184, in handle_connection
2023-05-24T14:33:51,659 [INFO ] W-9001-mnist_8-stdout MODEL_LOG -     service, result, code = self.load_model(msg)
2023-05-24T14:33:51,660 [INFO ] W-9001-mnist_8-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/model_service_worker.py", line 131, in load_model
2023-05-24T14:33:51,661 [INFO ] W-9001-mnist_8-stdout MODEL_LOG -     service = model_loader.load(
2023-05-24T14:33:51,663 [INFO ] W-9001-mnist_8-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/model_loader.py", line 135, in load
2023-05-24T14:33:51,664 [INFO ] W-9001-mnist_8-stdout MODEL_LOG -     initialize_fn(service.context)
2023-05-24T14:33:51,665 [INFO ] W-9001-mnist_8-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/torch_handler/vision_handler.py", line 23, in initialize
2023-05-24T14:33:51,665 [INFO ] W-9001-mnist_8-stdout MODEL_LOG -     super().initialize(context)
2023-05-24T14:33:51,665 [INFO ] W-9001-mnist_8-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/torch_handler/base_handler.py", line 171, in initialize
2023-05-24T14:33:51,666 [INFO ] W-9001-mnist_8-stdout MODEL_LOG -     self.model = setup_ort_session(self.model_pt_path)
2023-05-24T14:33:51,667 [INFO ] W-9001-mnist_8-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/torch_handler/base_handler.py", line 83, in setup_ort_session
2023-05-24T14:33:51,671 [INFO ] W-9001-mnist_8-stdout MODEL_LOG -     if self.map_location == "cuda"
2023-05-24T14:33:51,673 [INFO ] W-9001-mnist_8-stdout MODEL_LOG - NameError: name 'self' is not defined

### Installation instructions

I'm using the officially released docker image: v0.8.0-cpu

### Model Packaing

The issue is not related to the MAR file since the same model archive worked with v0.7.1-cpu.  Nevertheless the packaging instruction is provided below

```
wget https://github.com/onnx/models/raw/main/vision/classification/mnist/model/mnist-8.onnx
torch-model-archive --model-name mnist --version 8 --serialized-file=mnist-8.onnx --handler image_classifier
```

### Versions

I'm using the official docker image: pytorch/torchserve:v0.8.0-cpu

### Repro instructions

```
wget https://github.com/onnx/models/raw/main/vision/classification/mnist/model/mnist-8.onnx
torch-model-archive --model-name mnist --version 8 --serialized-file=mnist-8.onnx --handler image_classifier
torchserve --start
```

**Comment by msaroufim** [comment]
Strange how our unit test didn't catch this, would you like to send over a PR fixing this?
