### ISSUE TITLE
Worker PID is not available yet

### ISSUE THREAD

**Issue by viratbiz** [pytorch/serve#2368]
### 🐛 Describe the bug

I am using python version 3.9. There is error coming that "Worker pid is not available yet." This is due to the model_service_worker.py in ts. The error is `name: "Integer" is not defined`. I have also attached the image for reference.

<img width="1371" alt="Screenshot 2023-05-29 at 1 42 22 PM" src="https://github.com/pytorch/serve/assets/122271047/763bbcb1-bcd3-4b82-9534-106dc11b14dc">

### Error logs

2023-05-29T13:36:37,550 [INFO ] W-9001-midjourney_1.0-stdout MODEL_LOG - Backend worker process died.
2023-05-29T13:36:37,551 [INFO ] W-9001-midjourney_1.0-stdout MODEL_LOG - Traceback (most recent call last):
2023-05-29T13:36:37,551 [INFO ] W-9001-midjourney_1.0-stdout MODEL_LOG -   File "/Users/virat.s/miniconda3/envs/python_39/lib/python3.9/site-packages/ts/model_service_worker.py", line 250, in <module>
2023-05-29T13:36:37,551 [INFO ] W-9001-midjourney_1.0-stdout MODEL_LOG -     worker = TorchModelServiceWorker(
2023-05-29T13:36:37,551 [INFO ] W-9001-midjourney_1.0-stdout MODEL_LOG -   File "/Users/virat.s/miniconda3/envs/python_39/lib/python3.9/site-packages/ts/model_service_worker.py", line 69, in __init__
2023-05-29T13:36:37,551 [INFO ] W-9001-midjourney_1.0-stdout MODEL_LOG -     self.port = Integer.pa + LOCAL_RANK
2023-05-29T13:36:37,551 [INFO ] W-9001-midjourney_1.0-stdout MODEL_LOG - NameError: name 'Integer' is not defined
2023-05-29T13:36:37,554 [INFO ] W-9005-midjourney_1.0-stdout MODEL_LOG - Backend worker process died.

### Installation instructions

pip install torch-model-archiver torchserve

### Model Packaing

Standard sytable_diffusion_handler.py

### Versions

Python version 3.9

### Repro instructions

torch-model-archiver --model-name midjourney --version 1.0 --handler midjourney_handler.py --extra-files model.zip -r requirements.txt

requirements.txt:
transformers
diffusers==0.16.1
numpy

torchserve --start --ts-config config.properties

**Comment by lxning** [comment]
@viratbiz could you provide your config.properties?

**Comment by viratbiz** [comment]
Using the default config properties given here: https://github.com/pytorch/serve/blob/master/examples/diffusers/config.properties

**Comment by lxning** [comment]
@viratbiz according to the above error log, [tcp](https://github.com/pytorch/serve/blob/master/ts/model_service_worker.py#L69) is used. However, the config.properties uses the socket. there is a log starting with "Worker cmdline:" in logs/ts_log.log. could you provide it so that i can know which protocol is used? Thanks,
