### ISSUE TITLE
Model load failed

### ISSUE THREAD

**Issue by weinixuehao** [pytorch/serve#2499]
```
2023-07-25T15:36:15,414 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Listening on addr:port: 127.0.0.1:9000
2023-07-25T15:36:15,430 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Successfully loaded C:\ProgramData\anaconda3\Lib\site-packages/ts/configs/metrics.yaml.
2023-07-25T15:36:15,430 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - [PID]3032
2023-07-25T15:36:15,430 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Torch worker started.
2023-07-25T15:36:15,446 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Python runtime: 3.11.3
2023-07-25T15:36:15,473 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Connection accepted: ('127.0.0.1', 9000).
2023-07-25T15:36:15,537 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - model_name: smart_recruit_1.1.0, batchSize: 1
2023-07-25T15:36:18,559 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Backend worker process died.
2023-07-25T15:36:18,578 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Traceback (most recent call last):
2023-07-25T15:36:18,606 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG -   File "C:\ProgramData\anaconda3\Lib\site-packages\ts\model_loader.py", line 100, in load
2023-07-25T15:36:18,606 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG -     module, function_name = self._load_handler_file(handler)
2023-07-25T15:36:18,621 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG -                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-25T15:36:18,621 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG -   File "C:\ProgramData\anaconda3\Lib\site-packages\ts\model_loader.py", line 145, in _load_handler_file
2023-07-25T15:36:18,637 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG -     module = importlib.import_module(module_name)
2023-07-25T15:36:18,648 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-25T15:36:18,678 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG -   File "C:\ProgramData\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
2023-07-25T15:36:18,682 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG -     return _bootstrap._gcd_import(name[level:], package, level)
2023-07-25T15:36:18,699 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-25T15:36:22,634 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Listening on addr:port: 127.0.0.1:9000
2023-07-25T15:36:22,634 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Successfully loaded C:\ProgramData\anaconda3\Lib\site-packages/ts/configs/metrics.yaml.
2023-07-25T15:36:22,634 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - [PID]908
2023-07-25T15:36:22,650 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Torch worker started.
2023-07-25T15:36:22,655 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Python runtime: 3.11.3
2023-07-25T15:36:22,656 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Connection accepted: ('127.0.0.1', 9000).
2023-07-25T15:36:26,652 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Listening on addr:port: 127.0.0.1:9000
2023-07-25T15:36:26,668 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Successfully loaded C:\ProgramData\anaconda3\Lib\site-packages/ts/configs/metrics.yaml.
2023-07-25T15:36:26,668 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - [PID]7880
2023-07-25T15:36:26,668 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Torch worker started.
2023-07-25T15:36:26,668 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Python runtime: 3.11.3
2023-07-25T15:36:26,674 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Connection accepted: ('127.0.0.1', 9000).
2023-07-25T15:36:31,762 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Listening on addr:port: 127.0.0.1:9000
2023-07-25T15:36:31,778 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Successfully loaded C:\ProgramData\anaconda3\Lib\site-packages/ts/configs/metrics.yaml.
2023-07-25T15:36:31,778 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - [PID]8236
2023-07-25T15:36:31,778 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Torch worker started.
2023-07-25T15:36:31,787 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Python runtime: 3.11.3
2023-07-25T15:36:31,792 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Connection accepted: ('127.0.0.1', 9000).
2023-07-25T15:36:37,793 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Listening on addr:port: 127.0.0.1:9000
2023-07-25T15:36:37,808 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Successfully loaded C:\ProgramData\anaconda3\Lib\site-packages/ts/configs/metrics.yaml.
2023-07-25T15:36:37,808 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - [PID]508
2023-07-25T15:36:37,808 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Torch worker started.
2023-07-25T15:36:37,813 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Python runtime: 3.11.3
2023-07-25T15:36:37,814 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Connection accepted: ('127.0.0.1', 9000).
2023-07-25T16:01:43,402 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Listening on addr:port: 127.0.0.1:9000
2023-07-25T16:01:43,402 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Successfully loaded C:\ProgramData\anaconda3\Lib\site-packages/ts/configs/metrics.yaml.
2023-07-25T16:01:43,402 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - [PID]6872
2023-07-25T16:01:43,402 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Torch worker started.
2023-07-25T16:01:43,402 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Python runtime: 3.11.3
2023-07-25T16:01:43,433 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Connection accepted: ('127.0.0.1', 9000).
2023-07-25T16:01:43,510 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - model_name: smart_recruit_1.1.0, batchSize: 1
2023-07-25T16:01:46,391 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Backend worker process died.
2023-07-25T16:01:46,401 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Traceback (most recent call last):
2023-07-25T16:01:46,413 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG -   File "C:\ProgramData\anaconda3\Lib\site-packages\ts\model_loader.py", line 100, in load
2023-07-25T16:01:46,445 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG -     module, function_name = self._load_handler_file(handler)
2023-07-25T16:01:46,478 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG -                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-25T16:01:46,514 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG -   File "C:\ProgramData\anaconda3\Lib\site-packages\ts\model_loader.py", line 145, in _load_handler_file
2023-07-25T16:01:46,519 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG -     module = importlib.import_module(module_name)
2023-07-25T16:01:46,521 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-25T16:01:46,521 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG -   File "C:\ProgramData\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
2023-07-25T16:01:46,529 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG -     return _bootstrap._gcd_import(name[level:], package, level)
2023-07-25T16:01:46,549 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-25T16:01:50,530 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Listening on addr:port: 127.0.0.1:9000
2023-07-25T16:01:50,546 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Successfully loaded C:\ProgramData\anaconda3\Lib\site-packages/ts/configs/metrics.yaml.
2023-07-25T16:01:50,546 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - [PID]3144
2023-07-25T16:01:50,546 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Torch worker started.
2023-07-25T16:01:50,559 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Python runtime: 3.11.3
2023-07-25T16:01:50,563 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Connection accepted: ('127.0.0.1', 9000).
2023-07-25T16:01:54,539 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Listening on addr:port: 127.0.0.1:9000
2023-07-25T16:01:54,554 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Successfully loaded C:\ProgramData\anaconda3\Lib\site-packages/ts/configs/metrics.yaml.
2023-07-25T16:01:54,554 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - [PID]6640
2023-07-25T16:01:54,554 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Torch worker started.
2023-07-25T16:01:54,566 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Python runtime: 3.11.3
2023-07-25T16:01:54,570 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Connection accepted: ('127.0.0.1', 9000).
2023-07-25T16:01:59,538 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Listening on addr:port: 127.0.0.1:9000
2023-07-25T16:01:59,553 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Successfully loaded C:\ProgramData\anaconda3\Lib\site-packages/ts/configs/metrics.yaml.
2023-07-25T16:01:59,553 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - [PID]7768
2023-07-25T16:01:59,553 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Torch worker started.
2023-07-25T16:01:59,558 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Python runtime: 3.11.3
2023-07-25T16:01:59,559 [INFO ] W-9000-smart_recruit_1.1.0_1.1.0-stdout MODEL_LOG - Connection accepted: ('127.0.0.1', 9000).
```

what is wrong?

**Comment by agunapal** [comment]
Hi @weinixuehao  We would need more details.

Please try one of the examples Ex: https://github.com/pytorch/serve/tree/master/examples/image_classifier/resnet_18 and share the details of your setup. (version etc)

**Comment by weinixuehao** [comment]
@agunapal 
I try to install the torchserve from source that it treats the path as module?
```
2023-07-26T11:09:00,246 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG - handler=C:\Users\ADMINI~1\AppData\Local\Temp\2\models\695326545bfe4de8810f5b29651c9e3c    temp=['C', '\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\models\\695326545bfe4de8810f5b29651c9e3c']
2023-07-26T11:09:00,261 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG - module_name111=C
2023-07-26T11:09:00,267 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG - module_name222=C
2023-07-26T11:09:00,267 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG - Backend worker process died.
2023-07-26T11:09:00,267 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG - Traceback (most recent call last):
2023-07-26T11:09:00,267 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG -   File "C:\ProgramData\anaconda3\Lib\site-packages\ts\model_loader.py", line 100, in load
2023-07-26T11:09:00,267 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG -     module, function_name = self._load_handler_file(handler)
2023-07-26T11:09:00,267 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG -                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-26T11:09:00,267 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG -   File "C:\ProgramData\anaconda3\Lib\site-packages\ts\model_loader.py", line 148, in _load_handler_file
2023-07-26T11:09:00,267 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG -     module = importlib.import_module(module_name)
2023-07-26T11:09:00,267 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-26T11:09:00,283 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG -   File "C:\ProgramData\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
2023-07-26T11:09:00,283 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG -     return _bootstrap._gcd_import(name[level:], package, level)
2023-07-26T11:09:00,283 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-26T11:09:00,283 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG -   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
2023-07-26T11:09:00,283 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG -   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
2023-07-26T11:09:00,283 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG -   File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
2023-07-26T11:09:00,283 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG - ModuleNotFoundError: No module named 'C'
2023-07-26T11:09:00,283 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG - 
2023-07-26T11:09:00,283 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG - During handling of the above exception, another exception occurred:
2023-07-26T11:09:00,283 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG - 
2023-07-26T11:09:00,283 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG - Traceback (most recent call last):
2023-07-26T11:09:00,299 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG -   File "C:\ProgramData\anaconda3\Lib\site-packages\ts\model_service_worker.py", line 253, in <module>
2023-07-26T11:09:00,299 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG -     worker.run_server()
2023-07-26T11:09:00,299 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG -   File "C:\ProgramData\anaconda3\Lib\site-packages\ts\model_service_worker.py", line 221, in run_server
2023-07-26T11:09:00,299 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG -     self.handle_connection(cl_socket)
2023-07-26T11:09:00,299 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG -   File "C:\ProgramData\anaconda3\Lib\site-packages\ts\model_service_worker.py", line 184, in handle_connection
2023-07-26T11:09:00,299 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG -     service, result, code = self.load_model(msg)
2023-07-26T11:09:00,299 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG -                             ^^^^^^^^^^^^^^^^^^^^
2023-07-26T11:09:00,299 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG -   File "C:\ProgramData\anaconda3\Lib\site-packages\ts\model_service_worker.py", line 131, in load_model
2023-07-26T11:09:00,299 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG -     service = model_loader.load(
2023-07-26T11:09:00,299 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG -               ^^^^^^^^^^^^^^^^^^
2023-07-26T11:09:00,299 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG -   File "C:\ProgramData\anaconda3\Lib\site-packages\ts\model_loader.py", line 102, in load
2023-07-26T11:09:00,314 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG -     module = self._load_default_handler(handler)
2023-07-26T11:09:00,314 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-26T11:09:00,314 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG -   File "C:\ProgramData\anaconda3\Lib\site-packages\ts\model_loader.py", line 154, in _load_default_handler
2023-07-26T11:09:00,314 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG -     module = importlib.import_module(module_name, "ts.torch_handler")
2023-07-26T11:09:00,314 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG -              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-26T11:09:00,330 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG -   File "C:\ProgramData\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
2023-07-26T11:09:00,330 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG -     return _bootstrap._gcd_import(name[level:], package, level)
2023-07-26T11:09:00,330 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-07-26T11:09:00,330 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG -   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
2023-07-26T11:09:00,330 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG -   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
2023-07-26T11:09:00,330 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG -   File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
2023-07-26T11:09:00,330 [INFO ] W-9001-smart_recruit_1_1_0_1.0-stdout MODEL_LOG - ModuleNotFoundError: No module named 'ts.torch_handler.C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\models\\695326545bfe4de8810f5b29651c9e3c'
2023-07-26T11:09:00,373 [INFO ] W-9000-smart_recruit_1_1_0_1.0-stdout MODEL_LOG - handler=C:\Users\ADMINI~1\AppData\Local\Temp\2\models\695326545bfe4de8810f5b29651c9e3c    temp=['C', '\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\models\\695326545bfe4de8810f5b29651c9e3c']
2023-07-26T11:09:00,382 [INFO ] W-9000-smart_recruit_1_1_0_1.0-stdout MODEL_LOG - module_name111=C
2023-07-26T11:09:00,383 [INFO ] W-9000-smart_recruit_1_1_0_1.0-stdout MODEL_LOG - module_name222=C
2023-07-26T11:09:00,385 [INFO ] W-9000-smart_recruit_1_1_0_1.0-stdout MODEL_LOG - Backend worker process died.
2023-07-26T11:09:00,386 [INFO ] W-9000-smart_recruit_1_1_0_1.0-stdout MODEL_LOG - Traceback (most recent call last):
```

**Comment by agunapal** [comment]
Hi @weinixuehao  We haven't had CI running on windows for a while. We have it for ubuntu & mac.

For me to better understand the problem, please provide the steps/commands you ran in detail
