### ISSUE TITLE
ValueError: Expected only one class as model definition. []

### ISSUE THREAD

**Issue by RamiKassouf** [pytorch/serve#2502]
### 🐛 Describe the bug

This is kind of the opposite of issue #964 : 
Torchserve doesn't seem to find my handler even though I clearly have it there.

Okkay so I'm trying to add a Bert NER model that I finetuned to torchserve so I can use the api. 

- Using Docker
- Pytorch
- Image : pytorch-torchserve:latest
- HuggingFace Transformers library

### Error logs

2023-07-27 16:42:01 2023-07-27T13:42:01,232 [INFO ] W-9002-NER_BERT_Model_1.0-stdout MODEL_LOG - Backend worker process died.
2023-07-27 16:42:01 2023-07-27T13:42:01,234 [INFO ] W-9000-NER_BERT_Model_1.0-stdout MODEL_LOG - Backend worker process died.
2023-07-27 16:42:01 2023-07-27T13:42:01,235 [INFO ] W-9001-NER_BERT_Model_1.0-stdout MODEL_LOG - Backend worker process died.
2023-07-27 16:42:01 2023-07-27T13:42:01,235 [INFO ] W-9000-NER_BERT_Model_1.0-stdout MODEL_LOG - Traceback (most recent call last):
2023-07-27 16:42:01 2023-07-27T13:42:01,235 [INFO ] W-9001-NER_BERT_Model_1.0-stdout MODEL_LOG - Traceback (most recent call last):
2023-07-27 16:42:01 2023-07-27T13:42:01,235 [INFO ] W-9002-NER_BERT_Model_1.0-stdout MODEL_LOG - Traceback (most recent call last):
2023-07-27 16:42:01 2023-07-27T13:42:01,233 [INFO ] W-9003-NER_BERT_Model_1.0-stdout MODEL_LOG - Backend worker process died.
2023-07-27 16:42:01 2023-07-27T13:42:01,236 [INFO ] W-9003-NER_BERT_Model_1.0-stdout MODEL_LOG - Traceback (most recent call last):
2023-07-27 16:42:01 2023-07-27T13:42:01,267 [INFO ] W-9003-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/model_service_worker.py", line 253, in <module>
2023-07-27 16:42:01 2023-07-27T13:42:01,267 [INFO ] W-9002-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/model_service_worker.py", line 253, in <module>
2023-07-27 16:42:01 2023-07-27T13:42:01,267 [INFO ] W-9000-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/model_service_worker.py", line 253, in <module>
2023-07-27 16:42:01 2023-07-27T13:42:01,268 [INFO ] W-9003-NER_BERT_Model_1.0-stdout MODEL_LOG -     worker.run_server()
2023-07-27 16:42:01 2023-07-27T13:42:01,268 [INFO ] W-9000-NER_BERT_Model_1.0-stdout MODEL_LOG -     worker.run_server()
2023-07-27 16:42:01 2023-07-27T13:42:01,268 [INFO ] W-9003-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/model_service_worker.py", line 221, in run_server
2023-07-27 16:42:01 2023-07-27T13:42:01,268 [INFO ] W-9000-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/model_service_worker.py", line 221, in run_server
2023-07-27 16:42:01 2023-07-27T13:42:01,269 [INFO ] W-9003-NER_BERT_Model_1.0-stdout MODEL_LOG -     self.handle_connection(cl_socket)
2023-07-27 16:42:01 2023-07-27T13:42:01,269 [INFO ] W-9000-NER_BERT_Model_1.0-stdout MODEL_LOG -     self.handle_connection(cl_socket)
2023-07-27 16:42:01 2023-07-27T13:42:01,269 [INFO ] W-9003-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/model_service_worker.py", line 184, in handle_connection
2023-07-27 16:42:01 2023-07-27T13:42:01,269 [INFO ] W-9000-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/model_service_worker.py", line 184, in handle_connection
2023-07-27 16:42:01 2023-07-27T13:42:01,269 [INFO ] W-9000-NER_BERT_Model_1.0-stdout MODEL_LOG -     service, result, code = self.load_model(msg)
2023-07-27 16:42:01 2023-07-27T13:42:01,269 [INFO ] W-9003-NER_BERT_Model_1.0-stdout MODEL_LOG -     service, result, code = self.load_model(msg)
2023-07-27 16:42:01 2023-07-27T13:42:01,270 [INFO ] W-9002-NER_BERT_Model_1.0-stdout MODEL_LOG -     worker.run_server()
2023-07-27 16:42:01 2023-07-27T13:42:01,270 [INFO ] W-9002-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/model_service_worker.py", line 221, in run_server
2023-07-27 16:42:01 2023-07-27T13:42:01,276 [INFO ] W-9001-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/model_service_worker.py", line 253, in <module>
2023-07-27 16:42:01 2023-07-27T13:42:01,277 [INFO ] W-9001-NER_BERT_Model_1.0-stdout MODEL_LOG -     worker.run_server()
2023-07-27 16:42:01 2023-07-27T13:42:01,277 [INFO ] W-9001-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/model_service_worker.py", line 221, in run_server
2023-07-27 16:42:01 2023-07-27T13:42:01,278 [INFO ] W-9001-NER_BERT_Model_1.0-stdout MODEL_LOG -     self.handle_connection(cl_socket)
2023-07-27 16:42:01 2023-07-27T13:42:01,278 [INFO ] W-9001-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/model_service_worker.py", line 184, in handle_connection
2023-07-27 16:42:01 2023-07-27T13:42:01,279 [INFO ] W-9001-NER_BERT_Model_1.0-stdout MODEL_LOG -     service, result, code = self.load_model(msg)
2023-07-27 16:42:01 2023-07-27T13:42:01,281 [INFO ] W-9002-NER_BERT_Model_1.0-stdout MODEL_LOG -     self.handle_connection(cl_socket)
2023-07-27 16:42:01 2023-07-27T13:42:01,287 [INFO ] W-9002-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/model_service_worker.py", line 184, in handle_connection
2023-07-27 16:42:01 2023-07-27T13:42:01,288 [INFO ] W-9002-NER_BERT_Model_1.0-stdout MODEL_LOG -     service, result, code = self.load_model(msg)
2023-07-27 16:42:01 2023-07-27T13:42:01,297 [INFO ] W-9002-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/model_service_worker.py", line 131, in load_model
2023-07-27 16:42:01 2023-07-27T13:42:01,298 [INFO ] W-9002-NER_BERT_Model_1.0-stdout MODEL_LOG -     service = model_loader.load(
2023-07-27 16:42:01 2023-07-27T13:42:01,297 [INFO ] W-9003-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/model_service_worker.py", line 131, in load_model
2023-07-27 16:42:01 2023-07-27T13:42:01,298 [INFO ] W-9002-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/model_loader.py", line 135, in load
2023-07-27 16:42:01 2023-07-27T13:42:01,298 [INFO ] W-9003-NER_BERT_Model_1.0-stdout MODEL_LOG -     service = model_loader.load(
2023-07-27 16:42:01 2023-07-27T13:42:01,298 [INFO ] W-9002-NER_BERT_Model_1.0-stdout MODEL_LOG -     initialize_fn(service.context)
2023-07-27 16:42:01 2023-07-27T13:42:01,299 [INFO ] W-9003-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/model_loader.py", line 135, in load
2023-07-27 16:42:01 2023-07-27T13:42:01,299 [INFO ] W-9002-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/model_loader.py", line 164, in <lambda>
2023-07-27 16:42:01 2023-07-27T13:42:01,299 [INFO ] W-9003-NER_BERT_Model_1.0-stdout MODEL_LOG -     initialize_fn(service.context)
2023-07-27 16:42:01 2023-07-27T13:42:01,299 [INFO ] W-9002-NER_BERT_Model_1.0-stdout MODEL_LOG -     initialize_fn = lambda ctx: entry_point(None, ctx)
2023-07-27 16:42:01 2023-07-27T13:42:01,299 [INFO ] W-9003-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/model_loader.py", line 164, in <lambda>
2023-07-27 16:42:01 2023-07-27T13:42:01,299 [INFO ] W-9002-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/model-server/tmp/models/85846069644f4f8da8185c57559ec959/ner_handler.py", line 90, in handle
2023-07-27 16:42:01 2023-07-27T13:42:01,299 [INFO ] W-9003-NER_BERT_Model_1.0-stdout MODEL_LOG -     initialize_fn = lambda ctx: entry_point(None, ctx)
2023-07-27 16:42:01 2023-07-27T13:42:01,300 [INFO ] W-9002-NER_BERT_Model_1.0-stdout MODEL_LOG -     raise e
2023-07-27 16:42:01 2023-07-27T13:42:01,300 [INFO ] W-9003-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/model-server/tmp/models/85846069644f4f8da8185c57559ec959/ner_handler.py", line 90, in handle
2023-07-27 16:42:01 2023-07-27T13:42:01,300 [INFO ] W-9002-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/model-server/tmp/models/85846069644f4f8da8185c57559ec959/ner_handler.py", line 79, in handle
2023-07-27 16:42:01 2023-07-27T13:42:01,300 [INFO ] W-9002-NER_BERT_Model_1.0-stdout MODEL_LOG -     _service.initialize(context)
2023-07-27 16:42:01 2023-07-27T13:42:01,300 [INFO ] W-9003-NER_BERT_Model_1.0-stdout MODEL_LOG -     raise e
2023-07-27 16:42:01 2023-07-27T13:42:01,301 [INFO ] W-9003-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/model-server/tmp/models/85846069644f4f8da8185c57559ec959/ner_handler.py", line 79, in handle
2023-07-27 16:42:01 2023-07-27T13:42:01,301 [INFO ] W-9002-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/torch_handler/base_handler.py", line 157, in initialize
2023-07-27 16:42:01 2023-07-27T13:42:01,301 [INFO ] W-9003-NER_BERT_Model_1.0-stdout MODEL_LOG -     _service.initialize(context)
2023-07-27 16:42:01 2023-07-27T13:42:01,301 [INFO ] W-9003-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/torch_handler/base_handler.py", line 157, in initialize
2023-07-27 16:42:01 2023-07-27T13:42:01,302 [INFO ] W-9003-NER_BERT_Model_1.0-stdout MODEL_LOG -     self.model = self._load_pickled_model(
2023-07-27 16:42:01 2023-07-27T13:42:01,302 [INFO ] W-9001-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/model_service_worker.py", line 131, in load_model
2023-07-27 16:42:01 2023-07-27T13:42:01,302 [INFO ] W-9003-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/torch_handler/base_handler.py", line 246, in _load_pickled_model
2023-07-27 16:42:01 2023-07-27T13:42:01,302 [INFO ] W-9001-NER_BERT_Model_1.0-stdout MODEL_LOG -     service = model_loader.load(
2023-07-27 16:42:01 2023-07-27T13:42:01,302 [INFO ] W-9003-NER_BERT_Model_1.0-stdout MODEL_LOG -     raise ValueError(
2023-07-27 16:42:01 2023-07-27T13:42:01,302 [INFO ] W-9001-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/model_loader.py", line 135, in load
2023-07-27 16:42:01 2023-07-27T13:42:01,302 [INFO ] W-9003-NER_BERT_Model_1.0-stdout MODEL_LOG - ValueError: Expected only one class as model definition. []
2023-07-27 16:42:01 2023-07-27T13:42:01,302 [INFO ] W-9001-NER_BERT_Model_1.0-stdout MODEL_LOG -     initialize_fn(service.context)
2023-07-27 16:42:01 2023-07-27T13:42:01,303 [INFO ] W-9001-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/model_loader.py", line 164, in <lambda>
2023-07-27 16:42:01 2023-07-27T13:42:01,303 [INFO ] W-9001-NER_BERT_Model_1.0-stdout MODEL_LOG -     initialize_fn = lambda ctx: entry_point(None, ctx)
2023-07-27 16:42:01 2023-07-27T13:42:01,303 [INFO ] W-9001-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/model-server/tmp/models/85846069644f4f8da8185c57559ec959/ner_handler.py", line 90, in handle
2023-07-27 16:42:01 2023-07-27T13:42:01,303 [INFO ] W-9001-NER_BERT_Model_1.0-stdout MODEL_LOG -     raise e
2023-07-27 16:42:01 2023-07-27T13:42:01,304 [INFO ] W-9001-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/model-server/tmp/models/85846069644f4f8da8185c57559ec959/ner_handler.py", line 79, in handle
2023-07-27 16:42:01 2023-07-27T13:42:01,304 [INFO ] W-9001-NER_BERT_Model_1.0-stdout MODEL_LOG -     _service.initialize(context)
2023-07-27 16:42:01 2023-07-27T13:42:01,304 [INFO ] W-9002-NER_BERT_Model_1.0-stdout MODEL_LOG -     self.model = self._load_pickled_model(
2023-07-27 16:42:01 2023-07-27T13:42:01,304 [INFO ] W-9000-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/model_service_worker.py", line 131, in load_model
2023-07-27 16:42:01 2023-07-27T13:42:01,305 [INFO ] W-9000-NER_BERT_Model_1.0-stdout MODEL_LOG -     service = model_loader.load(
2023-07-27 16:42:01 2023-07-27T13:42:01,304 [INFO ] W-9001-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/torch_handler/base_handler.py", line 157, in initialize
2023-07-27 16:42:01 2023-07-27T13:42:01,319 [INFO ] W-9000-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/model_loader.py", line 135, in load
2023-07-27 16:42:01 2023-07-27T13:42:01,305 [INFO ] W-9002-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/torch_handler/base_handler.py", line 246, in _load_pickled_model
2023-07-27 16:42:01 2023-07-27T13:42:01,320 [INFO ] W-9000-NER_BERT_Model_1.0-stdout MODEL_LOG -     initialize_fn(service.context)
2023-07-27 16:42:01 2023-07-27T13:42:01,320 [INFO ] W-9001-NER_BERT_Model_1.0-stdout MODEL_LOG -     self.model = self._load_pickled_model(
2023-07-27 16:42:01 2023-07-27T13:42:01,320 [INFO ] W-9000-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/model_loader.py", line 164, in <lambda>
2023-07-27 16:42:01 2023-07-27T13:42:01,320 [INFO ] W-9002-NER_BERT_Model_1.0-stdout MODEL_LOG -     raise ValueError(
2023-07-27 16:42:01 2023-07-27T13:42:01,321 [INFO ] W-9001-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/torch_handler/base_handler.py", line 246, in _load_pickled_model
2023-07-27 16:42:01 2023-07-27T13:42:01,321 [INFO ] W-9000-NER_BERT_Model_1.0-stdout MODEL_LOG -     initialize_fn = lambda ctx: entry_point(None, ctx)
2023-07-27 16:42:01 2023-07-27T13:42:01,321 [INFO ] W-9002-NER_BERT_Model_1.0-stdout MODEL_LOG - ValueError: Expected only one class as model definition. []
2023-07-27 16:42:01 2023-07-27T13:42:01,321 [INFO ] W-9000-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/model-server/tmp/models/85846069644f4f8da8185c57559ec959/ner_handler.py", line 90, in handle
2023-07-27 16:42:01 2023-07-27T13:42:01,322 [INFO ] W-9001-NER_BERT_Model_1.0-stdout MODEL_LOG -     raise ValueError(
2023-07-27 16:42:01 2023-07-27T13:42:01,323 [INFO ] W-9001-NER_BERT_Model_1.0-stdout MODEL_LOG - ValueError: Expected only one class as model definition. []
2023-07-27 16:42:01 2023-07-27T13:42:01,332 [INFO ] W-9000-NER_BERT_Model_1.0-stdout MODEL_LOG -     raise e
2023-07-27 16:42:01 2023-07-27T13:42:01,334 [INFO ] W-9000-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/model-server/tmp/models/85846069644f4f8da8185c57559ec959/ner_handler.py", line 79, in handle
2023-07-27 16:42:01 2023-07-27T13:42:01,334 [INFO ] W-9000-NER_BERT_Model_1.0-stdout MODEL_LOG -     _service.initialize(context)
2023-07-27 16:42:01 2023-07-27T13:42:01,335 [INFO ] W-9000-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/torch_handler/base_handler.py", line 157, in initialize
2023-07-27 16:42:01 2023-07-27T13:42:01,335 [INFO ] W-9000-NER_BERT_Model_1.0-stdout MODEL_LOG -     self.model = self._load_pickled_model(
2023-07-27 16:42:01 2023-07-27T13:42:01,335 [INFO ] W-9000-NER_BERT_Model_1.0-stdout MODEL_LOG -   File "/home/venv/lib/python3.9/site-packages/ts/torch_handler/base_handler.py", line 246, in _load_pickled_model
2023-07-27 16:42:01 2023-07-27T13:42:01,335 [INFO ] W-9000-NER_BERT_Model_1.0-stdout MODEL_LOG -     raise ValueError(
2023-07-27 16:42:01 2023-07-27T13:42:01,335 [INFO ] W-9000-NER_BERT_Model_1.0-stdout MODEL_LOG - ValueError: Expected only one class as model definition. []

### Installation instructions

Using Docker: Here is my DockerFile:

    FROM pytorch/torchserve:latest-cpu
    
    
    
    RUN mkdir -p model-store
    RUN mkdir -p NER_BERT_Model
    
    
    
    COPY ner_handler.py model.py index_to_name.json NER_BERT_Model.pt  /home/model-server/
    COPY special_tokens_map.json tokenizer_config.json config.json tokenizer.json vocab.txt  pytorch_model.bin /home/model-server/NER_BERT_Model/
    COPY requirements.txt /home/model-server/
    
    
    RUN pip install -U -r /home/model-server/requirements.txt
    
    WORKDIR /home/model-server/
    
    
    RUN torch-model-archiver \
      --model-name=NER_BERT_Model \
      --version=1.0 \
      --model-file=model.py \
      --serialized-file=NER_BERT_Model.pt \
      --handler=/home/model-server/ner_handler.py \
      --extra-files=NER_BERT_Model/config.json,index_to_name.json,NER_BERT_Model/special_tokens_map.json,NER_BERT_Model/tokenizer_config.json,NER_BERT_Model/tokenizer.json \
      --export-path=model-store
    
    CMD ["torchserve", \
         "--start", \
         "--model-store", "/home/model-server/model-store", \
         "--models", \
         "NER_BERT_Model=NER_BERT_Model.mar"]

### Model Packaing

Custom Handler:

    import logging
    import torch
    from transformers import AutoTokenizer
    from ts.torch_handler.base_handler import BaseHandler
    
    logger = logging.getLogger(__name__)
    
    class NERHandler(BaseHandler):
        tokenizer : AutoTokenizer = None
          
        def __init__(self, *args, **kwargs):
            logger.info("Loading NER model")
            super(NERHandler, self).__init__()
            logger.info(kwargs["model_name"])
            self.tokenizer = AutoTokenizer.from_pretrained(kwargs["model_name"], local_files_only=True)
            logger.info("Model file %s loaded successfully", kwargs["model_name"])
             
        def preprocess(self, data):
            """preprocesses text before inference
    
            Args:
                data (str): input text
            
            Returns:
                inputs (str): input text
            """
            
            text = data[0].get("data")
            if text is None:
                text = data[0].get("body")
            sentences = text.decode('utf-8')
            logger.info("Received text: '%s'", sentences)
            
            # Tokenize the text
            inputs = [self.tokenizer(sentence, return_tensors="pt") for sentence in sentences]
            return inputs
            
        def inference(self, inputs):
            """inference on the input
    
            Args:
                inputs (str): input text
    
            Returns:
                outputs (str): output text
            """
            device = torch.cuda if torch.cuda.is_available() else "cpu"
            outputs = []
            for element in inputs:
                self.model.to(element.input_ids.device)
                with torch.no_grad():
                    output = self.model(**element)
                    predicted_labels = torch.argmax(output.logits, dim=2).tolist()[0]
                outputs.append(predicted_labels)
            return outputs
        
        def postprocess(self, inference_output):
            """postprocesses inference outputs
    
            Args:
                inference_output (str): inference outputs
            
            Returns:
                predictions (list): predictions
            """
            res=[]
            for predicted_labels in inference_output:
                predicted_labels = [self.model.config.id2label[label_id] for label_id in predicted_labels]
                res.append({"prediction":predicted_labels})
            return res         
     
    model_name = "/home/model-server/NER_BERT_Model"   
    _service = NERHandler(model_name=model_name)
    
    
    def handle(data, context):
        try:
            if not _service.initialized:
                _service.initialize(context)
    
            if data is None:
                return None
    
            data = _service.preprocess(data)
            data = _service.inference(data)
            data = _service.postprocess(data)
    
            return data
        except Exception as e:
            raise e

And here is model.py:

      from transformers import AutoModelForTokenClassification
      import torch
      
      model=AutoModelForTokenClassification.from_pretrained("/home/model-server/NER_BERT_Model",local_files_only=True)
      model.eval()
      torch.save(model.state_dict(), "./NER_BERT_Model.pt")
      print("saved model")

### config.properties

inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
metrics_address=http://0.0.0.0:8082
number_of_netty_threads=32
job_queue_size=1000
model_store=/home/model-server/model-store
workflow_store=/home/model-server/wf-store

### Versions

requirement.txt:

transformers==4.31.0
seqeval
torch
torchserve

and the rest is in the beginning of the logs

### Repro instructions

just ran the docker file with post 300:8080 and 3001:8081

**Comment by agunapal** [comment]
So, it looks like its finding your handler, but thinks there is more than one class

I noticed you have this extra code in your handler. 
typically, the base class handle method is sufficient for all cases i have seen so far.

Anyway, I need to try out your code. 

```
model_name = "/home/model-server/NER_BERT_Model"   
_service = NERHandler(model_name=model_name)


def handle(data, context):
    try:
        if not _service.initialized:
            _service.initialize(context)

        if data is None:
            return None

        data = _service.preprocess(data)
        data = _service.inference(data)
        data = _service.postprocess(data)

        return data
    except Exception as e:
        raise e
```

**Comment by RamiKassouf** [comment]
I didn t have it before I had it as a separate class and also I followed a page wich had this exact setup

Thank you for the fast reply though

Rami Kassouf
5th year CCE student at USJ, ESIB

**Comment by RamiKassouf** [comment]
> 

Was mostly following this and I had them in a separate file before but it had the same effect. Also the [] in the error means that no module was found (found that out by diving into the code of the base handler class this is supposed to be a list containing the handler classes and if it is != 1 it gives an error)
https://towardsdatascience.com/deploy-models-and-create-custom-handlers-in-torchserve-fc2d048fbe91

**Comment by RamiKassouf** [comment]
> So, it looks like its finding your handler, but thinks there is more than one class
> 
> I noticed you have this extra code in your handler. typically, the base class handle method is sufficient for all cases i have seen so far.
> 
> Anyway, I need to try out your code.
> 
> ```
> model_name = "/home/model-server/NER_BERT_Model"   
> _service = NERHandler(model_name=model_name)
> 
> 
> def handle(data, context):
>     try:
>         if not _service.initialized:
>             _service.initialize(context)
> 
>         if data is None:
>             return None
> 
>         data = _service.preprocess(data)
>         data = _service.inference(data)
>         data = _service.postprocess(data)
> 
>         return data
>     except Exception as e:
>         raise e
> ```

removed the extra code and still the same issue

**Comment by lxning** [comment]
@RamiKassouf the error is thrown at [here](https://github.com/pytorch/serve/blob/master/ts/torch_handler/base_handler.py#L253). Please check your input mdoel.pt and serialized-file. Detailed information is [here](https://github.com/pytorch/serve/tree/master/model-archiver#model-file)

**Comment by RamiKassouf** [comment]
> @RamiKassouf the error is thrown at [here](https://github.com/pytorch/serve/blob/master/ts/torch_handler/base_handler.py#L253). Please check your input mdoel.pt and serialized-file. Detailed information is [here](https://github.com/pytorch/serve/tree/master/model-archiver#model-file)

I saw this before and didn't know how to fix it
Anyway I changed the way I input my model from the .pt to the .bin of hugging face and added an initialize function to the handler and now it all works!

Thx for the help
