### ISSUE TITLE
Incorrect arguments when running serve with ipex through torch.backends.xeon.run_cpu

### ISSUE THREAD

**Issue by aalbersk** [pytorch/serve#2539]
### 🐛 Describe the bug

I tried to run an ipex optimized traced version of Densenet. I created the MAR-FILE according to following instructions: https://github.com/pytorch/serve/tree/master/examples/image_classifier/densenet_161 , defined config.properties to run the model with ipex enabled and started torchserve on a single machine with Intel(R) Xeon(R) Platinum 8375C CPU (that has 64 CPUs, 2 Thread(s) per core, 32 Core(s) per socket and 1 socket).
Unfortunatelly, the model cannot be loaded and serve raises issues about incorrect run_cpu arguments (logs in error logs). When I omit cpu_launcher_args, serve also runs into an error but with output `RuntimeError: there are 32 total cores but you specify 64 ninstances; please make sure ninstances <= total_cores)`.

### Error logs

```bash
2023-08-25T14:52:07,067 [DEBUG] W-9046-densenet161_ipex_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - launcherAvailable cmdline: [python, -m, torch.backends.xeon.run_cpu, --enable_jemalloc, --ninstances, 1, --ncores-per-instance, 32, --no_python, hostname]
2023-08-25T14:52:07,921 [DEBUG] W-9014-densenet161_ipex_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - launcherAvailable cmdline: [python, -m, torch.backends.xeon.run_cpu, --enable_jemalloc, --ninstances, 1, --ncores-per-instance, 32, --no_python, hostname]
2023-08-25T14:52:08,195 [DEBUG] W-9030-densenet161_ipex_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - Worker cmdline: [/home/ubuntu/aalbersk/bin/python3, -m, torch.backends.xeon.run_cpu, --enable_jemalloc, --ninstances, 1, --ncores-per-instance, 32, --ninstances, 64, --rank, 30, /home/ubuntu/aalbersk/lib/python3.8/site-packages/ts/model_service_worker.py, --sock-type, unix, --sock-name, /tmp/.ts.sock.9030, --metrics-config, /home/ubuntu/aalbersk/lib/python3.8/site-packages/ts/configs/metrics.yaml]
2023-08-25T14:52:08,195 [DEBUG] W-9030-densenet161_ipex_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - Worker cmdline: [/home/ubuntu/aalbersk/bin/python3, -m, torch.backends.xeon.run_cpu, --enable_jemalloc, --ninstances, 1, --ncores-per-instance, 32, --ninstances, 64, --rank, 30, /home/ubuntu/aalbersk/lib/python3.8/site-packages/ts/model_service_worker.py, --sock-type, unix, --sock-name, /tmp/.ts.sock.9030, --metrics-config, /home/ubuntu/aalbersk/lib/python3.8/site-packages/ts/configs/metrics.yaml]
2023-08-25T14:52:11,037 [DEBUG] W-9005-densenet161_ipex_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - Worker cmdline: [/home/ubuntu/aalbersk/bin/python3, -m, torch.backends.xeon.run_cpu, --enable_jemalloc, --ninstances, 1, --ncores-per-instance, 32, --ninstances, 64, --rank, 5, /home/ubuntu/aalbersk/lib/python3.8/site-packages/ts/model_service_worker.py, --sock-type, unix, --sock-name, /tmp/.ts.sock.9005, --metrics-config, /home/ubuntu/aalbersk/lib/python3.8/site-packages/ts/configs/metrics.yaml]
2023-08-25T14:52:11,081 [INFO ] W-9030-densenet161_ipex_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9030-densenet161_ipex_1.0-stderr
2023-08-25T14:52:11,081 [INFO ] W-9030-densenet161_ipex_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9030-densenet161_ipex_1.0-stderr
2023-08-25T14:52:11,081 [INFO ] W-9030-densenet161_ipex_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9030-densenet161_ipex_1.0-stdout
2023-08-25T14:52:11,081 [INFO ] W-9030-densenet161_ipex_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9030-densenet161_ipex_1.0-stdout
2023-08-25T14:52:11,082 [WARN ] W-9030-densenet161_ipex_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9030-densenet161_ipex_1.0-stderr
2023-08-25T14:52:11,082 [WARN ] W-9030-densenet161_ipex_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9030-densenet161_ipex_1.0-stderr
2023-08-25T14:52:11,082 [ERROR] W-9030-densenet161_ipex_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker error
org.pytorch.serve.wlm.WorkerInitializationException: Backend stream closed.
	at org.pytorch.serve.wlm.WorkerLifeCycle.startWorker(WorkerLifeCycle.java:173) ~[model-server.jar:?]
	at org.pytorch.serve.wlm.WorkerThread.connect(WorkerThread.java:339) ~[model-server.jar:?]
	at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:183) [model-server.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2023-08-25T14:52:11,082 [ERROR] W-9030-densenet161_ipex_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker error
org.pytorch.serve.wlm.WorkerInitializationException: Backend stream closed.
	at org.pytorch.serve.wlm.WorkerLifeCycle.startWorker(WorkerLifeCycle.java:173) ~[model-server.jar:?]
	at org.pytorch.serve.wlm.WorkerThread.connect(WorkerThread.java:339) ~[model-server.jar:?]
	at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:183) [model-server.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2023-08-25T14:52:11,082 [DEBUG] W-9030-densenet161_ipex_1.0 org.pytorch.serve.wlm.WorkerThread - W-9030-densenet161_ipex_1.0 State change WORKER_STOPPED -> WORKER_STOPPED
2023-08-25T14:52:11,082 [DEBUG] W-9030-densenet161_ipex_1.0 org.pytorch.serve.wlm.WorkerThread - W-9030-densenet161_ipex_1.0 State change WORKER_STOPPED -> WORKER_STOPPED
2023-08-25T14:52:11,082 [WARN ] W-9030-densenet161_ipex_1.0 org.pytorch.serve.wlm.WorkerThread - Auto recovery failed again
2023-08-25T14:52:11,082 [WARN ] W-9030-densenet161_ipex_1.0 org.pytorch.serve.wlm.WorkerThread - Auto recovery failed again
2023-08-25T14:52:11,082 [WARN ] W-9030-densenet161_ipex_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9030-densenet161_ipex_1.0-stderr
2023-08-25T14:52:11,082 [WARN ] W-9030-densenet161_ipex_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9030-densenet161_ipex_1.0-stderr
2023-08-25T14:52:11,327 [WARN ] W-9017-densenet161_ipex_1.0-stderr MODEL_LOG - Traceback (most recent call last):
2023-08-25T14:52:11,327 [WARN ] W-9017-densenet161_ipex_1.0-stderr MODEL_LOG -   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2023-08-25T14:52:11,327 [WARN ] W-9017-densenet161_ipex_1.0-stderr MODEL_LOG -     return _run_code(code, main_globals, None,
2023-08-25T14:52:11,327 [WARN ] W-9017-densenet161_ipex_1.0-stderr MODEL_LOG -   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
2023-08-25T14:52:11,327 [WARN ] W-9017-densenet161_ipex_1.0-stderr MODEL_LOG -     exec(code, run_globals)
2023-08-25T14:52:11,327 [WARN ] W-9017-densenet161_ipex_1.0-stderr MODEL_LOG -   File "/home/ubuntu/aalbersk/lib/python3.8/site-packages/torch/backends/xeon/run_cpu.py", line 661, in <module>
2023-08-25T14:52:11,327 [WARN ] W-9017-densenet161_ipex_1.0-stderr MODEL_LOG -     main(args)
2023-08-25T14:52:11,327 [WARN ] W-9017-densenet161_ipex_1.0-stderr MODEL_LOG -   File "/home/ubuntu/aalbersk/lib/python3.8/site-packages/torch/backends/xeon/run_cpu.py", line 639, in main
2023-08-25T14:52:11,327 [WARN ] W-9017-densenet161_ipex_1.0-stderr MODEL_LOG -     launcher.launch(args)
2023-08-25T14:52:11,327 [WARN ] W-9017-densenet161_ipex_1.0-stderr MODEL_LOG -   File "/home/ubuntu/aalbersk/lib/python3.8/site-packages/torch/backends/xeon/run_cpu.py", line 443, in launch
2023-08-25T14:52:11,327 [WARN ] W-9017-densenet161_ipex_1.0-stderr MODEL_LOG -     raise RuntimeError("Please make sure ninstances * ncores_per_instance <= total_cores")
2023-08-25T14:52:11,327 [WARN ] W-9017-densenet161_ipex_1.0-stderr MODEL_LOG - RuntimeError: Please make sure ninstances * ncores_per_instance <= total_cores
2023-08-25T14:52:11,391 [WARN ] W-9061-densenet161_ipex_1.0-stderr MODEL_LOG - Traceback (most recent call last):
2023-08-25T14:52:11,392 [WARN ] W-9061-densenet161_ipex_1.0-stderr MODEL_LOG -   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2023-08-25T14:52:11,392 [WARN ] W-9061-densenet161_ipex_1.0-stderr MODEL_LOG -     return _run_code(code, main_globals, None,
2023-08-25T14:52:11,392 [WARN ] W-9061-densenet161_ipex_1.0-stderr MODEL_LOG -   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
2023-08-25T14:52:11,392 [WARN ] W-9061-densenet161_ipex_1.0-stderr MODEL_LOG -     exec(code, run_globals)
2023-08-25T14:52:11,392 [WARN ] W-9061-densenet161_ipex_1.0-stderr MODEL_LOG -   File "/home/ubuntu/aalbersk/lib/python3.8/site-packages/torch/backends/xeon/run_cpu.py", line 661, in <module>
2023-08-25T14:52:11,392 [WARN ] W-9061-densenet161_ipex_1.0-stderr MODEL_LOG -     main(args)
2023-08-25T14:52:11,392 [WARN ] W-9061-densenet161_ipex_1.0-stderr MODEL_LOG -   File "/home/ubuntu/aalbersk/lib/python3.8/site-packages/torch/backends/xeon/run_cpu.py", line 639, in main
2023-08-25T14:52:11,392 [WARN ] W-9061-densenet161_ipex_1.0-stderr MODEL_LOG -     launcher.launch(args)
2023-08-25T14:52:11,392 [WARN ] W-9061-densenet161_ipex_1.0-stderr MODEL_LOG -   File "/home/ubuntu/aalbersk/lib/python3.8/site-packages/torch/backends/xeon/run_cpu.py", line 443, in launch
2023-08-25T14:52:11,392 [WARN ] W-9061-densenet161_ipex_1.0-stderr MODEL_LOG -     raise RuntimeError("Please make sure ninstances * ncores_per_instance <= total_cores")
2023-08-25T14:52:11,392 [WARN ] W-9061-densenet161_ipex_1.0-stderr MODEL_LOG - RuntimeError: Please make sure ninstances * ncores_per_instance <= total_cores
```

### Installation instructions

I installed torchserve using pip:

```bash
pip install torch torchvision torchaudio
pip install torchserve
```

### Model Packaing

Used instructions from https://github.com/pytorch/serve/tree/master/examples/image_classifier/densenet_161 :

So I saved traced model.

```python
from torchvision import models
import torch

if __name__ == "__main__":
    example_input = torch.rand(1, 3, 224, 224)
    model = models.densenet161(pretrained=True)
    model.eval()
    
    with torch.no_grad():
        scripted_model = torch.jit.trace(model, (example_input), check_trace=False, strict=False)
        scripted_model = torch.jit.freeze(scripted_model)
    torch.jit.save(scripted_model, "densenet161_ipex_jit.pt")
``` 

And packaged it like so:

```bash
torch-model-archiver --model-name densenet161_ts_ipex --version 1.0 --serialized-file densenet161_ipex_jit.pt  --handler image_classifier --extra-files index_to_name.json
```

### config.properties

ipex_enable=true
cpu_launcher_enable=true
cpu_launcher_args=--enable_jemalloc --ninstances 1 --ncores-per-instance 32

### Versions

------------------------------------------------------------------------------------------
Environment headers
------------------------------------------------------------------------------------------
Torchserve branch: 

torchserve==0.8.1
torch-model-archiver==0.8.1

Python version: 3.8 (64-bit runtime)
Python executable: /home/ubuntu/aalbersk/bin/python

Versions of relevant python libraries:
captum==0.6.0
intel-extension-for-pytorch==2.0.100
numpy==1.24.4
psutil==5.9.5
pytest==7.4.0
pytest-json-report==1.5.0
pytest-metadata==3.0.0
pytest-rerunfailures==12.0
pytest-timeout==2.1.0
pytest-xdist==3.3.1
requests==2.31.0
requests-file==1.5.1
torch==2.0.1
torch-model-archiver==0.8.1
torchaudio==2.0.2
torchserve==0.8.1
torchvision==0.15.2
transformers==4.31.0
wheel==0.33.4
torch==2.0.1
**Warning: torchtext not present ..
torchvision==0.15.2
torchaudio==2.0.2

Java Version:

OS: Ubuntu 20.04.6 LTS
GCC version: N/A
Clang version: N/A
CMake version: version 3.27.2

### Repro instructions

```bash
# Creating *mar with previous instructions
# Defining config.properties

mkdir model_store
cp densenet161_ts_ipex.mar model_store
torchserve --start --ncs --ts-config config.properties --model-store model_store --models densenet161_ipex=densenet161_ts_ipex.mar
```

### Possible Solution

There are 3 issues, I think that need to be fixed here:
* A user can add any cpu_launcher_args, even ones that are defined automatically (like --ninstances). In my opinion if a user defines --ninstances themselves, the code in [WorkerLifeCycle.java](https://github.com/pytorch/serve/pull/1401/files#diff-88e86db18d87ea2dd136cb1078dd4d7b31a94a78ea8033a5c132a4afc0b592b3) should pass user's arguments and omit the default ones. Currently all arguments are passed without any checks and that's why there's a redundancy.
* If `cpu_launch_args` are ommited, the code still fails but with another error `RuntimeError: there are 32 total cores but you specify 64 ninstances; please make sure ninstances <= total_cores)` . Not sure, why serve runs run_cpu on each core individually but if it does it should not use --ninstances argument alone, but try it with --ncores-per-instance ([Source](https://github.com/pytorch/pytorch/blob/main/torch/backends/xeon/run_cpu.py#L75)).
* Moreover, as for the machine I try to run it, it uses CPUs number instead of Core(s) per socket one, which is incorrect.

**Comment by min-jean-cho** [comment]
Hi @aalbersk, thank you for the report. (1) As for `cpu_launcher_enable=true` without specifying any `cpu_launcher_args`, the issue is due to `run_cpu` by default uses physical cores only while torchserve by default launches total cores, including logical cores, number of workers. In the meantime, a workaround is to add `cpu_launcher_args=--use_logical_core`. (2) And as for conflicting `--ninstances` when specified via `cpu_launcher_args`, I agree that there should be a check and pass the user defined `--nintsances` instead. Thank you for catching these.

**Comment by agunapal** [comment]
Hi @aalbersk Please feel free to propose a fix and we can review it.
