### ISSUE TITLE
TorchServe Nightly Benchmarks Failures

### ISSUE THREAD

**Issue by sachanub** [pytorch/serve#2616]
### 🐛 Describe the bug

In the last week, the CPU, Inf1 and Inf2 benchmarks failed to run due to some problems. I am creating this issue to address those bugs. 
- **Reason for Inf2 benchmark failures:**
The file path for `sample_text.txt` was changed to `./examples/large_models/inferentia2/opt/sample_text.txt` from `./examples/large_models/inferentia2/sample_text.txt` in https://github.com/pytorch/serve/pull/2458. As a result, we get the following error for the Inf2 benchmark:
```
Error: Invalid value for '--input' / '-i': Path './examples/large_models/inferentia2/sample_text.txt' does not exist.
```
- **Reason for CPU, Inf1 and Inf2 benchmark failures:**

The CPU, Inf1 and Inf2 benchmarks failed because the script was unable to find `torchserve-nightly==2023.9.18`
```
ERROR: Could not find a version that satisfies the requirement torchserve-nightly==2023.9.18 (from versions: 2022.5.2, 2022.5.3, 2022.5.4, 2022.5.5, 2022.5.6, 2022.5.7, 2022.5.8, 2022.5.9, 2022.5.10, 2022.5.11, 2022.5.12, 2022.5.13, 2022.5.14, 2022.5.15, 2022.5.17, 2022.5.19, 2022.5.20, 2022.5.21, 2022.5.22, 2022.5.23, 2022.5.24, 2022.5.25, 2022.5.26, 2022.5.27, 2022.5.28, 2022.5.29, 2022.5.30, 2022.5.31, 2022.6.1, 2022.6.2, 2022.6.3, 2022.6.4, 2022.6.5, 2022.6.6, 2022.6.7, 2022.6.8, 2022.6.9, 2022.6.10, 2022.6.11, 2022.6.12, 2022.6.13, 2022.6.14, 2022.6.15, 2022.6.16, 2022.6.17, 2022.6.18, 2022.6.19, 2022.6.20, 2022.6.21, 2022.6.22, 2022.6.23, 2022.6.24, 2022.6.25, 2022.6.26, 2022.6.27, 2022.6.28, 2022.6.29, 2022.6.30, 2022.7.1, 2022.7.2, 2022.7.3, 2022.7.4, 2022.7.5, 2022.7.6, 2022.7.7, 2022.7.8, 2022.7.9, 2022.7.10, 2022.7.11, 2022.7.12, 2022.7.13, 2022.7.14, 2022.7.15, 2022.7.16, 2022.7.17, 2022.7.18, 2022.7.19, 2022.7.20, 2022.7.21, 2022.7.22, 2022.7.23, 2022.7.24, 2022.7.25, 2022.7.26, 2022.7.27, 2022.7.28, 2022.7.29, 2022.7.30, 2022.7.31, 2022.8.1, 2022.8.2, 2022.8.3, 2022.8.4, 2022.8.5, 2022.8.6, 2022.8.7, 2022.8.8, 2022.8.9, 2022.8.10, 2022.8.11, 2022.8.13, 2022.8.14, 2022.8.15, 2022.8.16, 2022.8.17, 2022.8.18, 2022.8.19, 2022.8.20, 2022.8.21, 2022.8.22, 2022.8.23, 2022.8.24, 2022.8.25, 2022.8.26, 2022.8.27, 2022.8.29, 2022.8.30, 2022.8.31, 2022.9.1, 2022.9.2, 2022.9.3, 2022.9.4, 2022.9.5, 2022.9.6, 2022.9.7, 2022.9.8, 2022.9.9, 2022.9.10, 2022.9.11, 2022.9.12, 2022.9.13, 2022.9.14, 2022.9.15, 2022.9.16, 2022.9.17, 2022.9.18, 2022.9.19, 2022.9.20, 2022.9.21, 2022.9.22, 2022.9.23, 2022.9.24, 2022.9.25, 2022.9.26, 2022.9.27, 2022.9.28, 2022.9.29, 2022.9.30, 2022.10.1, 2022.10.2, 2022.10.3, 2022.10.4, 2022.10.5, 2022.10.6, 2022.10.7, 2022.10.8, 2022.10.9, 2022.10.10, 2022.10.11, 2022.10.12, 2022.10.13, 2022.10.14, 2022.10.15, 2022.10.16, 2022.10.17, 2022.10.18, 2022.10.19, 2022.10.20, 2022.10.21, 2022.10.22, 2022.10.23, 2022.10.24, 2022.10.25, 2022.10.26, 2022.10.27, 2022.10.28, 2022.10.29, 2022.11.1, 2022.11.2, 2022.11.3, 2022.11.4, 2022.11.5, 2022.11.6, 2022.11.7, 2022.11.8, 2022.11.9, 2022.11.10, 2022.11.11, 2022.11.13, 2022.11.14, 2022.11.15, 2022.11.16, 2022.11.17, 2022.11.18, 2022.11.19, 2022.11.20, 2022.11.21, 2022.11.22, 2022.11.23, 2022.11.24, 2022.11.25, 2022.11.26, 2022.11.27, 2022.11.28, 2022.11.29, 2022.11.30, 2022.12.1, 2022.12.2, 2022.12.3, 2022.12.4, 2022.12.5, 2022.12.6, 2022.12.7, 2022.12.8, 2022.12.9, 2022.12.10, 2022.12.11, 2022.12.12, 2022.12.13, 2022.12.14, 2022.12.15, 2022.12.16, 2022.12.17, 2022.12.18, 2022.12.19, 2022.12.20, 2022.12.21, 2022.12.22, 2022.12.23, 2022.12.24, 2022.12.25, 2022.12.26, 2022.12.27, 2022.12.28, 2022.12.29, 2022.12.30, 2022.12.31, 2023.1.1, 2023.1.2, 2023.1.3, 2023.1.4, 2023.1.5, 2023.1.6, 2023.1.7, 2023.1.8, 2023.1.9, 2023.1.10, 2023.1.11, 2023.1.12, 2023.1.13, 2023.1.14, 2023.1.15, 2023.1.16, 2023.1.17, 2023.1.18, 2023.1.19, 2023.1.20, 2023.1.21, 2023.1.22, 2023.1.23, 2023.1.24, 2023.1.25, 2023.1.26, 2023.1.27, 2023.1.28, 2023.1.29, 2023.1.30, 2023.1.31, 2023.2.1, 2023.2.2, 2023.2.3, 2023.2.4, 2023.2.5, 2023.2.6, 2023.2.7, 2023.2.8, 2023.2.9, 2023.2.10, 2023.2.11, 2023.2.12, 2023.2.13, 2023.2.14, 2023.2.15, 2023.2.16, 2023.2.17, 2023.2.18, 2023.2.19, 2023.2.20, 2023.2.21, 2023.2.22, 2023.2.23, 2023.2.24, 2023.2.25, 2023.2.26, 2023.2.27, 2023.2.28, 2023.3.1, 2023.3.2, 2023.3.3, 2023.3.4, 2023.3.5, 2023.3.6, 2023.3.7, 2023.3.8, 2023.3.9, 2023.3.10, 2023.3.11, 2023.3.12, 2023.3.13, 2023.3.14, 2023.3.15, 2023.3.16, 2023.3.17, 2023.3.18, 2023.3.19, 2023.3.20, 2023.3.21, 2023.3.22, 2023.3.23, 2023.3.24, 2023.3.25, 2023.3.26, 2023.3.27, 2023.3.28, 2023.3.29, 2023.3.30, 2023.3.31, 2023.4.1, 2023.4.2, 2023.4.3, 2023.4.4, 2023.4.5, 2023.4.6, 2023.4.7, 2023.4.8, 2023.4.9, 2023.4.10, 2023.4.11, 2023.4.12, 2023.4.13, 2023.4.14, 2023.4.15, 2023.4.16, 2023.4.17, 2023.4.18, 2023.4.19, 2023.4.20, 2023.4.21, 2023.4.22, 2023.4.23, 2023.4.24, 2023.4.25, 2023.4.26, 2023.4.27, 2023.4.28, 2023.4.29, 2023.4.30, 2023.5.1, 2023.5.2, 2023.5.3, 2023.5.4, 2023.5.5, 2023.5.6, 2023.5.7, 2023.5.8, 2023.5.9, 2023.5.10, 2023.5.11, 2023.5.12, 2023.5.13, 2023.5.14, 2023.5.15, 2023.5.16, 2023.5.17, 2023.5.18, 2023.5.19, 2023.5.20, 2023.5.21, 2023.5.22, 2023.5.23, 2023.5.24, 2023.5.25, 2023.5.26, 2023.5.27, 2023.5.28, 2023.5.29, 2023.5.30, 2023.5.31, 2023.6.1, 2023.6.2, 2023.6.3, 2023.6.4, 2023.6.5, 2023.6.6, 2023.6.7, 2023.6.8, 2023.6.9, 2023.6.10, 2023.6.11, 2023.6.12, 2023.6.13, 2023.6.14, 2023.6.15, 2023.6.16, 2023.6.17, 2023.6.18, 2023.6.19, 2023.6.20, 2023.6.21, 2023.6.24, 2023.6.25, 2023.6.26, 2023.6.27, 2023.6.28, 2023.6.29, 2023.6.30, 2023.7.1, 2023.7.2, 2023.7.3, 2023.7.4, 2023.7.5, 2023.7.6, 2023.7.7, 2023.7.8, 2023.7.9, 2023.7.10, 2023.7.11, 2023.7.12, 2023.7.13, 2023.7.14, 2023.7.15, 2023.7.16, 2023.7.17, 2023.7.19, 2023.7.20, 2023.7.21, 2023.7.22, 2023.7.23, 2023.7.24, 2023.7.25, 2023.7.26, 2023.7.27, 2023.7.30, 2023.7.31, 2023.8.1, 2023.8.2, 2023.8.3, 2023.8.4, 2023.8.5, 2023.8.7, 2023.8.8, 2023.8.9, 2023.8.10, 2023.8.11, 2023.8.12, 2023.8.13, 2023.8.14, 2023.8.15, 2023.8.16, 2023.8.17, 2023.8.18, 2023.8.19, 2023.8.20, 2023.8.21, 2023.8.22, 2023.8.23, 2023.8.24, 2023.8.25, 2023.8.26, 2023.8.27, 2023.8.28, 2023.8.29, 2023.8.30, 2023.8.31, 2023.9.1, 2023.9.2, 2023.9.3, 2023.9.4, 2023.9.6, 2023.9.7, 2023.9.8, 2023.9.9, 2023.9.10, 2023.9.11, 2023.9.12, 2023.9.13, 2023.9.15, 2023.9.16, 2023.9.17)
ERROR: No matching distribution found for torchserve-nightly==2023.9.18
``` 
The reason for being unable to build `torchserve-nightly==2023.9.18` is as follows:
```
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
         Project size too large. Limit for project 'torchserve-nightly' total   
         size is 10 GB. See https://pypi.org/help/#project-size-limit           
Traceback (most recent call last):
  File "/home/runner/work/serve/serve/binaries/upload.py", line 102, in <module>
    upload_pypi_packages(args, WHL_PATHS)
  File "/home/runner/work/serve/serve/binaries/upload.py", line 28, in upload_pypi_packages
    try_and_handle(f"twine upload --username __token__ {dist_path}/*", dry_run)
  File "/home/runner/work/serve/serve/ts_scripts/utils.py", line 55, in try_and_handle
    raise (e)
  File "/home/runner/work/serve/serve/ts_scripts/utils.py", line 53, in try_and_handle
    subprocess.run([cmd], shell=True, check=True)
  File "/usr/share/miniconda/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['twine upload --username __token__ /home/runner/work/serve/serve/binaries/../dist/*']' returned non-zero exit status 1.
Error: Process completed with exit code 1.
```

### Error logs

Mentioned above.

### Installation instructions

N/A

### Model Packaing

N/A

### Versions

N/A

### Repro instructions

N/A

### Possible Solution

The suggested solutions are as follows:
1. Fix the path for the input payload. 
2. For any future scenarios, we can modify the script to search for previously available `torchserve-nightly` versions as well, in case the latest one is not pushed to PyPi for some reason.

**Comment by sachanub** [comment]
@namannandan can you please assign this issue to yourself? Thanks!

**Comment by msaroufim** [comment]
I just bulk deleted old nightlies so this should be fixed

**Comment by msaroufim** [comment]
For future reference here's what i did

```
Ok so we can just do another bulk delete in about 6 months for reference here's what i did
git clone https://github.com/arcivanov/pypi-cleanup
pip install .
Dry run command showed me long of exactly what would be deleted, change username and project to whatever you want, you'll need to put in your pypi password
The regex pattern i used was just 2022 since i didn't wanna get too clever
pypi-cleanup -u marksaroufim -p torchserve-nightly -r '2022' -y
Once you're happy with the output you can do this which will actually delete
 pypi-cleanup -u marksaroufim -p torchserve-nightly -r '2022' -y --do-it
```
