### ISSUE TITLE
TorchServe build fails sometimes inside of Docker build

### ISSUE THREAD

**Issue by C24IO** [pytorch/serve#266]
Hit the following error sometimes when building Docker containers for TorchServe. 

`BUILD FAILED in 3m 22s
  26 actionable tasks: 23 executed, 3 up-to-date
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-z505ad23/setup.py", line 160, in <module>
      license='Apache License Version 2.0'
    File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/dist-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-z505ad23/setup.py", line 98, in run
      self.run_command('build_frontend')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-z505ad23/setup.py", line 85, in run
      subprocess.check_call('frontend/gradlew -p frontend clean build', shell=True)
    File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'frontend/gradlew -p frontend clean build' returned non-zero exit status 1.

  ERROR: Failed building wheel for torchserve
  Running setup.py clean for torchserve
Failed to build torchserve
Installing collected packages: torchserve
    Running setup.py install for torchserve: started
    Running setup.py install for torchserve: still running...
    Running setup.py install for torchserve: still running...
    Running setup.py install for torchserve: finished with status 'done'
Successfully installed torchserve-0.0.1b20200423`

**Comment by dhanainme** [comment]
Can you provide some additional details about the steps that you had to perform to run in to this error. 

Have you been trying the docker files in https://github.com/pytorch/serve/tree/master/docker ?

**Comment by vdantu** [comment]
@dhanainme : Is there any reason why we build torchserve when we are building the container? 

Ideally we should be doing a `pip install torchserve==<version>` in the Dockerfile. If customers want latest torchserve, they should ideally be pulling the "prerelease" versions, which should be pushed to pypi on a nightly basis. Would like to hear more opinions about this.

**Comment by dhanainme** [comment]
@vdantu , I agree with you. The Dockerfile was probably created before we had the pypi packages.

**Comment by dhaniram-kshirsagar** [comment]
PR #308 will address this.
