### ISSUE TITLE
Model archiver API

### ISSUE THREAD

**Issue by Chichilele** [pytorch/serve#2695]
### 🚀 The feature

A python API for model archiver

### Motivation, pitch

It'd be nice to be able to archive a model  directly from the python application, without having to run a bash command with a subshell or others.

### Alternatives

I've used a script like this which is almost identical to what the entry point of `torch-model-archiver` is. The only addition is a pydantic model as config instead of arg parse. 

The application then imports `ModelArchiverConfig` and `generate_model_archive` to build a new mar file.

One of the limitations here is not being able to pass a custom handler in a clean way when it's part of the library/application.

```python
from typing import Optional, Literal, Union
import os
import logging
import shutil
from pathlib import Path

from pydantic import BaseModel
from model_archiver.model_archiver_error import ModelArchiverError
from model_archiver.model_packaging_utils import ModelExportUtils
from model_archiver.manifest_components.manifest import RuntimeType


class ModelArchiverConfig(BaseModel):
    model_name: str
    serialized_file: Optional[str] = None
    model_file: Optional[str] = None
    handler: str
    extra_files: Optional[str] = None
    runtime: str = RuntimeType.PYTHON.value
    export_path: Union[str, Path] = os.getcwd()
    archive_format: Literal["default", "tgz", "no-archive"] = "default"
    force: bool = False
    version: str
    requirements_file: Optional[str] = None


def _package_model(config: ModelArchiverConfig, manifest: str):
    """
    Internal helper for the exporting model command line interface.
    """
    model_file = config.model_file
    serialized_file = config.serialized_file
    model_name = config.model_name
    handler = config.handler
    extra_files = config.extra_files
    export_file_path = config.export_path
    requirements_file = config.requirements_file

    try:
        ModelExportUtils.validate_inputs(model_name, export_file_path)
        # Step 1 : Check if .mar already exists with the given model name
        export_file_path = ModelExportUtils.check_mar_already_exists(
            model_name, export_file_path, config.force, config.archive_format
        )

        # Step 2 : Copy all artifacts to temp directory
        artifact_files = {
            "model_file": model_file,
            "serialized_file": serialized_file,
            "handler": handler,
            "extra_files": extra_files,
            "requirements-file": requirements_file,
        }

        model_path = ModelExportUtils.copy_artifacts(model_name, **artifact_files)

        # Step 2 : Zip 'em all up
        ModelExportUtils.archive(
            export_file_path, model_name, model_path, manifest, config.archive_format
        )
        shutil.rmtree(model_path)
        logging.info(
            "Successfully exported model %s to file %s", model_name, export_file_path
        )
    except ModelArchiverError as e:
        logging.error(e)
        raise e


def generate_model_archive(config: ModelArchiverConfig):
    """
    Generate a model archive file
    :return:
    """

    logging.basicConfig(format="%(levelname)s - %(message)s")
    manifest = ModelExportUtils.generate_manifest_json(config)
    _package_model(config, manifest=manifest)

```

**Comment by msaroufim** [comment]
I think this is a great idea TBH, we already have something like this in our test utils https://github.com/pytorch/serve/blob/master/test/pytest/test_utils.py

We could and should make this part of our public API instead

**Comment by Chichilele** [comment]
I've tried setting up the environment following https://github.com/pytorch/serve/blob/master/CONTRIBUTING.md#install-torchserve-for-development and had some issues. Would you be able to help?

## Environment
I run on mac M1 pro with macOS Ventura. My typical setup is pyenv+poetry. I have no experience with node/java/gradle (anything but python essentially). The 2 scripts `python ./ts_scripts/install_dependencies.py --environment=dev` and `python ./ts_scripts/install_from_src.py --environment=dev` ran as far as I can tell.

## Issues

### 1. Installer does not create a python environment
I realised the script had installed packages to my "base" `pyenv` which isn't ideal. Would it be possible to leverage conda or any python env tool somewhere at the top of the [install_python_package()](https://github.com/pytorch/serve/blob/master/ts_scripts/install_dependencies.py#L53) function? Alternatively, it would be worth adding a disclaimer suggesting to create an environment before running the script.

### 2. Sanity check fails
When running the sanity check I get a grade error.

<details><summary>torchserve_sanity.py error</summary>

```bash
$ python torchserve_sanity.py
## Started frontend build and tests
## In directory: /Users/gauthiercastro/code/serve | Executing command: frontend/gradlew -p frontend clean build
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file '/Users/gauthiercastro/code/serve/frontend/settings.gradle' (/Users/gauthiercastro/.gradle/caches/7.6/scripts/9hv7ydusbul6bfoozqlmkymv6).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 64

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
## Stopping TorchServe
## In directory: /Users/gauthiercastro/code/serve | Executing command: ['torchserve', '--stop']
## Successfully stopped TorchServe
## Deleting model_store_gen_dir: /Users/gauthiercastro/code/serve/ts_scripts/../model_store_gen

### Frontend Gradle Tests Failed !
```
</details>

### Regression tests fail
The regression_tests.py script seems to fail with similar complain about gradle but also `newman: requires node version >=16`
<details><summary>regression_tests.py error</summary>

```bash
$ python test/regression_tests.py
Current date and time : 2023-10-29 18:27:00
## In directory /Users/gauthiercastro/code/serve | Executing command pip install --force-reinstall .
Processing /Users/gauthiercastro/code/serve
  Preparing metadata (setup.py) ... done
Collecting Pillow (from torchserve==0.8.1b20231029)
  Using cached Pillow-10.1.0-cp38-cp38-macosx_11_0_arm64.whl.metadata (9.5 kB)
Collecting psutil (from torchserve==0.8.1b20231029)
  Using cached psutil-5.9.6-cp38-abi3-macosx_11_0_arm64.whl.metadata (21 kB)
Collecting packaging (from torchserve==0.8.1b20231029)
  Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting wheel (from torchserve==0.8.1b20231029)
  Using cached wheel-0.41.2-py3-none-any.whl.metadata (2.2 kB)
Using cached packaging-23.2-py3-none-any.whl (53 kB)
Using cached Pillow-10.1.0-cp38-cp38-macosx_11_0_arm64.whl (3.3 MB)
Using cached psutil-5.9.6-cp38-abi3-macosx_11_0_arm64.whl (246 kB)
Using cached wheel-0.41.2-py3-none-any.whl (64 kB)
Building wheels for collected packages: torchserve
  Building wheel for torchserve (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [66 lines of output]
      -- torchserve building version: 0.8.1b20231029
      running bdist_wheel
      running build
      running build_py
      running build_frontend
      
      FAILURE: Build failed with an exception.
      
      * What went wrong:
      Could not open settings generic class cache for settings file '/Users/gauthiercastro/code/serve/frontend/settings.gradle' (/Users/gauthiercastro/.gradle/caches/7.6/scripts/9hv7ydusbul6bfoozqlmkymv6).
      > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 64
      
      * Try:
      > Run with --stacktrace option to get the stack trace.
      > Run with --info or --debug option to get more log output.
      > Run with --scan to get full insights.
      
      * Get more help at https://help.gradle.org
      
      BUILD FAILED in 305ms
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/Users/gauthiercastro/code/serve/setup.py", line 163, in <module>
          setup(
        File "/Users/gauthiercastro/.pyenv/versions/3.8.14/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/Users/gauthiercastro/.pyenv/versions/3.8.14/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/Users/gauthiercastro/.pyenv/versions/3.8.14/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/gauthiercastro/.pyenv/versions/3.8.14/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/Users/gauthiercastro/.pyenv/versions/3.8.14/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/Users/gauthiercastro/.pyenv/versions/3.8.14/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/gauthiercastro/.pyenv/versions/3.8.14/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/Users/gauthiercastro/.pyenv/versions/3.8.14/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/Users/gauthiercastro/.pyenv/versions/3.8.14/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/Users/gauthiercastro/.pyenv/versions/3.8.14/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/gauthiercastro/.pyenv/versions/3.8.14/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/Users/gauthiercastro/.pyenv/versions/3.8.14/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/Users/gauthiercastro/.pyenv/versions/3.8.14/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/Users/gauthiercastro/.pyenv/versions/3.8.14/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/gauthiercastro/code/serve/setup.py", line 110, in run
          self.run_command("build_frontend")
        File "/Users/gauthiercastro/.pyenv/versions/3.8.14/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/Users/gauthiercastro/.pyenv/versions/3.8.14/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/Users/gauthiercastro/.pyenv/versions/3.8.14/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/gauthiercastro/code/serve/setup.py", line 97, in run
          subprocess.check_call(build_frontend_command[platform.system()], shell=True)
        File "/Users/gauthiercastro/.pyenv/versions/3.8.14/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command 'frontend/gradlew -p frontend clean assemble' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for torchserve
  Running setup.py clean for torchserve
Failed to build torchserve
ERROR: Could not build wheels for torchserve, which is required to install pyproject.toml-based projects
## In directory /Users/gauthiercastro/code/serve | Executing command pip install --force-reinstall model-archiver/.
Processing ./model-archiver
  Preparing metadata (setup.py) ... done
Collecting enum-compat (from torch-model-archiver==0.8.1b20231029)
  Using cached enum_compat-0.0.3-py3-none-any.whl (1.3 kB)
Building wheels for collected packages: torch-model-archiver
  Building wheel for torch-model-archiver (setup.py) ... done
  Created wheel for torch-model-archiver: filename=torch_model_archiver-0.8.1b20231029-py3-none-any.whl size=14829 sha256=d2bb68ad75f9ccb42c305611d87ba4a9a630b561cc77b93586cd165dbe4aa44b
  Stored in directory: /Users/gauthiercastro/Library/Caches/pip/wheels/22/b3/19/4406635d35836ce09ce29168013a196d6890fe544d303cf931
Successfully built torch-model-archiver
Installing collected packages: enum-compat, torch-model-archiver
  Attempting uninstall: enum-compat
    Found existing installation: enum-compat 0.0.3
    Uninstalling enum-compat-0.0.3:
      Successfully uninstalled enum-compat-0.0.3
  Attempting uninstall: torch-model-archiver
    Found existing installation: torch-model-archiver 0.8.1b20231029
    Uninstalling torch-model-archiver-0.8.1b20231029:
      Successfully uninstalled torch-model-archiver-0.8.1b20231029
Successfully installed enum-compat-0.0.3 torch-model-archiver-0.8.1b20231029
## In directory /Users/gauthiercastro/code/serve | Executing command pip install --force-reinstall workflow-archiver/.
Processing ./workflow-archiver
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: torch-workflow-archiver
  Building wheel for torch-workflow-archiver (setup.py) ... done
  Created wheel for torch-workflow-archiver: filename=torch_workflow_archiver-0.2.9b20231029-py3-none-any.whl size=12724 sha256=8e273d8695bc21dce5fde4d4a8851f29519f0b277af7bd7a63fb6b5918fcec52
  Stored in directory: /Users/gauthiercastro/Library/Caches/pip/wheels/09/54/e4/1592874f0b2465df1d159e0bdc11ea744780755b7c06f817e8
Successfully built torch-workflow-archiver
Installing collected packages: torch-workflow-archiver
  Attempting uninstall: torch-workflow-archiver
    Found existing installation: torch-workflow-archiver 0.2.9b20231029
    Uninstalling torch-workflow-archiver-0.2.9b20231029:
      Successfully uninstalled torch-workflow-archiver-0.2.9b20231029
Successfully installed torch-workflow-archiver-0.2.9b20231029
## Starting generate_mars, mar_config:/Users/gauthiercastro/code/serve/ts_scripts/../ts_scripts/mar_config.json, model_store_dir:/Users/gauthiercastro/code/serve/ts_scripts/../model_store_gen

## In directory: /Users/gauthiercastro/code/serve | Executing command: torch-model-archiver --model-name fastrcnn --version 1.0 --model-file examples/object_detector/fast-rcnn/model.py --serialized-file /Users/gauthiercastro/code/serve/ts_scripts/../model_store_gen/fasterrcnn_resnet50_fpn_coco-258fb6c6.pth --handler object_detector --extra-files examples/object_detector/index_to_name.json --archive-format zip-store --export-path /Users/gauthiercastro/code/serve/ts_scripts/../model_store_gen --force

## fastrcnn.mar is generated.

## In directory: /Users/gauthiercastro/code/serve | Executing command: torch-model-archiver --model-name alexnet --version 1.0 --model-file examples/image_classifier/alexnet/model.py --serialized-file /Users/gauthiercastro/code/serve/ts_scripts/../model_store_gen/alexnet-owt-7be5be79.pth --handler image_classifier --extra-files examples/image_classifier/index_to_name.json --archive-format zip-store --export-path /Users/gauthiercastro/code/serve/ts_scripts/../model_store_gen --force

## alexnet.mar is generated.

## In directory: /Users/gauthiercastro/code/serve | Executing command: torch-model-archiver --model-name densenet161 --version 1.0 --model-file examples/image_classifier/densenet_161/model.py --serialized-file /Users/gauthiercastro/code/serve/ts_scripts/../model_store_gen/densenet161-8d451a50.pth --handler image_classifier --extra-files examples/image_classifier/index_to_name.json --archive-format zip-store --export-path /Users/gauthiercastro/code/serve/ts_scripts/../model_store_gen --force

## densenet161.mar is generated.

## In directory: /Users/gauthiercastro/code/serve | Executing command: torch-model-archiver --model-name mnist --version 1.0 --model-file examples/image_classifier/mnist/mnist.py --serialized-file examples/image_classifier/mnist/mnist_cnn.pt --handler examples/image_classifier/mnist/mnist_handler.py --archive-format zip-store --export-path /Users/gauthiercastro/code/serve/ts_scripts/../model_store_gen --force

## mnist.mar is generated.

## In directory: /Users/gauthiercastro/code/serve | Executing command: torch-model-archiver --model-name resnet-152-batch --version 1.0 --model-file examples/image_classifier/resnet_152_batch/model.py --serialized-file /Users/gauthiercastro/code/serve/ts_scripts/../model_store_gen/resnet152-394f9c45.pth --handler image_classifier --extra-files examples/image_classifier/index_to_name.json --archive-format zip-store --export-path /Users/gauthiercastro/code/serve/ts_scripts/../model_store_gen --force

## resnet-152-batch.mar is generated.

## In directory: /Users/gauthiercastro/code/serve | Executing command: torch-model-archiver --model-name resnet-18 --version 1.0 --model-file examples/image_classifier/resnet_18/model.py --serialized-file /Users/gauthiercastro/code/serve/ts_scripts/../model_store_gen/resnet18-f37072fd.pth --handler image_classifier --extra-files examples/image_classifier/index_to_name.json --archive-format zip-store --export-path /Users/gauthiercastro/code/serve/ts_scripts/../model_store_gen --force

## resnet-18.mar is generated.

## In directory: /Users/gauthiercastro/code/serve | Executing command: torch-model-archiver --model-name squeezenet1_1 --version 1.0 --model-file examples/image_classifier/squeezenet/model.py --serialized-file /Users/gauthiercastro/code/serve/ts_scripts/../model_store_gen/squeezenet1_1-b8a52dc0.pth --handler image_classifier --extra-files examples/image_classifier/index_to_name.json --archive-format zip-store --export-path /Users/gauthiercastro/code/serve/ts_scripts/../model_store_gen --force

## squeezenet1_1.mar is generated.

## In directory: /Users/gauthiercastro/code/serve | Executing command: torch-model-archiver --model-name vgg16 --version 1.0 --model-file examples/image_classifier/vgg_16/model.py --serialized-file /Users/gauthiercastro/code/serve/ts_scripts/../model_store_gen/vgg16-397923af.pth --handler examples/image_classifier/vgg_16/vgg_handler.py --extra-files examples/image_classifier/index_to_name.json --archive-format zip-store --export-path /Users/gauthiercastro/code/serve/ts_scripts/../model_store_gen --force

## vgg16.mar is generated.

## In directory: /Users/gauthiercastro/code/serve | Executing command: torch-model-archiver --model-name deeplabv3_resnet_101_eager --version 1.0 --model-file examples/image_segmenter/deeplabv3/model.py --serialized-file /Users/gauthiercastro/code/serve/ts_scripts/../model_store_gen/deeplabv3_resnet101_coco-586e9e4e.pth --handler image_segmenter --extra-files examples/image_segmenter/deeplabv3/deeplabv3.py,examples/image_segmenter/deeplabv3/intermediate_layer_getter.py,examples/image_segmenter/deeplabv3/fcn.py --archive-format zip-store --export-path /Users/gauthiercastro/code/serve/ts_scripts/../model_store_gen --force

## deeplabv3_resnet_101_eager.mar is generated.

## In directory: /Users/gauthiercastro/code/serve | Executing command: torch-model-archiver --model-name fcn_resnet_101 --version 1.0 --model-file examples/image_segmenter/fcn/model.py --serialized-file /Users/gauthiercastro/code/serve/ts_scripts/../model_store_gen/fcn_resnet101_coco-7ecb50ca.pth --handler image_segmenter --extra-files examples/image_segmenter/fcn/fcn.py,examples/image_segmenter/fcn/intermediate_layer_getter.py --archive-format zip-store --export-path /Users/gauthiercastro/code/serve/ts_scripts/../model_store_gen --force

## fcn_resnet_101.mar is generated.

## In directory: /Users/gauthiercastro/code/serve | Executing command: torch-model-archiver --model-name maskrcnn --version 1.0 --model-file examples/object_detector/maskrcnn/model.py --serialized-file /Users/gauthiercastro/code/serve/ts_scripts/../model_store_gen/maskrcnn_resnet50_fpn_coco-bf2d0c1e.pth --handler object_detector --extra-files examples/object_detector/index_to_name.json --archive-format zip-store --export-path /Users/gauthiercastro/code/serve/ts_scripts/../model_store_gen --force

## maskrcnn.mar is generated.

## Starting gen_mar: model_store

## Create symlink for mar files

## Symlink /Users/gauthiercastro/code/serve/ts_scripts/../model_store_gen/squeezenet1_1.mar, model_store/squeezenet1_1.mar successfully.
## Symlink /Users/gauthiercastro/code/serve/ts_scripts/../model_store_gen/fastrcnn.mar, model_store/fastrcnn.mar successfully.
## Symlink /Users/gauthiercastro/code/serve/ts_scripts/../model_store_gen/resnet-152-batch.mar, model_store/resnet-152-batch.mar successfully.
## Symlink /Users/gauthiercastro/code/serve/ts_scripts/../model_store_gen/densenet161.mar, model_store/densenet161.mar successfully.
## Symlink /Users/gauthiercastro/code/serve/ts_scripts/../model_store_gen/maskrcnn.mar, model_store/maskrcnn.mar successfully.
## Symlink /Users/gauthiercastro/code/serve/ts_scripts/../model_store_gen/mnist.mar, model_store/mnist.mar successfully.
## Symlink /Users/gauthiercastro/code/serve/ts_scripts/../model_store_gen/resnet-18.mar, model_store/resnet-18.mar successfully.
## Symlink /Users/gauthiercastro/code/serve/ts_scripts/../model_store_gen/fcn_resnet_101.mar, model_store/fcn_resnet_101.mar successfully.
## Symlink /Users/gauthiercastro/code/serve/ts_scripts/../model_store_gen/deeplabv3_resnet_101_eager.mar, model_store/deeplabv3_resnet_101_eager.mar successfully.
## Symlink /Users/gauthiercastro/code/serve/ts_scripts/../model_store_gen/alexnet.mar, model_store/alexnet.mar successfully.
## Symlink /Users/gauthiercastro/code/serve/ts_scripts/../model_store_gen/vgg16.mar, model_store/vgg16.mar successfully.
## Starting TorchServe
## Console logs redirected to file: ts_console.log
## In directory: /Users/gauthiercastro/code/serve/test | Executing command: torchserve --start --model-store=model_store --ncs
## Successfully started TorchServe
newman: required node version >=16
## Stopping TorchServe
## In directory: /Users/gauthiercastro/code/serve/test | Executing command: ['torchserve', '--stop']
## Successfully stopped TorchServe
Traceback (most recent call last):
  File "test/regression_tests.py", line 28, in <module>
    test_api(
  File "/Users/gauthiercastro/code/serve/ts_scripts/api_utils.py", line 432, in test_api
    exit_code = switcher[collection]()
  File "/Users/gauthiercastro/code/serve/ts_scripts/api_utils.py", line 359, in trigger_all
    exit_code1 = trigger_management_tests()
  File "/Users/gauthiercastro/code/serve/ts_scripts/api_utils.py", line 126, in trigger_management_tests
    move_logs(TS_CONSOLE_LOG_FILE, ARTIFACTS_MANAGEMENT_DIR)
  File "/Users/gauthiercastro/code/serve/ts_scripts/api_utils.py", line 113, in move_logs
    os.rename(log_file, os.path.join(logs_dir, log_file))  # mv file logs/
FileNotFoundError: [Errno 2] No such file or directory: 'ts_console.log' -> 'logs/ts_console.log'
```

</details> 


##¢ Pytest fails to find python module `inference_pb2`

<details><summary>missing `inference_pb2`</summary>

```bash
pytest test/pytest 
======================================================================= test session starts ========================================================================
platform darwin -- Python 3.8.14, pytest-7.3.1, pluggy-1.0.0
rootdir: /Users/gauthiercastro/code/serve
plugins: mock-3.10.0, cov-4.1.0
collected 106 items / 3 errors                                                                                                                                     

============================================================================== ERRORS ==============================================================================
_____________________________________________________ ERROR collecting test/pytest/test_gRPC_inference_api.py ______________________________________________________
ImportError while importing test module '/Users/gauthiercastro/code/serve/test/pytest/test_gRPC_inference_api.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../.pyenv/versions/3.8.14/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/pytest/test_gRPC_inference_api.py:5: in <module>
    import inference_pb2
E   ModuleNotFoundError: No module named 'inference_pb2'
____________________________________________________ ERROR collecting test/pytest/test_gRPC_management_apis.py _____________________________________________________
ImportError while importing test module '/Users/gauthiercastro/code/serve/test/pytest/test_gRPC_management_apis.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../.pyenv/versions/3.8.14/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/pytest/test_gRPC_management_apis.py:4: in <module>
    import test_gRPC_utils
test/pytest/test_gRPC_utils.py:2: in <module>
    import inference_pb2_grpc
E   ModuleNotFoundError: No module named 'inference_pb2_grpc'
_________________________________________________________ ERROR collecting test/pytest/test_gRPC_utils.py __________________________________________________________
ImportError while importing test module '/Users/gauthiercastro/code/serve/test/pytest/test_gRPC_utils.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../.pyenv/versions/3.8.14/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test/pytest/test_gRPC_utils.py:2: in <module>
    import inference_pb2_grpc
E   ModuleNotFoundError: No module named 'inference_pb2_grpc'
========================================================================= warnings summary =========================================================================
test/pytest/test_torch_compile.py:11
  /Users/gauthiercastro/code/serve/test/pytest/test_torch_compile.py:11: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    from pkg_resources import packaging

../../.pyenv/versions/3.8.14/lib/python3.8/site-packages/pkg_resources/__init__.py:2871
  /Users/gauthiercastro/.pyenv/versions/3.8.14/lib/python3.8/site-packages/pkg_resources/__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
===================================================================== short test summary info ======================================================================
ERROR test/pytest/test_gRPC_inference_api.py
ERROR test/pytest/test_gRPC_management_apis.py
ERROR test/pytest/test_gRPC_utils.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================================== 2 warnings, 3 errors in 1.69s ===================================================================
```

</details>

**Comment by msaroufim** [comment]
@Chichilele it might be easier if you join the PyTorch slack we can discuss this stuff more actively. What's your email?

In the meantime some specific answers to your questions
1. You need a virtual environment before you call `install_dependencies.py`, if you're noticing some packages are leaking to your root environment that's a bug
2. This happens if you don't have your java and gradle versions matched, what does your `java --version` say
3. This might happen in case you already have node installed locally https://github.com/pytorch/serve/blob/master/ts_scripts/install_dependencies.py#L115 try using the force argument to get a newer version
4. This test is weird in that it requires more upfront setup by following here https://github.com/pytorch/serve/blob/master/docs/grpc_api.md which we do do in our test scripts

**Comment by Chichilele** [comment]
Alright, I got everything to work (I think) with your suggestions! 🍾 Where would you start to expose an API for the torch archiver? Adding a couple of public classes in a new file here perhaps?: https://github.com/pytorch/serve/tree/master/model-archiver/model_archiver
The test suit might need changing too? https://github.com/pytorch/serve/blob/master/model-archiver/model_archiver/tests/integ_tests/test_integration_model_archiver.py

**Comment by msaroufim** [comment]
Ok just sent you an invite now, just needs mods approval but should be ready soon

> Adding a couple of public classes in a new file here perhaps?: https://github.com/pytorch/serve/tree/master/model-archiver/model_archiver

Yes

> The test suit might need changing too? https://github.com/pytorch/serve/blob/master/model-archiver/model_archiver/tests/integ_tests/test_integration_model_archiver.py

We can just create new tests and change the test utilities in a followup PR but you're right that it's better to just also make this change sooner

Also cc @mreso who has been thinking about similar problems

**Comment by mreso** [comment]
> Alright, I got everything to work (I think) with your suggestions! 🍾 Where would you start to expose an API for the torch archiver? Adding a couple of public classes in a new file here perhaps?: https://github.com/pytorch/serve/tree/master/model-archiver/model_archiver The test suit might need changing too? https://github.com/pytorch/serve/blob/master/model-archiver/model_archiver/tests/integ_tests/test_integration_model_archiver.py

Hi, great idea and thanks for taking this on. As an interface its probably a good a idea to separate this from the ModelExportUtils and create a new class ModelArchiver that we can use like this:
```
from model_archiver import ModelArchiver, ModelArchiverConfig

config = ModelArchiverConfig(
model_name="...",
...)
ModelArchiver.generate_model_archive(config)
```
To integrate you can internally use generate)model_archive from here https://github.com/pytorch/serve/blob/7f4419f5885852199f8e5b568da1b822e1628262/model-archiver/model_archiver/model_packaging.py#L59 and add the config parameter as optional. When the parameter is given use it otherwise call https://github.com/pytorch/serve/blob/7f4419f5885852199f8e5b568da1b822e1628262/model-archiver/model_archiver/model_packaging.py#L66
