### ISSUE TITLE
custom python package dependency install fails

### ISSUE THREAD

**Issue by rbavery** [pytorch/serve#2713]
### 🐛 Describe the bug

I'm trying to install a custom python module that I included as a .at.gz in a MAR archive

relevant section of the Dockerfile
```
COPY src/sam_serve/ ./sam_serve/

COPY requirements.txt ./requirements.txt

# Zip up the sam_serve module
RUN tar czf sam_serve.tar.gz -C sam_serve .

RUN torch-model-archiver --model-name sam_vit_h_encode --version 1.0.0 --serialized-file model-weights/sam_vit_h_4b8939.pth --handler handler_encode.py --extra-files sam_serve.tar.gz --requirements-file requirements.txt
```

but I get this error when torchserve starts

```
2023-10-13T23:06:08,291 [ERROR] main org.pytorch.serve.wlm.ModelManager - Dependency installation stderr:
ERROR: Could not find a version that satisfies the requirement sam_serve (from versions: none)ERROR: No matching distribution found for sam_serve
2023-10-13T23:06:08,291 [WARN ] main org.pytorch.serve.ModelServer - Failed to load model: /home/model-server/volume/model-store/sam_vit_h_encode.mar
org.pytorch.serve.archive.model.ModelException: Custom pip package installation failed for sam_vit_h_encode
	at org.pytorch.serve.wlm.ModelManager.setupModelDependencies(ModelManager.java:280) ~[model-server.jar:?]
	at org.pytorch.serve.wlm.ModelManager.registerModel(ModelManager.java:155) ~[model-server.jar:?]
	at org.pytorch.serve.wlm.ModelManager.registerModel(ModelManager.java:73) ~[model-server.jar:?]
	at org.pytorch.serve.ModelServer.initModelStore(ModelServer.java:198) [model-server.jar:?]
	at org.pytorch.serve.ModelServer.startRESTserver(ModelServer.java:396) [model-server.jar:?]
	at org.pytorch.serve.ModelServer.startAndWait(ModelServer.java:118) [model-server.jar:?]
	at org.pytorch.serve.ModelServer.main(ModelServer.java:99) [model-server.jar:?]
```

I've tried other variations of this like trying individual files but can't seem to get it to recognize and install anything in extra-files.

### Error logs

Warning: TorchServe is using non-default JVM parameters: -Xmx24g
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2023-10-13T23:05:37,128 [WARN ] main org.pytorch.serve.util.ConfigManager - Your torchserve instance can access any URL to load models. When deploying to production, make sure to limit the set of allowed_urls in config.properties
2023-10-13T23:05:37,129 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager - Initializing plugins manager...
2023-10-13T23:05:37,166 [INFO ] main org.pytorch.serve.metrics.configuration.MetricConfiguration - Successfully loaded metrics configuration from /home/venv/lib/python3.9/site-packages/ts/configs/metrics.yaml
2023-10-13T23:05:37,253 [INFO ] main org.pytorch.serve.ModelServer - 
Torchserve version: 0.9.0
TS Home: /home/venv/lib/python3.9/site-packages
Current directory: /home/model-server
Temp directory: /home/model-server/volume/tmp
Metrics config path: /home/venv/lib/python3.9/site-packages/ts/configs/metrics.yaml
Number of GPUs: 1
Number of CPUs: 12
Max heap size: 24576 M
Python executable: /home/venv/bin/python
Config file: ./config.properties
Inference address: http://0.0.0.0:8080
Management address: http://0.0.0.0:8081
Metrics address: http://127.0.0.1:8082
Model Store: /home/model-server/volume/model-store
Initial Models: all
Log dir: /home/model-server/logs
Metrics dir: /home/model-server/logs
Netty threads: 1
Netty client threads: 0
Default workers per model: 1
Blacklist Regex: N/A
Maximum Response Size: 17797905
Maximum Request Size: 17797905
Limit Maximum Image Pixels: true
Prefer direct buffer: false
Allowed Urls: [file://.*|http(s)?://.*]
Custom python dependency for model allowed: true
Enable metrics API: true
Metrics mode: log
Disable system metrics: false
Workflow Store: /home/model-server/volume/model-store
Model config: N/A
2023-10-13T23:05:37,257 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager -  Loading snapshot serializer plugin...
2023-10-13T23:05:37,271 [DEBUG] main org.pytorch.serve.ModelServer - Loading models from model store: sam_vit_h_encode.mar
2023-10-13T23:06:07,781 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Adding new version 1.0.0 for model sam_vit_h_encode
2023-10-13T23:06:07,781 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Setting default version to 1.0.0 for model sam_vit_h_encode
2023-10-13T23:06:08,291 [ERROR] main org.pytorch.serve.wlm.ModelManager - Dependency installation stderr:
ERROR: Could not find a version that satisfies the requirement sam_serve (from versions: none)ERROR: No matching distribution found for sam_serve
2023-10-13T23:06:08,291 [WARN ] main org.pytorch.serve.ModelServer - Failed to load model: /home/model-server/volume/model-store/sam_vit_h_encode.mar
org.pytorch.serve.archive.model.ModelException: Custom pip package installation failed for sam_vit_h_encode
	at org.pytorch.serve.wlm.ModelManager.setupModelDependencies(ModelManager.java:280) ~[model-server.jar:?]
	at org.pytorch.serve.wlm.ModelManager.registerModel(ModelManager.java:155) ~[model-server.jar:?]
	at org.pytorch.serve.wlm.ModelManager.registerModel(ModelManager.java:73) ~[model-server.jar:?]
	at org.pytorch.serve.ModelServer.initModelStore(ModelServer.java:198) [model-server.jar:?]
	at org.pytorch.serve.ModelServer.startRESTserver(ModelServer.java:396) [model-server.jar:?]
	at org.pytorch.serve.ModelServer.startAndWait(ModelServer.java:118) [model-server.jar:?]
	at org.pytorch.serve.ModelServer.main(ModelServer.java:99) [model-server.jar:?]
2023-10-13T23:06:08,299 [INFO ] main org.pytorch.serve.ModelServer - Initialize Inference server with: EpollServerSocketChannel.
2023-10-13T23:06:08,337 [INFO ] main org.pytorch.serve.ModelServer - Inference API bind to: http://0.0.0.0:8080
2023-10-13T23:06:08,337 [INFO ] main org.pytorch.serve.ModelServer - Initialize Management server with: EpollServerSocketChannel.
2023-10-13T23:06:08,338 [INFO ] main org.pytorch.serve.ModelServer - Management API bind to: http://0.0.0.0:8081
2023-10-13T23:06:08,338 [INFO ] main org.pytorch.serve.ModelServer - Initialize Metrics server with: EpollServerSocketChannel.
2023-10-13T23:06:08,339 [INFO ] main org.pytorch.serve.ModelServer - Metrics API bind to: http://127.0.0.1:8082
Model server started.

### Installation instructions

The full file to build the MAR archives

```
FROM pytorch/pytorch:latest

USER root

RUN apt-get update && apt-get install -y curl

RUN mkdir -p model-weights/ \
    && curl -o model-weights/sam_vit_h_4b8939.pth https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth

RUN mkdir -p model-weights/ \
    && curl -o model-weights/sam_vit_h_4b8939.pth https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth

RUN apt-get install -y git

RUN pip install "onnxruntime==1.14.1" "onnx==1.13.1" "git+https://github.com/facebookresearch/segment-anything.git#567662b" torch-model-archiver awscli

COPY handler*.py ./

COPY src/sam_serve/ ./sam_serve/

COPY requirements.txt ./requirements.txt

# Zip up the sam_serve module
RUN tar czf sam_serve.tar.gz -C sam_serve .

RUN torch-model-archiver --model-name sam_vit_h_encode --version 1.0.0 --serialized-file model-weights/sam_vit_h_4b8939.pth --handler handler_encode.py --extra-files sam_serve.tar.gz --requirements-file requirements.txt

COPY scripts ./scripts

RUN python scripts/export_onnx_model.py --checkpoint model-weights/sam_vit_h_4b8939.pth --model-type vit_h --output sam_vit_h_decode.onnx

RUN torch-model-archiver --model-name sam_vit_h_decode --version 1.0.0 --serialized-file sam_vit_h_decode.onnx --handler handler_decode.py --extra-files sam_serve.tar.gz --requirements-file requirements.txt

RUN mkdir -p /home/model-store \
    && mv *.mar /home/model-store/ \
    && rm *.onnx \
    && rm -rf model-weights
```

and to serve 

```
FROM pytorch/torchserve:latest-gpu

USER root

RUN apt update \
    && apt install -y unzip git curl \
    && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && ./aws/install

RUN pip install "onnxruntime==1.14.1" "onnx==1.13.1" "git+https://github.com/facebookresearch/segment-anything.git"

COPY ./deployment/config_encode.properties /home/model-server/config.properties
COPY ./deployment/append_memory_setting.sh /home/model-server/append_memory_setting.sh
RUN chmod +x /home/model-server/append_memory_setting.sh \
    && /home/model-server/append_memory_setting.sh

COPY start ./

WORKDIR /home/model-server
ENV TEMP=/home/model-server/volume/tmp
ENV ENABLE_TORCH_PROFILER=TRUE

CMD ./start

```

### Model Packaing

see the dockerfile for building above. I followed these instructions

https://github.com/pytorch/serve/blob/master/docs/configuration.md#allow-model-specific-custom-python-packages

### config.properties

inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
number_of_netty_threads=1
default_workers_per_model=1
job_queue_size=1000
model_store=/home/model-server/volume/model-store
load_models=all
vmargs=-Xmx8g
max_request_size=17797905
max_response_size=17797905
cors_allowed_origin=*
cors_allowed_methods=GET, POST, PUT, OPTIONS
cors_allowed_headers=X-Custom-Header,content-type,content-length,crossorigin
install_py_dep_per_model=true

### Versions

I'm using torchserve latest gpu via docker

### Repro instructions

to be filled in if needed!

### Possible Solution

I'm not sure if I'm formatting the archive wrong? I've tried to wrap my python module in another directory but that failed with the same error

```
COPY src/ ./src/

COPY requirements.txt ./requirements.txt

# Zip up the sam_serve module
RUN tar czf sam_serve.tar.gz -C src .

RUN torch-model-archiver --model-name sam_vit_h_encode --version 1.0.0 --serialized-file model-weights/sam_vit_h_4b8939.pth --handler handler_encode.py --extra-files sam_serve.tar.gz --requirements-file requirements.txt
```

**Comment by msaroufim** [comment]
What does your requirements.txt look like? You can have individual entries that are paths to wheels of the the package you'd like to install

**Comment by rbavery** [comment]
It's just the name of the package, `sam_serve`. But great tip I will use a wheel file and point to that absolute path in the requirements.txt

**Comment by lxning** [comment]
@rbavery "--extra-files sam_serve.tar.gz" means you need uncompress in the handler. I suggest you use this way:

1. torch-model-archiver --model-name sam_vit_h_encode --version 1.0.0 --serialized-file model-weights/sam_vit_h_4b8939.pth --handler handler_encode.py  --requirements-file requirements.txt --archive-format no-archive
2. mv src/sam_serve/  sam_vit_h_encode/sam_serve/
