### ISSUE TITLE
Backend process failed 

### ISSUE THREAD

**Issue by naveenjr** [pytorch/serve#2770]
### 🐛 Describe the bug

Command i have used to create model file 
`torch-model-archiver --model-name yolo_tiny --version 1.0 --model-file model.pth --handler handler.py   

torchserve --start --model-store model_store --models yolo_tiny.mar --no-config-snapshot`
  this is my handler.py

`from ts.torch_handler.base_handler import BaseHandler
from transformers import YolosImageProcessor, YolosForObjectDetection
from PIL import Image
import torch
import requests
print("Transformers version %s", transformers.__version__)
class YolosHandler(BaseHandler):
    def __init__(self):
        super().__init__()
        self.initialized = False
        self.model = None
        self.processor = None

    def initialize(self, context):
        """Initialize model and processor"""
        properties = context.system_properties
        model_dir = properties.get("model_dir")

        # Initialize the model and processor
        self.model = YolosForObjectDetection.from_pretrained(model_dir)
        self.processor = YolosImageProcessor.from_pretrained(model_dir)

    def preprocess(self, data):
        """Preprocess the input data"""
        # Assuming the input is in the form of a JSON file with an image URL
        image_url = data[0].get("data") or data[0].get("body")
        if isinstance(image_url, (bytes, bytearray)):
            image_url = image_url.decode('utf-8')

        # Load the image from the URL
        image = Image.open(requests.get(image_url, stream=True).raw)
        
        # Process image
        inputs = self.processor(images=image, return_tensors="pt")
        return inputs

    def inference(self, inputs):
        """Run inference on the preprocessed data"""
        with torch.no_grad():
            outputs = self.model(**inputs)
        return outputs

    def postprocess(self, outputs):
        """Postprocess the inference output"""
        logits = outputs.logits
        bboxes = outputs.pred_boxes
        target_sizes = torch.tensor([outputs.input_sizes.tolist()])
        results = self.processor.post_process_object_detection(outputs, threshold=0.9, target_sizes=target_sizes)[0]

        response = []
        for score, label, box in zip(results["scores"], results["labels"], results["boxes"]):
            box = [round(i, 2) for i in box.tolist()]
            response.append(
                f"Detected {self.model.config.id2label[label.item()]} with confidence "
                f"{round(score.item(), 3)} at location {box}"
            )
        return response
`

### Error logs

2023-11-07T05:11:39,015 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG - Listening on port: /tmp/.ts.sock.9000
2023-11-07T05:11:39,021 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG - Successfully loaded /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/ts/configs/metrics.yaml.
2023-11-07T05:11:39,022 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG - [PID]19364
2023-11-07T05:11:39,023 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG - Torch worker started.
2023-11-07T05:11:39,023 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG - Python runtime: 3.10.11
2023-11-07T05:11:39,092 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG - Connection accepted: /tmp/.ts.sock.9000.
2023-11-07T05:11:39,159 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG - model_name: yolo_tiny, batchSize: 1
2023-11-07T05:11:40,049 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG - Backend worker process died.
2023-11-07T05:11:40,049 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG - Traceback (most recent call last):
2023-11-07T05:11:40,050 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -   File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/ts/model_service_worker.py", line 221, in <module>
2023-11-07T05:11:40,050 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -     worker.run_server()
2023-11-07T05:11:40,050 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -   File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/ts/model_service_worker.py", line 189, in run_server
2023-11-07T05:11:40,051 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -     self.handle_connection(cl_socket)
2023-11-07T05:11:40,052 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -   File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/ts/model_service_worker.py", line 154, in handle_connection
2023-11-07T05:11:40,052 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -     service, result, code = self.load_model(msg)
2023-11-07T05:11:40,052 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -   File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/ts/model_service_worker.py", line 118, in load_model
2023-11-07T05:11:40,055 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -     service = model_loader.load(
2023-11-07T05:11:40,055 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -   File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/ts/model_loader.py", line 135, in load
2023-11-07T05:11:40,056 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -     initialize_fn(service.context)
2023-11-07T05:11:40,056 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -   File "/tmp/models/002de4ebcfb34c45ac2fa3619db6b020/handler.py", line 20, in initialize
2023-11-07T05:11:40,056 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -     self.model = YolosForObjectDetection.from_pretrained(model_dir)
2023-11-07T05:11:40,056 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -   File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2662, in from_pretrained
2023-11-07T05:11:40,057 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -     config, model_kwargs = cls.config_class.from_pretrained(
2023-11-07T05:11:40,057 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -   File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/transformers/configuration_utils.py", line 591, in from_pretrained
2023-11-07T05:11:40,057 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -     config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
2023-11-07T05:11:40,058 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -   File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/transformers/configuration_utils.py", line 620, in get_config_dict
2023-11-07T05:11:40,058 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -     config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
2023-11-07T05:11:40,058 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -   File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/transformers/configuration_utils.py", line 675, in _get_config_dict
2023-11-07T05:11:40,059 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -     resolved_config_file = cached_file(
2023-11-07T05:11:40,059 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -   File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/transformers/utils/hub.py", line 400, in cached_file
2023-11-07T05:11:40,060 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -     raise EnvironmentError(
2023-11-07T05:11:40,060 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG - OSError: /tmp/models/002de4ebcfb34c45ac2fa3619db6b020 does not appear to have a file named config.json. Checkout 'https://huggingface.co//tmp/models/002de4ebcfb34c45ac2fa3619db6b020/main' for available files.
2023-11-07T05:11:42,589 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG - Listening on port: /tmp/.ts.sock.9000
2023-11-07T05:11:42,594 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG - Successfully loaded /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/ts/configs/metrics.yaml.
2023-11-07T05:11:42,595 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG - [PID]19725
2023-11-07T05:11:42,600 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG - Torch worker started.
2023-11-07T05:11:42,600 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG - Python runtime: 3.10.11
2023-11-07T05:11:42,604 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG - Connection accepted: /tmp/.ts.sock.9000.
2023-11-07T05:11:42,632 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG - model_name: yolo_tiny, batchSize: 1
2023-11-07T05:11:43,522 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG - Backend worker process died.
2023-11-07T05:11:43,523 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG - Traceback (most recent call last):
2023-11-07T05:11:43,524 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -   File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/ts/model_service_worker.py", line 221, in <module>
2023-11-07T05:11:43,524 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -     worker.run_server()
2023-11-07T05:11:43,525 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -   File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/ts/model_service_worker.py", line 189, in run_server
2023-11-07T05:11:43,526 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -     self.handle_connection(cl_socket)
2023-11-07T05:11:43,527 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -   File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/ts/model_service_worker.py", line 154, in handle_connection
2023-11-07T05:11:43,527 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -     service, result, code = self.load_model(msg)
2023-11-07T05:11:43,528 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -   File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/ts/model_service_worker.py", line 118, in load_model
2023-11-07T05:11:43,528 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -     service = model_loader.load(
2023-11-07T05:11:43,528 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -   File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/ts/model_loader.py", line 135, in load
2023-11-07T05:11:43,528 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -     initialize_fn(service.context)
2023-11-07T05:11:43,528 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -   File "/tmp/models/002de4ebcfb34c45ac2fa3619db6b020/handler.py", line 20, in initialize
2023-11-07T05:11:43,529 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -     self.model = YolosForObjectDetection.from_pretrained(model_dir)
2023-11-07T05:11:46,036 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG - Listening on port: /tmp/.ts.sock.9000
2023-11-07T05:11:46,041 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG - Successfully loaded /home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/ts/configs/metrics.yaml.
2023-11-07T05:11:46,041 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG - [PID]19733
2023-11-07T05:11:46,042 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG - Torch worker started.
2023-11-07T05:11:46,043 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG - Python runtime: 3.10.11
2023-11-07T05:11:46,051 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG - Connection accepted: /tmp/.ts.sock.9000.
2023-11-07T05:11:46,073 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG - model_name: yolo_tiny, batchSize: 1
2023-11-07T05:11:46,904 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG - Backend worker process died.
2023-11-07T05:11:46,905 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG - Traceback (most recent call last):
2023-11-07T05:11:46,905 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -   File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/ts/model_service_worker.py", line 221, in <module>
2023-11-07T05:11:46,905 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -     worker.run_server()
2023-11-07T05:11:46,906 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -   File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/ts/model_service_worker.py", line 189, in run_server
2023-11-07T05:11:46,906 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -     self.handle_connection(cl_socket)
2023-11-07T05:11:46,906 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -   File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/ts/model_service_worker.py", line 154, in handle_connection
2023-11-07T05:11:46,906 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -     service, result, code = self.load_model(msg)
2023-11-07T05:11:46,907 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -   File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/ts/model_service_worker.py", line 118, in load_model
2023-11-07T05:11:46,908 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -     service = model_loader.load(
2023-11-07T05:11:46,908 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG -   File "/home/ec

### Installation instructions

No

### Model Packaing

`torch-model-archiver --model-name yolo_tiny --version 1.0 --model-file model.pth --handler handler.py   

### config.properties

metrics_address=http://0.0.0.0:8082
job_queue_size=1000
model_store=/home/model-server/model-store
enable_envvars_config=true
install_py_dep_per_model=true

inference_address=http://127.0.0.1:8090
management_address=http://127.0.0.1:8091

### Versions

TorchServe Version is 0.7.1

### Repro instructions

NiL

**Comment by lxning** [comment]
@naveenjr The error "OSError: /tmp/models/002de4ebcfb34c45ac2fa3619db6b020 does not appear to have a file named config.json. Checkout 'https://huggingface.co//tmp/models/002de4ebcfb34c45ac2fa3619db6b020/main' for available files."

Please make sure if the model is completely downloaded from HF and stored in model artifacts.

**Comment by lxning** [comment]
@naveenjr The log shows "user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2864, in from_pretrained
2023-11-08T06:55:22,325 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG - raise EnvironmentError(
2023-11-08T06:55:22,326 [INFO ] W-9000-yolo_tiny_1.0-stdout MODEL_LOG - OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /tmp/models/e0675cae7c07449daa30bcd78ecd3a99."

it seems that you didn't provided all the model files in model artifacts.
