### ISSUE TITLE
Error register a new model when use '--requirements-file'

### ISSUE THREAD

**Issue by IonBoleac** [pytorch/serve#2810]
### 🐛 Describe the bug

# Describe
When i try to register a new `model.mar` file the system return an error and this is in log file
```log
2023-11-23T13:13:19,271 [WARN ] W-9000-logreg_2.0-stderr MODEL_LOG -     from ts.arg_parser import ArgParser
2023-11-23T13:13:19,272 [WARN ] W-9000-logreg_2.0-stderr MODEL_LOG - ModuleNotFoundError: No module named 'ts.arg_parser'
```
And this in terminal:
```bash
{
  "code": 500,
  "type": "InternalServerException",
  "message": "Failed to start workers for model logreg version: 2.0"
}
```
I create the archiver via:
```bash
torch-model-archiver --model-name logreg --version 2.0 --handler ./logreg/logreg_handler.py --model-file ./logreg/logreg_model.py --serialized-file ./logreg/logreg_parameters.pt --export-path ./model_store/ -f --requirements-file ./logreg/logreg_requirements.txt
```
I supposed that the error is caused because i used the requirements-file and in the file `ts.arg_parser` is not defined `--requirements-file` option. Because when i register a `file.ma` without --requirements-file option work all thinks. But i'd like to deploy *torchserve* on *kubernetess* cluster and if any model use some packages that are not default installed in torchserve i must use `--requirements-file` option. 

### Error logs

In log file `ts_log.log` is written:
```log
2023-11-23T13:01:45,885 [DEBUG] W-9000-logreg_2.0 org.pytorch.serve.wlm.WorkerLifeCycle - Worker cmdline: [/home/ion/work/PyTorchServing/venv/bin/python3, /home/ion/work/PyTorchServing/venv/lib/python3.10/site-packages/ts/model_service_worker.py, --sock-type, unix, --sock-name, /tmp/.ts.sock.9000, --metrics-config, /home/ion/work/PyTorchServing/original_metrics_config.yml]
2023-11-23T13:01:45,885 [DEBUG] W-9000-logreg_2.0 org.pytorch.serve.wlm.WorkerLifeCycle - Worker cmdline: [/home/ion/work/PyTorchServing/venv/bin/python3, /home/ion/work/PyTorchServing/venv/lib/python3.10/site-packages/ts/model_service_worker.py, --sock-type, unix, --sock-name, /tmp/.ts.sock.9000, --metrics-config, /home/ion/work/PyTorchServing/original_metrics_config.yml]
2023-11-23T13:01:45,917 [WARN ] W-9000-logreg_2.0-stderr MODEL_LOG - Traceback (most recent call last):
2023-11-23T13:01:45,918 [WARN ] W-9000-logreg_2.0-stderr MODEL_LOG -   File "/home/ion/work/PyTorchServing/venv/lib/python3.10/site-packages/ts/model_service_worker.py", line 15, in <module>
2023-11-23T13:01:45,919 [WARN ] W-9000-logreg_2.0-stderr MODEL_LOG -     from ts.arg_parser import ArgParser
2023-11-23T13:01:45,919 [WARN ] W-9000-logreg_2.0-stderr MODEL_LOG - ModuleNotFoundError: No module named 'ts.arg_parser'
2023-11-23T13:01:45,926 [INFO ] W-9000-logreg_2.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-logreg_2.0-stderr
2023-11-23T13:01:45,926 [INFO ] W-9000-logreg_2.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-logreg_2.0-stdout
2023-11-23T13:01:45,926 [INFO ] W-9000-logreg_2.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-logreg_2.0-stderr
2023-11-23T13:01:45,926 [INFO ] W-9000-logreg_2.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-logreg_2.0-stdout
2023-11-23T13:01:45,927 [WARN ] W-9000-logreg_2.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-logreg_2.0-stderr
2023-11-23T13:01:45,927 [WARN ] W-9000-logreg_2.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-logreg_2.0-stderr
2023-11-23T13:01:45,927 [WARN ] W-9000-logreg_2.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-logreg_2.0-stdout
2023-11-23T13:01:45,927 [WARN ] W-9000-logreg_2.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-logreg_2.0-stdout
2023-11-23T13:01:45,927 [ERROR] W-9000-logreg_2.0 org.pytorch.serve.wlm.WorkerThread - Backend worker error
org.pytorch.serve.wlm.WorkerInitializationException: Backend stream closed.
	at org.pytorch.serve.wlm.WorkerLifeCycle.startWorker(WorkerLifeCycle.java:175) ~[model-server.jar:?]
	at org.pytorch.serve.wlm.WorkerThread.connect(WorkerThread.java:348) ~[model-server.jar:?]
	at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:191) [model-server.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
2023-11-23T13:01:45,927 [ERROR] W-9000-logreg_2.0 org.pytorch.serve.wlm.WorkerThread - Backend worker error
org.pytorch.serve.wlm.WorkerInitializationException: Backend stream closed.
	at org.pytorch.serve.wlm.WorkerLifeCycle.startWorker(WorkerLifeCycle.java:175) ~[model-server.jar:?]
	at org.pytorch.serve.wlm.WorkerThread.connect(WorkerThread.java:348) ~[model-server.jar:?]
	at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:191) [model-server.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
2023-11-23T13:01:45,942 [DEBUG] W-9000-logreg_2.0 org.pytorch.serve.wlm.ModelVersionedRefs - Removed model: logreg version: 2.0
2023-11-23T13:01:45,942 [DEBUG] W-9000-logreg_2.0 org.pytorch.serve.wlm.ModelVersionedRefs - Removed model: logreg version: 2.0
2023-11-23T13:01:45,943 [DEBUG] W-9000-logreg_2.0 org.pytorch.serve.wlm.WorkerThread - W-9000-logreg_2.0 State change null -> WORKER_SCALED_DOWN
2023-11-23T13:01:45,943 [DEBUG] W-9000-logreg_2.0 org.pytorch.serve.wlm.WorkerThread - W-9000-logreg_2.0 State change null -> WORKER_SCALED_DOWN
2023-11-23T13:01:45,943 [WARN ] W-9000-logreg_2.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-logreg_2.0-stderr
2023-11-23T13:01:45,943 [WARN ] W-9000-logreg_2.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-logreg_2.0-stderr
2023-11-23T13:01:45,943 [WARN ] W-9000-logreg_2.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-logreg_2.0-stdout
2023-11-23T13:01:45,943 [WARN ] W-9000-logreg_2.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-logreg_2.0-stdout
2023-11-23T13:01:46,106 [INFO ] W-9000-logreg_2.0 org.pytorch.serve.wlm.ModelManager - Model logreg unregistered.
2023-11-23T13:01:46,106 [INFO ] W-9000-logreg_2.0 org.pytorch.serve.wlm.ModelManager - Model logreg unregistered.
```

And in the terminal:
```bash
{
  "code": 500,
  "type": "InternalServerException",
  "message": "Failed to start workers for model logreg version: 2.0"
}
```

### Installation instructions

I use torchserve on localhost. 

## How i create archiver
```bash
torch-model-archiver --model-name logreg --version 2.0 --handler ./logreg_handler.py --model-file ./logreg_model.py --serialized-file ./logreg_parameters.pt --export-path ../model_store/ -f --requirements-file ./logreg_requirements.txt
```
- In the file logreg_requirements.txt there is written three packages that i need 
```properties
pandas
numpy
ts
```
- logreg_handler.py: 
```python
from ts.torch_handler.base_handler import BaseHandler
import logging, base64, io
from io import StringIO
import pandas as pd
from io import StringIO
import numpy as np
from torch.autograd import Variable
import torch

logger = logging.getLogger(__name__)


class LogReg(BaseHandler):
    
    def __init__(self):
        super(LogReg, self).__init__()
        self.initialized = False
        self.manifest = None
        self.model = None
        self.device = None

    def preprocess(self, data):

        '''raw_data = []
        for row in data:
            logger.warning(f"preprocess row: {row}")
            # Compat layer: normally the envelope should just return the data
            # directly, but older versions of Torchserve didn't have envelope.
            row_line = row.get("data") or row.get("body")
            if isinstance(row_line, str):
                # 
                line = StringIO(row_line)
                pd.read_csv(line, index_col='id')

            # If the data is sent as bytesarray
            if isinstance(row_line, (bytearray, bytes)):
                line = row_line.decode('utf-8')
                pd_data = pd.read_csv(StringIO(line), sep=",", index_col='id')
                np_array = np.array(pd_data)
                variable_data = Variable(torch.FloatTensor(np_array), requires_grad=True)
                
            else:
                # if the data is a list
                #line = torch.FloatTensor(row)
                pass
            logger.warning(f"preprocess line: {type(line)}, {line}")
            
            raw_data.append(line)
        
        return line'''
        for raw in data:
            logger.warning(f"preprocess raw: {raw}")
            raw = raw.get("body") or raw.get("data")
            if (isinstance(raw, (bytearray, bytes))):
                line = raw.decode('utf-8')
                pd_data = pd.read_csv(StringIO(line), sep=",", index_col='id')
                np_array = np.array(pd_data)
                variable_data = Variable(torch.FloatTensor(np_array), requires_grad=True)
                torch_data = torch.FloatTensor(np_array)
                return variable_data
            if (isinstance(raw, str)):
                line = StringIO(raw)
                pd_data = pd.read_csv(line, sep=",", index_col='id')
                np_array = np.array(pd_data)
                variable_data = Variable(torch.FloatTensor(np_array), requires_grad=True)
                torch_data = torch.FloatTensor(np_array)
                return variable_data
        '''logger.warning(f"preprocess data: {data}, type {type(data)}")
        raw = data[0].get("body") or data[0].get("data")
        logger.warning(f"preprocess raw: {raw}, type {type(raw)}")
        line = raw.decode('utf-8')
        pd_data = pd.read_csv(StringIO(line), sep=",", index_col='id')
        np_array = np.array(pd_data)
        variable_data = Variable(torch.FloatTensor(np_array), requires_grad=True)
        torch_data = torch.FloatTensor(np_array)
        return variable_data'''
    
    def inference(self, data, *args, **kwargs):
        """
        The Inference Function is used to make a prediction call on the given input request.
        The user needs to override the inference function to customize it.

        Args:
            data (Torch Tensor): A Torch Tensor is passed to make the Inference Request.
            The shape should match the model input shape.

        Returns:
            Torch Tensor : The Predicted Torch Tensor is returned in this function.
        """
        
        with torch.no_grad():
            results = []
            for one in data:
                logger.warning(f"inference one: {one}")
                marshalled_data = one.to(self.device)
                result = self.model(marshalled_data, *args, **kwargs)
                results.append(result)
        
        results = torch.stack(results)
        logger.warning(f"inference results: {results}")
        return results
    
    def postprocess(self, data):
        '''
        Args: 
            data (tensor): Data to be passed to postprocess function and converti it to list of dictionary.
        Returns:
            list: a list of a dictionary containing the prediction. Return must be a list big one that contains a dictionary or all tensors.
        '''
        logger.warning(f"postprocess data: {data}")
        re_results = []
        re_results.append({"predictions": data.tolist()})
        return re_results
    
    


# torch-model-archiver --model-name logreg --version 2.0 --handler ./logreg/logreg_handler.py --model-file ./logreg/logreg_model.py --serialized-file ./logreg/logreg_parameters.pt --export-path ./model_store/ -f --requirements-file ./logreg/logreg_requirements.txt
# curl -X POST "http://localhost:8081/models?model_name=logreg&url=logreg.mar&batch_size=1&max_batch_delay=5000&initial_workers=1&synchronous=true"
# curl -X POST "http://localhost:8080/predictions/logreg" -T ./head1.csv
# curl -X POST -H "Content-Type: text/csv" --data-binary test_csv http://localhost:8080/predictions/logreg
# curl http://localhost:8080/predictions/logreg --data-binary @head1.csv -H 'Content-type:text/plain; charset=utf-8'
```
- model.py:
```python
import torch.nn as nn
import torch.nn.functional as F

class LogisticRegression(nn.Module):
    def __init__(self):
        super(LogisticRegression,self).__init__()
        self.f1 = nn.Linear(100, 1000)
        self.f2 = nn.Linear(1000, 2)

    def forward(self,x):
        x = self.f1(x)
        x = F.leaky_relu(x)
        x = F.dropout(x, p = 0.2)
        x = self.f2(x)
        return  F.sigmoid(x)
 ```
- logreg_parameters.pt: there are yhe state_dict of the model saved with the code line
```python
torch.save(the_model.state_dict(), PATH)
```  
    

### config.properties

enable_envvars_config=true 
model_store=$$PWD$$/model_store
metrics_mode=log
metrics_config=$$PWD$$/original_metrics_config.yml
install_py_dep_per_model=true

### Versions

I use the latest version of torchserve

### Repro instructions

```python
torchserve --start --ncs --model-store model_store/

torch-model-archiver --model-name logreg --version 2.0 --handler ./logreg/logreg_handler.py --model-file ./logreg/logreg_model.py --serialized-file ./logreg/logreg_parameters.pt --export-path ./model_store/ -f --requirements-file ./logreg/logreg_requirements.txt

curl -X POST "http://localhost:8081/models?model_name=logreg&url=logreg.mar&batch_size=1&max_batch_delay=5000&initial_workers=1&synchronous=true"
```

**Comment by IonBoleac** [comment]
I ingenuously add ts in requirements.txt
