### ISSUE TITLE
StreamPredictions2 gPRC method produces an 

### ISSUE THREAD

**Issue by ferugit** [pytorch/serve#2813]
### 🐛 Describe the bug

Hello, I am trying to use the StreamPredictions2 gPRC method but the model-server produces an internal error when executing it.

I successfully served a model, I tested it with API REST and some of the gRPC methods and works fine. The problem comes when using the StreamPredictions2 method.

### Error logs

The error `produced in the model server is shown next:

```bash
2023-11-30T15:23:02,946 [ERROR] grpc-default-executor-0 org.pytorch.serve.wlm.Model - Skip the requestId: 582e6816-b77f-438c-8b17-a1bdda126a89 for sequence: XXXXXXXX due to exception

java.lang.NullPointerException: Cannot invoke "java.util.concurrent.locks.ReentrantLock.lockInterruptibly()" because "this.jobGroupLock" is null
        at org.pytorch.serve.wlm.Model.addJobInGroup(Model.java:277) [model-server.jar:?]
        at org.pytorch.serve.wlm.Model.addJob(Model.java:270) [model-server.jar:?]
        at org.pytorch.serve.wlm.ModelManager.addJob(ModelManager.java:570) [model-server.jar:?]
        at org.pytorch.serve.grpcimpl.InferenceImpl.prediction(InferenceImpl.java:243) [model-server.jar:?]
        at org.pytorch.serve.grpcimpl.InferenceImpl.access$100(InferenceImpl.java:40) [model-server.jar:?]
        at org.pytorch.serve.grpcimpl.InferenceImpl$1.onNext(InferenceImpl.java:117) [model-server.jar:?]
        at org.pytorch.serve.grpcimpl.InferenceImpl$1.onNext(InferenceImpl.java:100) [model-server.jar:?]
        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:262) [model-server.jar:?]
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:333) [model-server.jar:?]
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:316) [model-server.jar:?]
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:835) [model-server.jar:?]
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [model-server.jar:?]
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) [model-server.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

In the client-side, the produced error has to do with an internal error:
```bash
_handle_response exception: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = ""
        debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"", grpc_status:2, created_time:"2023-11-30T16:23:02.960985226+01:00"}"
>
```

### Installation instructions

I am using the nightly docker build:
```bash 
./build_image.sh -n
``` 

### Model Packaing

I am using a custom model that I cannot share, but the problem is not the handler, model or the generated .mar file. I previously tested it with API REST.

### config.properties

```bash
inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
metrics_address=http://0.0.0.0:8082
number_of_netty_threads=32
job_queue_size=1000
model_store=/home/model-server/model-store
workflow_store=/home/model-server/wf-store
disable_system_metrics=true
```

### Versions

Output:

```bash
------------------------------------------------------------------------------------------
Environment headers
------------------------------------------------------------------------------------------
Torchserve branch: 

torchserve==0.9.0b20231124
torch-model-archiver==0.9.0

Python version: 3.10 (64-bit runtime)
Python executable: serve/.venv/bin/python

Versions of relevant python libraries:
numpy==1.24.3
psutil==5.9.6
requests==2.31.0
torch==2.1.0+cpu
torch-model-archiver==0.9.0
torch-workflow-archiver==0.2.11
torchaudio==2.1.0+cpu
torchdata==0.7.0
torchserve==0.9.0b20231124
torchtext==0.16.0+cpu
torchvision==0.16.0+cpu
wheel==0.40.0
torch==2.1.0+cpu
torchtext==0.16.0+cpu
torchvision==0.16.0+cpu
torchaudio==2.1.0+cpu

Java Version:


OS: Ubuntu 22.04.3 LTS
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: N/A
CMake version: version 3.22.1
```

### Repro instructions

```bash
python ts_scripts/torchserve_grpc_client.py infer_stream2 model_name "1234" file_1,file_2
```

When running another method, everything works fine:

```bash
python ts_scripts/torchserve_grpc_client.py infer model_name file_1
```

**Comment by ferugit** [comment]
Okay, that solved the problem. 

Using the default configuration to build the .mar leaves the `sequenceMaxIdleMSec=0`. To change this, we must use a model-config.yaml as the one you shared, by doing so we can change the default value of the parameter. Thank you!
