### ISSUE TITLE
Auto recovery failed when killing TorchServe worker processes

### ISSUE THREAD

**Issue by xzk-seu** [pytorch/serve#2870]
### 🐛 Describe the bug

I am using TorchServe to deploy the service, each model corresponds to multiple workers. when i manually kill the process of a worker, it tries to do auto recovery, but the recovery fails.

### Error logs
```
2023-12-25T00:22:56,740 [INFO ] KQueueEventLoopGroup-3-1 ACCESS_LOG - /127.0.0.1:57998 "GET /models/xuzk_model/1.0 HTTP/1.1" 200 1
2023-12-25T00:22:56,741 [INFO ] KQueueEventLoopGroup-3-1 TS_METRICS - Requests2XX.Count:1.0|#Level:Host|#hostname:ZhongkaideMacBook-Pro.local,timestamp:1703434976
2023-12-25T00:23:06,000 [INFO ] W-9007-xuzk_model_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9007-xuzk_model_1.0-stdout
2023-12-25T00:23:06,000 [INFO ] W-9007-xuzk_model_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9007-xuzk_model_1.0-stderr
2023-12-25T00:23:06,001 [INFO ] KQueueEventLoopGroup-5-3 org.pytorch.serve.wlm.WorkerThread - 9007 Worker disconnected. WORKER_MODEL_LOADED
2023-12-25T00:23:06,002 [DEBUG] W-9007-xuzk_model_1.0 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_MODEL_LOADED
2023-12-25T00:23:06,002 [DEBUG] W-9007-xuzk_model_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException: null
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireInterruptibly(AbstractQueuedSynchronizer.java:944) ~[?:?]
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1263) ~[?:?]
        at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:317) ~[?:?]
        at org.pytorch.serve.wlm.Model.pollBatch(Model.java:363) ~[model-server.jar:?]
        at org.pytorch.serve.wlm.BatchAggregator.getRequest(BatchAggregator.java:36) ~[model-server.jar:?]
        at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:194) [model-server.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2023-12-25T00:23:06,026 [DEBUG] W-9007-xuzk_model_1.0 org.pytorch.serve.wlm.WorkerThread - W-9007-xuzk_model_1.0 State change WORKER_MODEL_LOADED -> WORKER_STOPPED
2023-12-25T00:23:06,026 [INFO ] W-9007-xuzk_model_1.0 org.pytorch.serve.wlm.WorkerThread - Auto recovery start timestamp: 1703434986026
2023-12-25T00:23:06,027 [WARN ] W-9007-xuzk_model_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9007-xuzk_model_1.0-stderr
2023-12-25T00:23:06,027 [WARN ] W-9007-xuzk_model_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9007-xuzk_model_1.0-stdout
2023-12-25T00:23:06,028 [INFO ] W-9007-xuzk_model_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9007 in 1 seconds.
2023-12-25T00:23:07,032 [DEBUG] W-9007-xuzk_model_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - Worker cmdline: [/Users/zhongkai/opt/anaconda3/envs/nreccv/bin/python, /Users/zhongkai/opt/anaconda3/envs/nreccv/lib/python3.8/site-packages/ts/model_service_worker.py, --sock-type, unix, --sock-name, /var/folders/zb/7k2lc0lx4q1g7ww2vnt031yr0000gn/T//.ts.sock.9007, --metrics-config, /Users/zhongkai/opt/anaconda3/envs/nreccv/lib/python3.8/site-packages/ts/configs/metrics.yaml]
2023-12-25T00:23:10,301 [INFO ] W-9007-xuzk_model_1.0-stdout MODEL_LOG - s_name_part0=/var/folders/zb/7k2lc0lx4q1g7ww2vnt031yr0000gn/T//.ts.sock, s_name_part1=9007, pid=76373
2023-12-25T00:23:10,303 [INFO ] W-9007-xuzk_model_1.0-stdout MODEL_LOG - Listening on port: /var/folders/zb/7k2lc0lx4q1g7ww2vnt031yr0000gn/T//.ts.sock.9007
2023-12-25T00:23:10,369 [INFO ] W-9007-xuzk_model_1.0-stdout MODEL_LOG - Successfully loaded /Users/zhongkai/opt/anaconda3/envs/nreccv/lib/python3.8/site-packages/ts/configs/metrics.yaml.
2023-12-25T00:23:10,370 [INFO ] W-9007-xuzk_model_1.0-stdout MODEL_LOG - [PID]76373
2023-12-25T00:23:10,370 [INFO ] W-9007-xuzk_model_1.0-stdout MODEL_LOG - Torch worker started.
2023-12-25T00:23:10,370 [INFO ] W-9007-xuzk_model_1.0-stdout MODEL_LOG - Python runtime: 3.8.0
2023-12-25T00:23:10,370 [DEBUG] W-9007-xuzk_model_1.0 org.pytorch.serve.wlm.WorkerThread - W-9007-xuzk_model_1.0 State change WORKER_STOPPED -> WORKER_STARTED
2023-12-25T00:23:10,370 [INFO ] W-9007-xuzk_model_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /var/folders/zb/7k2lc0lx4q1g7ww2vnt031yr0000gn/T//.ts.sock.9007
2023-12-25T00:23:10,372 [INFO ] KQueueEventLoopGroup-5-3 org.pytorch.serve.wlm.WorkerThread - 9007 Worker disconnected. WORKER_STARTED
2023-12-25T00:23:10,372 [INFO ] W-9007-xuzk_model_1.0-stdout MODEL_LOG - Connection accepted: /var/folders/zb/7k2lc0lx4q1g7ww2vnt031yr0000gn/T//.ts.sock.9007.
2023-12-25T00:23:10,372 [DEBUG] W-9007-xuzk_model_1.0 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_STARTED
2023-12-25T00:23:10,372 [DEBUG] W-9007-xuzk_model_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException: null
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireInterruptibly(AbstractQueuedSynchronizer.java:944) ~[?:?]
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1263) ~[?:?]
        at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:317) ~[?:?]
        at org.pytorch.serve.wlm.Model.pollBatch(Model.java:363) ~[model-server.jar:?]
        at org.pytorch.serve.wlm.BatchAggregator.getRequest(BatchAggregator.java:36) ~[model-server.jar:?]
        at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:194) [model-server.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2023-12-25T00:23:10,373 [DEBUG] W-9007-xuzk_model_1.0 org.pytorch.serve.wlm.WorkerThread - W-9007-xuzk_model_1.0 State change WORKER_STARTED -> WORKER_STOPPED
2023-12-25T00:23:10,373 [WARN ] W-9007-xuzk_model_1.0 org.pytorch.serve.wlm.WorkerThread - Auto recovery failed again
2023-12-25T00:23:10,374 [WARN ] W-9007-xuzk_model_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9007-xuzk_model_1.0-stderr
2023-12-25T00:23:10,374 [INFO ] W-9007-xuzk_model_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9007-xuzk_model_1.0-stdout
2023-12-25T00:23:10,374 [WARN ] W-9007-xuzk_model_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9007-xuzk_model_1.0-stdout
2023-12-25T00:23:10,374 [INFO ] W-9007-xuzk_model_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9007-xuzk_model_1.0-stderr
2023-12-25T00:23:10,374 [INFO ] W-9007-xuzk_model_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9007 in 1 seconds.
2023-12-25T00:23:11,377 [DEBUG] W-9007-xuzk_model_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - Worker cmdline: [/Users/zhongkai/opt/anaconda3/envs/nreccv/bin/python, /Users/zhongkai/opt/anaconda3/envs/nreccv/lib/python3.8/site-packages/ts/model_service_worker.py, --sock-type, unix, --sock-name, /var/folders/zb/7k2lc0lx4q1g7ww2vnt031yr0000gn/T//.ts.sock.9007, --metrics-config, /Users/zhongkai/opt/anaconda3/envs/nreccv/lib/python3.8/site-packages/ts/configs/metrics.yaml]
2023-12-25T00:23:13,717 [INFO ] W-9007-xuzk_model_1.0-stdout MODEL_LOG - s_name_part0=/var/folders/zb/7k2lc0lx4q1g7ww2vnt031yr0000gn/T//.ts.sock, s_name_part1=9007, pid=76375
2023-12-25T00:23:13,718 [INFO ] W-9007-xuzk_model_1.0-stdout MODEL_LOG - Listening on port: /var/folders/zb/7k2lc0lx4q1g7ww2vnt031yr0000gn/T//.ts.sock.9007
2023-12-25T00:23:13,779 [INFO ] W-9007-xuzk_model_1.0-stdout MODEL_LOG - Successfully loaded /Users/zhongkai/opt/anaconda3/envs/nreccv/lib/python3.8/site-packages/ts/configs/metrics.yaml.
2023-12-25T00:23:13,779 [INFO ] W-9007-xuzk_model_1.0-stdout MODEL_LOG - [PID]76375
2023-12-25T00:23:13,780 [INFO ] W-9007-xuzk_model_1.0-stdout MODEL_LOG - Torch worker started.
2023-12-25T00:23:13,780 [DEBUG] W-9007-xuzk_model_1.0 org.pytorch.serve.wlm.WorkerThread - W-9007-xuzk_model_1.0 State change WORKER_STOPPED -> WORKER_STARTED
2023-12-25T00:23:13,780 [INFO ] W-9007-xuzk_model_1.0-stdout MODEL_LOG - Python runtime: 3.8.0
2023-12-25T00:23:13,780 [INFO ] W-9007-xuzk_model_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /var/folders/zb/7k2lc0lx4q1g7ww2vnt031yr0000gn/T//.ts.sock.9007
2023-12-25T00:23:13,782 [INFO ] KQueueEventLoopGroup-5-3 org.pytorch.serve.wlm.WorkerThread - 9007 Worker disconnected. WORKER_STARTED
2023-12-25T00:23:13,782 [INFO ] W-9007-xuzk_model_1.0-stdout MODEL_LOG - Connection accepted: /var/folders/zb/7k2lc0lx4q1g7ww2vnt031yr0000gn/T//.ts.sock.9007.
2023-12-25T00:23:13,782 [DEBUG] W-9007-xuzk_model_1.0 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_STARTED
2023-12-25T00:23:13,783 [DEBUG] W-9007-xuzk_model_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException: null
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireInterruptibly(AbstractQueuedSynchronizer.java:944) ~[?:?]
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1263) ~[?:?]
        at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:317) ~[?:?]
        at org.pytorch.serve.wlm.Model.pollBatch(Model.java:363) ~[model-server.jar:?]
        at org.pytorch.serve.wlm.BatchAggregator.getRequest(BatchAggregator.java:36) ~[model-server.jar:?]
        at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:194) [model-server.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
2023-12-25T00:23:13,783 [DEBUG] W-9007-xuzk_model_1.0 org.pytorch.serve.wlm.WorkerThread - W-9007-xuzk_model_1.0 State change WORKER_STARTED -> WORKER_STOPPED
2023-12-25T00:23:13,784 [WARN ] W-9007-xuzk_model_1.0 org.pytorch.serve.wlm.WorkerThread - Auto recovery failed again
2023-12-25T00:23:13,784 [INFO ] W-9007-xuzk_model_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9007-xuzk_model_1.0-stdout
2023-12-25T00:23:13,785 [WARN ] W-9007-xuzk_model_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9007-xuzk_model_1.0-stderr
2023-12-25T00:23:13,785 [WARN ] W-9007-xuzk_model_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9007-xuzk_model_1.0-stdout
2023-12-25T00:23:13,785 [INFO ] W-9007-xuzk_model_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9007 in 2 seconds.
```

### Installation instructions

Did you install torchserve from source: No, from pip.
Are you using Docker: No.

### Model Packaing

torch-model-archiver --model-name xuzk_model --version 1.0 --handler handler/test_handler.py --export-path model_store --serialized-file handler/add_model.txt --model-file handler/add_model.txt --extra-files handler/

### Versions

Environment headers
------------------------------------------------------------------------------------------
Torchserve branch: 

torchserve==0.9.0
torch-model-archiver==0.9.0

Python version: 3.8 (64-bit runtime)
Python executable: /Users/zhongkai/opt/anaconda3/envs/nreccv/bin/python

Versions of relevant python libraries:
captum==0.6.0
numpy==1.23.4
psutil==5.9.4
requests==2.31.0
requests-oauthlib==1.3.1
torch==2.1.0
torch-model-archiver==0.9.0
torch-workflow-archiver==0.2.11
torchaudio==2.1.0
torchdata==0.7.0
torchserve==0.9.0
torchtext==0.16.0
torchvision==0.16.0
wheel==0.40.0
torch==2.1.0
torchtext==0.16.0
torchvision==0.16.0
torchaudio==2.1.0

Java Version:

OS: Mac OSX 14.1.2 (x86_64)
GCC version: N/A
Clang version: 11.0.0 (clang-1100.0.33.12)
CMake version: N/A

Versions of npm installed packages:
**Warning: newman, newman-reporter-html markdown-link-check not installed...

### Repro instructions

**Reproduction Steps:** 
1. Deploy a TorchServe service with multiple workers per model. 
3. Kill a worker's process by `kill -9 <pid>`.

**Expected Behavior:** I expect TorchServe to succeed in Auto recovery, not fail.

**Actual Behavior:** Auto recovery fails and I see the above warning log.

**Comment by lxning** [comment]
@xzk-seu there was a bug [fixing](https://github.com/pytorch/serve/pull/2746) for auto-recovery. Please try it on the master branch.

**Comment by xzk-seu** [comment]
> @xzk-seu there was a bug [fixing](https://github.com/pytorch/serve/pull/2746) for auto-recovery. Please try it on the master branch.

@lxning Thank you for the prompt response! 
I have tested it on the master branch, and I can confirm that the bug has been fixed on it. 
Auto-recovery is now working as expected.
