### ISSUE TITLE
Invalid Port while running inside a PaaS

### ISSUE THREAD

**Issue by prabhuomkar** [pytorch/serve#291]
[HERE](https://github.com/pytorch/serve/blob/1f16a7e5989e046f0e5ce5a9f4c73182f63c4573/frontend/server/src/main/java/org/pytorch/serve/util/Connector.java#L108) there is a validation for port being less than or equal to `Short.MAX_VALUE`

**Possible Fix**:
Change the validation to `PORT <= 2*Short.MAX_VALUE + 1`  i.e. 65535 being the upper limit for PORT.

**Failure with PORT = 42523**
```
2020-05-01T02:36:00.546027+00:00 app[web.1]: 2020-05-01 02:36:00,545 [INFO ] main org.pytorch.serve.ModelServer - Torchserve stopped.
2020-05-01T02:36:00.546355+00:00 app[web.1]: Invalid configuration: Invalid port number: http://0.0.0.0:42523
2020-05-01T02:36:00.558874+00:00 app[web.1]: Exception in thread "Thread-0" java.lang.NullPointerException
2020-05-01T02:36:00.559051+00:00 app[web.1]: 	at org.pytorch.serve.ModelServer.stop(ModelServer.java:374)
2020-05-01T02:36:00.559131+00:00 app[web.1]: 	at org.pytorch.serve.ModelServer$1.run(ModelServer.java:79)
```

**Success with PORT = 18229**
```
2020-05-01T02:36:34.820448+00:00 app[web.1]: 2020-05-01 02:36:34,819 [INFO ] main org.pytorch.serve.ModelServer - 
2020-05-01T02:36:34.820471+00:00 app[web.1]: TS Home: /usr/local/lib/python3.6/dist-packages
2020-05-01T02:36:34.820471+00:00 app[web.1]: Current directory: /home/model-server
2020-05-01T02:36:34.820472+00:00 app[web.1]: Temp directory: /home/model-server/tmp
2020-05-01T02:36:34.820472+00:00 app[web.1]: Number of GPUs: 0
2020-05-01T02:36:34.820472+00:00 app[web.1]: Number of CPUs: 8
2020-05-01T02:36:34.820472+00:00 app[web.1]: Max heap size: 15362 M
2020-05-01T02:36:34.820473+00:00 app[web.1]: Python executable: /usr/bin/python3
2020-05-01T02:36:34.820473+00:00 app[web.1]: Config file: /home/model-server/config.properties
2020-05-01T02:36:34.820473+00:00 app[web.1]: Inference address: http://0.0.0.0:18229
2020-05-01T02:36:34.820473+00:00 app[web.1]: Management address: http://0.0.0.0:8081
2020-05-01T02:36:34.820474+00:00 app[web.1]: Model Store: /home/model-server/model-store
2020-05-01T02:36:34.820474+00:00 app[web.1]: Initial Models: all
2020-05-01T02:36:34.820474+00:00 app[web.1]: Log dir: /home/model-server/logs
2020-05-01T02:36:34.820474+00:00 app[web.1]: Metrics dir: /home/model-server/logs
2020-05-01T02:36:34.820474+00:00 app[web.1]: Netty threads: 4
2020-05-01T02:36:34.820474+00:00 app[web.1]: Netty client threads: 4
2020-05-01T02:36:34.820475+00:00 app[web.1]: Default workers per model: 1
2020-05-01T02:36:34.820475+00:00 app[web.1]: Blacklist Regex: N/A
2020-05-01T02:36:34.820475+00:00 app[web.1]: Maximum Response Size: 6553500
2020-05-01T02:36:34.820475+00:00 app[web.1]: Maximum Request Size: 6553500
```

**Comment by vdantu** [comment]
@prabhuomkar : Excellent catch.

**Comment by prabhuomkar** [comment]
@vdantu any timeline when this will be fixed? I'm working on something with TorchServe and want to release soon :)
