### ISSUE TITLE
Warning in regression test: test_install_dependencies_to_target_directory_with_requirements

### ISSUE THREAD

**Issue by agunapal** [pytorch/serve#2941]
### 🐛 Describe the bug

```  
  warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))
test/pytest/test_model_custom_dependencies.py::test_install_dependencies_to_target_directory_with_requirements
  /home/venv/lib/python3.9/site-packages/_pytest/threadexception.py:73: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-107
  
  Traceback (most recent call last):
    File "/usr/lib/python3.9/threading.py", line 980, in _bootstrap_inner
      self.run()
    File "/home/serve/test/pytest/test_utils.py", line 49, in run
      for line in self.reader:
    File "/usr/lib/python3.9/encodings/ascii.py", line 26, in decode
      return codecs.ascii_decode(input, self.errors)[0]
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1112: ordinal not in range(128)
  ```

### Error logs

```  
  warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))
test/pytest/test_model_custom_dependencies.py::test_install_dependencies_to_target_directory_with_requirements
  /home/venv/lib/python3.9/site-packages/_pytest/threadexception.py:73: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-107
  
  Traceback (most recent call last):
    File "/usr/lib/python3.9/threading.py", line 980, in _bootstrap_inner
      self.run()
    File "/home/serve/test/pytest/test_utils.py", line 49, in run
      for line in self.reader:
    File "/usr/lib/python3.9/encodings/ascii.py", line 26, in decode
      return codecs.ascii_decode(input, self.errors)[0]
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1112: ordinal not in range(128)
  ```

### Installation instructions

N/A

### Model Packaing

N/A

### Versions

nightly

### Repro instructions

Regression test

**Comment by namannandan** [comment]
Fixed in PR: https://github.com/pytorch/serve/pull/2946
