### ISSUE TITLE
StreamPredictions2 gPRC method execution produces a server error while changing from version *0.10.0* to *0.11.1*

### ISSUE THREAD

**Issue by ferugit** [pytorch/serve#3264]
### 🐛 Describe the bug

Hello, I am trying to use the StreamPredictions2 gPRC method but the model-server produces an internal error when executing it.

### Error logs

The error produced in the model server is shown next:
```java
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable@3f65050b
java.lang.NullPointerException: Cannot invoke "java.util.concurrent.ConcurrentMap.get(Object)" because "this.jobGroups" is null
        at org.pytorch.serve.wlm.Model.getJobGroup(Model.java:630)
        at org.pytorch.serve.grpcimpl.InferenceImpl.getJobGroup(InferenceImpl.java:294)
        at org.pytorch.serve.grpcimpl.InferenceImpl.access$300(InferenceImpl.java:40)
        at org.pytorch.serve.grpcimpl.InferenceImpl$1.onNext(InferenceImpl.java:127)
        at org.pytorch.serve.grpcimpl.InferenceImpl$1.onNext(InferenceImpl.java:101)
        at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:262)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:333)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:316)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:835)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

In the client side:
```python
InferStream2 started
_handle_response exception: <_MultiThreadedRendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = ""
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-07-23T14:51:03.046421523+02:00", grpc_status:2, grpc_message:""}"
```

### Installation instructions

I am building the nightly version of the docker container.
```bash
./build_image.sh -n
```

### Model Packaging

I am using a custom model I cannot share, but the problem is not the handler, model or the generated .mar file. Whit the previous version of TorchServe, *0.10.0* everything worked ok. 

### config.properties

```bash
# API REST settings
inference_address=https://127.0.0.1:8443
management_address=https://127.0.0.1:8444
metrics_address=https://127.0.0.1:8445

# Security settings
private_key_file="something"
certificate_file="something"
number_of_netty_threads=32
job_queue_size=1000
disable_system_metrics=false

# Model server settings
model_store=/home/model-server/model-store
workflow_store=/home/model-server/wf-store
min_workers=2
max_workers=8
default_workers_per_model=4
disable_token_authorization=true
enable_model_api=false
vmargs=-Xmx4g -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError

# gRPC settings
grpc_inference_address=0.0.0.0
grpc_management_address=0.0.0.0
enable_grpc_ssl=true
grpc_inference_port=7070
grpc_management_port=7071
```

### Versions

```bash
------------------------------------------------------------------------------------------
Environment headers
------------------------------------------------------------------------------------------
Torchserve branch: 

torchserve==0.11.1
torch-model-archiver==0.11.1

Python version: 3.10 (64-bit runtime)
Python executable: ~/Projects/serve/.venv/bin/python

Versions of relevant python libraries:
captum==0.6.0
numpy==1.24.3
nvgpu==0.10.0
pillow==10.2.0
psutil==5.9.5
requests==2.31.0
torch==2.2.1+cu121
torch-model-archiver==0.11.1
torchaudio==2.2.1+cu121
torchdata==0.7.1
torchserve==0.11.1
torchtext==0.17.1
torchvision==0.17.1+cu121
wheel==0.42.0
torch==2.2.1+cu121
torchtext==0.17.1
torchvision==0.17.1+cu121
torchaudio==2.2.1+cu121

Java Version:


OS: Ubuntu 22.04.4 LTS
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: N/A
CMake version: version 3.22.1

Is CUDA available: Yes
CUDA runtime version: 11.5.119
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3060 Laptop GPU
Nvidia driver version: 535.183.01
cuDNN version: None


Environment:
library_path (LD_/DYLD_): 
```

### Repro instructions

# Generate my .mar file with the following parms in the yaml

```yaml
minWorkers: 4
maxWorkers: 8
batchSize: 1
maxNumSequence: 10
sequenceMaxIdleMSec: 60000
maxSequenceJobQueueSize: 2


handler:
  cache:
    capacity: 8
```

**Comment by ferugit** [comment]
We need to add the following flag while building the *.mar* file. Otherwise, no jobs are created. 

```yaml
sequenceBatching: true
```
