### ISSUE TITLE
serve fails to process 'version number' after load resnest50 and aborts server with "java.lang.AssertionError: Model version not not found for model : resnest50"

### ISSUE THREAD

**Issue by lessw2020** [pytorch/serve#387]
I'm attempting to load a custom resnest model (SOTA - https://github.com/zhanghang1989/ResNeSt) which currently is not jit scriptable due to it's split attention internals.

Thus I am loading via eager mode - however, when attempting to load serve hits this error and then aborts:`2020-05-22 21:38:14,080 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Adding new version 22.0 for model resnest50
2020-05-22 21:38:14,080 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Setting default version to 22.0 for model resnest50
2020-05-22 21:38:14,080 [INFO ] main org.pytorch.serve.wlm.ModelManager - Model resnest50 loaded.
2020-05-22 21:38:16,294 [INFO ] main org.pytorch.serve.ModelServer - Torchserve stopped.
java.lang.AssertionError: Model version not not found for model : resnest50
        at org.pytorch.serve.wlm.ModelManager.updateModel(ModelManager.java:216)
        at org.pytorch.serve.snapshot.SnapshotManager.initModels(SnapshotManager.java:149)
        at org.pytorch.serve.snapshot.SnapshotManager.restore(SnapshotManager.java:120)
        at org.pytorch.serve.ModelServer.initModelStore(ModelServer.java:133)
        at org.pytorch.serve.ModelServer.start(ModelServer.java:303)
        at org.pytorch.serve.ModelServer.startAndWait(ModelServer.java:102)
        at org.pytorch.serve.ModelServer.main(ModelServer.java:83)'

I have built the .mar with a version flag.  
Can you advise any debugging tips on how to further resolve?

**Comment by lessw2020** [comment]
oddly, I started from a new directory and so it used the snapshot config at which point it was able to load the model and version?

2020-05-22 21:53:42,454 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Adding new version 22.242 for model resnest50
2020-05-22 21:53:42,454 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Setting default version to 22.242 for model resnest50
2020-05-22 21:53:42,454 [INFO ] main org.pytorch.serve.wlm.ModelManager - Model resnest50 loaded.
2020-05-22 21:53:42,454 [DEBUG] main org.pytorch.serve.wlm.ModelManager - updateModel: resnest50, count: 0
2020-05-22 21:53:42,454 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Setting default version to 22.242 for model resnest50
2020-05-22 21:53:42,456 [INFO ] main org.pytorch.serve.ModelServer - Initialize Inference server with: EpollServerSocketChannel.
2020-05-22

**Comment by lessw2020** [comment]
ok that load had 0 workers so I attempted to scale workers and that fails.
So likely the issue is model fails to scale a worker and that cascades into the version number assignment failing?

 curl -v -X PUT "http://localhost:8081/models/resnest50?min_workers=2&synchronous=true"
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8081 (#0)
> PUT /models/resnest50?min_workers=2&synchronous=true HTTP/1.1
> Host: localhost:8081
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< content-type: application/json
< x-request-id: 976d2954-6663-4795-bb54-c7745baf9a04
< Pragma: no-cache
< Cache-Control: no-cache; no-store, must-revalidate, private
< Expires: Thu, 01 Jan 1970 00:00:00 UTC
< content-length: 95
< connection: close
<
{
  "code": 500,
  "type": "InternalServerException",
  "message": "Failed to start workers"
}
* Closing connection 0

**Comment by maaquib** [comment]
@lessw2020 Can you attach the server logs for the above failure? I can take a look

**Comment by lessw2020** [comment]
Hi @maaquib  - I was able to get a fix for JIT export for resneST thanks to @rwightman and with that, things worked fine (running JIT version).
Thus I don't have the logs atm but I did review them earlier and didn't see anything interesting.  
One question - what is the working dir for the model running in eager mode inside Serve?  Wondering if that was the issue as it loads fine locally. 
B/c of the very different internal architecture of resneST, maybe it's better if I try to repro with a more standard EfficientNet model in eager mode?  
Anyway, I'm not blocked so other than info on what the working dir is when eager run, can go ahead and close this if you like or I can try with eager load on a different model to try and isolate if it's specific to neST split arch or not.

**Comment by rwightman** [comment]
@lessw2020 since I was mentioned. EfficientNets aren't standard issue in PT either. I'd debug with a Torchvision ResNet34 or 50 and go from there :)

**Comment by maaquib** [comment]
> One question - what is the working dir for the model running in eager mode inside Serve? Wondering if that was the issue as it loads fine locally.
> B/c of the very different internal architecture of resneST, maybe it's better if I try to repro with a more standard EfficientNet model in eager mode?
> Anyway, I'm not blocked so other than info on what the working dir is when eager run, can go ahead and close this if you like or I can try with eager load on a different model to try and isolate if it's specific to neST split arch or not.

@lessw2020 The working directory for the eager model should also be the same i.e. what you provide for param `--model-store MODEL_STORE`. Let me know if the behaviour you are seeing is inconsistent with this and feel free to reopen this issue.
