### ISSUE TITLE
Netty IndexOutOfBoundException

### ISSUE THREAD

**Issue by boscotsang** [pytorch/serve#455]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/pytorch/serve/issues) before creating one.

## Context

* torchserve version: build docker image from master branch 719add34dce99680ed3f9
* torch version: 1.5.0
* Operating System and version: Ubuntu 18.04

## Your Environment

* Installed using source? [yes/no]: yes
* Are you planning to deploy it using docker container? [yes/no]: yes
* Is it a CPU or GPU environment?: CPU
* Using a default/custom handler? [If possible upload/share custom handler/model]: Custom
* What kind of model is it e.g. vision, text, audio?:
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?

  [If public url then provide link.]:
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs:
* Link to your project [if any]:

## Expected Behavior

It should not be any exception.
## Current Behavior

Http resposne {
  "code": 500,
  "type": "InternalServerException",
  "message": "Worker died."
}
## Steps to Reproduce

Maybe with high throughput requests.

## Failure Logs [if any]

```
2020-06-12 09:17:50,695 [ERROR] epollEventLoopGroup-4-1 org.pytorch.serve.wlm.WorkerThread - Unknown exception
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(65534) + length(4) exceeds writerIndex(65536): PooledUnsafeDirectByteBuf(ridx: 65534, widx: 65536, cap: 65536)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
        at io.netty.channel.epoll.EpollDomainSocketChannel$EpollDomainUnsafe.epollInReady(EpollDomainSocketChannel.java:138)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(65534) + length(4) exceeds writerIndex(65536): PooledUnsafeDirectByteBuf(ridx: 65534, widx: 65536, cap: 65536)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1405)
        at io.netty.buffer.AbstractByteBuf.readInt(AbstractByteBuf.java:786)
        at org.pytorch.serve.util.codec.ModelResponseDecoder.decode(ModelResponseDecoder.java:56)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
        ... 15 more
```

**Comment by maaquib** [comment]
@boscotsang I am not able to reproduce this. Can you provide some more details for the reproduction steps?

**Comment by yangp725** [comment]
### Encountered the same problem when high concurrent requests

`io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(496) + length(4) exceeds writerIndex(496): PooledUnsafeDirectByteBuf(ridx: 496, widx: 496, cap: 496)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808)
        at io.netty.channel.epoll.EpollDomainSocketChannel$EpollDomainUnsafe.epollInReady(EpollDomainSocketChannel.java:138)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(496) + length(4) exceeds writerIndex(496): PooledUnsafeDirectByteBuf(ridx: 496, widx: 496, cap: 496)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1405)
        at io.netty.buffer.AbstractByteBuf.readInt(AbstractByteBuf.java:786)
        at org.pytorch.serve.util.codec.ModelResponseDecoder.decode(ModelResponseDecoder.java:56)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
        ... 15 more`

**Comment by harshbafna** [comment]
@yangp725 please share the following details :

* Operating System and version:
* CPU/GPU environment?
* Number of CPU cores/ GPUs:
* What kind of model is it e.g. vision, text, audio?
* Using a default/custom handler?
* In case of a custom model, model's mar file, and sample input
* Provide config.properties, logs [ts.log], and parameters used for model registration/update APIs:
* Bare minimum code/steps to reproduce the issues

**Comment by harshbafna** [comment]
Closing due to no response from OP.
