### ISSUE TITLE
About running torchserve

### ISSUE THREAD

**Issue by baopanda** [pytorch/serve#496]
Hi all, 
After running torch serve for a few times and I get an erorr, can you help me to fix this?

> Removing orphan pid file.
java.text.ParseException: Unparseable date: ".directory"
        at java.base/java.text.DateFormat.parse(DateFormat.java:395)
        at org.pytorch.serve.snapshot.FSSnapshotSerializer.getSnapshotTime(FSSnapshotSerializer.java:95)
        at org.pytorch.serve.snapshot.FSSnapshotSerializer.lambda$getLastSnapshotFS$1(FSSnapshotSerializer.java:79)
        at java.base/java.util.Comparator.lambda$comparingLong$6043328a$1(Comparator.java:511)
        at java.base/java.util.function.BinaryOperator.lambda$maxBy$1(BinaryOperator.java:74)
        at java.base/java.util.stream.ReduceOps$2ReducingSink.accept(ReduceOps.java:123)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:558)
        at java.base/java.util.stream.ReferencePipeline.max(ReferencePipeline.java:594)
        at org.pytorch.serve.snapshot.FSSnapshotSerializer.getLastSnapshotFS(FSSnapshotSerializer.java:77)
        at org.pytorch.serve.snapshot.SnapshotUtils.getLastSnapshot(SnapshotUtils.java:9)
        at org.pytorch.serve.util.ConfigManager.getLastSnapshot(ConfigManager.java:473)
        at org.pytorch.serve.util.ConfigManager.<init>(ConfigManager.java:130)
        at org.pytorch.serve.util.ConfigManager.init(ConfigManager.java:246)
        at org.pytorch.serve.ModelServer.main(ModelServer.java:70)
java.lang.NullPointerException
        at org.pytorch.serve.snapshot.FSSnapshotSerializer.getSnapshotTime(FSSnapshotSerializer.java:99)
        at org.pytorch.serve.snapshot.FSSnapshotSerializer.lambda$getLastSnapshotFS$1(FSSnapshotSerializer.java:79)
        at java.base/java.util.Comparator.lambda$comparingLong$6043328a$1(Comparator.java:511)
        at java.base/java.util.function.BinaryOperator.lambda$maxBy$1(BinaryOperator.java:74)
        at java.base/java.util.stream.ReduceOps$2ReducingSink.accept(ReduceOps.java:123)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:558)
        at java.base/java.util.stream.ReferencePipeline.max(ReferencePipeline.java:594)
        at org.pytorch.serve.snapshot.FSSnapshotSerializer.getLastSnapshotFS(FSSnapshotSerializer.java:77)
        at org.pytorch.serve.snapshot.SnapshotUtils.getLastSnapshot(SnapshotUtils.java:9)
        at org.pytorch.serve.util.ConfigManager.getLastSnapshot(ConfigManager.java:473)
        at org.pytorch.serve.util.ConfigManager.<init>(ConfigManager.java:130)
        at org.pytorch.serve.util.ConfigManager.init(ConfigManager.java:246)
        at org.pytorch.serve.ModelServer.main(ModelServer.java:70)

Thank you in advance

**Comment by harshbafna** [comment]
@baopanda : 

From the shared logs, `TorchServe` is starting with the last saved snapshot file. However, looks like the `config` directory inside the `logs` directory contains some invalid file named `.directory`.

Could you please share the output of `ls -al` command for `logs/config` directory.

Note:  The logs directory is by-default generated on the path from where `TorchServe` is started.
