### ISSUE TITLE
Failure after a bunch of requests (memory leak?)

### ISSUE THREAD

**Issue by faustomilletari** [pytorch/serve#532]
Hello, 

I experience failure after a number of requests to the prediction endpoint. My input sizes are rather large (tens of megabytes. videos).

I am seeing what looks like a potential memory leak somewhere.

As the model starts: MemoryAvailable.Megabytes:1512.77734375
```
Model server started.
2020-07-14 14:37:32,383 [INFO ] W-9000-model_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Connection accepted: /tmp/.ts.sock.9000.
2020-07-14 14:37:32,437 [INFO ] pool-2-thread-1 TS_METRICS - CPUUtilization.Percent:0.0|#Level:Host|#hostname:a6ffb5233cbe,timestamp:1594737452
2020-07-14 14:37:32,439 [INFO ] pool-2-thread-1 TS_METRICS - DiskAvailable.Gigabytes:27.937580108642578|#Level:Host|#hostname:a6ffb5233cbe,timestamp:1594737452
2020-07-14 14:37:32,439 [INFO ] pool-2-thread-1 TS_METRICS - DiskUsage.Gigabytes:27.48440933227539|#Level:Host|#hostname:a6ffb5233cbe,timestamp:1594737452
2020-07-14 14:37:32,440 [INFO ] pool-2-thread-1 TS_METRICS - DiskUtilization.Percent:49.6|#Level:Host|#hostname:a6ffb5233cbe,timestamp:1594737452
2020-07-14 14:37:32,440 [INFO ] pool-2-thread-1 TS_METRICS - MemoryAvailable.Megabytes:1512.77734375|#Level:Host|#hostname:a6ffb5233cbe,timestamp:1594737452
2020-07-14 14:37:32,441 [INFO ] pool-2-thread-1 TS_METRICS - MemoryUsed.Megabytes:294.98046875|#Level:Host|#hostname:a6ffb5233cbe,timestamp:1594737452
2020-07-14 14:37:32,442 [INFO ] pool-2-thread-1 TS_METRICS - MemoryUtilization.Percent:24.0|#Level:Host|#hostname:a6ffb5233cbe,timestamp:1594737452
```

as I keep making requests: MemoryAvailable.Megabytes:278.9453125

```
2020-07-14 14:38:32,536 [INFO ] pool-2-thread-1 TS_METRICS - CPUUtilization.Percent:0.0|#Level:Host|#hostname:a6ffb5233cbe,timestamp:1594737512
2020-07-14 14:38:32,536 [INFO ] pool-2-thread-1 TS_METRICS - DiskAvailable.Gigabytes:27.937461853027344|#Level:Host|#hostname:a6ffb5233cbe,timestamp:1594737512
2020-07-14 14:38:32,536 [INFO ] pool-2-thread-1 TS_METRICS - DiskUsage.Gigabytes:27.484527587890625|#Level:Host|#hostname:a6ffb5233cbe,timestamp:1594737512
2020-07-14 14:38:32,536 [INFO ] pool-2-thread-1 TS_METRICS - DiskUtilization.Percent:49.6|#Level:Host|#hostname:a6ffb5233cbe,timestamp:1594737512
2020-07-14 14:38:32,536 [INFO ] pool-2-thread-1 TS_METRICS - MemoryAvailable.Megabytes:278.9453125|#Level:Host|#hostname:a6ffb5233cbe,timestamp:1594737512
2020-07-14 14:38:32,536 [INFO ] pool-2-thread-1 TS_METRICS - MemoryUsed.Megabytes:1568.28125|#Level:Host|#hostname:a6ffb5233cbe,timestamp:1594737512
2020-07-14 14:38:32,536 [INFO ] pool-2-thread-1 TS_METRICS - MemoryUtilization.Percent:86.0|#Level:Host|#hostname:a6ffb5233cbe,timestamp:1594737512
```
 After a while:

```
2020-07-14 14:38:46,354 [INFO ] epollEventLoopGroup-4-1 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_MODEL_LOADED
2020-07-14 14:38:46,418 [DEBUG] W-9000-model_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133)
	at java.base/java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:432)
	at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:128)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-07-14 14:38:46,575 [INFO ] W-9000-model_1.0 ACCESS_LOG - /172.17.0.1:58820 "POST /predictions/model HTTP/1.1" 507 506
2020-07-14 14:38:46,575 [INFO ] W-9000-model_1.0 TS_METRICS - Requests5XX.Count:1|#Level:Host|#hostname:a6ffb5233cbe,timestamp:null
```

and again the memory is lower: MemoryAvailable.Megabytes:45.4453125

```
2020-07-14 14:39:33,405 [INFO ] pool-2-thread-1 TS_METRICS - CPUUtilization.Percent:75.0|#Level:Host|#hostname:a6ffb5233cbe,timestamp:1594737573
2020-07-14 14:39:33,410 [INFO ] pool-2-thread-1 TS_METRICS - DiskAvailable.Gigabytes:27.937362670898438|#Level:Host|#hostname:a6ffb5233cbe,timestamp:1594737573
2020-07-14 14:39:33,418 [INFO ] pool-2-thread-1 TS_METRICS - DiskUsage.Gigabytes:27.48462677001953|#Level:Host|#hostname:a6ffb5233cbe,timestamp:1594737573
2020-07-14 14:39:33,420 [INFO ] pool-2-thread-1 TS_METRICS - DiskUtilization.Percent:49.6|#Level:Host|#hostname:a6ffb5233cbe,timestamp:1594737573
2020-07-14 14:39:33,421 [INFO ] pool-2-thread-1 TS_METRICS - MemoryAvailable.Megabytes:45.4453125|#Level:Host|#hostname:a6ffb5233cbe,timestamp:1594737573
2020-07-14 14:39:33,423 [INFO ] pool-2-thread-1 TS_METRICS - MemoryUsed.Megabytes:1812.3828125|#Level:Host|#hostname:a6ffb5233cbe,timestamp:1594737573
2020-07-14 14:39:33,424 [INFO ] pool-2-thread-1 TS_METRICS - MemoryUtilization.Percent:97.7|#Level:Host|#hostname:a6ffb5233cbe,timestamp:1594737573
```

I am using a custom handler. Is there something explicit I need to do in the custom handler to free the memory relative to one request?

**Comment by faustomilletari** [comment]
is this related to #415 ?

**Comment by harshbafna** [comment]
@faustomilletari: There are multiple factors that should be considered.

 - Is it a JIT/eager mode model [as indicated by you, this was the problem in #415]
 - Number of workers [model is loaded in memory for every worker]
 - PyTorch's model's size increases in memory whenever a prediction is made based on the input tensor  [not permanent, changes with different inputs] 
 - Input size, inference concurrency, number of workers, and CPU cores/GPU. [The requests, along with input data, are queued at the frontend and are passed on to the model workers in the round-robin fashion. Thus, if the server is fairly overloaded, the input data will stay in memory till the request is completed and Java's GC kicks in.]

You could try enabling the `prefer_direct_buffer` [config param for TorchServe](https://github.com/pytorch/serve/blob/master/docs/configuration.md#prefer-direct-buffer). This should ease some memory pressure at netty layer as [direct buffer](https://github.com/mrniko/netty-socketio/blob/bed2a3b05d68a5ac84eba32c59d410c0f88dc0d7/src/main/java/com/corundumstudio/socketio/Configuration.java#L347) is suitable for I/O instead of HeapBuffer

**Comment by faustomilletari** [comment]
Hello, the model is a .pt file obtained as a result of torch.save. I do believe it is not a JIT compiled model then. 

do you think that setting the following env variables will do? 

```
TS_DEFAULT_WORKERS_PER_MODEL 1
TS_PREFER_DIRECT_BUFFER true
```

**Comment by harshbafna** [comment]
> Hello, the model is a .pt file obtained as a result of torch.save. I do believe it is not a JIT compiled model then.
> 
> do you think that setting the following env variables will do?
> 
> ```
> TS_DEFAULT_WORKERS_PER_MODEL 1
> TS_PREFER_DIRECT_BUFFER true
> ```
> 
> (I do have enable_envvars_config=true in config.properties)

In that case, you could simply set `TS_PREFER_DIRECT_BUFFER` to true in the environment variable and restart. You can control the number of workers using the scale API, the default workers per model is 0 by default.

Question: Have you installed `TorchServe` from binary or from source?

**Comment by faustomilletari** [comment]
I have done pip install TorchServe (I have also tried to install from git by pip install git+http://github-repo)

**Comment by harshbafna** [comment]
> I have done pip install TorchServe (I have also tried to install from git by pip install git+http://github-repo)

Just wanted to confirm because of a recent bug (#511) which got introduced in the master.

**Comment by faustomilletari** [comment]
unfortunately the behaviour does not change with the two env variables set :( . does it matter that my model is being executed on CPU?

**Comment by harshbafna** [comment]
@faustomilletari :

Could you please share the following details :

 - Total memory on your machine
 - Total CPU cores
 - Are you using docker?
 - Number of workers being used for your model
 - Memory consumed by model? [top command output on `TorchServe` startup, after model registration, after worker scale]
 - Inference request concurrency?
 - What is the average response time observed for the inference requests?
 - If possible please share your model's mar file and sample input.


> does it matter that my model is being executed on CPU?

The performance will depend on how complex the model is, number of CPU cores, and the number of model workers. However, it could be genuinely running out of memory as well.

**Comment by harshbafna** [comment]
Closing due to no response from OP.
