### ISSUE TITLE
VGG11 model in the model zoo is broken for GPU.

### ISSUE THREAD

**Issue by harshbafna** [pytorch/serve#535]
## Context

* torchserve version: latest master
* torch version: 1.5.1
* torchvision version [if any]: 0.6.1
* torchtext version [if any]: NA
* torchaudio version [if any]: NA
* java version: JDK-11
* Operating System and version: Ubuntu 18.04 on p3.8xlarge instance

## Your Environment

* Installed using source? [yes/no]: Yes
* Are you planning to deploy it using docker container? [yes/no]: No
* Is it a CPU or GPU environment?: GPU
* Using a default/custom handler? [If possible upload/share custom handler/model]: Default `image_classifier` handler
* What kind of model is it e.g. vision, text, audio?: Vision
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
  [If public url then provide link.]: https://torchserve.s3.amazonaws.com/mar_files/vgg11.mar
* Link to your project [if any]: NA

## Expected Behavior
The model should register successfully with the requested number of workers

## Current Behavior
Model registration fails with `InternalServerError` status on GPU instance because of the following error in backend

```
RuntimeError: Expected object of device type cpu but got device type cuda for argument #2 'source'
```

## Possible Solution
NA

## Steps to Reproduce

```
curl -X POST "http://localhost:8081/models?url=https://torchserve.s3.amazonaws.com/mar_files/vgg11.mar&initial_workers=1"
```

## Failure Logs [if any]
```
ubuntu@ip-172-31-65-228:~/serve$
ubuntu@ip-172-31-65-228:~/serve$ 2020-07-15 07:12:39,276 [DEBUG] epollEventLoopGroup-3-3 org.pytorch.serve.wlm.ModelVersionedRefs - Adding new version 1.0 for model vgg11
2020-07-15 07:12:39,277 [DEBUG] epollEventLoopGroup-3-3 org.pytorch.serve.wlm.ModelVersionedRefs - Setting default version to 1.0 for model vgg11
2020-07-15 07:12:39,277 [INFO ] epollEventLoopGroup-3-3 org.pytorch.serve.wlm.ModelManager - Model vgg11 loaded.
2020-07-15 07:12:39,277 [DEBUG] epollEventLoopGroup-3-3 org.pytorch.serve.wlm.ModelManager - updateModel: vgg11, count: 1
2020-07-15 07:12:39,353 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Listening on port: /tmp/.ts.sock.9004
2020-07-15 07:12:39,353 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - [PID]13396
2020-07-15 07:12:39,353 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Torch worker started.
2020-07-15 07:12:39,353 [DEBUG] W-9004-vgg11_1.0 org.pytorch.serve.wlm.WorkerThread - W-9004-vgg11_1.0 State change null -> WORKER_STARTED
2020-07-15 07:12:39,353 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Python runtime: 3.7.7
2020-07-15 07:12:39,353 [INFO ] W-9004-vgg11_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /tmp/.ts.sock.9004
2020-07-15 07:12:39,355 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Connection accepted: /tmp/.ts.sock.9004.
2020-07-15 07:12:43,656 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Backend worker process died.
2020-07-15 07:12:43,657 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Traceback (most recent call last):
2020-07-15 07:12:43,657 [INFO ] epollEventLoopGroup-4-5 org.pytorch.serve.wlm.WorkerThread - 9004 Worker disconnected. WORKER_STARTED
2020-07-15 07:12:43,657 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ts/torch_handler/image_classifier.py", line 90, in handle
2020-07-15 07:12:43,657 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     _service.initialize(context)
2020-07-15 07:12:43,657 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ts/torch_handler/base_handler.py", line 58, in initialize
2020-07-15 07:12:43,657 [DEBUG] W-9004-vgg11_1.0 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_STARTED
2020-07-15 07:12:43,657 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     state_dict = torch.load(model_pt_path, map_location=map_location)
2020-07-15 07:12:43,658 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 593, in load
2020-07-15 07:12:43,658 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
2020-07-15 07:12:43,658 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 773, in _legacy_load
2020-07-15 07:12:43,658 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     result = unpickler.load()
2020-07-15 07:12:43,658 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 147, in __setstate__
2020-07-15 07:12:43,658 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     self.set_(*state)
2020-07-15 07:12:43,658 [DEBUG] W-9004-vgg11_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException
    at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
    at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133)
    at java.base/java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:432)
    at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:129)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
2020-07-15 07:12:43,658 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - RuntimeError: Expected object of device type cpu but got device type cuda for argument #2 'source'
2020-07-15 07:12:43,661 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -
2020-07-15 07:12:43,661 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - During handling of the above exception, another exception occurred:
2020-07-15 07:12:43,661 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -
2020-07-15 07:12:43,661 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Traceback (most recent call last):
2020-07-15 07:12:43,661 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ts/model_service_worker.py", line 176, in <module>
2020-07-15 07:12:43,661 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     worker.run_server()
2020-07-15 07:12:43,661 [WARN ] W-9004-vgg11_1.0 org.pytorch.serve.wlm.BatchAggregator - Load model failed: vgg11, error: Worker died.
2020-07-15 07:12:43,661 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ts/model_service_worker.py", line 148, in run_server
2020-07-15 07:12:43,662 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     self.handle_connection(cl_socket)
2020-07-15 07:12:43,662 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ts/model_service_worker.py", line 112, in handle_connection
2020-07-15 07:12:43,662 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     service, result, code = self.load_model(msg)
2020-07-15 07:12:43,662 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ts/model_service_worker.py", line 85, in load_model
2020-07-15 07:12:43,662 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     service = model_loader.load(model_name, model_dir, handler, gpu, batch_size)
2020-07-15 07:12:43,662 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ts/model_loader.py", line 102, in load
2020-07-15 07:12:43,662 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     entry_point(None, service.context)
2020-07-15 07:12:43,662 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ts/torch_handler/image_classifier.py", line 101, in handle
2020-07-15 07:12:43,662 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     raise Exception("Please provide a custom handler in the model archive." + e)
2020-07-15 07:12:43,662 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - TypeError: can only concatenate str (not "RuntimeError") to str
2020-07-15 07:12:43,663 [INFO ] W-9004-vgg11_1.0 ACCESS_LOG - /127.0.0.1:51158 "POST /models?url=https://torchserve.s3.amazonaws.com/mar_files/vgg11.mar&initial_workers=1&synchronous=true HTTP/1.1" 500 21826
2020-07-15 07:12:43,663 [INFO ] W-9004-vgg11_1.0 TS_METRICS - Requests5XX.Count:1|#Level:Host|#hostname:ip-172-31-65-228,timestamp:null
2020-07-15 07:12:43,664 [DEBUG] W-9004-vgg11_1.0 org.pytorch.serve.wlm.ModelVersionedRefs - Removed model: vgg11 version: 1.0
2020-07-15 07:12:43,664 [DEBUG] W-9004-vgg11_1.0 org.pytorch.serve.wlm.WorkerThread - W-9004-vgg11_1.0 State change WORKER_STARTED -> WORKER_SCALED_DOWN
2020-07-15 07:12:43,665 [WARN ] W-9004-vgg11_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9004-vgg11_1.0-stderr
2020-07-15 07:12:43,665 [WARN ] W-9004-vgg11_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9004-vgg11_1.0-stdout
2020-07-15 07:12:43,762 [INFO ] W-9004-vgg11_1.0 org.pytorch.serve.wlm.ModelManager - Model vgg11 unregistered.
2020-07-15 07:12:43,820 [INFO ] W-9004-vgg11_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9004-vgg11_1.0-stdout
2020-07-15 07:12:43,820 [INFO ] W-9004-vgg11_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9004-vgg11_1.0-stderr
2020-07-15 07:12:43,844 [DEBUG] W-9004-vgg11_1.0 org.pytorch.serve.wlm.WorkerThread - W-9004-vgg11_1.0 State change WORKER_SCALED_DOWN -> WORKER_STOPPED
2020-07-15 07:12:43,844 [WARN ] W-9004-vgg11_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9004-vgg11_1.0-stderr
2020-07-15 07:12:43,844 [WARN ] W-9004-vgg11_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9004-vgg11_1.0-stdout
2020-07-15 07:12:43,844 [DEBUG] W-9004-vgg11_1.0 org.pytorch.serve.wlm.WorkerThread - Worker terminated due to scale-down call.
```

This was first reported by @shivamshriwas .

**Comment by harshbafna** [comment]
This is a bug in `torchvision`. Created following ticket with `torchvision` GH repo :

https://github.com/pytorch/vision/issues/2473

**Comment by harshbafna** [comment]
Currently removed the test case to validate `VGG11` mar file from model zoo. Will add back the test case as a part of the fix for this issue once the actual issue is fixed by PyTorch.

**Comment by harshbafna** [comment]
Moving this back to 0.2.0 milestone as vgg11 is important for benchmarking, and fix is available through adding a custom handler.

**Comment by harshbafna** [comment]
Closing as this has been merged to master.
