### ISSUE TITLE
failing to load a custom model

### ISSUE THREAD

**Issue by Sandeep418** [pytorch/serve#538]
[ts_log.log](https://github.com/pytorch/serve/files/4936445/ts_log.log)

torchserve version: 0.1.1
torch version : 1.5.1
torchvision version : 0.6.1
os : wsl 
java version : "11.0.7"

[handler.txt](https://github.com/pytorch/serve/files/4937001/handler.txt)
[nets.txt](https://github.com/pytorch/serve/files/4937006/nets.txt)
[commands_used.txt](https://github.com/pytorch/serve/files/4937030/commands_used.txt)
mar file : https://drive.google.com/file/d/13BOt2Qi11WkW2rtPF9euSER2-o6tjSBY/view?usp=sharing

I am trying to load the custom model but while loading the model I am getting the below error. I followed the same steps what you mentioned in the document for the custom handler.
 
020-07-17 13:26:24,948 [INFO ] W-9000-cust_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/sandeep/.local/lib/python3.8/site-packages/ts/model_service_worker.py", line 147, in run_server
2020-07-17 13:26:24,944 [INFO ] W-9006-cust_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     worker.run_server()
2020-07-17 13:26:24,940 [INFO ] W-9008-cust_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     worker.run_server()
2020-07-17 13:26:24,937 [DEBUG] W-9007-cust_1.0 org.pytorch.serve.wlm.WorkerThread - W-9007-cust_1.0 State change WORKER_STARTED -> WORKER_STOPPED
2020-07-17 13:26:24,932 [DEBUG] W-9004-cust_1.0 org.pytorch.serve.wlm.WorkerThread - W-9004-cust_1.0 State change WORKER_STARTED -> WORKER_STOPPED
2020-07-17 13:26:24,930 [INFO ] W-9007-cust_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     worker.run_server()
2020-07-17 13:26:24,926 [DEBUG] W-9005-cust_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133)
        at java.base/java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:432)
        at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:129)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
2020-07-17 13:26:24,924 [DEBUG] W-9009-cust_1.0 org.pytorch.serve.wlm.WorkerThread - W-9009-cust_1.0 State change WORKER_STARTED -> WORKER_STOPPED
2020-07-17 13:26:24,916 [INFO ] W-9009-cust_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/sandeep/.local/lib/python3.8/site-packages/ts/model_service_worker.py", line 175, in <module>
2020-07-17 13:26:24,918 [INFO ] W-9005-cust_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Connection accepted: /tmp/.ts.sock.9005.
2020-07-17 13:26:24,914 [INFO ] W-9004-cust_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/sandeep/.local/lib/python3.8/site-packages/ts/model_service_worker.py", line 175, in <module>
2020-07-17 13:26:25,005 [INFO ] W-9005-cust_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Backend worker process died.
2020-07-17 13:26:25,003 [INFO ] W-9009-cust_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     worker.run_server()
2020-07-17 13:26:25,002 [WARN ] W-9009-cust_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9009-cust_1.0-stderr
2020-07-17 13:26:25,001 [WARN ] W-9005-cust_1.0 org.pytorch.serve.wlm.BatchAggregator - Load model failed: cust, error: Worker died.
2020-07-17 13:26:24,993 [INFO ] W-9007-cust_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/sandeep/.local/lib/python3.8/site-packages/ts/model_service_worker.py", line 147, in run_server
2020-07-17 13:26:24,992 [WARN ] W-9004-cust_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9004-cust_1.0-stderr
2020-07-17 13:26:24,991 [WARN ] W-9007-cust_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9007-cust_1.0-stderr
2020-07-17 13:26:24,989 [INFO ] W-9008-cust_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/sandeep/.local/lib/python3.8/site-packages/ts/model_service_worker.py", line 147, in run_server
2020-07-17 13:26:24,989 [INFO ] W-9006-cust_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/sandeep/.local/lib/python3.8/site-packages/ts/model_service_worker.py", line 147, in run_server
2020-07-17 13:26:24,987 [INFO ] W-9000-cust_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     self.handle_connection(cl_socket)
2020-07-17 13:26:24,982 [WARN ] W-9008-cust_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9008-cust_1.0-stderr
2020-07-17 13:26:24,982 [WARN ] W-9006-cust_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9006-cust_1.0-stderr
2020-07-17 13:26:24,981 [INFO ] W-9002-cust_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/sandeep/.local/lib/python3.8/site-packages/ts/model_service_worker.py", line 147, in run_server
2020-07-17 13:26:24,980 [WARN ] W-9000-cust_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-cust_1.0-stderr
2020-07-17 13:26:24,979 [INFO ] W-9010-cust_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/sandeep/.local/lib/python3.8/site-packages/ts/model_service_worker.py", line 147, in run_server
2020-07-17 13:26:24,978 [WARN ] W-9002-cust_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9002-cust_1.0-stderr
2020-07-17 13:26:25,031 [WARN ] W-9002-cust_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9002-cust_1.0-stdout
2020-07-17 13:26:24,977 [INFO ] W-9001-cust_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/sandeep/.local/lib/python3.8/site-packages/ts/model_service_worker.py", line 147, in run_server
2020-07-17 13:26:24,976 [DEBUG] W-9003-cust_1.0 org.pytorch.serve.wlm.WorkerThread - W-9003-cust_1.0 State change WORKER_STARTED -> WORKER_STOPPED
2020-07-17 13:26:24,975 [INFO ] W-9011-cust_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/sandeep/.local/lib/python3.8/site-packages/ts/model_service_worker.py", line 147, in run_server
2020-07-17 13:26:24,973 [WARN ] W-9010-cust_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9010-cust_1.0-stderr
2020-07-17 13:26:24,973 [WARN ] W-9011-cust_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9011-cust_1.0-stderr
2020-07-17 13:26:24,970 [WARN ] W-9001-cust_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9001-cust_1.0-stderr
2020-07-17 13:26:24,969 [INFO ] W-9003-cust_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Backend worker process died.
2020-07-17 13:26:25,047 [WARN ] W-9001-cust_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9001-cust_1.0-stdout
2020-07-17 13:26:25,043 [WARN ] W-9011-cust_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9011-cust_1.0-stdout
2020-07-17 13:26:25,042 [WARN ] W-9010-cust_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9010-cust_1.0-stdout
2020-07-17 13:26:25,040 [INFO ] W-9011-cust_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     self.handle_connection(cl_socket)
2020-07-17 13:26:25,038 [WARN ] W-9003-cust_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9003-cust_1.0-stderr
2020-07-17 13:26:25,036 [INFO ] W-9001-cust_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     self.handle_connection(cl_socket)
2020-07-17 13:26:25,032 [INFO ] W-9002-cust_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9002 in 610 seconds.
2020-07-17 13:26:25,030 [INFO ] W-9010-cust_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     self.handle_connection(cl_socket)
2020-07-17 13:26:25,029 [WARN ] W-9000-cust_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-cust_1.0-stdout
2020-07-17 13:26:25,027 [INFO ] W-9002-cust_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     self.handle_connection(cl_socket)
2020-07-17 13:26:25,024 [WARN ] W-9006-cust_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9006-cust_1.0-stdout
2020-07-17 13:26:25,024 [WARN ] W-9008-cust_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9008-cust_1.0-stdout
2020-07-17 13:26:25,023 [INFO ] W-9000-cust_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/sandeep/.local/lib/python3.8/site-packages/ts/model_service_worker.py", line 111, in handle_connection

**Comment by harshbafna** [comment]
@Sandeep418 : Could you please update the ticket and share all the details asked in the bug template. 

The logs are not conclusive enough, but there is something wrong with your custom handler. We will need the mar file or the handler code at the least to check the issue.

**Comment by harshbafna** [comment]
@Sandeep418 
Following import statements are missing from your handler :
```
import logging
import os
from torch.autograd import Variable
```

and the handler uses these modules in various places. Could you please check and confirm?

**Comment by Sandeep418** [comment]
> @Sandeep418
> Following import statements are missing from your handler :
> 
> ```
> import logging
> import os
> from torch.autograd import Variable
> ```
> 
> and the handler uses these modules in various places. Could you please check and confirm?



> @Sandeep418
> Following import statements are missing from your handler :
> 
> ```
> import logging
> import os
> from torch.autograd import Variable
> ```
> 
> and the handler uses these modules in various places. Could you please check and confirm?



> @Sandeep418
> Following import statements are missing from your handler :
> 
> ```
> import logging
> import os
> from torch.autograd import Variable
> ```
> 
> and the handler uses these modules in various places. Could you please check and confirm?

Thanks for your reply, yes I added the above libraries still facing the same issue.

**Comment by harshbafna** [comment]
> Thanks for your reply, yes I added the above libraries still facing the same issue.

I missed out on one more import statement which is missing :
```
import io
```

**Comment by Sandeep418** [comment]
> > Thanks for your reply, yes I added the above libraries still facing the same issue.
> 
> There is one more import statement missing in your handler:
> 
> ```
> import io
> ```
> 
> If the problem still persists, please share the latest `ts_log.log` file and your model's `state-dict` file.

state-dict file  :https://drive.google.com/file/d/16vISYfIr8oYOWeOymfZUNvNMfiWf8Txj/view?usp=sharing
[ts_log.log](https://github.com/pytorch/serve/files/4938221/ts_log.log)

**Comment by harshbafna** [comment]
@Sandeep418 : I was able to successfully register the model with the suggested changes in the handler. Please try with the following updated handler file 

[handler.txt](https://github.com/pytorch/serve/files/4939088/handler.txt)

Steps executed :

 - added the handler.py, nets.py and pymodel.pth file in a directory and created the model-archive using following command.

```
torch-model-archiver --model-name custommodel --version 1.0 --model-file nets.py --serialized-file pymodel.pth --handler handler.py
```
 - copy above mar file to model-store
```
cp custommodel.mar ~/model-store/
```

 - Start `TorchServe`  :

```
cd ~
torchserve --start --model-store model-store --ncs
```

 - Register model

```
curl -X POST "http://localhost:8081/models?url=custommodel.mar&initial_workers=1"
{
  "status": "Model \"custommodel\" Version: 1.0 registered with 1 initial workers"
}
```

 - Sample inference with `kitten.jpg` image
```
curl -X POST "http://localhost:8080/predictions/custommodel" -T kitten.jpg 
emergency
```

Note : I have used `--ncs` flag while starting `TorchServe` just to ensure it doesn't restore any previous [snapshot](https://github.com/pytorch/serve/blob/master/docs/snapshot.md)

**Comment by Sandeep418** [comment]
> @Sandeep418 : I was able to successfully register the model with the suggested changes in the handler. Please try with the following updated handler file
> 
> [handler.txt](https://github.com/pytorch/serve/files/4939088/handler.txt)
> 
> Steps executed :
> 
> * added the handler.py, nets.py and pymodel.pth file in a directory and created the model-archive using following command.
> 
> ```
> torch-model-archiver --model-name custommodel --version 1.0 --model-file nets.py --serialized-file pymodel.pth --handler handler.py
> ```
> 
> * copy above mar file to model-store
> 
> ```
> cp custommodel.mar ~/model-store/
> ```
> 
> * Start `TorchServe`  :
> 
> ```
> cd ~
> torchserve --start --model-store model-store --ncs
> ```
> 
> * Register model
> 
> ```
> curl -X POST "http://localhost:8081/models?url=custommodel.mar&initial_workers=1"
> {
>   "status": "Model \"custommodel\" Version: 1.0 registered with 1 initial workers"
> }
> ```
> 
> * Sample inference with `kitten.jpg` image
> 
> ```
> curl -X POST "http://localhost:8080/predictions/custommodel" -T kitten.jpg 
> emergency
> ```
> 
> Note : I have used `--ncs` flag while starting `TorchServe` just to ensure it doesn't restore any previous [snapshot](https://github.com/pytorch/serve/blob/master/docs/snapshot.md)

Thank you @harshbafna, It's working after using the --ncs flag.
