### ISSUE TITLE
Backend worker process died

### ISSUE THREAD

**Issue by wow-1129** [pytorch/serve#568]
## 📚 Documentation
Some error made backend worker process died. 
```
2020-07-30 14:49:31,633 [INFO ] epollEventLoopGroup-3-5 ACCESS_LOG - /127.0.0.1:43006 "GET /models HTTP/1.1" 200 3
2020-07-30 14:49:31,633 [INFO ] epollEventLoopGroup-3-5 TS_METRICS - Requests2XX.Count:1|#Level:Host|#hostname:SVR31198DE740,timestamp:null
2020-07-30 14:49:50,371 [DEBUG] epollEventLoopGroup-3-6 org.pytorch.serve.wlm.ModelVersionedRefs - Adding new version 1.0 for model face_anti_spoofing
2020-07-30 14:49:50,371 [DEBUG] epollEventLoopGroup-3-6 org.pytorch.serve.wlm.ModelVersionedRefs - Setting default version to 1.0 for model face_anti_spoofing
2020-07-30 14:49:50,371 [INFO ] epollEventLoopGroup-3-6 org.pytorch.serve.wlm.ModelManager - Model face_anti_spoofing loaded.
2020-07-30 14:49:50,371 [DEBUG] epollEventLoopGroup-3-6 org.pytorch.serve.wlm.ModelManager - updateModel: face_anti_spoofing, count: 1
2020-07-30 14:49:50,486 [INFO ] W-9012-face_anti_spoofing_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Listening on port: /tmp/.ts.sock.9012
2020-07-30 14:49:50,487 [INFO ] W-9012-face_anti_spoofing_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - [PID]323456
2020-07-30 14:49:50,487 [INFO ] W-9012-face_anti_spoofing_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Torch worker started.
2020-07-30 14:49:50,487 [INFO ] W-9012-face_anti_spoofing_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Python runtime: 3.6.8
2020-07-30 14:49:50,487 [DEBUG] W-9012-face_anti_spoofing_1.0 org.pytorch.serve.wlm.WorkerThread - W-9012-face_anti_spoofing_1.0 State change null -> WORKER_STARTED
2020-07-30 14:49:50,487 [INFO ] W-9012-face_anti_spoofing_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /tmp/.ts.sock.9012
2020-07-30 14:49:50,488 [INFO ] W-9012-face_anti_spoofing_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Connection accepted: /tmp/.ts.sock.9012.
2020-07-30 14:49:51,088 [INFO ] W-9012-face_anti_spoofing_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Backend worker process died.
2020-07-30 14:49:51,088 [INFO ] W-9012-face_anti_spoofing_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Traceback (most recent call last):
2020-07-30 14:49:51,088 [INFO ] W-9012-face_anti_spoofing_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/hotel_ai/anaconda3/envs/yk_torchserve/lib/python3.6/site-packages/ts/model_loader.py", line 85, in load
2020-07-30 14:49:51,088 [INFO ] W-9012-face_anti_spoofing_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     module = importlib.import_module(module_name)
2020-07-30 14:49:51,089 [INFO ] W-9012-face_anti_spoofing_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/hotel_ai/anaconda3/envs/yk_torchserve/lib/python3.6/importlib/__init__.py", line 126, in import_module
2020-07-30 14:49:51,089 [INFO ] W-9012-face_anti_spoofing_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     return _bootstrap._gcd_import(name[level:], package, level)
2020-07-30 14:49:51,089 [INFO ] W-9012-face_anti_spoofing_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
2020-07-30 14:49:51,089 [INFO ] W-9012-face_anti_spoofing_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
2020-07-30 14:49:51,092 [INFO ] W-9012-face_anti_spoofing_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
2020-07-30 14:49:51,092 [INFO ] epollEventLoopGroup-4-13 org.pytorch.serve.wlm.WorkerThread - 9012 Worker disconnected. WORKER_STARTED
2020-07-30 14:49:51,092 [INFO ] W-9012-face_anti_spoofing_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
2020-07-30 14:49:51,092 [INFO ] W-9012-face_anti_spoofing_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
2020-07-30 14:49:51,092 [INFO ] W-9012-face_anti_spoofing_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2020-07-30 14:49:51,092 [DEBUG] W-9012-face_anti_spoofing_1.0 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_STARTED
2020-07-30 14:49:51,092 [DEBUG] W-9012-face_anti_spoofing_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133)
        at java.base/java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:432)
        at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:129)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
From log, I guess there is a environmental configuration problem about importlib. But I don't know to solve it.

**Comment by harshbafna** [comment]
@wow-1129: Please share your custom handler and attach the `logs/ts_log.log` file.

**Comment by harshbafna** [comment]
Closing due to no response from OP.
