### ISSUE TITLE
Supply a requirements file with the model-archive. 

### ISSUE THREAD

**Issue by sevenold** [pytorch/serve#577]
version
```bash

torch                1.5.1
torch-model-archiver 0.2.0b20200731
torchserve           0.1.1
torchtext            0.6.0
torchvision          0.6.0a0+35d732a

```
export command
```bash

 torch-model-archiver --model-name craft --version 1.0 --model-file ./craft.py  --serialized-file ./model/craft_mlt_25k.pth  --handler  ./craft_handler.py -r requirements.txt

```
requirements.txt

```bash

-i https://pypi.tuna.tsinghua.edu.cn/simple
pillow
opencv_python==3.4.1.15

```

docerk command
```bash

docker run --rm -it \                                                                                                              
           -p 8080:8080 -p 8081:8081 \
           --name torch_serve_cpu \
           -v (pwd)/model_store:/home/model-server/model-store \
           pytorch/torchserve \
           torchserve --start --ncs --model-store model-store --models craft.mar

```

logs

```bash

2020-07-31 08:22:18,079 [INFO ] W-9003-craft_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     import cv2
2020-07-31 08:22:18,079 [INFO ] W-9003-craft_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - ModuleNotFoundError: No module named 'cv2'

```

**Comment by harshbafna** [comment]
@sevenold: By-default this feature is disabled. 

To enable installing model-specific python dependencies you need to set `install_py_dep_per_model`  parameter to true in config.properties and supply this config file while starting torchserve.

Refer [configuration documentation](https://github.com/pytorch/serve/blob/master/docs/configuration.md#allow-model-specific-custom-python-packages) for more details.

Also, note that this feature only available in the latest master and not on 0.1.1 official release builds. So you will need to install torchserve and torch-model-archiver from the source.

**Comment by sevenold** [comment]
@harshbafna  docker images also is disabled?

docker command 
```bash

 docker run --runtime=nvidia --rm -it \                                                                                                                      (torchserve)
           -p 8082:8080 -p 8083:8081 \
           --name torch_serve_gpu -e install_py_dep_per_model=true  \
           -v (pwd)/model_store:/home/model-server/model-store \
           pytorch/torchserve:latest-gpu \
           torchserve --start --ncs --model-store model-store --models craft.mar

```

logs
```bash

2020-08-02 07:30:35,075 [INFO ] W-9000-craft_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/model-server/tmp/models/e66d6e0b971ca6925a1513365df0dfbe2965c556/craft_handler.py", line 7, in <module>
2020-08-02 07:30:35,075 [WARN ] W-9000-craft_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-craft_1.0-stdout
2020-08-02 07:30:35,075 [INFO ] W-9000-craft_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     import cv2
2020-08-02 07:30:35,075 [INFO ] W-9000-craft_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-craft_1.0-stdout
2020-08-02 07:30:35,075 [INFO ] W-9000-craft_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9000 in 1 seconds.
2020-08-02 07:30:35,079 [INFO ] W-9000-craft_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-craft_1.0-stderr

```

**Comment by sevenold** [comment]
docker image pip error

docker image:  pytorch/torchserve:latest-gpu

command 
```bash
pip list
```

logs 
```bash 

Traceback (most recent call last):
  File "/home/venv/bin/pip3", line 7, in <module>
    from pip import main
  File "/home/venv/lib/python3.6/site-packages/pip/__init__.py", line 29, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/home/venv/lib/python3.6/site-packages/pip/utils/__init__.py", line 23, in <module>
    from pip.locations import (
  File "/home/venv/lib/python3.6/site-packages/pip/locations.py", line 9, in <module>
    from distutils import sysconfig
ImportError: cannot import name 'sysconfig'

```

**Comment by harshbafna** [comment]
@sevenold: Please refer to [TorchServe's docker documentation](https://github.com/pytorch/serve/tree/master/docker#create-torchserve-docker-image-from-source) for creating a docker image with `TorchServe` installed from source.

**Comment by MartinEliasQ** [comment]
Hi, everybody.
Inside the .mar file of my model I have the respective requirements file. I'm using the Kubernetes deployment guide with Helm and I get the same error as if I didn't install the external packages that are in my file. Also, I tried to set the install_py_dep_per_model attribute to true without success.
Does anyone else have the same problem?

**Comment by harshbafna** [comment]
@MartinEliasQ: You will need to add the `install_py_dep_per_model` property in the config.properties file and restart TorchServe. To enable controlling different config params through environment variables you will need to set `enable_envvars_config` to `true` in config.properties. Refer [TorchServe configuration documentation](https://github.com/pytorch/serve/blob/master/docs/configuration.md) for more details

For more details on how to set config.properties file for Kubernetes deployment, refer the [documentation](https://github.com/pytorch/serve/blob/master/kubernetes/README.md).

**Comment by Leoduv** [comment]
I'm having this `ImportError: cannot import name 'sysconfig'` problem, but I think that my config.properties file is correct :

> (venv) model-server@0c3998cd6395:~$ cat config.properties
inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
number_of_netty_threads=32
job_queue_size=1000
model_store=/home/model-server/model-store
install_py_dep_per_model=true

Isn't `python3-distutils` missing from the image ? I'm building from source and tempted to add `apt-get -y install python3-distutils` and see if it works. Am I doing something wrong or am I on the right path ? 

(PS : I also have issues where job_queue_size=1000 isn't taking effect  #623 )

**Comment by harshbafna** [comment]
> I'm having this `ImportError: cannot import name 'sysconfig'` problem, but I think that my config.properties file is correct :
> 
> > (venv) model-server@0c3998cd6395:~$ cat config.properties
> > inference_address=http://0.0.0.0:8080
> > management_address=http://0.0.0.0:8081
> > number_of_netty_threads=32
> > job_queue_size=1000
> > model_store=/home/model-server/model-store
> > install_py_dep_per_model=true
> 
> Isn't `python3-distutils` missing from the image ? I'm building from source and tempted to add `apt-get -y install python3-distutils` and see if it works. Am I doing something wrong or am I on the right path ?

@Leoduv: Please create a separate ticket with details about your environment (as per the BUG template).
This issue looks related to your python environment and not related to the requirements file supplied with model-archive.

> 
> (PS : I also have issues where job_queue_size=1000 isn't taking effect #623 )

I have added a comment in the other ticket, could you share the requested information there.

**Comment by Leoduv** [comment]
Thank you @harshbafna , I've created another ticket #628

**Comment by maaquib** [comment]
@Leoduv Closing this since #635 is merged. Please reopen if this is still an issue.

**Comment by IamMohitM** [comment]
I have the install_py_dep_per_model property set to true in my config.properties:
```

max_response_size=146285000
inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
metrics_address=http://0.0.0.0:8082

cors_allowed_origin=*
cors_allowed_methods=GET, POST, PUT, OPTIONS
cors_allowed_headers=X-Custom-Header

#install requirements for each model if specified
install_py_dep_per_model=true
```

and I'm passing the following requirements.txt

```
numpy==1.22.3
opencv-python==4.5.5.64
Pillow==9.0.1
protobuf==3.20.0
pydot==1.4.2
toml==0.10.2
torch==1.10.0
torch-tb-profiler==0.3.1
torch-model-archiver==0.5.3
torch-workflow-archiver==0.2.3
torchaudio==0.10.0
torchserve==0.5.3
torch-model-archiver==0.5.3
torch-workflow-archiver==0.2.3
torchtext==0.11.0
torchvision==0.11.1
```

to my model-archiver command

```
torch-model-archiver ............ -r requirements.txt
```

However, while running torchserve via docker I still get the same error: `no module named cv2`

**Comment by IamMohitM** [comment]
@FestinaI Yes, this seems to be working however, a differnect error occurs:

```
2022-06-01T13:42:45,014 [INFO ] W-9001-darknet_1.0-stdout MODEL_LOG -     import cv2
2022-06-01T13:42:45,014 [INFO ] W-9001-darknet_1.0-stdout MODEL_LOG -   File "/home/model-server/tmp/models/0ffa93eb26234c73995f9e7d197593c6/cv2/__init__.py", line 180, in <module>
2022-06-01T13:42:45,014 [INFO ] W-9001-darknet_1.0-stdout MODEL_LOG -     bootstrap()
2022-06-01T13:42:45,015 [INFO ] W-9001-darknet_1.0-stdout MODEL_LOG -   File "/home/model-server/tmp/models/0ffa93eb26234c73995f9e7d197593c6/cv2/__init__.py", line 152, in bootstrap
2022-06-01T13:42:45,015 [INFO ] W-9001-darknet_1.0-stdout MODEL_LOG -     native_module = importlib.import_module("cv2")
2022-06-01T13:42:45,015 [INFO ] W-9001-darknet_1.0-stdout MODEL_LOG -   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
2022-06-01T13:42:45,015 [INFO ] W-9001-darknet_1.0-stdout MODEL_LOG -     return _bootstrap._gcd_import(name[level:], package, level)
2022-06-01T13:42:45,015 [INFO ] W-9001-darknet_1.0-stdout MODEL_LOG - ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

Is this an opencv installation error? I'm adding the following version `opencv-contrib-python==4.5.4.58`

**Comment by IamMohitM** [comment]
Actually, it worked at some later point with a different installation (tensorflow) in the requirements file. Haven't tested with opencv as shown above. Used the `--requirements-file` option instead of `-r`
