### ISSUE TITLE
Service workers dying when creating a server with a custom handler for Bert trained with the HuggingFace (transformers) library.

### ISSUE THREAD

**Issue by Bartlett-Will** [pytorch/serve#617]
## Context
Hi all, I'm trying to serve a model trained with the transformers library on a EC2 instance. I have been following [this](https://medium.com/analytics-vidhya/deploy-huggingface-s-bert-to-production-with-pytorch-serve-27b068026d18) blog post and looking at AWS's Deploying PyTorch models for inference at scale using TorchServe blog post as well. 
I followed the installation, and got an example running (you can see the first attempt in the logs). 
I am just using the handler written by MFreidank. 
I believe that the first error came because I did not have the transformers library installed on the ec2 instance. But then I did install it and it threw some abstract errors. (I could use a second pair of eyes on)

* torchserve version: 0.2.0
* torch version: 1.0
* java version: 11
* Operating System and version: Deep Learning AMI (Ubuntu 18.04) Version 32.0 (ami-0dc2264cd927ca9eb)

## Environment
* Installed using source? [yes/no]: no
* Are you planning to deploy it using docker container? [yes/no]: no
* Is it a CPU or GPU environment?: vCPU
* Using a default/custom handler? [If possible upload/share custom handler/model]: customer handler from blog post. Model is transformers bert-base-cased.
* What kind of model is it e.g. vision, text, audio?: Text
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
  [If public url then provide link.]: local models from model-store but may use public url in the future.
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs: [ts_log.log](https://github.com/pytorch/serve/files/5071114/ts_log.log)

## Expected Behavior
The serve starts hosting the Bert.mar file inside the model_store

## Current Behavior
Service workers are dying.

**Comment by maaquib** [comment]
@Bartlett-Will Seems like you are missing the `transformers` module

```
   File "/home/ubuntu/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
     return _bootstrap._gcd_import(name[level:], package, level)
   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
   File "/tmp/models/98aa38a913bb465997a839c009515088/handler.py", line 8, in <module>
     from transformers import AutoModelForSequenceClassification, AutoTokenizer, PreTrainedModel
 ModuleNotFoundError: No module named 'transformers'
```

**Comment by Bartlett-Will** [comment]
@maaquib Yeah, That is the first log! But, I just found the docs for serving transformers, which I didn't think existed. I tried starting the server after I installed transformers module and it threw some different errors. It might be that I did not include an index_to_name.json file in the --extra-files tag

**Comment by Bartlett-Will** [comment]
Here is another log trying to run the server with the same model save and handler file, on macOS.
[ts_log.log](https://github.com/pytorch/serve/files/5076135/ts_log.log)

**Comment by maaquib** [comment]
@Bartlett-Will Seems like it is having trouble loading the model. Can you provide details/command on how you generated the mar file?

```
Traceback (most recent call last):
  File "/Users/Will/dev/Jarvis-repos/server/pyEnv/lib/python3.7/site-packages/ts/model_service_worker.py", line 175, in <module>
    worker.run_server()
  File "/Users/Will/dev/Jarvis-repos/server/pyEnv/lib/python3.7/site-packages/ts/model_service_worker.py", line 147, in run_server
    self.handle_connection(cl_socket)
  File "/Users/Will/dev/Jarvis-repos/server/pyEnv/lib/python3.7/site-packages/ts/model_service_worker.py", line 111, in handle_connection
    service, result, code = self.load_model(msg)
  File "/Users/Will/dev/Jarvis-repos/server/pyEnv/lib/python3.7/site-packages/ts/model_service_worker.py", line 84, in load_model
    service = model_loader.load(model_name, model_dir, handler, gpu, batch_size)
  File "/Users/Will/dev/Jarvis-repos/server/pyEnv/lib/python3.7/site-packages/ts/model_loader.py", line 102, in load
    entry_point(None, service.context)
  File "/private/var/folders/t5/s8044qxs2wxcs8_rdznjkq2c0000gn/T/models/53574cbc0782293e663d5ec35e73a04fb084a921/handler.py", line 109, in handle
    raise e
  File "/private/var/folders/t5/s8044qxs2wxcs8_rdznjkq2c0000gn/T/models/53574cbc0782293e663d5ec35e73a04fb084a921/handler.py", line 98, in handle
    _service.initialize(context)
  File "/private/var/folders/t5/s8044qxs2wxcs8_rdznjkq2c0000gn/T/models/53574cbc0782293e663d5ec35e73a04fb084a921/handler.py", line 32, in initialize
    self.model = AutoModelForSequenceClassification.from_pretrained(model_dir)
  File "/Users/Will/dev/Jarvis-repos/server/pyEnv/lib/python3.7/site-packages/transformers/modeling_auto.py", line 1359, in from_pretrained
    config = AutoConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "/Users/Will/dev/Jarvis-repos/server/pyEnv/lib/python3.7/site-packages/transformers/configuration_auto.py", line 203, in from_pretrained
    config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/Users/Will/dev/Jarvis-repos/server/pyEnv/lib/python3.7/site-packages/transformers/configuration_utils.py", line 223, in get_config_dict
    if os.path.isdir(pretrained_model_name_or_path):
  File "/usr/local/bin/../Cellar/python/3.7.7/bin/../Frameworks/Python.framework/Versions/3.7/lib/python3.7/genericpath.py", line 42, in isdir
    st = os.stat(s)
```

**Comment by Bartlett-Will** [comment]
Yeah, it is having trouble loading the model, even in just a regular Colab file. Not sure why though.

This is the code that saved the model:
`model_to_save = model.module if hasattr(model, 'module') else model  # Take care of distributed/parallel training
model_to_save.save_pretrained(output_dir)
tokenizer.save_pretrained(output_dir)
`
here is the bit of code that is being run to load the checkpoint 
`from transformers import AutoModelForSequenceClassification, AutoTokenizer, PreTrainedModel

# Load a trained model and vocabulary that you have fine-tuned
model = AutoModelForSequenceClassification.from_pretrained(output_dir)
tokenizer = AutoTokenizer.from_pretrained(output_dir)

# Copy the model to the GPU.
model.to(device)`

and the .mar file is generated like this:
`torch-model-archiver --model-name "bert" --version 1.0 --serialized-file ./model_save/pytorch_model.bin --extra-files "./model_save/config.json,./model_save/vocab.txt" --handler "./handler.py"`

**Comment by maaquib** [comment]
> Does the .mar file need to be located in the same directory as the model_save directory? as per:

Yes, the .mar file is expected to be in the `--model-store <dir>` directory that is specified at server startup

**Comment by HamidShojanazeri** [comment]
>         model_dir = properties.get("model_save")

Hi @Bartlett-Will , as @maaquib mentioned the .mar file should be place in a folder named model_store, if  you are using

 torchserve --start --model-store model_store --models bert=bert.mar

 to start the server.

That would be great if you could share a minimal code to reproduce the issue. 

Would please confirm if you are using:

```python
model_dir = properties.get("model_save")
```
in your handler.

If that's the case, I believe, you may want to change 

```python
model_dir = properties.get("model_save")
```

to 

```python
model_dir = properties.get("model_dir")
```

Then if you list the files in this directory as :

```python
print(os.listdir(model_dir))
```
You will be able to see the handler and checkpoint along with config file and all the files you specified during making the .mar file.  In addition to that passing vocab.txt in the extra-files is not necesssary. 

Also, if you check the properties.keys() in initialize function  there are the keys dict_keys(['model_dir', 'gpu_id', 'batch_size', 'server_name', 'server_version']), this should not include the "model_save" key, which can cause the issue when you want to read the model from checkpoint. 

I could reproduce the issue by model_dir = properties.get("model_save") where model_save in my setting is equal to "Transformer_model" folder, is where my checkpoints and transformer config.json are saved. Here is the log for the reference.
[error.log](https://github.com/pytorch/serve/files/5092406/error.log)


Please let me know if that helps or you are still facing the issue. Thanks.

**Comment by harshbafna** [comment]
CLosing as the query has been answered and no response from OP.
