### ISSUE TITLE
Torchserve error while serving

### ISSUE THREAD

**Issue by vishal-wiai** [pytorch/serve#632]
Can anyone help me understand what this error means? I'm having the issue with a particular version of my model, the other is working fine. I tried testing the `Torchscript` model of this and it works fine. The issue seems to be in the `mar` file.

Can somebody please help me understand what this error means? Thanks

```
org.pytorch.serve.wlm.WorkerLifeCycle - Model loaded from /var/folders/6l/3r0c9gjn5kd68lsqb1m0qsj00000gn/T/models/f8331b67fe613241f391ef9c9bd5d423ce8c939e/model.pt
[ERROR] KQueueEventLoopGroup-4-10 org.pytorch.serve.wlm.WorkerThread - Unknown exception
io.netty.handler.codec.CorruptedFrameException: Message size exceed limit: 15615479
        at org.pytorch.serve.util.codec.CodecUtils.readLength(CodecUtils.java:24)
        at org.pytorch.serve.util.codec.ModelResponseDecoder.decode(ModelResponseDecoder.java:72)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.kqueue.AbstractKQueueStreamChannel$KQueueStreamUnsafe.readReady(AbstractKQueueStreamChannel.java:551)
        at io.netty.channel.kqueue.KQueueDomainSocketChannel$KQueueDomainUnsafe.readReady(KQueueDomainSocketChannel.java:131)
        at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.readReady(AbstractKQueueChannel.java:399)
        at io.netty.channel.kqueue.KQueueEventLoop.processReady(KQueueEventLoop.java:195)
        at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:269)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
2020-08-20 19:13:25,264 [INFO ] KQueueEventLoopGroup-4-10 org.pytorch.serve.wlm.WorkerThread - 9008 Worker disconnected. WORKER_MODEL_LOADED
2020-08-20 19:13:25,264 [INFO ] W-9008-cfssd_0_3_0.3-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Backend worker process died.
2020-08-20 19:13:25,264 [DEBUG] W-9008-cfssd_0_3_0.3 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_MODEL_LOADED
2020-08-20 19:13:25,264 [INFO ] W-9008-cfssd_0_3_0.3-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Traceback (most recent call last):
2020-08-20 19:13:25,264 [DEBUG] W-9008-cfssd_0_3_0.3 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133)
        at java.base/java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:432)
        at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:129)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by harshbafna** [comment]
@vishal-wiai: From the above logs like the model response size exceeds the default limit of `6553500` bytes. You can change the response size value by setting the `max_response_size` parameter in the config.properties file.

For more details refer [torchserve configuration documentation](https://github.com/pytorch/serve/blob/master/docs/configuration.md#other-properties)

**Comment by vishal-wiai** [comment]
@harshbafna Thank you! This worked!
