### ISSUE TITLE
SSL TorchServe: 405 Connection Refused Error 

### ISSUE THREAD

**Issue by krrishdholakia** [pytorch/serve#663]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/pytorch/serve/issues) before creating one.
## Context

I'm trying to run my huggingface model locally. 

*Torch Serve Version: 0.2.0
*Java Version: 11
* Operating System and Version: MacOS version 10.15.4 (Catalina) 

## Your Environment

* Installed using source? [yes/no]: Yes
* Are you planning to deploy it using docker container? [yes/no]: Not sure - never deployed before
* Is it a CPU or GPU environment?: CPU 
* Using a default/custom handler? [If possible upload/share custom handler/model]: Custom
* What kind of model is it e.g. vision, text, audio?: Text-based (Question Generation Model) 

## Expected Behavior

I'm running:  `torchserve --start --model-store model_store --models bert=t5.mar`

Expect it to deploy to 127.0.0.1:8080 and be able to test the inference API

## Current Behavior

Currently seeing:

running: `curl -X OPTIONS https://localhost:8080`

result: `Failed to connect to localhost port 8080: Connection refused`

**Comment by dhaniram-kshirsagar** [comment]
> https://localhost:8080

Why https? By default it is http

**Comment by krrishdholakia** [comment]
tried on both - thought it might be accepting https only, when i initially tried it w/ http

**Comment by dhaniram-kshirsagar** [comment]
Can you please attach logs else it is difficult to help. At least on my Mac this works fine `curl -X OPTIONS http://localhost:8080`

**Comment by krrishdholakia** [comment]
hi @dhaniram-kshirsagar not sure what happened but the endpoint managed to run it's now giving errors related to the huggingface library itself: 
```

Traceback (most recent call last):
2020-09-04 18:19:50,279 [INFO ] W-9002-t5_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ts/service.py", line 100, in predict
2020-09-04 18:19:50,279 [INFO ] W-9002-t5_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     ret = self._entry_point(input_batch, self.context)
2020-09-04 18:19:50,279 [INFO ] W-9002-t5_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/private/var/folders/bj/qp8k0pxs4c7b1svhbjy5cjh40000gn/T/models/bc8832cd8c984378ac4e2eef1530c444/transformers_generator.py", line 116, in handle
2020-09-04 18:19:50,279 [INFO ] W-9002-t5_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     raise e
2020-09-04 18:19:50,279 [INFO ] W-9002-t5_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/private/var/folders/bj/qp8k0pxs4c7b1svhbjy5cjh40000gn/T/models/bc8832cd8c984378ac4e2eef1530c444/transformers_generator.py", line 111, in handle
2020-09-04 18:19:50,279 [INFO ] W-9002-t5_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     data = _service.inference(data)
2020-09-04 18:19:50,280 [INFO ] W-9002-t5_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/private/var/folders/bj/qp8k0pxs4c7b1svhbjy5cjh40000gn/T/models/bc8832cd8c984378ac4e2eef1530c444/transformers_generator.py", line 86, in inference
2020-09-04 18:19:50,280 [INFO ] W-9002-t5_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     outs = self.model.generate(
2020-09-04 18:19:50,280 [INFO ] W-9002-t5_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
2020-09-04 18:19:50,280 [INFO ] W-9002-t5_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     return func(*args, **kwargs)
2020-09-04 18:19:50,280 [INFO ] W-9002-t5_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/transformers/modeling_utils.py", line 770, in generate
2020-09-04 18:19:50,280 [INFO ] W-9002-t5_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     output = self._generate_beam_search(
2020-09-04 18:19:50,280 [INFO ] W-9002-t5_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1063, in _generate_beam_search
2020-09-04 18:19:50,280 [INFO ] W-9002-t5_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     for idx, score in zip(next_words[batch_idx], next_scores[batch_idx]):
2020-09-04 18:19:50,280 [INFO ] W-9002-t5_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - UnboundLocalError: local variable 'next_words' referenced before assignment
```
