### ISSUE TITLE
Model version is not defined

### ISSUE THREAD

**Issue by hyperparameters** [pytorch/serve#664]
## Issue
I want to serve 2 models using torch serve but, torchserve is throwing an error 
```
org.pytorch.serve.archive.InvalidModelException: Model version is not defined.
```

following are the commands i used to create model-archive
> I only have one `.mar` file per model <br>
> both my models are of different version

**model 1**
```
torch-model-archiver --model-name centernet_resnet18 --version 1.1 --serialized-file models/res18_model.pth --extra-files index_to_name.json --model-file model.py --handler model_handler.py  --requirements-file requirements.txt -f
```

**model 2**
```
torch-model-archiver --model-name yolov5x --version 1 --serialized-file exp35_last.torchscript.pt --extra-files index_to_name.json --handler model_handler.py -f
```

**config**
```
inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
number_of_netty_threads=32
job_queue_size=1000
default_workers_per_model=2
async_logging=true
model_store=/home/model-server/model-store
```

**torch serve**
```
torchserve --start --ts-config /home/model-server/config.properties  --models yolov5x.mar --ncs
```

* torchserve version: 0.2.0
* torch-model-archiver: 0.2.0
install using `pip install torchserve==0.2.0 torch-model-archiver==0.2.0`

* torch version:1.6.0
* torchvision version: 0.7.0
* torchtext version: 0.6.0
* java version: 11
* Operating System and version: ubuntu 18

## Expected Behavior
how do i tell `torch-serve` which version to use for each model
I cant find any doc related to this

## Current Behavior
`torch-serve` throwing error asking for default model version
I am facing this issue in docker container only on local its working file and assigning default version by itself

## Failure Logs
```
2020-09-03 06:13:12,307 [INFO ] main org.pytorch.serve.ModelServer - 
Torchserve version: 0.2.0
TS Home: /usr/local/lib/python3.6/dist-packages
Current directory: /home/model-server
Temp directory: /home/model-server/tmp
Number of GPUs: 0
Number of CPUs: 8
Max heap size: 1962 M
Python executable: /usr/bin/python3
Config file: /home/model-server/config.properties
Inference address: http://0.0.0.0:8080
Management address: http://0.0.0.0:8081
Metrics address: http://127.0.0.1:8082
Model Store: /home/model-server/model-store
Initial Models: all
Log dir: /home/model-server/logs
Metrics dir: /home/model-server/logs
Netty threads: 32
Netty client threads: 0
Default workers per model: 2
Blacklist Regex: N/A
Maximum Response Size: 6553500
Maximum Request Size: 6553500
Prefer direct buffer: false
Custom python dependency for model allowed: false
Metrics report format: prometheus
Enable metrics API: true
2020-09-03 06:13:12,364 [DEBUG] main org.pytorch.serve.ModelServer - Loading models from model store: centernet_resnet18.mar
2020-09-03 06:13:12,375 [INFO ] main org.pytorch.serve.archive.ModelArchive - eTag 59f22da511324ca39be78e387049df13
2020-09-03 06:13:12,377 [WARN ] main org.pytorch.serve.ModelServer - Failed to load model: /home/model-server/model-store/centernet_resnet18.mar
org.pytorch.serve.archive.InvalidModelException: Model version is not defined.
	at org.pytorch.serve.archive.ModelArchive.validate(ModelArchive.java:158)
	at org.pytorch.serve.wlm.ModelManager.createModelArchive(ModelManager.java:156)
	at org.pytorch.serve.wlm.ModelManager.registerModel(ModelManager.java:115)
	at org.pytorch.serve.wlm.ModelManager.registerModel(ModelManager.java:68)
	at org.pytorch.serve.ModelServer.initModelStore(ModelServer.java:177)
	at org.pytorch.serve.ModelServer.start(ModelServer.java:308)
	at org.pytorch.serve.ModelServer.startAndWait(ModelServer.java:104)
	at org.pytorch.serve.ModelServer.main(ModelServer.java:85)
2020-09-03 06:13:12,379 [DEBUG] main org.pytorch.serve.ModelServer - Loading models from model store: yolov5x.mar
2020-09-03 06:13:12,380 [INFO ] main org.pytorch.serve.archive.ModelArchive - eTag 7a1253dd425d47d7b7623c91078d4e25
2020-09-03 06:13:12,380 [WARN ] main org.pytorch.serve.ModelServer - Failed to load model: /home/model-server/model-store/yolov5x.mar
org.pytorch.serve.archive.InvalidModelException: Model version is not defined.
	at org.pytorch.serve.archive.ModelArchive.validate(ModelArchive.java:158)
	at org.pytorch.serve.wlm.ModelManager.createModelArchive(ModelManager.java:156)
	at org.pytorch.serve.wlm.ModelManager.registerModel(ModelManager.java:115)
	at org.pytorch.serve.wlm.ModelManager.registerModel(ModelManager.java:68)
	at org.pytorch.serve.ModelServer.initModelStore(ModelServer.java:177)
	at org.pytorch.serve.ModelServer.start(ModelServer.java:308)
	at org.pytorch.serve.ModelServer.startAndWait(ModelServer.java:104)
	at org.pytorch.serve.ModelServer.main(ModelServer.java:85)
2020-09-03 06:13:12,383 [INFO ] main org.pytorch.serve.ModelServer - Initialize Inference server with: EpollServerSocketChannel.
2020-09-03 06:13:12,476 [INFO ] main org.pytorch.serve.ModelServer - Inference API bind to: http://0.0.0.0:8080
2020-09-03 06:13:12,476 [INFO ] main org.pytorch.serve.ModelServer - Initialize Management server with: EpollServerSocketChannel.
2020-09-03 06:13:12,478 [INFO ] main org.pytorch.serve.ModelServer - Management API bind to: http://0.0.0.0:8081
2020-09-03 06:13:12,478 [INFO ] main org.pytorch.serve.ModelServer - Initialize Metrics server with: EpollServerSocketChannel.
2020-09-03 06:13:12,479 [INFO ] main org.pytorch.serve.ModelServer - Metrics API bind to: http://127.0.0.1:8082
Model server started.

```

**Comment by harshbafna** [comment]
@hyperparameters

Please provide the following details:

 - What's the version of `torch-model-archiver` you are using?
 - And how was `torchserve` and `torch-model-archiver` installed? From source or from binary?

**Comment by hyperparameters** [comment]
torch-model-archiver: 0.2.0
install using pip install torchserve==0.2.0 torch-model-archiver==0.2.0

updated original issue too

one thing I noticed is i am facing this issue in `docker` on `local` its working

this is the log from local run 
```
Enable metrics API: true
2020-09-03 12:41:01,231 [INFO ] main org.pytorch.serve.ModelServer - Loading initial models: centernet_resnet18.mar
2020-09-03 12:41:03,790 [INFO ] main org.pytorch.serve.archive.ModelArchive - eTag 34f73092b7094261b5ed7740cac76337
2020-09-03 12:41:03,799 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Adding new version 1 for model centernet_resnet18
2020-09-03 12:41:03,799 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Setting default version to 1 for model centernet_resnet18
2020-09-03 12:41:03,799 [INFO ] main org.pytorch.serve.wlm.ModelManager - Model centernet_resnet18 loaded.
2020-09-03 12:41:03,799 [DEBUG] main org.pytorch.serve.wlm.ModelManager - updateModel: centernet_resnet18, count: 2
2020-09-03 12:41:03,809 [INFO ] main org.pytorch.serve.ModelServer - Loading initial models: yolov5x.mar
2020-09-03 12:41:04,019 [INFO ] W-9000-centernet_resnet18_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Listening on port: /tmp/.ts.sock.9000
2020-09-03 12:41:04,019 [INFO ] W-9001-centernet_resnet18_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Listening on port: /tmp/.ts.sock.9001
2020-09-03 12:41:04,021 [INFO ] W-9000-centernet_resnet18_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - [PID]21643
2020-09-03 12:41:04,021 [INFO ] W-9001-centernet_resnet18_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - [PID]21644
2020-09-03 12:41:04,021 [INFO ] W-9000-centernet_resnet18_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Torch worker started.
2020-09-03 12:41:04,021 [INFO ] W-9001-centernet_resnet18_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Torch worker started.
2020-09-03 12:41:04,021 [INFO ] W-9000-centernet_resnet18_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Python runtime: 3.7.5
2020-09-03 12:41:04,021 [INFO ] W-9001-centernet_resnet18_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Python runtime: 3.7.5
2020-09-03 12:41:04,022 [DEBUG] W-9001-centernet_resnet18_1 org.pytorch.serve.wlm.WorkerThread - W-9001-centernet_resnet18_1 State change null -> WORKER_STARTED
2020-09-03 12:41:04,022 [DEBUG] W-9000-centernet_resnet18_1 org.pytorch.serve.wlm.WorkerThread - W-9000-centernet_resnet18_1 State change null -> WORKER_STARTED
2020-09-03 12:41:04,056 [INFO ] W-9001-centernet_resnet18_1 org.pytorch.serve.wlm.WorkerThread - Connecting to: /tmp/.ts.sock.9001
2020-09-03 12:41:04,056 [INFO ] W-9000-centernet_resnet18_1 org.pytorch.serve.wlm.WorkerThread - Connecting to: /tmp/.ts.sock.9000
2020-09-03 12:41:04,137 [INFO ] W-9001-centernet_resnet18_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Connection accepted: /tmp/.ts.sock.9001.
2020-09-03 12:41:04,137 [INFO ] W-9000-centernet_resnet18_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Connection accepted: /tmp/.ts.sock.9000.
2020-09-03 12:41:08,514 [INFO ] main org.pytorch.serve.archive.ModelArchive - eTag 46110681ac36473493fe9d4cce1d2ea0
2020-09-03 12:41:08,515 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Adding new version 1 for model yolov5x
2020-09-03 12:41:08,515 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Setting default version to 1 for model yolov5x
2020-09-03 12:41:08,515 [INFO ] main org.pytorch.serve.wlm.ModelManager - Model yolov5x loaded.
2020-09-03 12:41:08,515 [DEBUG] main org.pytorch.serve.wlm.ModelManager - updateModel: yolov5x, count: 2
2020-09-03 12:41:08,517 [INFO ] main org.pytorch.serve.ModelServer - Initialize Inference server with: EpollServerSocketChannel.
2020-09-03 12:41:08,539 [INFO ] main org.pytorch.serve.ModelServer - Inference API bind to: http://0.0.0.0:8080
2020-09-03 12:41:08,540 [INFO ] main org.pytorch.serve.ModelServer - Initialize Management server with: EpollServerSocketChannel.
2020-09-03 12:41:08,541 [INFO ] main org.pytorch.serve.ModelServer - Management API bind to: http://0.0.0.0:8081
2020-09-03 12:41:08,542 [INFO ] main org.pytorch.serve.ModelServer - Initialize Metrics server with: EpollServerSocketChannel.
2020-09-03 12:41:08,542 [INFO ] main org.pytorch.serve.ModelServer - Metrics API bind to: http://127.0.0.1:8082
Model server started.
```

**Comment by harshbafna** [comment]
@hyperparameters:

Please share minimal steps to reproduce this issue. Also include the docker image creation and container start command used.

**Comment by hyperparameters** [comment]
Dockerfile  (model path removed)
```
FROM ubuntu:18.04

ENV PYTHONUNBUFFERED TRUE

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    fakeroot \
    ca-certificates \
    dpkg-dev \
    g++ \
    python3-dev \
    openjdk-11-jdk \
    curl \
    vim \
    git\
    libgtk2.0-dev\
    libglib2.0-0\
    && rm -rf /var/lib/apt/lists/* \
    && cd /tmp \
    && curl -O https://bootstrap.pypa.io/get-pip.py \
    && python3 get-pip.py

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1
RUN update-alternatives --install /usr/local/bin/pip pip /usr/local/bin/pip3 1

RUN pip install torch==1.6.0 torchvision==0.7.0 torch-model-archiver==0.2.0 torchserve==0.2.0 torchtext==0.6.0

RUN useradd -m model-server \
    && mkdir -p /home/model-server/tmp

RUN mkdir /home/model-server/model-store && chown -R model-server /home/model-server/model-store
RUN mkdir -p /home/model-server/tmp/models/checkpoints/
ENV TORCH_HOME=/home/model-server/tmp/models/

#model download
RUN curl https://download.pytorch.org/models/resnet18-5c106cde.pth --output /home/model-server/tmp/models/checkpoints/resnet18-5c106cde.pth
RUN curl <path to model 1> --output /home/model-server/model-store/model1.mar
RUN curl <path to model 2> --output /home/model-server/model-store/model2.mar

COPY dockerd-entrypoint.sh /usr/local/bin/dockerd-entrypoint.sh

RUN chmod +x /usr/local/bin/dockerd-entrypoint.sh \
    && chown -R model-server /home/model-server

COPY config.properties /home/model-server/config.properties

EXPOSE 8080 8081

USER model-server
WORKDIR /home/model-server
ENV TEMP=/home/model-server/tmp
ENTRYPOINT ["/usr/local/bin/dockerd-entrypoint.sh"]
CMD ["serve"]
```

dockerd-entrypoint.sh
```
#!/bin/bash
set -e

if [[ "$1" = "serve" ]]; then
    shift 1
    torchserve --start --ts-config /home/model-server/config.properties  --models all --ncs
else
    eval "$@"
fi

# prevent docker exit
tail -f /dev/null

```

config file
```
inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
number_of_netty_threads=32
job_queue_size=1000
default_workers_per_model=1
async_logging=true
model_store=/home/model-server/model-store
```

model-archive
```
torch-model-archiver --model-name model1 --version 1 --serialized-file models/model1.pth --extra-files index_to_name.json --model-file model.py --handler model_handler.py  --requirements-file requirements.txt -f

torch-model-archiver --model-name model2 --version 1 --serialized-file models/model2.pth --extra-files index_to_name.json --model-file model.py --handler model_handler.py  -f

@harshbafna  if there anything else that you would need, kindly mention

**Comment by hyperparameters** [comment]
**SOLVED**
model-archives were corrupted when downloading
that was the reason it failed to load the `manifest` file

**SUGGESTION**
 if the error message can be more relevant when it cant find `manifest` file

**Comment by dhaniram-kshirsagar** [comment]
> @harshbafna still my question is if I have multiple versions of same model, how can I configure which version to serve by default?

There is [set default management api](https://github.com/pytorch/serve/blob/master/docs/management_api.md#set-default-version) to do that.

**Comment by hyperparameters** [comment]
@dhaniram-kshirsagar thanx, 
sorry I forgot to mention without using management API.
I am not exposing management API.

**Comment by harshbafna** [comment]
@hyperparameters: TorchServe registers the models with the version specified at the time of mar creation.

**Comment by hyperparameters** [comment]
@harshbafna yes, but if I have registered 2 models `version 1.1` and `version 1.2` is there a way for me to specify which `version` to pick when `torchserve` initialises. Other than management API, may be from config.properties
