### ISSUE TITLE
Failing to serve model

### ISSUE THREAD

**Issue by duckroll** [pytorch/serve#811]
Im trying to serve model on Windows but get this error.  I am able to serve same model on Linux.

Conda version: conda 4.9.2
Pytorch version: 1.7.0+cu101
Cuda version: Cuda compilation tools, release 10.1, V10.1.243
TorchServe sersion: 0.2.0
 
```
Torchserve version: 0.2.0
TS Home: D:\anaconda3\envs\tf\Lib\site-packages
Current directory: D:\serve
Temp directory: C:\Users\barik\AppData\Local\Temp
Number of GPUs: 1
Number of CPUs: 16
Max heap size: 4084 M
Python executable: d:\anaconda3\envs\tf\python.exe
Config file: config.properties
Inference address: http://127.0.0.1:4444
Management address: http://127.0.0.1:4445
Metrics address: http://127.0.0.1:8082
Model Store: D:\serve\model-store
Initial Models: mm.mar
Log dir: D:\serve\logs
Metrics dir: D:\serve\logs
Netty threads: 0
Netty client threads: 0
Default workers per model: 1
Blacklist Regex: N/A
Maximum Response Size: 6553500
Maximum Request Size: 6553500
Prefer direct buffer: false
Custom python dependency for model allowed: false
Metrics report format: prometheus
Enable metrics API: true
2020-11-28 19:20:24,927 [INFO ] main org.pytorch.serve.ModelServer - Loading initial models: mm.mar
2020-11-28 19:20:30,745 [INFO ] main org.pytorch.serve.archive.ModelArchive - eTag 4d1e25fc20f34f73a8f592431f407261
2020-11-28 19:20:30,752 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Adding new version 1.0 for model mm
2020-11-28 19:20:30,752 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Setting default version to 1.0 for model mm
2020-11-28 19:20:30,752 [INFO ] main org.pytorch.serve.wlm.ModelManager - Model mm loaded.
2020-11-28 19:20:30,752 [DEBUG] main org.pytorch.serve.wlm.ModelManager - updateModel: mm, count: 1
2020-11-28 19:20:30,760 [INFO ] main org.pytorch.serve.ModelServer - Initialize Inference server with: NioServerSocketChannel.
2020-11-28 19:20:30,850 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Listening on port: None
2020-11-28 19:20:30,851 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - [PID]8600
2020-11-28 19:20:30,851 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Torch worker started.
2020-11-28 19:20:30,851 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Python runtime: 3.8.5
2020-11-28 19:20:30,851 [DEBUG] W-9000-mm_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-mm_1.0 State change null -> WORKER_STARTED
2020-11-28 19:20:30,854 [INFO ] W-9000-mm_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /127.0.0.1:9000
2020-11-28 19:20:30,967 [INFO ] main org.pytorch.serve.ModelServer - Inference API bind to: http://127.0.0.1:4444
2020-11-28 19:20:30,967 [INFO ] main org.pytorch.serve.ModelServer - Initialize Management server with: NioServerSocketChannel.
2020-11-28 19:20:30,968 [INFO ] main org.pytorch.serve.ModelServer - Management API bind to: http://127.0.0.1:4445
2020-11-28 19:20:30,969 [INFO ] main org.pytorch.serve.ModelServer - Initialize Metrics server with: NioServerSocketChannel.
2020-11-28 19:20:30,969 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Connection accepted: ('127.0.0.1', 9000).
2020-11-28 19:20:30,969 [INFO ] main org.pytorch.serve.ModelServer - Metrics API bind to: http://127.0.0.1:8082
Model server started.
2020-11-28 19:20:31,007 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Backend worker process died.
2020-11-28 19:20:31,007 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Traceback (most recent call last):
2020-11-28 19:20:31,007 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "d:\anaconda3\envs\tf\lib\site-packages\ts\model_loader.py", line 84, in load
2020-11-28 19:20:31,007 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     module = importlib.import_module(module_name)
2020-11-28 19:20:31,007 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "d:\anaconda3\envs\tf\lib\importlib\__init__.py", line 127, in import_module
2020-11-28 19:20:31,007 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     return _bootstrap._gcd_import(name[level:], package, level)
2020-11-28 19:20:31,008 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2020-11-28 19:20:31,008 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2020-11-28 19:20:31,008 [INFO ] nioEventLoopGroup-5-1 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_STARTED
2020-11-28 19:20:31,008 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2020-11-28 19:20:31,009 [DEBUG] W-9000-mm_1.0 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_STARTED
2020-11-28 19:20:31,009 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
2020-11-28 19:20:31,010 [DEBUG] W-9000-mm_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133)
        at java.base/java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:432)
        at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:129)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
2020-11-28 19:20:31,010 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
2020-11-28 19:20:31,011 [WARN ] W-9000-mm_1.0 org.pytorch.serve.wlm.BatchAggregator - Load model failed: mm, error: Worker died.
2020-11-28 19:20:31,011 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2020-11-28 19:20:31,012 [INFO ] W-9000-mm_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-mm_1.0-stderr
2020-11-28 19:20:31,012 [DEBUG] W-9000-mm_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-mm_1.0 State change WORKER_STARTED -> WORKER_STOPPED
2020-11-28 19:20:31,013 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "C:\Users\barik\AppData\Local\Temp\models\4d1e25fc20f34f73a8f592431f407261\detectron2-handler.py", line 8, in <module>
2020-11-28 19:20:31,014 [WARN ] W-9000-mm_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-mm_1.0-stderr
2020-11-28 19:20:31,015 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     import detectron2
2020-11-28 19:20:31,017 [WARN ] W-9000-mm_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-mm_1.0-stdout
2020-11-28 19:20:31,018 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - ModuleNotFoundError: No module named 'detectron2'
2020-11-28 19:20:31,031 [INFO ] W-9000-mm_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9000 in 1 seconds.
2020-11-28 19:20:31,031 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-mm_1.0-stdout
2020-11-28 19:20:31,061 [INFO ] pool-2-thread-1 TS_METRICS - CPUUtilization.Percent:0.0|#Level:Host|#hostname:DESKTOP-AKBS7RC,timestamp:1606584031
2020-11-28 19:20:31,061 [INFO ] pool-2-thread-1 TS_METRICS - DiskAvailable.Gigabytes:228.91899490356445|#Level:Host|#hostname:DESKTOP-AKBS7RC,timestamp:1606584031
2020-11-28 19:20:31,062 [INFO ] pool-2-thread-1 TS_METRICS - DiskUsage.Gigabytes:63.93451690673828|#Level:Host|#hostname:DESKTOP-AKBS7RC,timestamp:1606584031
2020-11-28 19:20:31,062 [INFO ] pool-2-thread-1 TS_METRICS - DiskUtilization.Percent:21.8|#Level:Host|#hostname:DESKTOP-AKBS7RC,timestamp:1606584031
2020-11-28 19:20:31,063 [INFO ] pool-2-thread-1 TS_METRICS - MemoryAvailable.Megabytes:9452.52734375|#Level:Host|#hostname:DESKTOP-AKBS7RC,timestamp:1606584031
2020-11-28 19:20:31,064 [INFO ] pool-2-thread-1 TS_METRICS - MemoryUsed.Megabytes:6880.48046875|#Level:Host|#hostname:DESKTOP-AKBS7RC,timestamp:1606584031
2020-11-28 19:20:31,064 [INFO ] pool-2-thread-1 TS_METRICS - MemoryUtilization.Percent:42.1|#Level:Host|#hostname:DESKTOP-AKBS7RC,timestamp:1606584031
2020-11-28 19:20:32,106 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Listening on port: None
2020-11-28 19:20:32,107 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - [PID]3672
2020-11-28 19:20:32,107 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Torch worker started.
2020-11-28 19:20:32,107 [DEBUG] W-9000-mm_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-mm_1.0 State change WORKER_STOPPED -> WORKER_STARTED
2020-11-28 19:20:32,108 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Python runtime: 3.8.5
2020-11-28 19:20:32,108 [INFO ] W-9000-mm_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /127.0.0.1:9000
2020-11-28 19:20:32,110 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Connection accepted: ('127.0.0.1', 9000).
2020-11-28 19:20:32,122 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Backend worker process died.
2020-11-28 19:20:32,122 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Traceback (most recent call last):
2020-11-28 19:20:32,122 [INFO ] nioEventLoopGroup-5-2 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_STARTED
2020-11-28 19:20:32,122 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "d:\anaconda3\envs\tf\lib\site-packages\ts\model_loader.py", line 84, in load
2020-11-28 19:20:32,123 [DEBUG] W-9000-mm_1.0 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_STARTED
2020-11-28 19:20:32,123 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     module = importlib.import_module(module_name)
2020-11-28 19:20:32,123 [DEBUG] W-9000-mm_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133)
        at java.base/java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:432)
        at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:129)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
2020-11-28 19:20:32,124 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "d:\anaconda3\envs\tf\lib\importlib\__init__.py", line 127, in import_module
2020-11-28 19:20:32,124 [WARN ] W-9000-mm_1.0 org.pytorch.serve.wlm.BatchAggregator - Load model failed: mm, error: Worker died.
2020-11-28 19:20:32,125 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     return _bootstrap._gcd_import(name[level:], package, level)
2020-11-28 19:20:32,125 [DEBUG] W-9000-mm_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-mm_1.0 State change WORKER_STARTED -> WORKER_STOPPED
2020-11-28 19:20:32,125 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2020-11-28 19:20:32,126 [WARN ] W-9000-mm_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-mm_1.0-stderr
2020-11-28 19:20:32,127 [INFO ] W-9000-mm_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-mm_1.0-stderr
2020-11-28 19:20:32,126 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2020-11-28 19:20:32,127 [WARN ] W-9000-mm_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-mm_1.0-stdout
2020-11-28 19:20:32,129 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2020-11-28 19:20:32,129 [INFO ] W-9000-mm_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9000 in 1 seconds.
2020-11-28 19:20:32,129 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-mm_1.0-stdout
2020-11-28 19:20:33,224 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Listening on port: None
2020-11-28 19:20:33,224 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - [PID]11012
2020-11-28 19:20:33,225 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Torch worker started.
2020-11-28 19:20:33,225 [DEBUG] W-9000-mm_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-mm_1.0 State change WORKER_STOPPED -> WORKER_STARTED
2020-11-28 19:20:33,226 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Python runtime: 3.8.5
2020-11-28 19:20:33,226 [INFO ] W-9000-mm_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /127.0.0.1:9000
2020-11-28 19:20:33,228 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Connection accepted: ('127.0.0.1', 9000).
2020-11-28 19:20:33,239 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Backend worker process died.
2020-11-28 19:20:33,239 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Traceback (most recent call last):
2020-11-28 19:20:33,240 [INFO ] nioEventLoopGroup-5-3 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_STARTED
2020-11-28 19:20:33,240 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "d:\anaconda3\envs\tf\lib\site-packages\ts\model_loader.py", line 84, in load
2020-11-28 19:20:33,240 [DEBUG] W-9000-mm_1.0 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_STARTED
2020-11-28 19:20:33,241 [INFO ] W-9000-mm_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     module = importlib.import_module(module_name)
2020-11-28 19:20:33,241 [DEBUG] W-9000-mm_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133)
        at java.base/java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:432)
        at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:129)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by duckroll** [comment]
Oops, I didnt install detectron2.
