### ISSUE TITLE
Deploying Model with Custom handler, error in module = importlib.import_module(module_name)

### ISSUE THREAD

**Issue by Aldo-Aditiya** [pytorch/serve#849]
## Context

I'm trying to deploy a custom model, and I faced some bugs. Problem is, the ts_log doesn't seem to provide enough information 

* torchserve version: 0.2.0
* torch version: 1.6.0
* torchvision version [if any]: 0.7.0
* java version: not sure (I used pytorch/torchserve latest, taken from 19th of November)
* Operating System and version: Ubuntu 20.04, running the serving on Docker

## Your Environment

* Installed using source? [yes/no]: no
* Are you planning to deploy it using docker container? [yes/no]: yes
* Is it a CPU or GPU environment?: GPU
* Using a default/custom handler? [If possible upload/share custom handler/model]: custom, https://drive.google.com/file/d/1pZyb4F4K61nlpf3YR-dHeqPGPlW_shcY/view?usp=sharing
* What kind of model is it e.g. vision, text, audio?: vision
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs: attached in the error log below

## Expected Behavior

The worker doesn't die, and a clear information to debug

## Current Behavior

The worker died, and the log doesn't seem to capture enough info to debug. The closest that I think is relevant is this messageL
```
File "/home/venv/lib/python3.6/site-packages/ts/model_loader.py", line 84, in load
    module = importlib.import_module(module_name)
```

## Steps to Reproduce

1. Run this script to achieve model.mar
```
torch-model-archiver --model-name efdet_vehicle \
	--version 1.0 \
	--serialized-file /workspace/_model/efdet_02-12-20/efdet_02-12-20/efficientdet-d2_29_22000.pth \
	--export-path /workspace/_model/efdet_02-12-20/serve \
	--extra-files /workspace/_model/efdet_02-12-20/serve/index_to_name.json,/workspace/_model/efdet_02-12-20/serve/dep.zip \
	--handler /workspace/_model/efdet_02-12-20/serve/handler.py
```

2.Serve the generated MAR
```
torchserve --start --ncs \
	--ts-config /workspace/_model/efdet_02-12-20/serve/config.properties \
	--model-store /workspace/_model/efdet_02-12-20/serve  \
	--models efdet_vehicle=efdet_vehicle.mar
```

## Failure Logs [if any]

```
2020-12-09 10:53:06,574 [INFO ] main org.pytorch.serve.ModelServer - 
Torchserve version: 0.2.0
TS Home: /home/venv/lib/python3.6/site-packages
Current directory: /workspace/_model/efdet_02-12-20/serve
Temp directory: /home/model-server/tmp
Number of GPUs: 1
Number of CPUs: 12
Max heap size: 3986 M
Python executable: /home/venv/bin/python3
Config file: /workspace/_model/efdet_02-12-20/serve/config.properties
Inference address: http://0.0.0.0:21212
Management address: http://127.0.0.1:8081
Metrics address: http://127.0.0.1:8082
Model Store: /workspace/_model/efdet_02-12-20/serve
Initial Models: efdet_vehicle=efdet_vehicle.mar
Log dir: /workspace/_model/efdet_02-12-20/serve/logs
Metrics dir: /workspace/_model/efdet_02-12-20/serve/logs
Netty threads: 0
Netty client threads: 0
Default workers per model: 1
Blacklist Regex: N/A
Maximum Response Size: 6553500
Maximum Request Size: 6553500
Prefer direct buffer: false
Custom python dependency for model allowed: false
Metrics report format: prometheus
Enable metrics API: true
2020-12-09 10:53:06,596 [INFO ] main org.pytorch.serve.ModelServer - Loading initial models: efdet_vehicle.mar
2020-12-09 10:53:07,046 [INFO ] main org.pytorch.serve.archive.ModelArchive - eTag d8277dafb9304de5b2ea4263f185eb0e
2020-12-09 10:53:07,053 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Adding new version 1.0 for model efdet_vehicle
2020-12-09 10:53:07,053 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Setting default version to 1.0 for model efdet_vehicle
2020-12-09 10:53:07,054 [INFO ] main org.pytorch.serve.wlm.ModelManager - Model efdet_vehicle loaded.
2020-12-09 10:53:07,054 [DEBUG] main org.pytorch.serve.wlm.ModelManager - updateModel: efdet_vehicle, count: 1
2020-12-09 10:53:07,061 [INFO ] main org.pytorch.serve.ModelServer - Initialize Inference server with: EpollServerSocketChannel.
2020-12-09 10:53:07,109 [INFO ] main org.pytorch.serve.ModelServer - Inference API bind to: http://0.0.0.0:21212
2020-12-09 10:53:07,109 [INFO ] main org.pytorch.serve.ModelServer - Initialize Management server with: EpollServerSocketChannel.
2020-12-09 10:53:07,110 [INFO ] main org.pytorch.serve.ModelServer - Management API bind to: http://127.0.0.1:8081
2020-12-09 10:53:07,111 [INFO ] main org.pytorch.serve.ModelServer - Initialize Metrics server with: EpollServerSocketChannel.
2020-12-09 10:53:07,111 [INFO ] main org.pytorch.serve.ModelServer - Metrics API bind to: http://127.0.0.1:8082
2020-12-09 10:53:07,114 [WARN ] pool-2-thread-1 org.pytorch.serve.metrics.MetricCollector - worker pid is not available yet.
2020-12-09 10:53:07,151 [INFO ] W-9000-efdet_vehicle_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Listening on port: /home/model-server/tmp/.ts.sock.9000
2020-12-09 10:53:07,151 [INFO ] W-9000-efdet_vehicle_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - [PID]700
2020-12-09 10:53:07,151 [INFO ] W-9000-efdet_vehicle_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Torch worker started.
2020-12-09 10:53:07,152 [INFO ] W-9000-efdet_vehicle_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Python runtime: 3.6.9
2020-12-09 10:53:07,152 [DEBUG] W-9000-efdet_vehicle_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-efdet_vehicle_1.0 State change null -> WORKER_STARTED
2020-12-09 10:53:07,155 [INFO ] W-9000-efdet_vehicle_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /home/model-server/tmp/.ts.sock.9000
2020-12-09 10:53:07,165 [INFO ] W-9000-efdet_vehicle_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Connection accepted: /home/model-server/tmp/.ts.sock.9000.
2020-12-09 10:53:07,200 [INFO ] W-9000-efdet_vehicle_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Backend worker process died.
2020-12-09 10:53:07,200 [INFO ] W-9000-efdet_vehicle_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Traceback (most recent call last):
2020-12-09 10:53:07,200 [INFO ] W-9000-efdet_vehicle_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/venv/lib/python3.6/site-packages/ts/model_service_worker.py", line 176, in <module>
2020-12-09 10:53:07,200 [INFO ] W-9000-efdet_vehicle_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     worker.run_server()
2020-12-09 10:53:07,200 [INFO ] epollEventLoopGroup-5-1 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_STARTED
2020-12-09 10:53:07,201 [INFO ] W-9000-efdet_vehicle_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/venv/lib/python3.6/site-packages/ts/model_service_worker.py", line 148, in run_server
2020-12-09 10:53:07,201 [DEBUG] W-9000-efdet_vehicle_1.0 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_STARTED
2020-12-09 10:53:07,201 [INFO ] W-9000-efdet_vehicle_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     self.handle_connection(cl_socket)
2020-12-09 10:53:07,201 [INFO ] W-9000-efdet_vehicle_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/venv/lib/python3.6/site-packages/ts/model_service_worker.py", line 112, in handle_connection
2020-12-09 10:53:07,201 [DEBUG] W-9000-efdet_vehicle_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133)
	at java.base/java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:432)
	at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:129)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-12-09 10:53:07,201 [INFO ] W-9000-efdet_vehicle_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     service, result, code = self.load_model(msg)
2020-12-09 10:53:07,202 [INFO ] W-9000-efdet_vehicle_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/venv/lib/python3.6/site-packages/ts/model_service_worker.py", line 85, in load_model
2020-12-09 10:53:07,202 [WARN ] W-9000-efdet_vehicle_1.0 org.pytorch.serve.wlm.BatchAggregator - Load model failed: efdet_vehicle, error: Worker died.
2020-12-09 10:53:07,203 [INFO ] W-9000-efdet_vehicle_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     service = model_loader.load(model_name, model_dir, handler, gpu, batch_size)
2020-12-09 10:53:07,203 [DEBUG] W-9000-efdet_vehicle_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-efdet_vehicle_1.0 State change WORKER_STARTED -> WORKER_STOPPED
2020-12-09 10:53:07,203 [INFO ] W-9000-efdet_vehicle_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/venv/lib/python3.6/site-packages/ts/model_loader.py", line 84, in load
2020-12-09 10:53:07,203 [INFO ] W-9000-efdet_vehicle_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     module = importlib.import_module(module_name)
2020-12-09 10:53:07,203 [WARN ] W-9000-efdet_vehicle_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-efdet_vehicle_1.0-stderr
2020-12-09 10:53:07,203 [WARN ] W-9000-efdet_vehicle_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-efdet_vehicle_1.0-stdout
2020-12-09 10:53:07,203 [INFO ] W-9000-efdet_vehicle_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
2020-12-09 10:53:07,204 [INFO ] W-9000-efdet_vehicle_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-efdet_vehicle_1.0-stdout
2020-12-09 10:53:07,204 [INFO ] W-9000-efdet_vehicle_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9000 in 1 seconds.
2020-12-09 10:53:07,204 [INFO ] W-9000-efdet_vehicle_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-efdet_vehicle_1.0-stderr
2020-12-09 10:53:08,279 [INFO ] W-9000-efdet_vehicle_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Listening on port: /home/model-server/tmp/.ts.sock.9000
```

**Comment by harshbafna** [comment]
@Aldo-Aditiya: Could you share the `mar` file for this model?

I am suspecting one of the following `import` statements are failing:
```
from backbone import EfficientDetBackbone
from efficientdet.utils import BBoxTransform, ClipBoxes
```

**Comment by Aldo-Aditiya** [comment]
The MAR file is attached here:
https://drive.google.com/file/d/1M5E-a8_Y3IEqezyKsGKfcEEs9NtrQWwp/view?usp=sharing

**Comment by Aldo-Aditiya** [comment]
After exploring my code a bit, I have a suspicion it's because I haven't installed "pycocotools" though I couldn't verify this until tomorrow.

But aside from that, do you have any suggestions to make errors from such missing imports more visible in the debug log? Something perhaps a bit more verbose than the one below?
```
File "/home/venv/lib/python3.6/site-packages/ts/model_loader.py", line 84, in load
    module = importlib.import_module(module_name)
```

**Comment by harshbafna** [comment]
> After exploring my code a bit, I have a suspicion it's because I haven't installed "pycocotools" though I couldn't verify this until tomorrow.
> 
> But aside from that, do you have any suggestions to make errors from such missing imports more visible in the debug log? Something perhaps a bit more verbose than the one below?
> 
> ```
> File "/home/venv/lib/python3.6/site-packages/ts/model_loader.py", line 84, in load
>     module = importlib.import_module(module_name)
> ```

The code has been refactored in the latest master and there have been some fixes related to logging as well.

**Comment by Aldo-Aditiya** [comment]
I've tried installing "pycocotools" but it doesn't seem to solve it. I'll try using a newer version of the code to see if the new logging fix would help

**Comment by harshbafna** [comment]
@Aldo-Aditiya: I checked your mar file and there are a bunch of import issues with your handler file. For e.g.,

 - Usage of undefined variables
 - Usage of undefined functions
 - Missing various import statements

Simply extract the mar file in a directory and load the directory in any Python IDE like PyCharm should help you see the errors in the handler.

You can always test your custom handler by manually executing the script before deploying it on TorchServe.

**Comment by Aldo-Aditiya** [comment]
Thank you, will do so - and will also note your suggestion to extract the mar file for debugging it. 

As the problem seems to stem from my fault, I will close the issue for now. Many thanks!
