### ISSUE TITLE
Torchserve fails to run. Uses too much resources

### ISSUE THREAD

**Issue by jagadeeshi2i** [pytorch/serve#887]
Torchserve stops running on GPU resource throwing below error. Upon increasing the resources torchserve works as intended. 

```
2020-12-12 18:54:44,167 [INFO ] main org.pytorch.serve.ModelServer - 
Torchserve version: 0.3.0
TS Home: /usr/local/lib/python3.6/dist-packages
Current directory: /home/model-server
Temp directory: /home/model-server/tmp
Number of GPUs: 1
Number of CPUs: 1
Max heap size: 494 M
Python executable: /usr/bin/python3
Config file: /mnt/models/config/config.properties
Inference address: http://0.0.0.0:8085
Management address: http://0.0.0.0:8081
Metrics address: http://127.0.0.1:8082
Model Store: /mnt/pvc/model-store
Initial Models: N/A
Log dir: /home/model-server/logs
Metrics dir: /home/model-server/logs
Netty threads: 4
Netty client threads: 0
Default workers per model: 1
Blacklist Regex: N/A
Maximum Response Size: 6553500
Maximum Request Size: 6553500
Prefer direct buffer: false
Allowed Urls: [file://.*|http(s)?://.*]
Custom python dependency for model allowed: true
Metrics report format: prometheus
Enable metrics API: true
2020-12-12 18:54:44,258 [INFO ] main org.pytorch.serve.snapshot.SnapshotManager - Started restoring models from snapshot {"name":"startup.cfg","modelCount":1,"models":{"mnist":{"1.0":{"defaultVersion":true,"marName":"mnist_new_1.mar","minWorkers":1,"maxWorkers":5,"batchSize":1,"maxBatchDelay":5000,"responseTimeout":120}}}}
2020-12-12 18:54:44,333 [INFO ] main org.pytorch.serve.snapshot.SnapshotManager - Validating snapshot startup.cfg
2020-12-12 18:54:44,336 [INFO ] main org.pytorch.serve.snapshot.SnapshotManager - Snapshot startup.cfg validated successfully
2020-12-12 18:54:45,142 [INFO ] main org.pytorch.serve.archive.ModelArchive - eTag fddbcdc036fb4690adbc7db266afef01
2020-12-12 18:54:45,150 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Adding new version 1.0 for model mnist
2020-12-12 18:54:45,150 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Setting default version to 1.0 for model mnist
2020-12-12 18:54:45,150 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Setting default version to 1.0 for model mnist
2020-12-12 18:54:45,150 [INFO ] main org.pytorch.serve.wlm.ModelManager - Model mnist loaded.
2020-12-12 18:54:45,150 [DEBUG] main org.pytorch.serve.wlm.ModelManager - updateModel: mnist, count: 1
2020-12-12 18:54:45,233 [INFO ] main org.pytorch.serve.ModelServer - Initialize Inference server with: EpollServerSocketChannel.
2020-12-12 18:54:45,536 [INFO ] main org.pytorch.serve.ModelServer - Inference API bind to: http://0.0.0.0:8085
2020-12-12 18:54:45,536 [INFO ] main org.pytorch.serve.ModelServer - Initialize Management server with: EpollServerSocketChannel.
2020-12-12 18:54:45,537 [INFO ] main org.pytorch.serve.ModelServer - Management API bind to: http://0.0.0.0:8081
2020-12-12 18:54:45,537 [INFO ] main org.pytorch.serve.ModelServer - Initialize Metrics server with: EpollServerSocketChannel.
2020-12-12 18:54:45,537 [INFO ] main org.pytorch.serve.ModelServer - Metrics API bind to: http://127.0.0.1:8082
2020-12-12 18:54:45,558 [INFO ] W-10000-mnist_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Listening on port: /home/model-server/tmp/.ts.sock.10000
2020-12-12 18:54:45,633 [INFO ] W-10000-mnist_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - [PID]91
2020-12-12 18:54:45,633 [INFO ] W-10000-mnist_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Torch worker started.
2020-12-12 18:54:45,633 [INFO ] W-10000-mnist_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Python runtime: 3.6.9
2020-12-12 18:54:45,634 [DEBUG] W-10000-mnist_1.0 org.pytorch.serve.wlm.WorkerThread - W-10000-mnist_1.0 State change null -> WORKER_STARTED
2020-12-12 18:54:45,639 [INFO ] W-10000-mnist_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /home/model-server/tmp/.ts.sock.10000
2020-12-12 18:54:45,650 [INFO ] W-10000-mnist_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Connection accepted: /home/model-server/tmp/.ts.sock.10000.
Model server started.
[I 201212 18:54:46 __main__:68] Wrapper : Model names ['mnist'], inference address http//0.0.0.0:8085, management address http://0.0.0.0:8081, model store /mnt/models/model-store
[I 201212 18:54:46 TorchserveModel:48] kfmodel Predict URL set to 0.0.0.0:8085
[I 201212 18:54:46 TorchserveModel:50] kfmodel Explain URL set to 0.0.0.0:8085
[I 201212 18:54:46 TSModelRepository:26] TSModelRepo is initialized
[I 201212 18:54:46 kfserver:115] Registering model: mnist
[I 201212 18:54:46 kfserver:96] Listening on port 8080
[I 201212 18:54:46 kfserver:98] Will fork 1 workers
2020-12-12 18:54:46,842 [INFO ] pool-2-thread-1 TS_METRICS - CPUUtilization.Percent:0.0|#Level:Host|#hostname:torch-pred-gpu-predictor-default-nj2qs-deployment-7f687bfb8zf9b,timestamp:1607799286
2020-12-12 18:54:46,843 [INFO ] pool-2-thread-1 TS_METRICS - DiskAvailable.Gigabytes:54.05517578125|#Level:Host|#hostname:torch-pred-gpu-predictor-default-nj2qs-deployment-7f687bfb8zf9b,timestamp:1607799286
2020-12-12 18:54:46,843 [INFO ] pool-2-thread-1 TS_METRICS - DiskUsage.Gigabytes:25.933086395263672|#Level:Host|#hostname:torch-pred-gpu-predictor-default-nj2qs-deployment-7f687bfb8zf9b,timestamp:1607799286
2020-12-12 18:54:46,843 [INFO ] pool-2-thread-1 TS_METRICS - DiskUtilization.Percent:32.4|#Level:Host|#hostname:torch-pred-gpu-predictor-default-nj2qs-deployment-7f687bfb8zf9b,timestamp:1607799286
2020-12-12 18:54:46,843 [INFO ] pool-2-thread-1 TS_METRICS - MemoryAvailable.Megabytes:755181.0390625|#Level:Host|#hostname:torch-pred-gpu-predictor-default-nj2qs-deployment-7f687bfb8zf9b,timestamp:1607799286
2020-12-12 18:54:46,844 [INFO ] pool-2-thread-1 TS_METRICS - MemoryUsed.Megabytes:6224.3984375|#Level:Host|#hostname:torch-pred-gpu-predictor-default-nj2qs-deployment-7f687bfb8zf9b,timestamp:1607799286
2020-12-12 18:54:46,844 [INFO ] pool-2-thread-1 TS_METRICS - MemoryUtilization.Percent:1.4|#Level:Host|#hostname:torch-pred-gpu-predictor-default-nj2qs-deployment-7f687bfb8zf9b,timestamp:1607799286
2020-12-12 18:54:47,181 [INFO ] W-10000-mnist_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Generating new fontManager, this may take some time...
2020-12-12 18:54:47,589 [INFO ] W-10000-mnist_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - the device name is cuda:0
2020-12-12 18:54:51,632 [INFO ] W-10000-mnist_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-10000-mnist_1.0-stdout
2020-12-12 18:54:51,632 [INFO ] W-10000-mnist_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-10000-mnist_1.0-stderr
2020-12-12 18:54:51,634 [INFO ] epollEventLoopGroup-5-1 org.pytorch.serve.wlm.WorkerThread - 10000 Worker disconnected. WORKER_STARTED
2020-12-12 18:54:51,634 [DEBUG] W-10000-mnist_1.0 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_STARTED
2020-12-12 18:54:51,635 [DEBUG] W-10000-mnist_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133)
	at java.base/java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:432)
	at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:188)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-12-12 18:54:51,636 [WARN ] W-10000-mnist_1.0 org.pytorch.serve.wlm.BatchAggregator - Load model failed: mnist, error: Worker died.
2020-12-12 18:54:51,637 [DEBUG] W-10000-mnist_1.0 org.pytorch.serve.wlm.WorkerThread - W-10000-mnist_1.0 State change WORKER_STARTED -> WORKER_STOPPED
```

## Context

* torchserve version:
* torch-model-archiver version:
* torch version:
* torchvision version [if any]:
* torchtext version [if any]:
* torchaudio version [if any]:
* java version:
* Operating System and version:

## Your Environment

* Installed using source? [yes/no]:no
* Are you planning to deploy it using docker container? [yes/no]:yes - Kubernetes environment
* Is it a CPU or GPU environment?: cuda:11.1-cudnn8-runtime-ubuntu18.04
* Using a default/custom handler? [If possible upload/share custom handler/model]:
* What kind of model is it e.g. vision, text, audio?:vision- mnist
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
  [If public url then provide link.]:
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs:[config.properties.txt](https://github.com/pytorch/serve/files/5683614/config.properties.txt)

* Link to your project [if any]: 

## Steps to Reproduce

1.
2.
...

**Comment by fbbradheintz** [comment]
@jagadeeshi2i How much RAM was allocated to the Docker container?

**Comment by msaroufim** [comment]
Hi @jagadeeshi2i, it looks like your CPU, RAM and Disk look fine. What do you mean by increasing your GPU resources? Did you increase the number of GPUs? The on device memory of the GPU? Or did you configure the parameters of your docker container

2020-12-12 18:54:46,842 [INFO ] pool-2-thread-1 TS_METRICS - CPUUtilization.Percent:0.0|#Level:Host|#hostname:torch-pred-gpu-predictor-default-nj2qs-deployment-7f687bfb8zf9b,timestamp:1607799286
2020-12-12 18:54:46,843 [INFO ] pool-2-thread-1 TS_METRICS - DiskUtilization.Percent:32.4|#Level:Host|#hostname:torch-pred-gpu-predictor-default-nj2qs-deployment-7f687bfb8zf9b,timestamp:1607799286
2020-12-12 18:54:46,844 [INFO ] pool-2-thread-1 TS_METRICS - MemoryUtilization.Percent:1.4|#Level:Host|#hostname:torch-pred-gpu-predictor-default-nj2qs-deployment-7f687bfb8zf9b,timestamp:1607799286

**Comment by HeroadZ** [comment]
face the same issue here.
Works fine locally but fails in k8s environment.

**Comment by HeroadZ** [comment]
@fbbradheintz @msaroufim Could you give me some advice?

**Comment by jagadeeshi2i** [comment]
Did you try increasing memory in k8s deployment

**Comment by HeroadZ** [comment]
@jagadeeshi2i 
yes, the default cpu is 0.5v and memory is 256M for 1 pod. I have increased it to 1 vCPU and 1G memory. But it not works.

**Comment by HeroadZ** [comment]
@jagadeeshi2i @fbbradheintz @msaroufim 
Increasing memory to 2G works. Torchserve really eats a lot 😢

**Comment by ronit29** [comment]
Saved the day.

But can someone tell me if Torchserve is memory bound(even when a GPU is used), or it only requires a specific amount of memory for Model Loading only.
@jagadeeshi2i , @fbbradheintz , @msaroufim , @HeroadZ 

Thanks!

**Comment by HeroadZ** [comment]
@ronit29  don't know the answer. But it seems like that fastapi+pytorch+docker also needs 2G memory to work if I remember it correctly.
