### ISSUE TITLE
kfserving failed to predict 

### ISSUE THREAD

**Issue by lxning** [pytorch/serve#890]
Please have a look at [FAQ's](../../docs/FAQs.md) and [Troubleshooting guide](../../docs/Troubleshooting.md), your query may be already addressed.

Your issue may already be reported!
Please search on the [issue tracker](https://github.com/pytorch/serve/issues) before creating one.

## Context

* torchserve version: 0.3.0
* torch-model-archiver version:
* torch version: 
* torchvision version [if any]:
* torchtext version [if any]:
* torchaudio version [if any]:
* java version:
* Operating System and version:

## Your Environment

* Installed using source? [yes/no]: yes
* Are you planning to deploy it using docker container? [yes/no]: yes
* Is it a CPU or GPU environment?: CPU
* Using a default/custom handler? [If possible upload/share custom handler/model]:
* What kind of model is it e.g. vision, text, audio?: bert
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
  [If public url then provide link.]: https://torchserve.s3.amazonaws.com/mar_files/BERTSeqClassification_Torchscript_batch.mar
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs:
config.properties:
inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081

number_of_netty_threads=32
job_queue_size=1000

model_store=/home/ubuntu/model-store
load_models=benchmark:bert.mar
service_envelope=kfserving
model_snapshot={"name":"startup.cfg","modelCount":1,"models":{"benchmark":{"1.0":{"defaultVersion":true,"marName":"bert.mar","minWorkers":1,"maxWorkers":2,"batchSize":2,"maxBatchDelay":200,"responseTimeout":60}}}}

log:
2020-12-13 04:16:45,043 [INFO ] W-9000-benchmark_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Parsing input in KFServing.py
2020-12-13 04:16:45,043 [INFO ] W-9000-benchmark_1.0 org.pytorch.serve.wlm.WorkerThread - Backend response time: 0
2020-12-13 04:16:45,044 [INFO ] W-9000-benchmark_1.0 ACCESS_LOG - /127.0.0.1:46788 "POST /v1/models/benchmark:explain HTTP/1.1" 503 202
2020-12-13 04:16:45,044 [INFO ] W-9000-benchmark_1.0 TS_METRICS - Requests5XX.Count:1|#Level:Host|#hostname:ip-172-31-0-171,timestamp:null
2020-12-13 04:16:45,044 [INFO ] W-9000-benchmark_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Parse input data_list [{'question': 'How is the weather in summer', 'context': 'it is hot and dry and not cold'}]
2020-12-13 04:16:45,044 [DEBUG] W-9000-benchmark_1.0 org.pytorch.serve.job.Job - Waiting time ns: 200296693, Inference time ns: 201826128
2020-12-13 04:16:45,044 [INFO ] W-9000-benchmark_1.0 TS_METRICS - WorkerThreadTime.ms:2|#Level:Host|#hostname:ip-172-31-0-171,timestamp:null
2020-12-13 04:16:45,044 [INFO ] W-9000-benchmark_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - KFServing parsed inputs None
2020-12-13 04:16:45,044 [INFO ] W-9000-benchmark_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Invoking custom service failed.
2020-12-13 04:16:45,045 [INFO ] W-9000-benchmark_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Traceback (most recent call last):
2020-12-13 04:16:45,045 [INFO ] W-9000-benchmark_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ts/service.py", line 100, in predict
2020-12-13 04:16:45,045 [INFO ] W-9000-benchmark_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     ret = self._entry_point(input_batch, self.context)
2020-12-13 04:16:45,046 [INFO ] W-9000-benchmark_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ts/torch_handler/request_envelope/base.py", line 28, in handle
2020-12-13 04:16:45,046 [INFO ] W-9000-benchmark_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     results = self._handle_fn(data, context)
2020-12-13 04:16:45,046 [INFO ] W-9000-benchmark_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/ts/torch_handler/base_handler.py", line 194, in handle
2020-12-13 04:16:45,046 [INFO ] W-9000-benchmark_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     data_preprocess = self.preprocess(data)
2020-12-13 04:16:45,047 [INFO ] W-9000-benchmark_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -   File "/tmp/models/ec671753c5474b2fa94616aa0ee1e35e/Transformer_handler_generalized.py", line 77, in preprocess
2020-12-13 04:16:45,047 [INFO ] W-9000-benchmark_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle -     for idx, data in enumerate(requests):
2020-12-13 04:16:45,047 [INFO ] W-9000-benchmark_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - TypeError: 'NoneType' object is not iterable

* Link to your project [if any]:

## Steps to Reproduce

mar: https://torchserve.s3.amazonaws.com/mar_files/BERTSeqClassification_Torchscript_batch.mar
input data: https://github.com/pytorch/serve/blob/master/examples/Huggingface_Transformers/QA_artifacts/sample_text0.txt
 curl -H "Content-Type: application/json" --data @examples/Huggingface_Transformers/QA_artifacts/sample_text0.txt http://127.0.0.1:8080/v1/models/benchmark:explain
{
  "code": 503,
  "type": "InternalServerException",
  "message": "Prediction failed"
}

**Comment by chauhang** [comment]
@lxning Explain is not supported for TorchScripted models. Docs will be updated for this. Captum does not support torchscripted models at present. Please test with eager mode version of the model

**Comment by lxning** [comment]
vgg11 model also failed.
mar: https://torchserve.pytorch.org/mar_files/vgg11_v2.mar
input data: [kitten](https://github.com/pytorch/serve/blob/bacdf0a626fc24d89f332c413a2039f7c0cf9953/examples/image_classifier/kitten.jpg)) json format converted by [img2bytearray.py](https://github.com/pytorch/serve/blob/master/kubernetes/kfserving/img2bytearray.py), or [input.json](https://github.com/pytorch/serve/blob/master/kubernetes/kfserving/image_transformer/input.json)

**Comment by lxning** [comment]
vgg11 also failed to predict 

mars: https://torchserve.pytorch.org/mar_files/vgg11_v2.mar
input data: [kitten](https://github.com/pytorch/serve/blob/bacdf0a626fc24d89f332c413a2039f7c0cf9953/examples/image_classifier/kitten.jpg) json format converted by [img2bytearray.py](https://github.com/pytorch/serve/blob/master/kubernetes/kfserving/img2bytearray.py)    , or [input.json](https://github.com/pytorch/serve/blob/master/kubernetes/kfserving/image_transformer/input.json)

**Comment by abishekchiffon** [comment]
> vgg11 also failed to predict
> 
> mars: https://torchserve.pytorch.org/mar_files/vgg11_v2.mar
> input data: [kitten](https://github.com/pytorch/serve/blob/bacdf0a626fc24d89f332c413a2039f7c0cf9953/examples/image_classifier/kitten.jpg) json format converted by [img2bytearray.py](https://github.com/pytorch/serve/blob/master/kubernetes/kfserving/img2bytearray.py) , or [input.json](https://github.com/pytorch/serve/blob/master/kubernetes/kfserving/image_transformer/input.json)

@lxning vgg11 model doesnot support explain for now. Only Mnist, Bert supports kfserving explain. Please attach logs of the vgg11 failure for more understanding.

**Comment by HamidShojanazeri** [comment]
@lxning I could reproduce the issue with prediction failure of kfserving using the [input.json](https://github.com/pytorch/serve/blob/master/kubernetes/kfserving/image_transformer/input.json), it needs to be modified and git rid of the inner key value of "image_bytes":{"b64":...}}", I have attached the modified version, in the logs. This suggest changes in https://github.com/pytorch/serve/blob/f3a6d7658fd68729a26eddcefa9243e3b79b5d18/kubernetes/kfserving/img2bytearray.py#L18 - L20. 
Also, please attach the error logs to give better visibility over the issue. 
Logs:
[output.logs.txt](https://github.com/pytorch/serve/files/5692070/output.logs.txt)

> https://torchserve.pytorch.org/mar_files/vgg11_v2.mar

**Comment by lxning** [comment]
@abishekchiffon, vgg11 failed to predit, not explain.
[ts_log.log](https://github.com/pytorch/serve/files/5692246/ts_log.log)

**Comment by lxning** [comment]
kfserving only works for mnist batch_size = 1, otherwise, it would fail.

**Comment by HamidShojanazeri** [comment]
> > vgg11 also failed to predict
> > mars: https://torchserve.pytorch.org/mar_files/vgg11_v2.mar
> > input data: [kitten](https://github.com/pytorch/serve/blob/bacdf0a626fc24d89f332c413a2039f7c0cf9953/examples/image_classifier/kitten.jpg) json format converted by [img2bytearray.py](https://github.com/pytorch/serve/blob/master/kubernetes/kfserving/img2bytearray.py) , or [input.json](https://github.com/pytorch/serve/blob/master/kubernetes/kfserving/image_transformer/input.json)
> 
> @lxning vgg11 model doesnot support explain for now. Only Mnist, Bert supports kfserving explain. Please attach logs of the vgg11 failure for more understanding.

@lxning I could reproduce the issue with prediction failure of kfserving using the [input.json](https://github.com/pytorch/serve/blob/master/kubernetes/kfserving/image_transformer/input.json) and make it working for prediction and explanation with following modifications, in the input.json, we need to change the key  "image_bytes" to "data" and need to change the [line](https://github.com/pytorch/serve/blob/f3a6d7658fd68729a26eddcefa9243e3b79b5d18/kubernetes/kfserving/image_transformer/image_transformer/image_transformer.py#L47) , to  instance["data"] ["b64"], we will make a PR to address this issue . Also, I recommend in case of using [img2bytearray.py](https://github.com/pytorch/serve/blob/master/kubernetes/kfserving/img2bytearray.py)  to convert the kitten, consider resizing the image first. I have attached the logs for input.json and the kitten(resized) converted version using the img2bytearray.py .

[converting_kitten_explain_prediciton.logs.txt](https://github.com/pytorch/serve/files/5692279/converting_kitten_explain_prediciton.logs.txt)

[input_json_predict_explain.logs.txt](https://github.com/pytorch/serve/files/5692286/input_json_predict_explain.logs.txt)
