### ISSUE TITLE
Failure running KFServing benchmarks w/ batch size 4 on CPU and GPU

### ISSUE THREAD

**Issue by fbbradheintz** [pytorch/serve#911]
## Context

Running benchmarks on CPU for KFServing API with batch size 4 fails consistently. Command line:

* torchserve version: 0.3.0rc
* torch version: 1.7.1
* java version: 11
* Operating System and version: Ubuntu 18

## Your Environment

* Installed using source? [yes/no]: yes
* Are you planning to deploy it using docker container? [yes/no]: no
* Is it a CPU or GPU environment?: CPU
* Using a default/custom handler? custom model handler for MNIST from TorchServe examples
* What kind of model is it e.g. vision, text, audio?: vision
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
  [If public url then provide link.]: https://torchserve.pytorch.org/mar_files/mnist.mar
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs:
* Link to your project [if any]:

## Expected Behavior

Benchmark should run to completion.

## Current Behavior

Benchmark fails immediately.

## Possible Solution

Uncertain - still investigating. I've excerpted what appears to be the relevant part of the TorchServe log below. It looks specifically like KFServing is failing on a batch size not equal to 1.

```
2020-12-16 17:20:02,051 [INFO ] epollEventLoopGroup-3-2 ACCESS_LOG - /127.0.0.1:51466 "POST /models?model_name=benchmark&url=https%3A%2F%2Ftorchserve.pytorch.org%2Fmar_files%2Fmnist.mar&batch_delay=200&batch_size=4&initial_workers=1&synchronous=true HTTP/1.1" 200 1509
2020-12-16 17:20:02,051 [INFO ] epollEventLoopGroup-3-2 TS_METRICS - Requests2XX.Count:1|#Level:Host|#hostname:ip-172-31-28-89,timestamp:null
2020-12-16 17:20:02,135 [INFO ] W-9000-benchmark_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Parsing input in KFServing.py
2020-12-16 17:20:02,137 [INFO ] W-9000-benchmark_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Parse input data_list [{'instances': [{'data': 'iVBORw0KGgoAAAANSUhEUgAAABwAAAAcCAAAAABXZoBIAAAAw0lEQVR4nGNgGFggVVj4/y8Q2GOR83n+58/fP0DwcSqmpNN7oOTJw6f+/H2pjUU2JCSEk0EWqN0cl828e/FIxvz9/9cCh1zS5z9/G9mwyzl/+PNnKQ45nyNAr9ThMHQ/UG4tDofuB4bQIhz6fIBenMWJQ+7Vn7+zeLCbKXv6z59NOPQVgsIcW4QA9YFi6wNQLrKwsBebW/68DJ388Nun5XFocrqvIFH59+XhBAxThTfeB0r+vP/QHbuDCgr2JmOXoSsAAKK7bU3vISS4AAAAAElFTkSuQmCC', 'target': 0}]}, {'instances': [{'data': 'iVBORw0KGgoAAAANSUhEUgAAABwAAAAcCAAAAABXZoBIAAAAw0lEQVR4nGNgGFggVVj4/y8Q2GOR83n+58/fP0DwcSqmpNN7oOTJw6f+/H2pjUU2JCSEk0EWqN0cl828e/FIxvz9/9cCh1zS5z9/G9mwyzl/+PNnKQ45nyNAr9ThMHQ/UG4tDofuB4bQIhz6fIBenMWJQ+7Vn7+zeLCbKXv6z59NOPQVgsIcW4QA9YFi6wNQLrKwsBebW/68DJ388Nun5XFocrqvIFH59+XhBAxThTfeB0r+vP/QHbuDCgr2JmOXoSsAAKK7bU3vISS4AAAAAElFTkSuQmCC', 'target': 0}]}, {'instances': [{'data': 'iVBORw0KGgoAAAANSUhEUgAAABwAAAAcCAAAAABXZoBIAAAAw0lEQVR4nGNgGFggVVj4/y8Q2GOR83n+58/fP0DwcSqmpNN7oOTJw6f+/H2pjUU2JCSEk0EWqN0cl828e/FIxvz9/9cCh1zS5z9/G9mwyzl/+PNnKQ45nyNAr9ThMHQ/UG4tDofuB4bQIhz6fIBenMWJQ+7Vn7+zeLCbKXv6z59NOPQVgsIcW4QA9YFi6wNQLrKwsBebW/68DJ388Nun5XFocrqvIFH59+XhBAxThTfeB0r+vP/QHbuDCgr2JmOXoSsAAKK7bU3vISS4AAAAAElFTkSuQmCC', 'target': 0}]}, {'instances': [{'data': 'iVBORw0KGgoAAAANSUhEUgAAABwAAAAcCAAAAABXZoBIAAAAw0lEQVR4nGNgGFggVVj4/y8Q2GOR83n+58/fP0DwcSqmpNN7oOTJw6f+/H2pjUU2JCSEk0EWqN0cl828e/FIxvz9/9cCh1zS5z9/G9mwyzl/+PNnKQ45nyNAr9ThMHQ/UG4tDofuB4bQIhz6fIBenMWJQ+7Vn7+zeLCbKXv6z59NOPQVgsIcW4QA9YFi6wNQLrKwsBebW/68DJ388Nun5XFocrqvIFH59+XhBAxThTfeB0r+vP/QHbuDCgr2JmOXoSsAAKK7bU3vISS4AAAAAElFTkSuQmCC', 'target': 0}]}]
2020-12-16 17:20:02,137 [INFO ] W-9000-benchmark_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - KFServing parsed inputs [{'data': 'iVBORw0KGgoAAAANSUhEUgAAABwAAAAcCAAAAABXZoBIAAAAw0lEQVR4nGNgGFggVVj4/y8Q2GOR83n+58/fP0DwcSqmpNN7oOTJw6f+/H2pjUU2JCSEk0EWqN0cl828e/FIxvz9/9cCh1zS5z9/G9mwyzl/+PNnKQ45nyNAr9ThMHQ/UG4tDofuB4bQIhz6fIBenMWJQ+7Vn7+zeLCbKXv6z59NOPQVgsIcW4QA9YFi6wNQLrKwsBebW/68DJ388Nun5XFocrqvIFH59+XhBAxThTfeB0r+vP/QHbuDCgr2JmOXoSsAAKK7bU3vISS4AAAAAElFTkSuQmCC', 'target': 0}]
2020-12-16 17:20:02,141 [INFO ] W-9000-benchmark_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - The Response of KFServing [2]
2020-12-16 17:20:02,142 [INFO ] W-9000-benchmark_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - model: benchmark, number of batch response mismatched, expect: 4, got: 1.
2020-12-16 17:20:02,142 [INFO ] W-9000-benchmark_1.0-stdout MODEL_METRICS - HandlerTime.Milliseconds:5.97|#ModelName:benchmark,Level:Model|#hostname:ip-172-31-28-89,requestID:f3f65433-9132-4932-a18a-bf1c449fdde4,0daccff6-1abb-4b78-a406-f81f4afbf787,faf568fb-c9ec-4264-8cf7-ccd0aa9de33c,94856728-6cab-4e71-9547-819aa7286ea2,timestamp:1608139202
2020-12-16 17:20:02,143 [INFO ] W-9000-benchmark_1.0 org.pytorch.serve.wlm.WorkerThread - Backend response time: 9
2020-12-16 17:20:02,144 [INFO ] W-9000-benchmark_1.0 ACCESS_LOG - /127.0.0.1:52144 "POST /v1/models/benchmark:predict HTTP/1.0" 503 21
2020-12-16 17:20:02,144 [INFO ] W-9000-benchmark_1.0 TS_METRICS - Requests5XX.Count:1|#Level:Host|#hostname:ip-172-31-28-89,timestamp:null
2020-12-16 17:20:02,144 [DEBUG] W-9000-benchmark_1.0 org.pytorch.serve.job.Job - Waiting time ns: 351068, Inference time ns: 11093221
2020-12-16 17:20:02,144 [WARN ] W-9000-benchmark_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker thread exception.
java.util.ConcurrentModificationException
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.base/java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:741)
	at org.pytorch.serve.wlm.BatchAggregator.sendResponse(BatchAggregator.java:81)
	at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:194)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-12-16 17:20:02,147 [ERROR] W-9000-benchmark_1.0 org.pytorch.serve.wlm.BatchAggregator - Unexpected job: f3f65433-9132-4932-a18a-bf1c449fdde4
```

## Steps to Reproduce

1. Install from source, https://github.com/abishekchiffon/serve.git, branch kf_benchmark
2. Run the following benchmark script:
```
python benchmark-ab.py --url https://torchserve.pytorch.org/mar_files/mnist.mar --content_type application/json --config_properties config_kf.properties --inference_model_url v1/models/benchmark:predict --batch_size 4 --input ../kubernetes/kfserving/kf_request_json/mnist.json -r 10000
```
3. Observe failure:
```
...
*Generating CSV output...
Traceback (most recent call last):
  File "benchmark-ab.py", line 483, in <module>
    benchmark()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "benchmark-ab.py", line 108, in benchmark
    generate_report()
  File "benchmark-ab.py", line 268, in generate_report
    generate_csv_output()
  File "benchmark-ab.py", line 317, in generate_csv_output
    artifacts['TS error rate'] = int(artifacts['TS failed requests']) / execution_params['requests'] * 100
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

## Failure Logs [if any]

See attached file.
[model_metrics.log](https://github.com/pytorch/serve/files/5704446/model_metrics.log)

**Comment by fbbradheintz** [comment]
Just verified identical failure on GPU - so it does not appear to be specific to processor type.

**Comment by fbbradheintz** [comment]
It turns out this is expected, and relates to KFServing's static batching behavior, which has the beginnings of documentation at #910 . The two changes needed to make this work:
* Change batch size to 1 in command line
* Alter the input JSON as described in #910 to contain multiple data instances.

**Comment by harshbafna** [comment]
@fbbradheintz: Are we good to close this ticket as #910 is merged to master now?

**Comment by chauhang** [comment]
Documentation updated with details
