### ISSUE TITLE
Java errors on Google Compute Engine instance with Ubuntu 20.04

### ISSUE THREAD

**Issue by cbasavaraj** [pytorch/serve#935]
Hi, I am trying to use TorchServe on a Google Compute Engine instance, as I working from home. Earlier, I've used on a Ubuntu Desktop in our office without any issues. Now I am getting Java errors right after registering my models (three of them, all vision models). Appreciate any help.

## Context
* torchserve version: 0.3
* torch-model-archiver version: 0.3
* torch version: 1.8.0.dev20210104+cu110
* torchvision version [if any]: 0.9.0.dev20210104+cu110
* torchtext version [if any]: --
* torchaudio version [if any]: --
* java version: openjdk 11.0.9.1 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
* Operating System and version: Ubuntu 20.04

## Your Environment

* Installed using source? [yes/no]: no
* Are you planning to deploy it using docker container? [yes/no]: no
* Is it a CPU or GPU environment?: GPU
* Using a default/custom handler? [If possible upload/share custom handler/model]: custom handler
* What kind of model is it e.g. vision, text, audio?: vision
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
  [If public url then provide link.]: local models
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs: 
model_store=data/store
load_models=all
inference_address=https://0.0.0.0:8443
management_address=https://0.0.0.0:8444
metrics_address=https://0.0.0.0:8445
private_key_file=certs/moka.key
certificate_file=certs/moka.pem
* Link to your project [if any]:

## Expected Behavior
I think model registration was working fine a couple of days ago. 

## Current Behavior
Getting the Java lang errors below, even before I start sending inference requests from my client.

## Failure Logs [if any]
```
021-01-07 04:35:41,693 [INFO ] epollEventLoopGroup-5-2 org.pytorch.serve.wlm.WorkerThread - 9001 Worker disconnected. WORKER_MODEL_LOADED
2021-01-07 04:35:41,692 [INFO ] W-9001-db_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9001-db_1.0-stdout
2021-01-07 04:35:41,726 [DEBUG] W-9001-db_1.0 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_MODEL_LOADED
2021-01-07 04:35:41,736 [DEBUG] W-9001-db_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133)
        at java.base/java.util.concurrent.LinkedBlockingDeque.pollFirst(LinkedBlockingDeque.java:513)
        at java.base/java.util.concurrent.LinkedBlockingDeque.poll(LinkedBlockingDeque.java:675)
        at org.pytorch.serve.wlm.Model.pollBatch(Model.java:189)
        at org.pytorch.serve.wlm.BatchAggregator.getRequest(BatchAggregator.java:33)
        at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:182)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
2021-01-07 04:35:41,919 [DEBUG] W-9001-db_1.0 org.pytorch.serve.wlm.WorkerThread - W-9001-db_1.0 State change WORKER_MODEL_LOADED -> WORKER_STOPPED
2021-01-07 04:35:42,023 [WARN ] W-9001-db_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9001-db_1.0-stderr
2021-01-07 04:35:42,024 [WARN ] W-9001-db_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9001-db_1.0-stdout
2021-01-07 04:35:42,084 [INFO ] W-9001-db_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9001 in 1 seconds.
```

```
2021-01-07 04:35:49,650 [INFO ] W-9005-d2_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Loading checkpoint from s6_0087999_rf.pth
2021-01-07 04:36:58,448 [INFO ] W-9003-db_1.0 org.pytorch.serve.wlm.WorkerThread - Backend response time: 126578
2021-01-07 04:36:58,449 [INFO ] W-9000-db_1.0 org.pytorch.serve.wlm.WorkerThread - Backend response time: 126557
2021-01-07 04:36:58,449 [INFO ] W-9005-d2_1.0 org.pytorch.serve.wlm.WorkerThread - Backend response time: 126578
2021-01-07 04:37:08,980 [ERROR] W-9003-db_1.0 org.pytorch.serve.wlm.WorkerThread - Number or consecutive unsuccessful inference 3
2021-01-07 04:37:11,923 [ERROR] W-9005-d2_1.0 org.pytorch.serve.wlm.WorkerThread - Number or consecutive unsuccessful inference 2
2021-01-07 04:37:10,935 [ERROR] W-9000-db_1.0 org.pytorch.serve.wlm.WorkerThread - Number or consecutive unsuccessful inference 4
2021-01-07 04:37:39,556 [ERROR] W-9005-d2_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker error
org.pytorch.serve.wlm.WorkerInitializationException: Backend worker did not respond in given time
        at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:198)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

```
021-01-07 04:41:41,304 [INFO ] epollEventLoopGroup-5-4 org.pytorch.serve.wlm.WorkerThread - 9002 Worker disconnected. WORKER_MODEL_LOADED
2021-01-07 04:41:41,321 [DEBUG] W-9002-db_1.0 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_MODEL_LOADED
2021-01-07 04:41:41,329 [DEBUG] W-9002-db_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133)
        at java.base/java.util.concurrent.LinkedBlockingDeque.pollFirst(LinkedBlockingDeque.java:513)
        at java.base/java.util.concurrent.LinkedBlockingDeque.poll(LinkedBlockingDeque.java:675)
        at org.pytorch.serve.wlm.Model.pollBatch(Model.java:189)
        at org.pytorch.serve.wlm.BatchAggregator.getRequest(BatchAggregator.java:33)
        at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:182)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
2021-01-07 04:41:41,560 [DEBUG] W-9002-db_1.0 org.pytorch.serve.wlm.WorkerThread - W-9002-db_1.0 State change WORKER_MODEL_LOADED -> WORKER_STOPPED
2021-01-07 04:41:41,619 [WARN ] W-9002-db_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9002-db_1.0-stderr
2021-01-07 04:41:41,619 [WARN ] W-9002-db_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9002-db_1.0-stdout
2021-01-07 04:41:41,722 [INFO ] W-9002-db_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9002 in 1 seconds.
```

**Comment by cbasavaraj** [comment]
Managed to fix this. Turns out I was running out of RAM with the three models. Solved it by increasing the RAM on the instance. I wonder if TorchServe could make this more obvious?
