### ISSUE TITLE
RuntimeError: Could not run 'aten::empty_strided' with arguments from the 'QuantizedCUDA' backend.

### ISSUE THREAD

**Issue by collinarnett** [pytorch/serve#984]
Please have a look at [FAQ's](../../docs/FAQs.md) and [Troubleshooting guide](../../docs/Troubleshooting.md), your query may be already addressed.

Your issue may already be reported!
Please search on the [issue tracker](https://github.com/pytorch/serve/issues) before creating one.

## Context

Trying to use a quantized version of GPT2-XL for language generation. Currently deploying locally before moving to AWS Sagemaker.

* torchserve version:
`torchserve==0.3.0`
* torch-model-archiver version:
`torch-model-archiver==0.3.0`
* torch version:
`torch==1.7.1+cu110`
* torchvision version [if any]:
* torchtext version [if any]:
* torchaudio version [if any]:
* java version:
```
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)
```
* Operating System and version:
Ubuntu 18.04

## Your Environment

* RTX 3090 
* CUDA 11.1
* virtualenv

* Installed using source? [yes/no]:
No
* Are you planning to deploy it using docker container? [yes/no]:
Yes
* Is it a CPU or GPU environment?:
GPU
* Using a default/custom handler? [If possible upload/share custom handler/model]:
Custom Handler - https://pastebin.com/SbExmBFs
* What kind of model is it e.g. vision, text, audio?:
Quantized Torchscript HuggingFace GPT2-XL 
* Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.?
model store at the moment
* Provide config.properties, logs [ts.log] and parameters used for model registration/update APIs:
Logs - https://pastebin.com/Ryqb5JPx
Registration Command - `torchserve --start --model-store model_store --models litai=litai.mar  --foreground --no-config-snapshots`
* Link to your project [if any]:

## Expected Behavior

Model should load and be ready for inference.

## Current Behavior

From `ts_log.log` on running torchserve:
```
Traceback (most recent call last):
2021-02-27 07:02:21,065 [WARN ] W-9000-litai_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/collin/.virtualenvs/litai/lib/python3.8/site-packages/ts/model_service_worker.py", line 89, in load_model
2021-02-27 07:02:21,065 [WARN ] W-9000-litai_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle -     service = model_loader.load(model_name, model_dir, handler, gpu, batch_size, envelope)
2021-02-27 07:02:21,065 [WARN ] W-9000-litai_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/collin/.virtualenvs/litai/lib/python3.8/site-packages/ts/model_loader.py", line 104, in load
2021-02-27 07:02:21,066 [WARN ] W-9000-litai_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle -     initialize_fn(service.context)
2021-02-27 07:02:21,066 [WARN ] W-9000-litai_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/collin/.virtualenvs/litai/lib/python3.8/site-packages/ts/torch_handler/base_handler.py", line 70, in initialize
2021-02-27 07:02:21,066 [WARN ] W-9000-litai_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle -     self.model = self._load_torchscript_model(model_pt_path)
2021-02-27 07:02:21,066 [WARN ] W-9000-litai_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/collin/.virtualenvs/litai/lib/python3.8/site-packages/ts/torch_handler/base_handler.py", line 92, in _load_torchscript_model
2021-02-27 07:02:21,066 [WARN ] W-9000-litai_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle -     return torch.jit.load(model_pt_path, map_location=self.map_location)
2021-02-27 07:02:21,066 [WARN ] W-9000-litai_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle -   File "/home/collin/.virtualenvs/litai/lib/python3.8/site-packages/torch/jit/_serialization.py", line 161, in load
2021-02-27 07:02:21,066 [WARN ] W-9000-litai_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle -     cpp_module = torch._C.import_ir_module(cu, f, map_location, _extra_files)
2021-02-27 07:02:21,066 [WARN ] W-9000-litai_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle - RuntimeError: Could not run 'aten::empty_strided' with arguments from the 'QuantizedCUDA' backend. 'aten::empty_strided' is only available for these backends: [CPU, CUDA, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].
```
## Steps to Reproduce

1. Quantize model with:
```python
import os

import torch
from transformers import GPT2LMHeadModel, GPT2TokenizerFast
from transformers.modeling_utils import Conv1D

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


def _conv1d_to_linear(module):
    in_size, out_size = module.weight.shape
    linear = torch.nn.Linear(in_size, out_size)
    linear.weight.data = module.weight.data.T.contiguous()
    linear.bias.data = module.bias.data
    return linear


def conv1d_to_linear(model):
    """in-place
    This is for Dynamic Quantization, as Conv1D is not recognized by PyTorch, convert it to nn.Linear
    """
    for name in list(model._modules):
        module = model._modules[name]
        if isinstance(module, Conv1D):
            linear = _conv1d_to_linear(module)
            model._modules[name] = linear
        else:
            conv1d_to_linear(module)


tokenizer = GPT2TokenizerFast.from_pretrained("gpt2-large")
text = "Test Text."
tokens = tokenizer(text, return_tensors="pt")["input_ids"]
model = torch.load("../model.pt")
model.resize_token_embeddings(len(tokenizer))
model.eval()
pretrained_model = GPT2LMHeadModel.from_pretrained("gpt2-xl", torchscript=True)
pretrained_model.resize_token_embeddings(len(tokenizer))
pretrained_model.load_state_dict(model.state_dict())
conv1d_to_linear(pretrained_model)
pretrained_model.eval()
quantized_model = torch.quantization.quantize_dynamic(
    pretrained_model, {torch.nn.Linear}, dtype=torch.qint8
)
traced_model = torch.jit.trace(quantized_model, tokens)
torch.jit.save(traced_model, "quantized_traced_model.pt")


def print_size_of_model(model):
    torch.save(model.state_dict(), "temp.p")
    print("Size (MB):", os.path.getsize("temp.p") / 1e6)
    os.remove("temp.p")


print_size_of_model(pretrained_model)
print_size_of_model(quantized_model)
```
2. Archive Model - `torch-model-archiver --model-name litai --version 1.0 --serialized-file quantized_traced_model.pt --handler handler.py --extra-files "setup_config.json,model_config.py" --requirements-file requirements.txt`
* `requirements.txt`
```
transformers==4.3.2
ml_collections==0.1.0
```
3. `torchserve --start --model-store model_store --models litai=litai.mar  --foreground --no-config-snapshots`
Fails here
## Failure Logs [if any]
See above

**Comment by dhanainme** [comment]
Are you able to perform inference on your model just with a simple python script w/o Torchserve. The stack-trace appears to be an exception with the inference itself & not anything TS specific.

**Comment by collinarnett** [comment]
Yes I found out later that this is not a issue with torch serve but a issue moving the model onto GPU with a traced model. I never got the issue fixed but I've realized that its not related to torch serve.

**Comment by HamidShojanazeri** [comment]
@collinarnett current quantization schemes do not support GPU inference, it is under development.
